import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const oneShot = prod || (process.argv[2] === 'dev');

const prodBanner = prod ? 'console.debug = function() {};\n' : '';

const context = await esbuild.context({
  banner: {
    js: banner + prodBanner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
    ...builtinModules.map((module) => `node:${module}`)],
  format: 'cjs',
  target: 'es2018',
  // Without this, esbuild defaults `platform` to 'browser', under which an
  // *external* dynamic import is assumed to be available natively and is left
  // in place. `node:module` is external (see above), so `await import(...)`
  // reached the shipped bundle as a native ESM import inside a CJS file, and
  // failed at runtime — silently, because the callers catch the TypeError.
  // Declaring the target unable to do it makes esbuild emit the
  // require-based form that a CJS bundle can actually load.
  supported: { 'dynamic-import': false },
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (oneShot) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
