export const DE_TEXTS = {
    // Plugin Info
    pluginTitle: 'Karpathy LLM-Wiki-Einstellungen',
    pluginIntro: 'Dieses Plugin setzt das {{link}}-Konzept für Obsidian um. Es liest deine Notizen, nutzt KI, um Entitäten, Konzepte und Zusammenhänge zu extrahieren, und erstellt ein strukturiertes, vernetztes Wiki in deinem Vault.',
    karpathyLinkText: 'Andrej Karpathys LLM-Wiki',

    // Features Section
    featuresTitle: 'Funktionsweise',
    workflow1Title: '1. Aufnehmen',
    workflow1Desc: 'Wähle eine Notiz — KI extrahiert Entitäten, Konzepte und Zusammenhänge in Wiki-Seiten.',
    workflow2Title: '2. Anfragen',
    workflow2Desc: 'Chatte mit deinem Wiki — Antworten basieren auf deinem aufgenommenen Wissen.',
    workflow3Title: '3. Pflegen',
    workflow3Desc: 'Automatisch generierte Indizes, Querverweise und Lint-Prüfungen halten das Wiki gesund.',

    // Language Switcher
    languageTitle: 'Oberflächensprache',
    languageDesc: 'Wähle deine bevorzugte Sprache für das Einstellungsfenster. Starte das Plugin neu, um die Sprachänderungen auf die Befehlspalette anzuwenden.',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // Status
    statusTitle: 'LLM-Client-Status',
    llmWikiStatusSection: 'LLM-Wiki-Status',
    statusInitialized: 'Initialisiert',
    statusReady: 'LLM bereit',
    statusNotReady: 'LLM nicht konfiguriert — Einrichtung oben abschließen und Verbindungstest bestehen',
    statusNotInitialized: 'Nicht initialisiert',
    currentProvider: 'Aktueller Anbieter',

    // Provider Configuration
    providerSection: 'LLM-Konfiguration',
    providerName: 'LLM-Anbieter',
    providerDesc: 'Vordefinierten Anbieter oder benutzerdefinierten OpenAI-kompatiblen Dienst wählen. Für Coding Plan oder ähnliche Bundles: Custom OpenAI/Anthropic wählen, Base URL und API Key des Providers manuell eingeben',

    // API Key
    apiKeyName: 'API-Schlüssel',
    apiKeyDesc: 'API-Schlüssel. Wird im OS-Schlüsselbund gespeichert, nicht in data.json.',
    apiKeyPlaceholder: 'API-Schlüssel eingeben',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: 'SecretStorage-Migration',
    apiKeyMigratedToSecretStorageSuccess: 'API-Schlüssel aus SecretStorage in die Einstellungen wiederhergestellt.',
    apiKeyMigrationFailedNotice: 'API-Schlüssel konnte nicht in SecretStorage gespeichert werden: {}',
    codexAuthName: 'Bei ChatGPT Plan anmelden',
    codexAuthDesc: 'Experimenteller Codex-OAuth-Zugriff über das Kontingent Ihres ChatGPT-Plans. Die Abrechnung der OpenAI Platform API erfolgt weiterhin separat.',
    codexAuthSignedOut: 'Nicht angemeldet',
    codexAuthSignedIn: 'Angemeldet',
    codexAuthBrowserButton: 'Im Browser anmelden',
    codexAuthDeviceButton: 'Gerätecode verwenden',
    codexAuthDeviceInstructions: 'Geben Sie diesen Code auf der OpenAI-Seite ein: {}',
    codexAuthCopyCode: 'Code kopieren',
    codexAuthSignOutButton: 'Abmelden',
    codexAuthBusy: 'Warten auf OpenAI-Autorisierung...',
    codexAuthFailed: 'ChatGPT-Autorisierung fehlgeschlagen: {}',
    codexAuthQuota: 'Das ChatGPT-Codex-Kontingent ist erreicht. Warten Sie bis zum angezeigten Zurücksetzungszeitpunkt und versuchen Sie es erneut.',
    codexAuthExperimental: 'Experimentell: Die Verfügbarkeit richtet sich nach den Authentifizierungs- und Modellrichtlinien von OpenAI Codex.',
    codexModelsRefreshName: 'Kontomodelle',
    codexModelsRefreshDesc: 'Synchronisiert auswählbare Modelle aus dem angemeldeten OpenAI-Codex-Konto.',
    codexModelsRefreshButton: 'Kontomodelle aktualisieren',
    codexModelsRefreshing: 'Wird aktualisiert...',
    codexModelsRefreshSuccess: '{} Kontomodelle synchronisiert.',
    codexModelsRefreshFailed: 'Kontomodelle konnten nicht aktualisiert werden; die verfügbare Ersatzliste wird verwendet. {}',

    // Base URL
    baseUrlName: 'API-Basis-URL',
    baseUrlDescCustom: 'Erforderlich: Benutzerdefinierte OpenAI-kompatible Endpunkt',
    baseUrlDescOverride: 'Optional: Voreingestellte Basis-URL überschreiben',

    // Ollama Hint
    ollamaHint: 'Ollama läuft lokal, kein API-Schlüssel erforderlich',
    lmstudioHint: 'LM Studio läuft lokal, API-Key ist optional',
    maxTokensPerCallName: 'Max. Ausgabe-Token pro Aufruf',
    maxTokensPerCallDesc: 'Begrenzt die Anzahl der Token, die das Modell in einer einzelnen Antwort generieren kann. Niedriger einstellen, falls Sie ein lokales Modell mit kleinem Kontextfenster verwenden und Fehler sehen. Für Cloud-Modelle auf dem Standardwert belassen (0 = kein Limit).',

    slugCaseName: 'Dateinamen-Schreibweise',
    slugCaseDesc: "Legt fest, ob generierte Wiki-Dateinamen kleingeschrieben werden. 'Beibehalten' empfohlen fuer Sprachen, in denen Gross-/Kleinschreibung bedeutungsrelevant ist (z. B. deutsche Substantive).",
    slugCaseLower: 'Kleinschreibung (Standard)',
    slugCasePreserve: 'Schreibweise beibehalten',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: 'Minimale Alias-Länge',
    minAliasLengthDesc: 'Aliase, die kürzer sind (nach Trimmen), werden nicht in Wiki-Seiten geschrieben. Standard 2 hält zweibuchstabige Abkürzungen (ML, KI, UI) nutzbar; auf 3 erhöhen, wenn der Vault zweibuchstabige Aliase sammelt, die sich nur in der Schreibung unterscheiden (Cr/CR). Bereich 2–6.',
    minAliasLengthClamped: 'Wert außerhalb des Bereichs (2–6), auf {} gesetzt',

    // Model Selection
    modelSection: 'Modellauswahl',
    fetchModelsName: 'Verfügbare Modelle abrufen',
    fetchModelsDesc: 'Aktuelle Modellliste von der Anbieter-API abrufen',
    fetchModelsButton: 'Modelle abrufen',
    fetchingModels: 'Wird abgerufen...',
    fetchSuccess: 'Erfolg! {} Modelle verfügbar',
    fetchFailed: 'Abruf fehlgeschlagen oder leere Liste, bitte Modellnamen manuell eingeben',
    fetchNotSupported: 'Anbieter unterstützt keine Modelllistenabfrage',
    fetchErrorAuth: 'Authentifizierung fehlgeschlagen (HTTP 401/403). Überprüfen Sie den API-Schlüssel, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorEndpoint: 'Endpunkt nicht gefunden (HTTP 404). Überprüfen Sie die Endpunkt-URL, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorServer: 'Anbieter-Serverfehler (HTTP 5xx). Versuchen Sie es später erneut, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorEmpty: 'Dieser Endpunkt stellt keine Modellliste bereit. Geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorNetwork: 'Netzwerkanfrage fehlgeschlagen. Überprüfen Sie Internetverbindung, Endpunkt-URL, Proxy-Einstellungen oder API Key. Sie können auch eine Modell-ID eingeben und auf Verbindung testen klicken.',

    selectModelName: 'Modell auswählen',
    selectModelDesc: 'Aus {} verfügbaren Modellen wählen',
    customInputOption: 'Benutzerdefinierte Eingabe...',
    customInputHint: 'Um andere Modelle zu verwenden, wähle "Benutzerdefinierte Eingabe..."',

    modelName: 'Modellname',
    modelDescCustom: 'Benutzerdefiniertes Modell wird verwendet (Schaltfläche oben klicken, um Liste erneut abzurufen)',
    modelDescFetchFailed: 'Abruf der Modellliste fehlgeschlagen. Überprüfen Sie API-Schlüssel und Endpunkt-URL, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    modelInputPlaceholder: 'Modell-ID eingeben, dann Verbindung testen',

    switchToDropdown: 'Zur Dropdown-Auswahl wechseln',
    useDropdownButton: 'Dropdown verwenden',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: 'Modellbereich',
    modelTaskModeDesc: 'Wählen Sie, ob alle Aufgaben dasselbe Modell verwenden oder ob pro Aufgabe (Erfassung / Wartung & Reparatur / Abfrage) unterschiedliche Modelle genutzt werden. Beim Zurückwechseln auf das einheitliche Modell bleiben ausgeblendete aufgabenspezifische Werte erhalten (werden nicht gelöscht).',
    modelTaskModeUnified: 'Einheitliches Modell verwenden (Standard)',
    modelTaskModePerTask: 'Pro Aufgabe unterschiedliche Modelle verwenden',
    perTaskIngestModelName: 'Erfassungsmodell',
    perTaskIngestModelDesc: 'Wird für die Erfassung von Notizen, Gesprächen, Schema-Wartung und Willkommensnotiz-Erstellung verwendet.',
    perTaskLintModelName: 'Wartungs- und Reparaturmodell',
    perTaskLintModelDesc: 'Wird für Lint-Analyse, Duplikaterkennung, Reparaturläufe und Korrektur verwaister Links verwendet.',
    perTaskQueryModelName: 'Abfragemodell',
    perTaskQueryModelDesc: 'Wird für Query Wiki-Chat und Wiki-Speicherungsbewertung verwendet.',

    // Test & Save
    testConnectionName: 'Verbindung testen',
    testConnectionDesc: 'Konfiguration überprüfen und LLM-API-Aufruf validieren',
    testButton: 'Verbindung testen',
    testing: 'Wird getestet...',

    saveSettingsName: 'Einstellungen speichern',
    saveSettingsDesc: 'Aktuelle Konfiguration speichern',
    saveButton: 'Einstellungen speichern',
    testConnectionSuccessful: 'Verbindung erfolgreich',
    testConnectionFailed: 'Verbindung fehlgeschlagen',
    testConnectionProvider: 'Anbieter: ',
    codexAuthRequired: 'Melden Sie sich vor dem Verbindungstest bei ChatGPT Plan an.',
    bedrockSsoRequired: 'Führen Sie vor dem Verbindungstest die AWS-SSO-Anmeldung durch (Einstellungen → Bedrock).',
    bedrockIamRequired: 'Geben Sie vor dem Verbindungstest Ihre IAM-Zugriffsschlüssel ein (Einstellungen → Bedrock).',
    bedrockAuthMethodName: 'Authentifizierung',
    bedrockAuthMethodDesc: 'API-Schlüssel verwendet einen Bedrock-API-Key; AWS SSO signiert Anfragen mit IAM Identity Center-Anmeldeinformationen; IAM-Schlüssel verwenden statische Zugriffsschlüssel.',
    bedrockAuthOptionApiKey: 'API-Schlüssel',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'IAM-Schlüssel',
    bedrockSsoStartUrlName: 'SSO-Start-URL',
    bedrockSsoStartUrlDesc: 'Portal-URL Ihrer Organisation, z. B. https://d-xxxxxxxxx.awsapps.com/start',
    bedrockSsoAccountIdName: 'AWS-Konto-ID',
    bedrockSsoAccountIdDesc: '12-stellige Konto-ID, deren Rolle angenommen wird, z. B. 123456789012',
    bedrockSsoRoleNameName: 'Rollenname',
    bedrockSsoRoleNameDesc: 'IAM-Rolle für den Bedrock-Zugriff, z. B. PowerUserAccess',
    bedrockSsoLoginButton: 'Mit AWS SSO anmelden',
    bedrockSsoSignOutButton: 'Von AWS SSO abmelden',
    bedrockSsoStatusSignedIn: 'Angemeldet · läuft {}',
    bedrockSsoStatusSignedOut: 'Nicht angemeldet',
    bedrockSsoBusy: 'Anmeldung läuft…',
    bedrockSsoUserCodeInstructions: 'AWS-SSO-Code: {}. Öffnen Sie den Link und bestätigen Sie den Zugriff.',
    bedrockSsoCopyCode: 'Code kopieren',
    bedrockSsoFailed: 'AWS-SSO-Anmeldung fehlgeschlagen: {}',
    bedrockSsoDetectedPrefill: 'Konto/Rolle erkannt: {}',
    bedrockIamKeyName: 'Access-Key-ID',
    bedrockIamKeyDesc: 'Kennung des IAM-Zugriffsschlüssels, z. B. AKIA… oder ASIA…',
    bedrockIamSecretName: 'Geheimer Zugriffsschlüssel',
    bedrockIamSecretDesc: 'Wird ausschließlich im Geheimspeicher dieses Geräts gespeichert — nie in data.json',
    bedrockIamSessionTokenName: 'Sitzungstoken (optional)',
    bedrockIamSessionTokenDesc: 'Nur für temporäre Anmeldeinformationen erforderlich (STS)',
    bedrockIamClearButton: 'Gespeicherte IAM-Schlüssel löschen',
    bedrockIamSaveFailed: 'Speichern der IAM-Schlüssel fehlgeschlagen: {}',
    errorUnknown: 'Unbekannter Fehler',
    savedNotice: 'Einstellungen gespeichert!',

    // v1.24.0 (Bug C 3.4 / plan C): Schrittweise Migrations-Benachrichtigung
    queryHistoryMigrationNotice: 'Der Query-Wiki-Verlauf enthält Links aus einem früheren Wiki-Ordner. Neue Anfragen verwenden automatisch den aktuellen Ordner. Um alle gespeicherten Nachrichten zu aktualisieren, öffnen Sie das Query-Wiki-Panel und klicken Sie dort auf „Verlauf löschen".',

    // v1.24.0 Issue #251: Benutzerdefinierte Query-Anweisungen (einklappbares Panel)
    customInstructionsTitle: 'Benutzerdefinierte Query-Anweisungen',
    customInstructionsDesc: 'Persistente Anweisungen, die an jede Query-Wiki-Systemaufforderung angehängt werden. Betrifft nur den Query-Wiki-Chat; Ingestion, Lint und Seitengenerierung sind nicht betroffen.',
    customInstructionsPlaceholder: 'z. B. Als Rechercheaufgabe behandeln: breit suchen, Quellen zitieren, Fakten von Interpretation trennen...',
    customInstructionsApply: 'Anwenden',
    customInstructionsClear: 'Löschen',
    customInstructionsCharCount: '{current}/{max} Zeichen',
    instructionsApplied: 'Benutzerdefinierte Query-Anweisungen gespeichert.',
    instructionsCleared: 'Benutzerdefinierte Query-Anweisungen gelöscht.',

    // Issue #137: LLM-Fallback-Hinweise
    fallbackThinkingDialect: 'Denksteuerung: Zum Dialekt "{dialect}" gewechselt (dieser Anbieter verwendet ein anderes Format für die Denksteuerung). Ausgabe unverändert.',
    fallbackThinkingNone: 'Denksteuerung für diesen Anbieter vollständig deaktiviert. Es können weiterhin Reasoning-Inhalte erscheinen; falls ja, versuchen Sie ein anderes Modell.',
    fallbackParamStripped: 'Parameter "{field}" wird von diesem Anbieter nicht unterstützt. Aus der Anfrage entfernt; Verhalten kann von der Konfiguration abweichen.',

    // Wiki Folder
    wikiSection: 'Wiki-Konfiguration',
    wikiFolderName: 'Wiki-Ordner',
    // v1.24.0: Hinweis, dass nach einer Änderung ein Neustart von Obsidian
    // erforderlich ist (Engine-Caches und offene Query-Wiki-Panels müssen neu gebunden werden).
    wikiFolderDesc: 'Speicherort für generierte Wiki-Seiten. Starten Sie Obsidian nach einer Änderung neu — Engine-Caches und offene Query-Wiki-Panels müssen neu gebunden werden.',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'Bitte zunächst API-Schlüssel konfigurieren',
    errorNoModel: 'Bitte zunächst ein Modell auswählen — „Modelle abrufen“ klicken oder Model-ID manuell eingeben',
    llmNotReady: 'LLM ist nicht konfiguriert. Gehen Sie zu Einstellungen → Karpathy LLM Wiki, um Ihren Anbieter zu konfigurieren und den Verbindungstest zu bestehen.',
    errorFetchFailed: 'Fehlgeschlagen: {}',

    // Query Settings
    querySectionTitle: 'Wiki-Anfrage-Konfiguration',
    // v1.24.0: Umbenannt von „Maximaler Konversationsverlauf" zu
    // „Konversations-Gedächtnis-Runden", um die Semantik klarer zu machen.
    // 1 = jede Runde unabhängig (kein vorgangsübergreifendes Gedächtnis).
    // Die Einstellung ist ein Dropdown, daher keine Voreinstellungsliste nötig.
    // v1.24.0: maxConversationHistoryHint war ein unbenutzter i18n-Schlüssel;
    // der Empfehlungstext ist jetzt in der Beschreibung integriert.
    maxConversationHistoryName: 'Konversations-Gedächtnis-Runden',
    maxConversationHistoryDesc: 'Wie viele vergangene Konversationsrunden das LLM als Gedächtnis sieht. 1 = jede Runde unabhängig (kein vorgangsübergreifendes Gedächtnis); höhere Werte lassen das Modell sich an frühere Runden in der Sitzung erinnern. Empfehlung: 1 für einmalige Q&A, 10–50 für laufende Recherche.',
    numberRangeValidation: 'Bitte eine Zahl zwischen 1 und 50 eingeben',
    numberRangeClamped: 'Wert außerhalb des Bereichs (1-500), automatisch auf {} gesetzt',
    // Query Modal UI
    queryModalTitle: 'Wiki-Anfrage — Konversationelle Abfrage',
    queryModalPlaceholder: 'Frage eingeben...',
    queryModalSendButton: 'Senden',
    queryModalStopButton: 'Stopp',
    queryModalSaveButton: 'Im Wiki speichern',
    queryModalClearButton: 'Verlauf löschen',
    queryModalHistoryCount: 'Konversationsverlauf: {}/{} Runden',
    queryModalStreaming: 'Streaming...',
    queryModalFallbackStreaming: 'Streaming nicht unterstützt, Wechsel zu Nicht-Streaming. Bitte warten...',
    queryPhaseSearching: 'Wiki-Index wird analysiert, relevante Seiten werden ausgewählt...',
    queryPhaseFoundPages: '{count} Seite(n) gefunden: {pages}',
    queryPhaseLoadingPages: 'Seiteninhalt wird geladen...',
    queryPhaseContextReady: 'Kontext bereit. Antwort wird generiert...',
    queryPhaseGenerating: 'Generierung... (verstrichen {time}s)',
    queryPhaseNonStreaming: 'Nicht-Streaming-Modus, Antwort wird generiert... (verstrichen {time}s)',
    queryModalErrorPrefix: 'Fehler: ',
    queryModalHint: 'Anfragen basieren auf Wiki-Inhalten. Klicke auf "Im Wiki speichern", um wertvolle Konversationen als Wiki-Seiten zu extrahieren.',

    // v1.20.0: Query Wiki Denkblock-Einklapp-Zusammenfassung
    queryThinkingSummary: 'Denkprozess',
    queryThinkingSteps: 'Schritte',

    // Error Messages
    errorLLMClientNotInit: 'LLM-Client nicht initialisiert. Bitte Einstellungen speichern.',
    errorIngestFailed: 'Aufnahme fehlgeschlagen: ',
    errorQueryFailed: 'Anfrage fehlgeschlagen: ',
    fileWriteFailed: 'Datei konnte nicht erstellt oder aktualisiert werden: {path}',

    // Success Messages
    ingestSuccess: 'Aufnahme erfolgreich: {} Seiten erstellt, {} Seiten aktualisiert',
    querySuccess: 'Anfrage abgeschlossen',
    lintSuccess: 'Wiki-Lint abgeschlossen',
    lintReadingPages: '{count} Wiki-Seiten werden gelesen...',
    lintReadingPagesProgress: 'Wiki-Seiten werden gelesen: {current}/{total}...',
    lintScanningLinks: 'Defekte Links werden geprüft...',
    lintScanningLinksProgress: 'Defekte Links werden geprüft: {current}/{total}...',
    lintCheckingDuplicates: 'Auf doppelte Seiten wird geprüft...',
    lintCheckingDuplicatesProgress: 'Duplikate werden überprüft: Stapel {current} ...',
    lintFixingPolluted: 'Bereinigte Seite wird repariert {current}/{total}: {title} → {newTitle}',
    lintModalFixPolluted: '🧹 Bereinigte Seiten reparieren ({count})',
    lintDuplicateCheckFailed: 'Duplikaterkennung fehlgeschlagen — Details in der Konsole',
    lintDuplicateCheckFailedDetail: 'Duplikatprüfung fehlgeschlagen bei {step}: {error}',
    lintMergeItemFailed: 'Zusammenführung fehlgeschlagen: {source} → {target} — {error}',
    lintAliasesMissing: 'Fehlende Aliase: {count} Seite(n) ohne Aliase',
    lintAliasesSection: 'Seiten ohne Aliase [{count}]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: 'Aliase vervollständigen ({count})',
    lintAliasesFilling: 'Aliase werden generiert {current}/{total}: {page}',
    lintAliasesFilled: 'Alias-Vervollständigung abgeschlossen. {filled}/{total} Seiten ergänzt.',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: 'Tags außerhalb des Vokabulars (erkannt) [{count}]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: 'Alias-Generierung fehlgeschlagen: {page} — {error}',
    lintFixItemFailed: 'Behebung fehlgeschlagen: [[{target}]] — {error}',
    lintLinkItemFailed: 'Verlinkung fehlgeschlagen: {page} — {error}',
    lintRetrying: 'Wiederholung ({attempt}/{max}) nach Fehler...',
    lintAnalyzingLLM: 'LLM analysiert Wiki-Gesundheit...',
    saveToWikiSuccess: 'Konversation im Wiki gespeichert!',
    querySaveAlreadyExists: 'Hinweis: Es wurde nichts geschrieben (Wissen ist bereits im Wiki vorhanden):',
    saveSummary: '{entities} Entitäten, {concepts} Konzepte, {pages} Seiten',
    aliasAdded: 'Alias \'{alias}\' zur Seite \'{page}\' hinzugefügt',

    // Status Messages
    ingestingSources: 'Quellen werden aufgenommen...',
    queryingWiki: 'Wiki wird angefragt...',
    lintingWiki: 'Wiki wird geprüft...',
    savingToWiki: 'Konversation wird im Wiki gespeichert...',
    clearingHistory: 'Konversationsverlauf wird gelöscht...',

    // Buttons
    ingestButton: 'Aufnehmen',
    queryButton: 'Anfragen',
    lintButton: 'Prüfen',
    cancelButton: 'Abbrechen',

    // Links
    karpathyGistLink: 'Karpathys LLM-Wiki Gist',
    obsidianPluginAPI: 'Obsidian-Plugin-API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'AWS-Region',
    bedrockRegionDesc: 'Amazon-Bedrock-Region für dieses Konto. Bestimmt die bedrock-mantle-Endpunkt-URL; kann nicht über baseURL überschrieben werden.',
    bedrockRegionHint: 'bedrock-mantle ist in 18 Regionen verfügbar; die Modellabdeckung variiert je nach Region.',

    // Other
    availableModelsLoading: 'Verfügbare Modelle werden geladen...',
    noModelsAvailable: 'Keine Modelle verfügbar',

    // LLM Language Hint
    llmLanguageHint: 'Bitte antworten Sie auf Deutsch.',

    // Schema Configuration
    schemaSection: 'Schema-Konfiguration',
    enableSchemaName: 'Schema aktivieren',
    enableSchemaDesc: 'Schema/config.md generieren und in alle LLM-Prompts einfügen, um strukturierte Wiki-Ausgabe zu ermöglichen',
    viewSchemaButton: 'Schema ansehen / bearbeiten',
    regenerateSchemaButton: 'Standard-Schema neu generieren',
    schemaRegeneratedNotice: 'Standard-Schema neu generiert.',
    schemaRegenerateFailed: 'Schema-Generierung fehlgeschlagen',

    // Wiki-Initialisierungsstatus
    wikiInitStatusReady: 'Wiki initialisiert',
    wikiInitStatusNotReady: 'Wiki nicht initialisiert — wird beim ersten Ingest automatisch erstellt',

    // Wiki Output Language
    wikiLanguageName: 'Wiki-Ausgabesprache',
    wikiLanguageDesc: 'Alle generierten Wiki-Seiten, Indizes, Protokolle und Anfrageantworten verwenden diese Sprache',
    customWikiLanguageOption: 'Benutzerdefiniert...',
    customWikiLanguageHint: 'Sprachnamen eingeben (z. B. Italienisch, Arabisch). Wird als Ausgabesprachen-Anweisung an das LLM übergeben.',
    customWikiLanguagePlaceholder: 'z. B. Italienisch',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // Extraction Settings
    extractionSectionTitle: 'Extraktion',
    extractionGranularityName: 'Extraktions-Granularität',
    extractionGranularityDesc: 'Steuert Extraktionen pro Quelldatei. Höher = mehr Seiten/API-Verbrauch.\nFein: Tiefenanalyse. Standard: Tägliche Notizen. Grob: Schnelle Übersicht. Minimal: 100+ Dateien stapeln (begrenzt Posten je Quelle, ~5 — nicht die Detailtiefe). Benutzerdefiniert: Eigene Limits (max 500).\nTipp: Verwenden Sie Minimal/Grob für Ordner mit vielen Dateien zur Zeit- und Kosteneinsparung.',
    extractionGranularityFine: 'Fein — Tiefenanalyse (≤100 Elemente)',
    extractionGranularityStandard: 'Standard — Tägliche Notizen (≤50 Elemente)',
    extractionGranularityCoarse: 'Grob — Schnellübersicht (≤10 Elemente)',
    extractionGranularityMinimal: 'Minimal — Stapelverarbeitung 100+ Dateien (≤5 Elemente)',
    extractionGranularityCustom: 'Benutzerdefiniert — Eigene Limits festlegen (1~500)',
    customEntityLimitName: 'Benutzerdefiniertes Entitätslimit',
    customEntityLimitDesc: 'Maximale Anzahl zu extrahierender Entitäten pro Quelldatei (1-500)',
    customConceptLimitName: 'Benutzerdefiniertes Konzeptlimit',
    customConceptLimitDesc: 'Maximale Anzahl zu extrahierender Konzepte pro Quelldatei (1-500)',

    // Issue #85 v2: Tag-Vokabular (Chip-Eingabe, in Wiki-Konfiguration eingebettet)
    tagVocabularyInlineDesc: 'Kontrolliertes Vokabular für entity- und concept-Frontmatter-Tags. Verschachtelte Obsidian-Tags mit „/" bleiben erhalten.',
    tagVocabularyModeName: 'Tag-Vokabular-Konfiguration',
    tagVocabularyModeDescDefault: 'Standard verwendet eingebaute Tags: {}. Wechseln Sie zu „Benutzerdefiniert", um Ihr eigenes Vokabular zu definieren.',
    tagVocabularyModeDescCustom: 'Benutzerdefiniert: Definieren Sie unten Ihre eigenen entity- und concept-Tags per Chip-Eingabe — Enter oder Komma zum Hinzufügen, × zum Entfernen.',
    tagVocabularyNotEnforcedHint: 'Nur ein Schema-Hinweis — die KI kann weiterhin Typen außerhalb des Vokabulars ausgeben. Lint ausführen, um diese Seiten zu finden und zu reparieren.',
    tagVocabularyModeDefault: 'Standard (eingebaute Subtyp-Tags)',
    tagVocabularyModeCustom: 'Benutzerdefiniert (eigene)',
    customEntityTagsName: 'Benutzerdefinierte Entitäts-Tags',
    customEntityTagsDesc: 'Enter oder Komma zum Hinzufügen eines Chips, × zum Entfernen. Verschachtelte Tags mit „/" bleiben erhalten.',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'Benutzerdefinierte Konzept-Tags',
    customConceptTagsDesc: 'Enter oder Komma zum Hinzufügen eines Chips, × zum Entfernen. Verschachtelte Tags mit „/" bleiben erhalten.',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: 'Doppeltes Tag übersprungen',

    // Ingestion Acceleration
    accelerationSectionTitle: 'Aufnahmen-Beschleunigung',
    pageGenerationConcurrencyName: 'LLM-Parallelität',
    pageGenerationConcurrencyDesc: 'Anzahl paralleler LLM-Aufrufe während Aufnahme und Lint-Operationen. Höhere Werte beschleunigen die Verarbeitung, erhöhen aber API-Kosten und können Ratenbegrenzungen auslösen.',
    concurrencyValueSingular: 'Aktuelle Parallelität: {} (seriell — am sichersten)',
    concurrencyValuePlural: 'Aktuelle Parallelität: {} (parallel)',
    batchDelayName: 'Batch-Verzögerung (ms)',
    batchDelayDesc: 'Verzögerung zwischen parallelen Stapeln zur Vermeidung von API-Ratenbegrenzungen (100–10000 ms). Aktuell: {}ms. Erhöhen bei 429-Fehlern.',

    // Auto Maintenance
    autoMaintainSection: 'Automatische Wartung',
    autoMaintainBetaBadge: 'BETA — Experimentelle Funktion. Kann Probleme aufweisen. Nur für erfahrene Benutzer empfohlen.',
    autoWatchName: 'Ordner beobachten',
    autoWatchDesc: 'Neue oder geänderte .md-Dateien in den beobachteten Ordnern automatisch erkennen und benachrichtigen oder automatisch aufnehmen',
    watchedFoldersName: 'Beobachtete Ordner',
    watchedFoldersDesc: 'Deine deklarierten Quellordner. Ihre Tags bilden das Domain-Tag-Vokabular beim Ingest, und — mit aktivierter Überwachung — werden sie auf neue Inhalte überwacht. Klicke auf "Ordner hinzufügen", um aus deinem Vault auszuwählen.',
    addWatchedFolderButton: 'Ordner hinzufügen',
    removeWatchedFolderButton: 'Entfernen',
    webClipperPresetName: 'Clippings beobachten (Web Clipper)',
    webClipperPresetDesc: 'Den Clippings/-Ordner von Obsidian Web Clipper zur Beobachtungsliste hinzufügen. Webclips werden automatisch ins Wiki aufgenommen.',
    noWatchedFoldersHint: 'Keine Ordner konfiguriert. Füge einen Ordner hinzu oder aktiviere die Clippings-Voreinstellung.',
    autoWatchModeName: 'Beobachtungsmodus',
    autoWatchModeDesc: '"Nur benachrichtigen" zeigt eine Eingabeaufforderung. "Automatisch aufnehmen" verarbeitet still.',
    watchModeNotify: 'Nur benachrichtigen',
    watchModeAuto: 'Automatisch aufnehmen',
    autoWatchDebounceName: 'Entprell-Verzögerung (Sekunden)',
    autoWatchDebounceDesc: 'Wartezeit vor der Aufnahmeauslösung nach einer Dateiänderung (1–60 Sekunden)',
    periodicLintName: 'Periodische Prüfung',
    periodicLintDesc: 'LLM-Prüfung zeitgesteuert ausführen, nur wenn sich Quelldateien seit der letzten Prüfung geändert haben',
    periodicLintOff: 'Aus',
    periodicLintDaily: 'Täglich',
    periodicLintWeekly: 'Wöchentlich',
    periodicLintMonthly: 'Monatlich',
    autoSmartFixName: 'Automatische Smart-Korrektur',
    autoSmartFixDesc: 'Wenn Lint ausgeführt wird, alle Korrekturen (Smart Fix All) automatisch anwenden, ohne das Berichts-Modal anzuzeigen. Die Zusammenfassung wird nach Abschluss weiterhin angezeigt.',
    autoSmartFixNotice: 'Automatische Smart-Korrektur: Alle Korrekturen werden angewendet...',
    autoIngestLevelName: 'Auto-Ingest-Benachrichtigung',
    autoIngestLevelDesc: 'Wie nach Abschluss des automatischen Imports benachrichtigt wird. "Hinweis" (transient) ist nicht blockierend. "Modal" öffnet den vollständigen Bericht. Deaktiviert, wenn der Watch-Modus auf "Nur benachrichtigen" gesetzt ist.',
    autoIngestLevelNotice: 'Hinweis (nicht blockierend)',
    autoIngestLevelModal: 'Modal (vollständiger Bericht)',
    startupCheckName: 'Schnellkorrekturen beim Start ausführen',
    startupCheckDesc: 'Beim Laden des Plugins低级 Formatprobleme (sources-Feld, doppelt verschachtelte Wikilinks) automatisch korrigieren und Wiki-Ordnerstruktur überprüfen. Standardmäßig aktiviert.',
    suggestSchemaCommand: 'Schema-Aktualisierungen vorschlagen',
    autoMaintainCostWarning: '⚠️ Kostenhinweis: Funktionen zur automatischen Wartung verbrauchen API-Tokens. "Automatisch aufnehmen" löst bei jeder Quelldatei-Änderung LLM-Aufrufe aus. "Periodische Prüfung" führt zeitgesteuerte LLM-Gesundheitsprüfungen durch (nur bei erkannten Quelländerungen). Sorgfältig konfigurieren, um unerwartete Kosten zu vermeiden.',

    // Notices
    startupCheckSummary: 'Wiki enthält {pages} Seiten ({entities} Entitäten, {concepts} Konzepte, {sources} Quellen)',
    watcherActiveNotice: 'Wiki: Datei-Beobachtung aktiv — beobachtete Ordner werden überwacht',
    watchIngestNotice: 'Wiki: {count} Datei(en) in sources/ geändert. "Quellen aufnehmen" ausführen, um zu verarbeiten.',
    autoIngestRunning: 'Automatische Aufnahme von {count} geänderter(n) Datei(en)...',
    autoIngestComplete: 'Automatische Aufnahme abgeschlossen: {success} erfolgreich, {fail} fehlgeschlagen',
    scheduledLintRunning: 'Geplante Wiki-Prüfung wird ausgeführt...',
    wikiLintStats: 'Wiki-Prüfung: {pages} Seiten ({entities} Entitäten, {concepts} Konzepte, {sources} Quellen)',
    wikiHealthStats: 'Wiki-Gesundheit: {pages} Seiten ({entities} Entitäten, {concepts} Konzepte, {sources} Quellen){indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki-Schnellkorrekturen abgeschlossen',
    startupCheckStructureLabel: 'Wiki-Struktur',
    startupCheckStructureOk: 'vollständig',
    startupCheckStructureMissing: 'unvollständig — wird beim ersten Ingest automatisch erstellt',
    startupCheckSourcesLabel: 'Sources normalisiert',
    startupCheckSourcesClean: 'bereits sauber',
    startupCheckSourcesCleaned: '{files} Datei(en), {entries} Eintrag/Einträge bereinigt',
    startupCheckIncompleteClean: 'unvollständige Seiten: keine',
    startupCheckIncompleteArchived: 'unvollständige Seiten: {count} archiviert (wiederherstellbar aus .trash)',
    startupCheckDisableHint: 'Zum Deaktivieren: Einstellungen → Auto-Wartung → Schnellkorrekturen beim Start ausführen',
    lintWikiStart: 'Wiki-Prüfung wird gestartet...',
    lintWikiComplete: 'Wiki-Prüfung abgeschlossen',
    lintWikiFailed: 'Wiki-Prüfung fehlgeschlagen',
    analyzingSchema: 'Wiki wird analysiert und Schema-Vorschläge werden generiert...',
    schemaSuggestionGenerated: 'Schema-Vorschläge generiert, siehe wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: 'Keine Schema-Aktualisierungen erforderlich.',
    schemaSuggestionFailed: 'Schema-Vorschlag fehlgeschlagen',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Schema-Update-Vorschau',
    schemaDiffSummary: '+{add} / -{del} Zeilen',
    schemaDiffRegenerateLabel: 'Vorschlag verfeinern (optional):',
    schemaDiffRegenerateBtn: 'Neu generieren',
    schemaDiffOpenFileBtn: 'Datei öffnen',
    schemaDiffApplyBtn: 'Anwenden',
    schemaDiffApplied: 'Schema aktualisiert. Sicherung: {path}',
    schemaDiffEmptyTitle: 'LLM empfiehlt keine Änderungen',
    schemaDiffFailed: 'Schema-Anwendung fehlgeschlagen: {reason}',
    schemaDiffRestoreHint: 'Backup gespeichert unter {path}. Zum Wiederherstellen benennen Sie diese Datei im Datei-Explorer in "wiki/schema/config.md" um. Die neuesten 3 Backups werden aufbewahrt.',
    schemaRegenerateNoBody: 'Neugenerierung erfolgreich, aber LLM hat keinen neuen Body zurückgegeben.',
    schemaNotFoundNotice: 'Schema-Datei nicht gefunden. Schema aktivieren, um sie zu erstellen.',
    selectFolderNoMdFiles: 'Keine Markdown-Dateien im Ordner: {path}',
    batchIngestSkipNotice: '{skipped}/{total} bereits aufgenommene Dateien werden übersprungen. {new} neue Datei(en) werden aufgenommen...',
    batchIngestAllIngested: 'Alle {total} Dateien in diesem Ordner wurden bereits aufgenommen.',
    batchIngestStarting: '{count} Datei(en) aus "{folder}" werden aufgenommen — dies kann mehrere Minuten dauern. Ein Bericht erscheint bei Abschluss.',
    batchIngestComplete: 'Batch-Aufnahme abgeschlossen: {success}/{total} erfolgreich, {fail} fehlgeschlagen',
    batchIngestFailedFiles: 'Fehlgeschlagene Dateien:',
    historyTruncated: 'Verlauf auf letzte {max} Runden gekürzt',
    historyCleared: 'Verlauf gelöscht',

    // User Feedback Loop
    reviewedPagePreserved: 'Benutzergeprüfte Inhalte werden beibehalten für: {}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: 'Im Wiki speichern?',
    querySuggestSaveDesc: 'Diese Konversation enthält wertvolles Wissen. Im Wiki speichern?',
    querySuggestSaveYes: 'Speichern',
    querySuggestSaveNo: 'Verwerfen',

    // Ingestion Report
    ingestReportElapsedTime: 'Verstrichene Zeit',
    ingestReportSkippedFiles: 'Übersprungen (bereits aufgenommen)',
    ingestReportRejectedFiles: 'Übersprungen',
    rejectionReasonEmpty: 'leer',
    rejectionReasonType: 'nicht unterstützter Typ',
    rejectionReasonDuplicate: 'doppelter Inhalt',
    rejectionReasonPdfUnsupported: 'Anbieter kann PDF nicht lesen',
    rejectionReasonMineruPageLimit: 'überschreitet das MinerU-Seitenlimit',
    rejectionReasonMineruSizeLimit: 'überschreitet das MinerU-Größenlimit',
    sourceRejectedEmpty: '⏭️ „{filename}" hat keinen Inhalt zum Einlesen — übersprungen. Leere oder nur aus Frontmatter bestehende Notizen erzeugen keine Wiki-Seiten.',
    sourceRejectedType: '⏭️ „{filename}" ist kein unterstützter Dateityp — übersprungen. Nur Textnotizen (z. B. .md, .txt) können eingelesen werden.',
    sourceRejectedDuplicate: '⏭️ „{filename}" übersprungen — der Inhalt ist bereits im Wiki vorhanden.',
    pdfReadingInProgress: 'PDF wird gelesen: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ „{filename}" übersprungen — Ihr aktueller Provider oder das Modell akzeptiert keine PDF-Eingabe. Wechseln Sie den Provider, aktivieren Sie „Force PDF support" unter Settings → LLM Configuration → Advanced und versuchen Sie es erneut, oder wechseln Sie das Markdown-Konvertierungs-Backend auf MinerU (verarbeitet auch Bilder und Office-Dokumente).',
    clearPdfCacheCommand: 'PDF-Konvertierungs-Cache leeren',
    pdfCacheCleared: 'PDF-Cache geleert ({count} Einträge entfernt).',
    // v1.25.0 PR3: Advanced PDF settings
    forcePdfSupportName: 'PDF-Unterstützung erzwingen',
    forcePdfSupportDesc: 'Standardmäßig aus. Schalten Sie dies ein, wenn Ihr Provider nicht in der nativen Liste steht, aber trotzdem PDFs verarbeiten kann. Bei aktiviertem Schalter wird das PDF an Ihren aktuellen Provider gesendet; wird es abgelehnt, sehen Sie einen Hinweis. Native PDF-Provider (Anthropic / OpenAI / Bedrock) benötigen diese Einstellung nicht.',
    writePdfMarkdownToVaultName: 'Konvertiertes Markdown in Vault schreiben',
    markdownConversionBackendName: 'Markdown-Konvertierungs-Backend',
    markdownConversionBackendDesc: 'Verwenden Sie die native PDF-Unterstützung Ihres Providers (begrenzter Umfang, nicht jeder Provider/jedes Modell verarbeitet PDF, verbraucht LLM-Tokens). MinerU ist ein Online-Dienst — schnell, bis zum täglichen Kontingent kostenlos, akzeptiert PDF/Bilder/Office — erfordert jedoch ein API-Token (im Feld unten festlegen).',
    markdownConversionBackendNative: 'Provider-PDF-/Bild-Unterstützung',
    markdownConversionBackendMineru: 'MinerU-Online-API',
    mineruApiBaseUrlName: 'MinerU-API-Basis-URL',
    mineruApiBaseUrlDesc: 'Basis-URL für die MinerU-API. Standard ist https://mineru.net/api/v4. Passen Sie die URL an, wenn Sie einen Proxy, Mirror oder ein Self-Hosting verwenden.',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'MinerU-API-Token',
    mineruApiTokenDesc: 'Token erhalten Sie unter https://mineru.net/apiManage/token. MinerU akzeptiert Dateien bis 200 MB und bis zu 200 Seiten.',
    mineruApiTokenPlaceholder: 'MinerU-API-Token einfügen',
    mineruUploadingInProgress: 'PDF wird zu MinerU hochgeladen: {filename}',
    mineruWaitingInProgress: 'Warten auf MinerU-Konvertierung: {filename}',
    mineruDownloadingInProgress: 'MinerU-Ergebnis wird heruntergeladen: {filename}',
    markdownConversionComplete: 'Konvertierung abgeschlossen: {filename}',
    markdownConversionCompleteSaved: 'Konvertierung abgeschlossen — geschrieben nach {path}: {filename}',
    mineruPageLimitRejected: '{filename} überschreitet das Limit von {limit} Seiten bei MinerU — bitte die Datei aufteilen und erneut versuchen',
    mineruSizeLimitRejected: '{filename} überschreitet das Größenlimit von {limit} MB bei MinerU',
    writePdfMarkdownToVaultDesc: 'Standardmäßig aus. Wenn aktiv, wird das Ergebnis jeder PDF-Konvertierung in eine „<basename>.pdf.md"-Datei neben dem Quell-PDF geschrieben. Wenn aus (nur-Cache-Architektur), bleiben Ergebnisse nur im Plugin-Cache und hinterlassen keine Artefakte in deinem Vault.',

    ingestRejectedSummary: '{count} Datei(en) übersprungen (leer, doppelt oder nicht unterstützter Typ).',
    reingestConfirmTitle: 'Diese Datei erneut einlesen?',
    reingestConfirmBody: 'Der Inhalt von „{filename}" ist bereits im Wiki. Trotzdem erneut einlesen?',
    reingestConfirmYes: 'Erneut einlesen',
    reingestConfirmNo: 'Überspringen',
    lintDedupIncludeSourcesName: 'Quellen in Deduplizierung einbeziehen',
    lintDedupIncludeSourcesDesc: 'Standardmäßig aktiviert. Wenn aktiv, werden Quellen mit identischem Body während lint als Duplikate markiert. Deaktivieren, wenn dein Quellkorpus Falsch-Positiv-Meldungen erzeugt.',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: 'Nur erwähnte Kandidaten überspringen',
    skipMentionOnlyCandidatesDesc: 'Standardmäßig aus. Wenn aktiv, bekommt eine extrahierte Entität oder ein Konzept, dessen Name im Fließtext der Notiz nicht vorkommt — gar nicht, oder nur in Klammern, Aufzählungen oder kurzen Listenpunkten — keine Seite und keinen weiteren Modellaufruf und wird aus den Verwandt-Listen der anderen Kandidaten entfernt. Gilt für Wiki-Sprachen mit Wortgrenzen-Profil (Deutsch gemessen; Englisch, Französisch, Spanisch, Portugiesisch, Niederländisch geschätzt); bei anderen Sprachen meldet der Ingest einmal, dass er nicht greifen kann. Aus lassen bei Glossar-Vaults oder Stichpunkt-Notizen, in denen jeder genannte Begriff eine Seite werden soll.',
    createStubsForUnresolvableLinksName: 'Stub-Seiten für nicht auflösbare Links anlegen',
    createStubsForUnresolvableLinksDesc: 'Standardmäßig an. Wenn „Defekte Links beheben“ einen Link zu keiner existierenden Seite auflösen kann, wird eine leere Platzhalterseite angelegt und der Link dorthin umgebogen — nie durch das LLM gefüllt. Ausschalten lässt solche Links unangetastet: Sie bleiben in jedem Bericht sichtbar, bis eine echte Quelle sie definiert.',
    lintDedupSectionHeading: 'Deduplizierung',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): generischer Wortlaut,
    // wiederverwendbar für alle LLM-Geschäftspfade. {count} ist die
    // Anzahl der wiederholten Batches. Kein "Lint abgeschlossen" — der
    // Wiederholungsversuch betrifft nur diesen Batch, andere laufen
    // möglicherweise noch.
    llmRetryRecoveredToast: 'LLM-Aufgabe: {count} Batch(es) wurden wegen einer vorübergehenden Provider-Antwort wiederholt. Details in der Konsole. Falls dies häufiger auftritt, reduziere die Page Generation Concurrency in den Provider-Einstellungen.',
    ingestReportFailedGuidance: 'Diese Elemente konnten nicht automatisch erstellt werden. Du kannst die entsprechenden Seiten manuell erstellen oder die Extraktions-Granularität senken und die Quelldatei erneut aufnehmen.',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: 'Einzelne Quelle aufnehmen',
    cmdIngestFolder: 'Aus Ordner aufnehmen',
    cmdIngestMultipleFiles: 'Mehrere Dateien aufnehmen',
    cmdQueryWiki: 'Wiki anfragen',
    cmdLintWiki: 'Wiki prüfen',
    cmdRegenerateIndex: 'Index neu generieren',
    cmdSuggestSchema: 'Schema-Aktualisierungen vorschlagen',
    cmdCancelIngestion: 'Aktuelle Aufnahme abbrechen',
    cmdIngestActiveFile: 'Aktuelle Datei aufnehmen',
    cmdViewHistory: 'Ingestionsverlauf anzeigen',
    noActiveFile: 'Keine Datei geöffnet',
    mdOnlyFile: 'Nur Markdown-Dateien können aufgenommen werden',
    ingestSingleFileStart: 'Verarbeite: {filename}',
    ingestCheckingExisting: 'Prüfe bereits verarbeitete Dateien...',
    lintFindingsSummary: '{total} Befunde',

    // Ingestion status bar
    ingestionStatusBar: 'Aufnahme läuft... zum Abbrechen klicken',
    lintStatusBar: 'Prüfung läuft... zum Abbrechen klicken',
    ingestStatusAnalyzing: 'Aufnahme läuft... (zum Abbrechen klicken)',
    lintStatusAnalyzing: 'Prüfung läuft... (zum Abbrechen klicken)',
    ingestStageAnalyze: 'Quelle wird analysiert',
    ingestStageSummary: 'Zusammenfassung wird erstellt',
    ingestStageEntity: 'Entität wird erstellt',
    ingestStageConcept: 'Konzept wird erstellt',
    ingestStageRetry: 'Fehlgeschlagene Seite wird wiederholt',
    ingestStageSave: 'Seiten werden gespeichert',
    ingestStageIndex: 'Index wird erstellt',
    pdfStageReading: 'PDF wird gelesen',
    pdfStageConverting: 'PDF wird konvertiert',
    pdfStageSidecar: 'Sidecar-Datei wird geschrieben',
    lintStagePrep: 'Seiten werden gelesen',
    lintStageProgrammatic: 'Links werden gescannt',
    lintStageAnalyzing: 'LLM-Analyse läuft',
    lintStageDedup: 'Duplikate werden erkannt',
    lintStageContradiction: 'Widersprüche werden erkannt',
    ingestionCancelling: 'Wird abgebrochen — Stopp nach aktuellem Batch',
    ingestionCancelled: 'Aufnahme abgebrochen',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: 'Analyse Batch 1/{total}...',
    ingestBatchProgress: 'Analyse Batch {current}/{total} ({entities} Entitäten, {concepts} Konzepte bisher)...',
    ingestBatchProcessed: 'Batch {current} analysiert, Verarbeitung...',
    ingestAnalyzing: 'Analysiere: {filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] Erstelle Zusammenfassung...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}: {name}',
    ingestUpdating: '[{step}/{totalSteps}] Aktualisiere: {name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] Erstelle Index...',
    ingestItemTypeEntity: 'Entität',
    ingestItemTypeConcept: 'Konzept',
    convAnalyzing: 'Analysiere Konversation...',
    convCheckingExisting: 'Prüfe vorhandenes Wissen...',
    convAlreadyExists: 'Dieses Wissen existiert bereits im Wiki',
    convCreatingSummary: 'Erstelle Zusammenfassungsseite...',
    convGeneratingSummary: 'Generiere Zusammenfassungsseite...',
    convSavingEntity: 'Speichere Entität: {name}',
    convSavingConcept: 'Speichere Konzept: {name}',
    convGeneratingIndex: 'Erstelle Index...',

    // Lint Report
    lintReportTitle: 'Wiki-Prüfbericht',
    lintReportSummary: 'Wiki-Statusübersicht: {total} Seiten gesamt, {aliasesMissing} Seiten ohne Aliase, {duplicates} Duplikate, {deadLinks} defekte Links ({deadLinkFromDup} betreffen Duplikate), {orphans} verwaiste Seiten ({orphanFromDup} sind Duplikate), {emptyPages} leere Seiten, {ungroundedQuotes} unbelegte Zitate, {tagViolations} Tags außerhalb des Vokabulars. Lint-Dauer: {elapsedSeconds}s',

    // Advanced LLM Settings (Issues #99 / #128)
    // v1.26.0 (#382 item 2): Name von „Erweiterte Parametereinstellungen" in
    // „LLM-Erweiterte Parameter" geändert — auf LLM-Sampling beschränkt,
    // um es vom generischen „Erweiterte Einstellungen"-Panel unten zu unterscheiden.
    advancedLlmModeName: 'LLM-erweiterte Parameter',
    advancedLlmModeDesc: 'Der Standardmodus folgt den Empfehlungen Ihres Modellanbieters. Wechseln Sie zu „Benutzerdefiniert”, nur wenn Sie einen triftigen Grund zum Überschreiben haben (z. B. ein bestimmtes Modell benötigt eine feste Temperatur, oder Sie möchten die Denkprozessausgabe deaktivieren).',
    advancedSettingsDefault: 'Standard (Anbieter folgen)',
    advancedSettingsCustom: 'Benutzerdefiniert (Anbieter überschreiben)',
    // v1.26.0 (#382 item 2): Panel „Erweiterte Einstellungen" unten — der
    // generische Ort für alle erweiterten Benutzereinstellungen, die keine
    // LLM-Sampling-Parameter sind (Lint-Schwellenwerte, Willkommensnotiz).
    advancedSettingsSection: 'Erweiterte Einstellungen',
    showAdvancedSettingsName: 'Erweiterte Einstellungen anzeigen',
    showAdvancedSettingsDesc: 'Aktivieren, um die erweiterten Einstellungen unten anzuzeigen. Beim Deaktivieren werden sie ausgeblendet und auf die Standardwerte zurückgesetzt.',
    disableThinkingName: 'Thinking deaktivieren',
    disableThinkingDesc: 'Schaltet die Gedankenkette/Denkprozess-Ausgabe des Modells aus. Standardmäßig aus — das Modell entscheidet selbst, ob es Reasoning anzeigt, was in der Regel die beste Antwort ergibt. Schalten Sie dies nur ein, wenn Ihr Anbieter rohen Reasoning-Text in die Antwort einstreut und Sie eine saubere Antwort wünschen.',
    taskPoliciesPlaceholder: 'Beispiel: extract=text:off',
    taskPoliciesName: 'Ausgabemodus und Reasoning je Schritt',
    taskPoliciesDesc: 'Ein Eintrag je Pipeline-Schritt, `schritt=modus:reasoning`, durch Komma getrennt — z. B. `extract=text:off`. Modi: `-` (unverändert), `schema`, `json`, `text`; Reasoning: `-`, `off`, `on`, `low`, `medium`, `high`. Schrittnamen sind u. a. extract, extract-retry, lemma-classify, merge-triage, source-stance, dedup, page-generate, related-page, lint-dedup (ein verschriebener Name trifft nichts). Leer = eingebaute Vorgabe (Extraktion im Textmodus). Ein unlesbarer Eintrag wird nicht gespeichert.',
    // Issue #137: Kompatibilitätshinweise (kurz gehalten; keine Provider-Liste)
    extractionTemperatureName: 'Extraktionstemperatur',
    extractionTemperatureDesc: 'Steuert, ob das Modell beim Schreiben von Entity-/Concept-Seiten eher konservativ oder kreativ vorgeht. Niedrigere Werte = deterministischer und originalgetreuer; höhere Werte = abwechslungsreicher. Die meisten Benutzer lassen dies leer.',
    chatTemperatureName: 'Abfragetemperatur',
    chatTemperatureDesc: 'Gleiches Konzept wie Extraktionstemperatur, betrifft aber nur, wie Query Wiki Fragen beantwortet. Niedrigere Werte = wörtlichere Antworten; höhere Werte = gesprächigere Antworten. Die meisten Benutzer lassen dies leer.',
    repetitionPenaltyName: 'Wiederholungsstrafe',
    repetitionPenaltyDesc: 'Verhindert, dass das Modell dieselben Wörter oder Phrasen wiederholt. Höhere Werte bedeuten weniger Wiederholungen. Nur bestimmte lokale Modellanbieter (Ollama, LM Studio, llama.cpp) akzeptieren diesen Parameter; Cloud-Anbieter ignorieren ihn stillschweigend. Die meisten Benutzer lassen dies leer. Werte über 1,0 können bei kleinen lokalen Modellen während der Extraktion zu LLM-Ausgabefehlern führen — falls ein Lauf fehlschlägt, reduzieren oder leeren Sie diesen Wert.',
    repetitionPenaltyErrorHint: 'Hinweis: Eine benutzerdefinierte Wiederholungsstrafe von {value} ist eingestellt. Werte über 1,0 können die grammatikgebundene Extraktion bei kleinen lokalen Modellen stören — reduzieren oder leeren Sie diese Einstellung und versuchen Sie es erneut.',
    temperaturePlaceholder: 'leer lassen = Anbieter-Standard',
    // v1.26.0 (#382 item 2): Schwellenwerte für die Duplikaterkennung
    // (nur benutzerdefinierter erweiterter Modus).
    lintDedupJaccardLinkThresholdName: 'Link-Duplikat-Ähnlichkeit',
    lintDedupJaccardLinkThresholdDesc: 'Bereich 0–1 (Standard 0.4). Zwei Seiten werden als Duplikate markiert, wenn der Anteil der gemeinsam angesteuerten Wiki-Links an der Gesamt-Linkliste mindestens diesem Wert entspricht. Niedriger → mehr Beinahe-Duplikate werden erfasst (auch Seiten, die nur denselben Hub verlinken); höher → nur Seiten mit nahezu identischen Linkzielen. Erhöhen Sie diesen Wert, wenn unabhängige Seiten fälschlich als Duplikate markiert werden, weil sie denselben Hub verlinken. Leer lassen, um den Standardwert zu verwenden.',
    lintDedupJaccardBodyGateName: 'Mindest-Textähnlichkeit',
    lintDedupJaccardBodyGateDesc: 'Bereich 0–1 (Standard 0.2). Auch wenn zwei Seiten Wiki-Links gemeinsam haben, werden sie nur dann als Duplikate markiert, wenn ihre Textkörper mindestens diesen Ähnlichkeitswert erreichen. Niedriger → mehr Kandidaten gelangen zur LLM-Prüfung; höher → nur nahezu identische Textkörper werden markiert. Erhöhen Sie diesen Wert, wenn das LLM offensichtlich nicht-duplizierte Seiten prüfen muss. Leer lassen, um den Standardwert zu verwenden.',
    lintDedupBigramThresholdName: 'Titel-Ähnlichkeit',
    lintDedupBigramThresholdDesc: 'Bereich 0–1 (Standard 0.4). Zwei Seiten werden als Duplikate markiert, wenn die Zeichen ihrer Titel (oder Aliase) mindestens zu diesem Anteil übereinstimmen. Niedriger → Schreibvarianten, Tippfehler und Übersetzungen desselben Konzepts werden erfasst; höher → nur nahezu identische Titel werden markiert. Erhöhen Sie diesen Wert, wenn das LLM Seiten mit sehr unterschiedlichen Namen prüfen muss, die keine Duplikate sind. Leer lassen, um den Standardwert zu verwenden.',
    lintDeadLinkSection: 'Defekte Links (erkannt) [{count}]',
    lintEmptyPageSection: 'Leere Seiten (erkannt) [{count}]',
    lintOrphanSection: 'Verwaiste Seiten (erkannt) [{count}]',
    lintContradictionSection: 'Widersprüche (erkannt)',
    lintDuplicateSection: 'Doppelte Seiten (erkannt)',
    lintNoIssuesFound: 'Keine Duplikate, defekten Links, leeren Seiten, verwaisten Seiten oder unbelegten Zitate erkannt.',
    lintSourceDriftSection: 'Quellnotizen seit dem Ingest geändert [{count}]',
    lintSourceDriftItem: '- [[{page}]] — Ursprungsnotiz [[{note}]] wurde nach dem Ingest bearbeitet; die Seite ist womöglich veraltet',
    lintContradictionMarkerSection: 'Seiten mit Widerspruchs-Marker (Merge-Triage) [{count}]',
    lintContradictionMarkerItem: '- [[{page}]] — widersprechende Quelle(n): {sources}; nach der Sichtung den contradictions:-Marker entfernen',
    lintQuoteGroundingSection: 'Unbelegte Zitate (erkannt) [{count}]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: "{quote}"',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (Seite existiert nicht){dupFlag}',
    lintDeadLinkMore: '- ... {count} weitere defekte Links',
    lintEmptyPageItem: '- [[{page}]] — weniger als 50 Zeichen substanziellen Inhalts',
    lintOrphanItem: '- [[{page}]] — keine anderen Wiki-Seiten verweisen hierher{dupFlag}',
    lintPollutedSection: 'Verschmutzte Seiten (erkannt) [{count}]',
    lintPollutedItem: '- [[{page}]] → sollte "{clean}" sein',
    lintSourcesNormalizedSection: 'Sources normalisiert (automatisch repariert) [{files} Dateien / {entries} Einträge]',
    lintSourcesNormalizedItem: '{entries} verschmutzte sources-Einträge in {files} Datei(en) bereinigt (externe Pfade, .md-Erweiterungen, Alias-Pipes entfernt und dedupliziert).',
    lintDuplicateItem: '- [[{target}]] und [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ betrifft doppelte Seite)',
    lintOrphanIsDuplicate: ' (⚠️ doppelte Seite)',
    lintHubLinkDensitySection: 'Hub-Link-Dichte-Probleme (Issue #157 / #175) [{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} eingehend, {relatedCount} verwandte Links, Unterscheidbarkeit {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ entfernen',
    lintHubLinkDensityReview: '🔍 prüfen',
    lintHubLinkDensityKeep: '✅ behalten',
    lintHubLinkDensitySummary: 'Zusammenfassung: {strip} Seite(n) zum Entfernen empfohlen, {review} Seite(n) zur Prüfung.',
    lintHubLinkDensityNoRelated: ' (kein ## Related-Abschnitt gefunden)',
    lintContradictionOpen: 'Offene Widersprüche: {count}',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: 'Erkannt',

    // Lint Analysis Prompt

    // Lint Fix Progress
    lintFixProgress: 'Behebung {current}/{total}: [[{target}]]',
    lintFixDeadComplete: 'Behebung defekter Links abgeschlossen. {fixed}/{total} Elemente behoben.',
    lintFillProgress: 'Erweiterung {current}/{total}: {page}',
    lintFillComplete: 'Seitenerweiterung abgeschlossen. {filled}/{total} Seiten gefüllt.',
    lintDeleteCompleted: '{count} leere Stubs gelöscht',
    lintDeleteFailed: 'Fehler beim Löschen von {failed}/{total} leeren Stubs (Details in der Konsole)',
    lintFillFailed: 'Erweiterung fehlgeschlagen: {page} — {error}',
    lintLinkProgress: 'Verlinkung {current}/{total}: {page}',
    lintLinkComplete: 'Verwaiste-Seiten-Verlinkung abgeschlossen. {linked} Seiten verlinkt.',
    lintFixNoAction: 'Keine Maßnahme ergriffen (kein Client)',
    lintFixIndexUpdated: 'Wiki-Index und Protokoll aktualisiert.',
    lintPollutedFixed: 'Beschädigte Seiten behoben: {fixed}/{total}. Index neu generiert.',
    regenerateIndexCompleted: 'Index neu generiert',
    operationFailed: 'Fehlgeschlagen: ',
    lintFixAllComplete: 'Alle Behebungen abgeschlossen. Details im Protokoll.',
    lintFixAllNoChanges: 'Keine Änderungen — alle Phasen meldeten 0 Behebungen. Details in wiki/log.md.',
    lintFixPhasesLabel: 'Phasen geändert',

    // Lint Report Modal
    lintModalActionsTitle: 'Behebungsvorschläge (benötigt LLM-Tokens):',
    lintLogReference: 'Vollständiger Bericht in log.md gespeichert',
    lintModalFixDeadLinks: 'Defekte Links beheben ({count})',
    lintModalExpandEmpty: 'Leere Seiten erweitern ({count})',
    lintModalDeleteEmpty: 'Leere Stubs löschen ({count})',
    lintModalLinkOrphans: 'Verwaiste Seiten verlinken ({count})',
    lintModalAnalyzeSchema: 'Schema analysieren',
    lintModalMergeDuplicates: 'Duplikate zusammenführen ({count})',
    lintModalFixAll: 'Intelligente Gesamtbehebung ({count} Probleme)',
    lintMergeProgress: 'Zusammenführung {current}/{total}: {source} → {target}',
    lintMergeComplete: 'Duplikat-Zusammenführung abgeschlossen. {merged}/{total} Paare zusammengeführt.',

    // Ingest Report Modal
    ingestReportTitle: 'Aufnahmebericht',
    ingestReportSourceFile: 'Quelldatei',
    ingestReportCreated: 'Erstellt',
    ingestReportUpdated: 'Aktualisiert',
    ingestReportContradictions: 'Widersprüche gefunden',
    ingestReportFailedTitle: 'Aufnahme fehlgeschlagen',
    ingestReportErrorDetail: 'Fehlerdetail',
    ingestReportClose: 'Schließen',
    ingestReportCreatedPages: 'Erstellte Seiten: {count}',
    ingestReportUpdatedPages: 'Aktualisierte Seiten: {count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki Betriebsprotokoll',
    logHeaderSubtitle: 'Jede Aufnahme, Lint-Ausführung und Wartungsoperation wird hier automatisch aufgezeichnet. Für eine bessere Ansicht nutzen Sie das **Betriebsverlauf**-Panel:',
    logHeaderShortcut: 'Cmd+P → "Betriebsverlauf anzeigen"',
    logHeaderSettingsShortcut: 'Oder über Einstellungen → Automatische Wartung → Betriebsverlauf',
    ingestionCreatedPages: '{count} Seite(n) erstellt',
    ingestionUpdatedPages: '{count} Seite(n) aktualisiert',
    ingestionNoticeHistoryHint: 'Details im Betriebsverlauf anzeigen',
    ingestReportEntitiesCount: '{count} Entitäten',
    ingestReportConceptsCount: '{count} Konzepte',
    ingestReportContradictionsFound: 'Gefundene Widersprüche: {count}',
    ingestReportEntityType: 'Entität',
    ingestReportConceptType: 'Konzept',
    timeMinutes: 'Min',
    timeSeconds: 'Sek',

    // Ratenbegrenzungs-Warnungen
    rateLimitDetected: '⚠️ Ratenbegrenzung erkannt: {count} Seite(n) mit 429-Fehlern fehlgeschlagen. Empfehlungen: (1) Parallelität auf {suggestedConcurrency} oder 1 (seriell) reduzieren, (2) Batch-Verzögerung auf {suggestedDelay}ms erhöhen, (3) Zu einem Anbieter mit höheren Ratenbegrenzungen wechseln.',
    rateLimitDetectedShort: '⚠️ Ratenbegrenzung erreicht — Reduzieren Sie die Parallelität oder erhöhen Sie die Batch-Verzögerung in Einstellungen → Aufnahmebeschleunigung.',

    longSourceNotice: '📄 "{filename}" hat {lines} Zeilen ({size}). Lange Texte erfordern iterative Stapel-Extraktion — das LLM liest das gesamte Dokument in mehreren Durchläufen. Dies kann einige Minuten dauern. Bitte haben Sie Geduld.',
    longSourceNoticeShort: '📄 Große Datei erkannt ({lines} Zeilen). Die Ingestion kann einige Zeit dauern.',

    // Ingestionsverlauf-Panel (#122) — UI-Texte
    historyButton: 'Operationsverlauf',
    historyButtonDesc: 'Letzte Ingestionen, Lint-Berichte und andere Änderungen Ihres Wikis anzeigen',
    historyButtonOpen: 'Verlauf anzeigen',
    historyModalTitle: 'Operationsverlauf',
    historyModalSubtitle: 'Letzte Änderungen Ihres LLM-Wikis',
    historyEmpty: 'Noch keine Operationen aufgezeichnet. Ingestiere eine Notiz oder führe Lint aus, um diese Liste zu füllen.',
    historyReadError: 'Operationsprotokoll konnte nicht gelesen werden: {error}',
    historyEntryKindIngest: 'Ingestion',
    historyEntryKindMaintenance: 'Wartung',
    historyEntryKindFix: 'Korrektur',
    historyEntryKindOther: 'Sonstige',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'Quelle: {source}',
    historyEntrySourceUnknown: 'Unbenannter Ingest',
    historyEntryCreatedLabel: 'Erstellt',
    historyEntryUpdatedLabel: 'Aktualisiert',
    historyEntryCreatedCount: '{count} erstellt',
    historyEntryUpdatedCount: '{count} aktualisiert',
    historyEntryNoChanges: 'Keine Seitenänderungen',
    historyEntryContradictions: '⚠️ {count} Widerspruch(e)',
    historyEntrySectionCreated: 'Erstellte Seiten',
    historyEntrySectionUpdated: 'Aktualisierte Seiten',
    historyEntrySectionContradictions: 'Widersprüche',
    historyEntrySectionDetails: 'Details',
    historyEntryOpenPage: 'Öffnen',
    historyEntryDetailsNoContradictions: 'Keine Widersprüche gefunden',
    historySearchPlaceholder: '🔍 Nach Quelltitel oder Seitenpfad suchen…',
    historyFilterAll: 'Alle',
    historyFilterIngest: 'Nur Ingest',
    historyFilterMaintenance: 'Nur Wartung',
    historyFilterFix: 'Nur Korrektur',
    historyFilterContradictions: '⚠️ Mit Widersprüchen',
    historyRefreshButton: '⟳ Aktualisieren',
    historyExpandDay: 'Zum Erweitern klicken',
    historyCollapseDay: 'Zum Einklappen klicken',
    historyShowMore: '{count} ältere Einträge anzeigen',
    historyNoMatch: 'Keine Operationen entsprechen Ihrer Suche/Ihrem Filter.',
    historyCloseButton: 'Schließen',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'Berichts-Befunde',
    historyKpiPages: 'Seiten',
    historyKpiDeadLinks: 'Tote Links',
    historyKpiOrphans: 'Verwaist',
    historyKpiEmpty: 'Leer',
    historyKpiDuplicates: 'Duplikate',
    historyKpiTagViolations: 'Tag-Probleme',
    historyKpiUnsourced: 'Unbelegt',
    historyKpiDuration: 'Lint-Zeit',
    historyKpiDurationSec: '{seconds}s',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'Tote Links ({count})',
    historySectionTagViolations: 'Tag-Verstöße ({count})',
    historySectionOrphans: 'Verwaiste Seiten ({count})',
    historySectionEmptyPages: 'Leere Seiten ({count})',
    historySectionLlmAnalysis: 'LLM-Analyse ({count})',
    historyDeadLinkSource: 'Quelle',
    historyDeadLinkTarget: 'Fehlt',
    historyOpenInLog: 'In log.md öffnen',
    historyShowMoreItems: '{count} weitere ausklappen',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ unverändert',
    historyChipContradiction: 'Widerspruch',
    historyChipOutdated: 'Veraltet',
    historyChipMissing: 'Fehlt',
    historyChipStructure: 'Struktur',
    historySeverityHigh: 'Hoch',
    historySeverityMedium: 'Mittel',
    historySeverityLow: 'Niedrig',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Ihr Wiki hat {dead} tote Links, {orphans} verwaiste Seiten und {tags} Tag-Probleme. Letzte Lint-Dauer: {duration}.',
    historyGlobalInsightClean: 'Ihr Wiki ist sauber — keine toten Links, verwaisten Seiten oder Tag-Probleme erkannt.',
    historyGlobalInsightNoData: 'Noch keine Wartungsberichte — führen Sie Lint aus.',
    historyModalHeaderTitle: 'Operationsverlauf',
    historyModalSubtitleWithCount: 'Letzte Änderungen Ihres LLM-Wikis · {count} Einträge',
    historyTimeRangeAll: 'Gesamter Zeitraum',
    historyTimeRange1d: 'Letzter Tag',
    historyTimeRange3d: 'Letzte 3 Tage',
    historyTimeRange1w: 'Letzte Woche',
    historyTimeRange1m: 'Letzter Monat',
    historyIngestTotal: 'Seiten gesamt',
    historyIngestByType: 'Nach Typ',
    historyIngestSource: 'Quelldatei',
    historyIngestNoTimestamp: 'Kein Zeitstempel',
    historyIngestFirstTime: 'Erste Ingestion',
    historyIngestLatestTime: 'Letzte Ingestion',
    historyTimeRangeCustom: 'Benutzerdef. Zeitraum',
    historyCustomRangeFrom: 'Von',
    historyCustomRangeTo: 'Bis',
    historyCustomRangeApply: 'Anwenden',
    historyCustomRangeClear: 'Zurücksetzen',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki: Vault ist leer. Erstelle deine erste Quellennotiz und führe Ingest aus, um zu beginnen.',
    welcomeNoteTierBNotice: 'Karpathy Wiki: Eine Welcome-Notiz wurde erstellt. Öffne sie, um deine Themenbereiche zu deklarieren und 2-3 Quellnotizen als Seed für den Link-Graphen auszuwählen.',
    welcomeNoteRecreateCommand: 'Wiki-Willkommen-Notiz neu erstellen',
    welcomeNoteRecreateCommandTooltip: 'Erstellt die Welcome-Notiz unter <wikiFolder>/Welcome.md mit aktuellen Themen-Seeds und LLM-Konfigurationstest neu. Existierende Datei wird überschrieben.',
    welcomeNoteSettingsToggle: 'Wiki-Willkommen-Notiz beim ersten Start erstellen',
    welcomeNoteSettingsToggleDesc: 'Erstellt beim ersten Start (wenn der Wiki-Ordner leer ist) eine einseitige Einstiegsnotiz unter <wikiFolder>/Welcome.md. Sie erklärt, was LLM-Wiki tut, fordert zur Angabe Ihres Domain-Fokus auf und führt durch die ersten 2-3 Quellnotizen. Die Notiz wird standardmäßig auf Englisch geschrieben; wenn ein LLM konfiguriert ist, in Ihrer Wiki-Sprache. Deaktivieren Sie dies, wenn Sie das Plugin bereits kennen und keine Einführungsnotiz wünschen.',
    welcomeNoteRunConfigTest: 'Wiki-Willkommen-Notiz wurde auf Englisch geschrieben. Öffne Einstellungen → LLM Provider → Test Connection, um sie beim nächsten Erstellen zu lokalisieren.',
    welcomeNoteRecreated: 'Wiki-Willkommen-Notiz neu erstellt unter {path}',
    welcomeNoteNotRecreated: 'Willkommen-Notiz wurde nicht neu erstellt. LLM-Konfiguration prüfen.',
    welcomeNoteGenerating: 'Wiki-Willkommen-Notiz wird im Hintergrund erstellt — Benachrichtigung erscheint, wenn fertig.',
    welcomeNoteGenerationFailed: 'Wiki-Willkommen-Notiz-Erstellung fehlgeschlagen: {error}',
    startupCheckWelcomePending: 'Willkommen-Notiz: wird im Hintergrund erstellt (Benachrichtigung erscheint, wenn fertig).',
    welcomeNoteFileName: 'Willkommen bei Karpathy LLM Wiki',
    startupCheckWelcomeCreated: 'Willkommen-Notiz erstellt unter {path}',
    // v1.23.0 Phase 5.1.5: Schaltfläche "Alle abbrechen" im Multi-Datei-Auswahl-Modal.
    // Bricht alle ausstehenden und laufenden Jobs in der Warteschlange ab.
    // Abgeschlossene und fehlgeschlagene Jobs bleiben zur Ansicht erhalten.
    cancelAllQueueJobs: 'Alle abbrechen',
    // v1.23.0 Phase 5.1.5: Multi-File-Suggest-Modal (cmdIngestMultipleFiles).
    // Titel, Hinweis, Suchplatzhalter, Schaltflächen, Statusbezeichnungen,
    // Platzhalter für leere Warteschlange.
    multiFileModalTitle: 'Mehrere Dateien importieren',
    multiFileModalHint: 'Wähle Quellnotizen für den Import. Der rechte Bereich zeigt die Live-Warteschlange und den Fortschritt.',
    multiFileSearchPlaceholder: 'Dateien nach Pfad filtern…',
    multiFileAddToQueue: 'Zur Warteschlange hinzufügen',
    multiFileSelectAll: 'Alle auswählen',
    multiFileFileCount: '{count} Datei(en)',
    multiFileNoFilesAvailable: 'Keine Dateien zum Importieren verfügbar.',
    multiFileNoFilesMatch: 'Keine Dateien gefunden für "{q}".',
    multiFileQueueEmpty: 'Warteschlange leer. Markiere links Dateien zum Hinzufügen.',
    multiFileStatusPending: 'Ausstehend',
    multiFileStatusRunning: 'Läuft',
    multiFileStatusCompleted: 'Abgeschlossen',
    multiFileStatusFailed: 'Fehlgeschlagen',
    multiFileCancelAria: 'Diese Datei abbrechen',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: 'Importiert',
    multiFileRowDrifted: 'Notiz seit dem Import geändert',
    startupCheckNoticeLevelName: 'Quick-Fix-Ergebnis anzeigen',
    startupCheckNoticeLevelDesc: 'QuickFixes laufen beim Plugin-Start immer (Willkommensnotiz, Ordnerstruktur, Quellen-Normalisierung, unvollständige Seiten, Log-Header). Wähle, ob die Zusammenfassungs-Notiz nach dem Start angezeigt wird. Im Silent-Modus wird nur in die Entwicklerkonsole und das Operationsverlaufs-Panel geschrieben.',
    startupCheckNoticeVisible: 'Sichtbar (Notiz anzeigen)',
    startupCheckNoticeSilent: 'Stumm (keine Notiz)',
} as const;
