export const ES_TEXTS = {
    // Plugin Info
    pluginTitle: 'Karpathy LLM Wiki Configuración',
    pluginIntro: 'Este plugin implementa el concepto de {{link}} para Obsidian. Lee tus notas, usa IA para extraer entidades, conceptos y relaciones, y construye una Wiki estructurada e interconectada en tu vault.',
    karpathyLinkText: 'Wiki LLM de Andrej Karpathy',

    // Features Section
    featuresTitle: 'Cómo funciona',
    workflow1Title: '1. Ingestión',
    workflow1Desc: 'Selecciona una nota — la IA extrae entidades, conceptos y relaciones en páginas Wiki.',
    workflow2Title: '2. Consulta',
    workflow2Desc: 'Chatea con tu Wiki — las respuestas se fundamentan en tu conocimiento ingerido.',
    workflow3Title: '3. Mantenimiento',
    workflow3Desc: 'Índice autogenerado, enlaces cruzados y verificaciones lint mantienen la Wiki saludable.',

    // Language Switcher
    languageTitle: 'Idioma de la interfaz',
    languageDesc: 'Selecciona tu idioma preferido para el panel de configuración. Reinicia el plugin para aplicar los cambios de idioma a la paleta de comandos.',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // Status
    statusTitle: 'Estado del cliente LLM',
    llmWikiStatusSection: 'Estado de LLM-Wiki',
    statusInitialized: 'Inicializado',
    statusReady: 'LLM listo',
    statusNotReady: 'LLM no configurado — complete la configuración y pase la prueba de conexión',
    statusNotInitialized: 'No inicializado',
    currentProvider: 'Proveedor actual',

    // Provider Configuration
    providerSection: 'Configuración LLM',
    providerName: 'Proveedor LLM',
    providerDesc: 'Selecciona un proveedor predefinido o un servicio compatible con OpenAI personalizado. Para Coding Plan o bundles similares: elige Custom OpenAI/Anthropic, ingresa manualmente el Base URL y API Key del proveedor',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: 'Clave API. Se guarda en el gestor de credenciales del sistema, no en data.json.',
    apiKeyPlaceholder: 'Introduce la API Key',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: 'Migrar SecretStorage',
    apiKeyMigratedToSecretStorageSuccess: 'API Key restaurada de SecretStorage a configuración.',
    apiKeyMigrationFailedNotice: 'Error al guardar la API Key en SecretStorage: {}',
    codexAuthName: 'Inicio de sesión del plan ChatGPT',
    codexAuthDesc: 'Acceso experimental a Codex mediante OAuth usando la asignación de tu plan ChatGPT. La facturación de la API de OpenAI Platform se mantiene separada.',
    codexAuthSignedOut: 'Sesión no iniciada',
    codexAuthSignedIn: 'Sesión iniciada',
    codexAuthBrowserButton: 'Iniciar sesión con el navegador',
    codexAuthDeviceButton: 'Usar código de dispositivo',
    codexAuthDeviceInstructions: 'Introduce este código en la página de OpenAI: {}',
    codexAuthCopyCode: 'Copiar código',
    codexAuthSignOutButton: 'Cerrar sesión',
    codexAuthBusy: 'Esperando la autorización de OpenAI...',
    codexAuthFailed: 'Error de autorización de ChatGPT: {}',
    codexAuthQuota: 'Se alcanzó la asignación de ChatGPT Codex. Espera al período de restablecimiento indicado y vuelve a intentarlo.',
    codexAuthExperimental: 'Experimental: la disponibilidad depende de las políticas de autenticación y modelos de OpenAI Codex.',
    codexModelsRefreshName: 'Modelos de la cuenta',
    codexModelsRefreshDesc: 'Sincroniza los modelos seleccionables de la cuenta de OpenAI Codex conectada.',
    codexModelsRefreshButton: 'Actualizar modelos de cuenta',
    codexModelsRefreshing: 'Actualizando...',
    codexModelsRefreshSuccess: 'Se sincronizaron {} modelos de la cuenta.',
    codexModelsRefreshFailed: 'No se pudieron actualizar los modelos de la cuenta; se usa la lista alternativa disponible. {}',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: 'Requerido: endpoint personalizado compatible con OpenAI',
    baseUrlDescOverride: 'Opcional: sobrescribe la Base URL preconfigurada',

    // Ollama Hint
    ollamaHint: 'Ollama se ejecuta localmente, no requiere API Key',
    lmstudioHint: 'LM Studio se ejecuta localmente, API Key es opcional',
    maxTokensPerCallName: 'Máx. tokens de salida por llamada',
    maxTokensPerCallDesc: 'Limita cuántos tokens puede generar el modelo en una sola respuesta. Reduce si usas un modelo local con ventana de contexto pequeña y ves errores. Para modelos en la nube, mantén el valor predeterminado (0 = sin límite).',

    slugCaseName: 'Mayúsculas en nombres de archivo',
    slugCaseDesc: "Controla si los nombres de archivo Wiki generados se ponen en minúsculas. Se recomienda 'Conservar' para idiomas donde las mayúsculas son significativas (p. ej. sustantivos alemanes).",
    slugCaseLower: 'Minúsculas (predeterminado)',
    slugCasePreserve: 'Conservar mayúsculas',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: 'Longitud mínima de alias',
    minAliasLengthDesc: 'Los alias más cortos (tras recortar espacios) no se escriben en las páginas del wiki. El valor 2 mantiene usables las abreviaturas de dos letras (ML, IA, UI); súbalo a 3 si su bóveda acumula alias de dos letras que solo difieren en mayúsculas (Cr/CR). Rango 2–6.',
    minAliasLengthClamped: 'Valor fuera de rango (2–6), ajustado a {}',

    // Model Selection
    modelSection: 'Selección del modelo',
    fetchModelsName: 'Obtener modelos disponibles',
    fetchModelsDesc: 'Obtiene la lista de modelos más reciente desde la API del proveedor',
    fetchModelsButton: 'Obtener modelos',
    fetchingModels: 'Obteniendo...',
    fetchSuccess: '¡Correcto! {} modelos disponibles',
    fetchFailed: 'Error o lista vacía. Introduce el nombre del modelo manualmente',
    fetchNotSupported: 'El proveedor no admite consultas de lista de modelos',
    fetchErrorAuth: 'Autenticación fallida (HTTP 401/403). Verifica la clave API, o introduce un ID de modelo y haz clic en Probar conexión.',
    fetchErrorEndpoint: 'Endpoint no encontrado (HTTP 404). Verifica la URL del endpoint, o introduce un ID de modelo y haz clic en Probar conexión.',
    fetchErrorServer: 'Error del servidor del proveedor (HTTP 5xx). Inténtalo más tarde, o introduce un ID de modelo y haz clic en Probar conexión.',
    fetchErrorEmpty: 'Este endpoint no expone lista de modelos. Introduce un ID de modelo y haz clic en Probar conexión.',
    fetchErrorNetwork: 'Falló la solicitud de red. Verifica tu conexión a internet, la URL del endpoint, la configuración del proxy o la clave API. También puedes introducir un ID de modelo y hacer clic en Probar conexión.',

    selectModelName: 'Seleccionar modelo',
    selectModelDesc: 'Elige entre {} modelos disponibles',
    customInputOption: 'Entrada personalizada...',
    customInputHint: 'Para usar otros modelos, selecciona "Entrada personalizada..."',

    modelName: 'Nombre del modelo',
    modelDescCustom: 'Usando modelo personalizado (pulsa el botón de arriba para volver a obtener la lista)',
    modelDescFetchFailed: 'Error al obtener la lista de modelos. Verifica la clave API y la URL del endpoint, o introduce un ID de modelo y haz clic en Probar conexión.',
    modelInputPlaceholder: 'Introduce el ID del modelo y prueba la conexión',

    switchToDropdown: 'Cambiar a selección con menú desplegable',
    useDropdownButton: 'Usar menú desplegable',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: 'Alcance del modelo',
    modelTaskModeDesc: 'Elija si todas las tareas usan el mismo modelo o si usa modelos diferentes por tarea (ingesta / mantenimiento y reparación / consulta). Los valores por tarea ocultos se conservan al volver al modelo unificado.',
    modelTaskModeUnified: 'Usar modelo unificado (predeterminado)',
    modelTaskModePerTask: 'Usar modelos diferentes por tarea',
    perTaskIngestModelName: 'Modelo de ingesta',
    perTaskIngestModelDesc: 'Se usa para ingerir notas, conversaciones, mantenimiento del esquema y generación de la nota de bienvenida.',
    perTaskLintModelName: 'Modelo de mantenimiento y reparación',
    perTaskLintModelDesc: 'Se usa para análisis Lint, detección de duplicados, ejecuciones de reparación y corrección de enlaces huérfanos.',
    perTaskQueryModelName: 'Modelo de consulta',
    perTaskQueryModelDesc: 'Se usa para el chat Query Wiki y la evaluación de guardado en Wiki.',

    // Test & Save
    testConnectionName: 'Probar conexión',
    testConnectionDesc: 'Valida que la configuración puede llamar correctamente a la API LLM',
    testButton: 'Probar conexión',
    testing: 'Probando...',

    saveSettingsName: 'Guardar configuración',
    saveSettingsDesc: 'Guarda la configuración actual',
    saveButton: 'Guardar configuración',
    testConnectionSuccessful: 'Conexión exitosa',
    testConnectionFailed: 'Conexión fallida',
    testConnectionProvider: 'Proveedor: ',
    codexAuthRequired: 'Inicia sesión en el plan ChatGPT antes de probar la conexión.',
    bedrockSsoRequired: 'Inicie sesión con AWS SSO (Ajustes → Bedrock) antes de probar la conexión.',
    bedrockIamRequired: 'Introduzca sus claves de acceso de IAM (Ajustes → Bedrock) antes de probar la conexión.',
    bedrockAuthMethodName: 'Autenticación',
    bedrockAuthMethodDesc: 'Clave API usa una clave de API de Bedrock; AWS SSO firma las solicitudes con credenciales de IAM Identity Center; las claves IAM usan claves de acceso estáticas.',
    bedrockAuthOptionApiKey: 'Clave API',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'Claves IAM',
    bedrockSsoStartUrlName: 'URL de inicio de SSO',
    bedrockSsoStartUrlDesc: 'URL del portal de su organización, p. ej. https://d-xxxxxxxxx.awsapps.com/start',
    bedrockSsoAccountIdName: 'ID de cuenta de AWS',
    bedrockSsoAccountIdDesc: 'Cuenta de 12 dígitos cuyo rol se asumirá, p. ej. 123456789012',
    bedrockSsoRoleNameName: 'Nombre del rol',
    bedrockSsoRoleNameDesc: 'Rol de IAM que se asumirá para el acceso a Bedrock, p. ej. PowerUserAccess',
    bedrockSsoLoginButton: 'Iniciar sesión con AWS SSO',
    bedrockSsoSignOutButton: 'Cerrar sesión de AWS SSO',
    bedrockSsoStatusSignedIn: 'Sesión iniciada · caduca {}',
    bedrockSsoStatusSignedOut: 'Sin sesión iniciada',
    bedrockSsoBusy: 'Inicio de sesión en curso…',
    bedrockSsoUserCodeInstructions: 'Código de AWS SSO: {}. Abra el enlace y apruebe el acceso.',
    bedrockSsoCopyCode: 'Copiar código',
    bedrockSsoFailed: 'Error al iniciar sesión con AWS SSO: {}',
    bedrockSsoDetectedPrefill: 'Cuenta/rol detectados: {}',
    bedrockIamKeyName: 'ID de clave de acceso',
    bedrockIamKeyDesc: 'Identificador de la clave de acceso de IAM, p. ej. AKIA… o ASIA…',
    bedrockIamSecretName: 'Clave de acceso secreta',
    bedrockIamSecretDesc: 'Se guarda solo en el almacenamiento de secretos de este dispositivo, nunca en data.json',
    bedrockIamSessionTokenName: 'Token de sesión (opcional)',
    bedrockIamSessionTokenDesc: 'Solo es necesario para credenciales temporales (STS)',
    bedrockIamClearButton: 'Borrar claves IAM guardadas',
    bedrockIamSaveFailed: 'Error al guardar las claves IAM: {}',
    errorUnknown: 'Error desconocido',
    savedNotice: '¡Configuración guardada!',

    // v1.24.0 (Bug C 3.4 / plan C): notificación de migración gradual
    queryHistoryMigrationNotice: 'El historial de Query Wiki contiene enlaces de una carpeta wiki anterior. Las nuevas consultas usan automáticamente la carpeta más reciente. Para actualizar todos los mensajes almacenados, abra el panel de Query Wiki y haga clic en el botón "Borrar historial" que aparece allí.',

    // v1.24.0 Issue #251: instrucciones de Query personalizadas (panel desplegable)
    customInstructionsTitle: 'Instrucciones de Query personalizadas',
    customInstructionsDesc: 'Instrucciones persistentes que se añaden al final del prompt del sistema de Query Wiki. Solo afectan al chat de Query Wiki; la ingestión, lint y generación de páginas no se ven afectadas.',
    customInstructionsPlaceholder: 'p. ej. Trátelo como tarea de investigación: buscar ampliamente, citar fuentes, separar hechos de interpretación...',
    customInstructionsApply: 'Aplicar',
    customInstructionsClear: 'Borrar',
    customInstructionsCharCount: '{current}/{max} caracteres',
    instructionsApplied: 'Instrucciones de Query personalizadas guardadas.',
    instructionsCleared: 'Instrucciones de Query personalizadas borradas.',

    // Issue #137: Avisos de fallback de LLM
    fallbackThinkingDialect: 'Control de pensamiento: cambiado al dialecto "{dialect}" (este proveedor usa un formato diferente). La salida no cambia.',
    fallbackThinkingNone: 'Control de pensamiento completamente deshabilitado para este proveedor. Puede seguir apareciendo contenido de razonamiento; si ocurre, pruebe con otro modelo.',
    fallbackParamStripped: 'El parámetro "{field}" no es compatible con este proveedor. Se ha eliminado de la solicitud; el comportamiento puede diferir de la configuración.',

    // Wiki Folder
    wikiSection: 'Configuración del Wiki',
    wikiFolderName: 'Carpeta Wiki',
    // v1.24.0: indica que se requiere reiniciar Obsidian tras un cambio
    // (las cachés del motor y los paneles abiertos de Query Wiki deben rebindearse).
    wikiFolderDesc: 'Ubicación para las páginas Wiki generadas. Reinicie Obsidian tras el cambio — las cachés del motor y los paneles abiertos de Query Wiki deben rebindearse.',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'Configura primero la API Key',
    errorNoModel: 'Selecciona primero un modelo: pulsa «Obtener modelos» o introduce un Model ID manualmente',
    llmNotReady: 'LLM no está configurado. Vaya a Configuración → Karpathy LLM Wiki para configurar su proveedor y pasar la prueba de conexión.',
    errorFetchFailed: 'Error: {}',

    // Query Settings
    querySectionTitle: 'Configuración de consulta Wiki',
    // v1.24.0: renombrado de "Máximo de historial de conversación" a
    // "Rondas de memoria de conversación" para mayor claridad.
    // 1 = cada turno independiente (sin memoria entre turnos).
    // El ajuste es un desplegable, no hace falta listar valores preestablecidos.
    // v1.24.0: maxConversationHistoryHint era una clave i18n sin uso;
    // la recomendación se integró en la descripción.
    maxConversationHistoryName: 'Rondas de memoria de conversación',
    maxConversationHistoryDesc: 'Cuántas rondas de conversación pasadas ve el LLM como memoria. 1 = cada turno independiente (sin memoria entre turnos); valores más altos permiten al modelo recordar turnos anteriores de la sesión. Recomendado: 1 para Q&A puntual, 10–50 para investigación continua.',
    numberRangeValidation: 'Introduce un número entre 1 y 50',
    numberRangeClamped: 'Valor fuera del rango (1-500), automáticamente establecido a {}',
    // Query Modal UI
    queryModalTitle: 'Consultar Wiki - Consulta conversacional',
    queryModalPlaceholder: 'Introduce una pregunta...',
    queryModalSendButton: 'Enviar',
    queryModalStopButton: 'Detener',
    queryModalSaveButton: 'Guardar en Wiki',
    queryModalClearButton: 'Limpiar historial',
    queryModalHistoryCount: 'Historial de conversación: {}/{} rondas',
    queryModalStreaming: 'Transmisión en curso...',
    queryModalFallbackStreaming: 'Transmisión no disponible, cambiado a modo sin transmisión. Espera...',
    queryPhaseSearching: 'Analizando índice Wiki, seleccionando páginas relevantes...',
    queryPhaseFoundPages: 'Se encontraron {count} página(s): {pages}',
    queryPhaseLoadingPages: 'Cargando contenido de las páginas...',
    queryPhaseContextReady: 'Contexto listo. Generando respuesta...',
    queryPhaseGenerating: 'Generando... (transcurrido {time}s)',
    queryPhaseNonStreaming: 'Modo sin transmisión, generando respuesta... (transcurrido {time}s)',
    queryModalErrorPrefix: 'Error: ',
    queryModalHint: 'Las consultas se basan en el contenido de la Wiki. Pulsa "Guardar en Wiki" para extraer conversaciones valiosas como páginas Wiki.',

    // v1.20.0: Resumen del bloque de pensamiento plegable de Query Wiki
    queryThinkingSummary: 'Proceso de pensamiento',
    queryThinkingSteps: 'pasos',

    // Error Messages
    errorLLMClientNotInit: 'Cliente LLM no inicializado. Guarda la configuración.',
    errorIngestFailed: 'La ingestión falló: ',
    errorQueryFailed: 'La consulta falló: ',
    fileWriteFailed: 'No se pudo crear ni actualizar el archivo: {path}',

    // Success Messages
    ingestSuccess: 'Ingestión completada: {} páginas creadas, {} páginas actualizadas',
    querySuccess: 'Consulta completada',
    lintSuccess: 'Verificación lint de Wiki completada',
    lintReadingPages: 'Leyendo {count} páginas Wiki...',
    lintReadingPagesProgress: 'Leyendo páginas Wiki: {current}/{total}...',
    lintScanningLinks: 'Escaneando enlaces rotos...',
    lintScanningLinksProgress: 'Escaneando enlaces rotos: {current}/{total}...',
    lintCheckingDuplicates: 'Buscando páginas duplicadas...',
    lintCheckingDuplicatesProgress: 'Verificando duplicados: lote {current} ...',
    lintFixingPolluted: 'Reparando página contaminada {current}/{total}: {title} → {newTitle}',
    lintModalFixPolluted: '🧹 Reparar páginas contaminadas ({count})',
    lintDuplicateCheckFailed: 'Falló la detección de duplicados — consulta la consola para más detalles',
    lintDuplicateCheckFailedDetail: 'Falló la comprobación de duplicados en {step}: {error}',
    lintMergeItemFailed: 'Falló la fusión: {source} → {target} — {error}',
    lintAliasesMissing: 'Alias faltantes: {count} página(s) sin alias',
    lintAliasesSection: 'Páginas sin alias [{count}]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: 'Completar alias ({count})',
    lintAliasesFilling: 'Generando alias {current}/{total}: {page}',
    lintAliasesFilled: 'Completado de alias finalizado. Rellenadas {filled}/{total} páginas.',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: 'Etiquetas fuera de vocabulario (detectadas) [{count}]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: 'Falló la generación de alias: {page} — {error}',
    lintFixItemFailed: 'Falló la corrección: [[{target}]] — {error}',
    lintLinkItemFailed: 'Falló el enlace: {page} — {error}',
    lintRetrying: 'Reintentando ({attempt}/{max}) tras error...',
    lintAnalyzingLLM: 'La IA está analizando el estado de la Wiki...',
    saveToWikiSuccess: '¡Conversación guardada en la Wiki!',
    querySaveAlreadyExists: 'Aviso: no se escribió nada (el conocimiento ya existe en la Wiki):',
    saveSummary: '{entities} entidades, {concepts} conceptos, {pages} páginas',
    aliasAdded: 'Añadido alias \'{alias}\' a la página \'{page}\'',

    // Status Messages
    ingestingSources: 'Ingestando fuentes...',
    queryingWiki: 'Consultando Wiki...',
    lintingWiki: 'Verificando Wiki...',
    savingToWiki: 'Guardando conversación en Wiki...',
    clearingHistory: 'Limpiando historial de conversación...',

    // Buttons
    ingestButton: 'Ingestar',
    queryButton: 'Consultar',
    lintButton: 'Verificar',
    cancelButton: 'Cancelar',

    // Links
    karpathyGistLink: 'Gist de Karpathy LLM Wiki',
    obsidianPluginAPI: 'API de plugins de Obsidian',
    anthropicSDK: 'SDK de Anthropic',
    openaiSDK: 'SDK de OpenAI',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'Región de AWS',
    bedrockRegionDesc: 'Región de Amazon Bedrock para esta cuenta. Determina la URL del endpoint bedrock-mantle; no se puede sobrescribir mediante baseURL.',
    bedrockRegionHint: 'bedrock-mantle está disponible en 18 regiones; la cobertura de modelos varía según la región.',

    // Other
    availableModelsLoading: 'Cargando modelos disponibles...',
    noModelsAvailable: 'No hay modelos disponibles',

    // LLM Language Hint
    llmLanguageHint: 'Please answer in Spanish.',

    // Schema Configuration
    schemaSection: 'Configuración del esquema',
    enableSchemaName: 'Activar esquema',
    enableSchemaDesc: 'Genera e inyecta schema/config.md en todos los prompts LLM para salida Wiki estructurada',
    viewSchemaButton: 'Ver / editar esquema',
    regenerateSchemaButton: 'Regenerar esquema predeterminado',
    schemaRegeneratedNotice: 'Esquema predeterminado regenerado.',
    schemaRegenerateFailed: 'Error al generar el esquema',

    // Estado de inicialización del Wiki
    wikiInitStatusReady: 'Wiki inicializado',
    wikiInitStatusNotReady: 'Wiki no inicializado — se creará automáticamente en la primera ingestión',

    // Wiki Output Language
    wikiLanguageName: 'Idioma de salida de la Wiki',
    wikiLanguageDesc: 'Todas las páginas wiki generadas, índice, registro y respuestas de consulta usan este idioma',
    customWikiLanguageOption: 'Personalizado...',
    customWikiLanguageHint: 'Introduce un idioma (p. ej. italiano, árabe). Se pasará al LLM como directiva de idioma de salida.',
    customWikiLanguagePlaceholder: 'p. ej. italiano',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // Extraction Settings
    extractionSectionTitle: 'Extracción',
    extractionGranularityName: 'Granularidad de extracción',
    extractionGranularityDesc: 'Controla extracciones por archivo fuente. Mayor = más páginas/tokens API.\nFina: análisis profundo. Estándar: notas diarias. Gruesa: visión rápida. Mínima: procesamiento 100+ archivos (limita elementos por fuente, ~5 — no el detalle por elemento). Personalizada: límites propios (hasta 300).\nConsejo: Use Mínima/Gruesa para carpetas con muchos archivos para ahorrar tiempo y costo.',
    extractionGranularityFine: 'Fina — análisis profundo (≤100 elementos)',
    extractionGranularityStandard: 'Estándar — notas diarias (≤50 elementos)',
    extractionGranularityCoarse: 'Gruesa — visión rápida (≤10 elementos)',
    extractionGranularityMinimal: 'Mínima — procesamiento por lotes 100+ archivos (≤5 elementos)',
    extractionGranularityCustom: 'Personalizado — Establecer tus propios límites (1~500)',
    customEntityLimitName: 'Límite personalizado de entidades',
    customEntityLimitDesc: 'Número máximo de entidades a extraer por archivo fuente (1-500)',
    customConceptLimitName: 'Límite personalizado de conceptos',
    customConceptLimitDesc: 'Número máximo de conceptos a extraer por archivo fuente (1-500)',

    // Issue #85 v2: Vocabulario de etiquetas (entrada por chips, integrado en Configuración Wiki)
    tagVocabularyInlineDesc: 'Vocabulario controlado para etiquetas frontmatter de entity y concept. Las etiquetas anidadas de Obsidian con «/» se conservan.',
    tagVocabularyModeName: 'Configuración del vocabulario de etiquetas',
    tagVocabularyModeDescDefault: 'Por defecto usa etiquetas integradas: {}. Cambie a «Personalizado» para definir su propio vocabulario.',
    tagVocabularyModeDescCustom: 'Personalizado: defina abajo sus propias etiquetas de entity y concept con la entrada por chips — Enter o coma para añadir, × para eliminar.',
    tagVocabularyNotEnforcedHint: 'Solo una sugerencia de esquema — la IA aún puede emitir tipos fuera del vocabulario. Ejecuta Lint para encontrar y reparar esas páginas.',
    tagVocabularyModeDefault: 'Por defecto (subtipos integrados)',
    tagVocabularyModeCustom: 'Personalizado (definido por el usuario)',
    customEntityTagsName: 'Etiquetas de entidad personalizadas',
    customEntityTagsDesc: 'Enter o coma para añadir un chip, × para eliminar. Las etiquetas anidadas con «/» se conservan.',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'Etiquetas de concepto personalizadas',
    customConceptTagsDesc: 'Enter o coma para añadir un chip, × para eliminar. Las etiquetas anidadas con «/» se conservan.',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: 'Etiqueta duplicada omitida',

    // Ingestion Acceleration
    accelerationSectionTitle: 'Aceleración de ingestión',
    pageGenerationConcurrencyName: 'Concurrencia LLM',
    pageGenerationConcurrencyDesc: 'Número de llamadas LLM en paralelo durante ingestión y operaciones lint. Valores más altos aceleran el procesamiento pero incrementan costes de API y pueden alcanzar límites de tasa.',
    concurrencyValueSingular: 'Concurrencia actual: {} (serial — más seguro)',
    concurrencyValuePlural: 'Concurrencia actual: {} (paralelo)',
    batchDelayName: 'Retraso entre lotes (ms)',
    batchDelayDesc: 'Retraso entre lotes paralelos para evitar límites de tasa de la API (100-10000ms). Actual: {}ms. Aumenta si ves errores 429.',

    // Auto Maintenance
    autoMaintainSection: 'Mantenimiento automático',
    autoMaintainBetaBadge: 'BETA — Función experimental. Puede tener problemas. Recomendado solo para usuarios avanzados.',
    autoWatchName: 'Monitorizar carpetas',
    autoWatchDesc: 'Detecta automáticamente archivos .md nuevos o modificados en las carpetas monitorizadas y notifica o ingesta automáticamente',
    watchedFoldersName: 'Carpetas monitorizadas',
    watchedFoldersDesc: 'Carpetas a monitorizar para contenido nuevo. Pulsa "Añadir carpeta" para seleccionar desde tu vault.',
    addWatchedFolderButton: 'Añadir carpeta',
    removeWatchedFolderButton: 'Eliminar',
    webClipperPresetName: 'Monitorizar recortes (Web Clipper)',
    webClipperPresetDesc: 'Añade la carpeta Clippings/ usada por Obsidian Web Clipper a la lista de monitorización. Tus recortes web se ingerirán automáticamente en la Wiki.',
    noWatchedFoldersHint: 'Ninguna carpeta configurada. Añade una carpeta o activa el preset Clippings.',
    autoWatchModeName: 'Modo de monitorización',
    autoWatchModeDesc: '"Solo notificar" muestra un aviso. "Ingestión automática" procesa sin intervención.',
    watchModeNotify: 'Solo notificar',
    watchModeAuto: 'Ingestión automática',
    autoWatchDebounceName: 'Retraso de debounce (segundos)',
    autoWatchDebounceDesc: 'Tiempo de espera antes de disparar la ingestión tras un cambio en un archivo (1-60 segundos)',
    periodicLintName: 'Verificación lint periódica',
    periodicLintDesc: 'Ejecuta lint LLM de forma programada, solo cuando los archivos fuente han cambiado desde la última comprobación',
    periodicLintOff: 'Desactivado',
    periodicLintDaily: 'Diario',
    periodicLintWeekly: 'Semanal',
    periodicLintMonthly: 'Mensual',
    autoSmartFixName: 'Corrección inteligente automática',
    autoSmartFixDesc: 'Cuando se ejecute el lint, aplica automáticamente todas las correcciones (Smart Fix All) sin mostrar el modal de informe. El resumen de correcciones se sigue mostrando al finalizar.',
    autoSmartFixNotice: 'Corrección inteligente automática: aplicando todas las correcciones...',
    autoIngestLevelName: 'Notificación de ingesta automática',
    autoIngestLevelDesc: 'Cómo notificar cuando la ingesta automática se completa. "Aviso" (transitorio) no bloquea. "Modal" abre el informe completo. Desactivado cuando el modo Watch es "Solo notificar".',
    autoIngestLevelNotice: 'Aviso (no bloqueante)',
    autoIngestLevelModal: 'Modal (informe completo)',
    startupCheckName: 'Ejecutar correcciones rápidas al inicio',
    startupCheckDesc: 'Corrige automáticamente problemas de formato de bajo nivel (campo sources, wikilinks doblemente anidados) al cargar el plugin. Verifica la estructura de carpetas de la Wiki. Activado por defecto.',
    suggestSchemaCommand: 'Sugerir actualizaciones del esquema',
    autoMaintainCostWarning: '⚠️ Aviso de coste: Las funciones de mantenimiento automático consumen tokens de API. "Ingestión automática" dispara llamadas LLM en cada cambio de archivo fuente. "Verificación lint periódica" ejecuta comprobaciones de salud programadas (solo cuando se detectan cambios). Configura con cuidado para evitar cargos inesperados.',

    // Notices
    startupCheckSummary: 'La Wiki tiene {pages} páginas ({entities} entidades, {concepts} conceptos, {sources} fuentes)',
    watcherActiveNotice: 'Wiki: monitor de archivos activo — supervisando carpetas monitorizadas',
    watchIngestNotice: 'Wiki: {count} archivo(s) modificado(s) en sources/. Ejecuta "Ingestar fuentes" para procesar.',
    autoIngestRunning: 'Ingestando automáticamente {count} archivo(s) modificado(s)...',
    autoIngestComplete: 'Ingestión automática completada: {success} correctas, {fail} fallidas',
    scheduledLintRunning: 'Ejecutando verificación lint programada de la Wiki...',
    wikiLintStats: 'Lint de Wiki: {pages} páginas ({entities} entidades, {concepts} conceptos, {sources} fuentes)',
    wikiHealthStats: 'Estado de la Wiki: {pages} páginas ({entities} entidades, {concepts} conceptos, {sources} fuentes){indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Correcciones rápidas Wiki completadas',
    startupCheckStructureLabel: 'Estructura Wiki',
    startupCheckStructureOk: 'completa',
    startupCheckStructureMissing: 'incompleta — se creará automáticamente en la primera ingestión',
    startupCheckSourcesLabel: 'Sources normalizados',
    startupCheckSourcesClean: 'ya limpio',
    startupCheckSourcesCleaned: '{files} archivo(s), {entries} entrada(s) limpiada(s)',
    startupCheckIncompleteClean: 'páginas incompletas: ninguna',
    startupCheckIncompleteArchived: 'páginas incompletas: {count} archivada(s) (recuperable desde .trash)',
    startupCheckDisableHint: 'Para desactivar: Configuración → Mantenimiento automático → Ejecutar correcciones rápidas al inicio',
    lintWikiStart: 'Iniciando verificación lint de la Wiki...',
    lintWikiComplete: 'Verificación lint de la Wiki completada',
    lintWikiFailed: 'Verificación lint de la Wiki fallida',
    analyzingSchema: 'Analizando la Wiki y generando sugerencias de esquema...',
    schemaSuggestionGenerated: 'Sugerencias de esquema generadas, consulta wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: 'No se necesitan actualizaciones del esquema.',
    schemaSuggestionFailed: 'Falló la sugerencia de esquema',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Vista previa de actualización del esquema',
    schemaDiffSummary: '+{add} / -{del} líneas',
    schemaDiffRegenerateLabel: 'Refinar la sugerencia (opcional):',
    schemaDiffRegenerateBtn: 'Regenerar',
    schemaDiffOpenFileBtn: 'Abrir archivo',
    schemaDiffApplyBtn: 'Aplicar',
    schemaDiffApplied: 'Esquema actualizado. Respaldo: {path}',
    schemaDiffEmptyTitle: 'LLM no recomienda cambios',
    schemaDiffFailed: 'Error al aplicar el esquema: {reason}',
    schemaDiffRestoreHint: 'Copia de seguridad guardada en {path}. Para restaurar, renombra ese archivo a "wiki/schema/config.md" en el explorador de archivos. Se conservan las 3 copias de seguridad más recientes.',
    schemaRegenerateNoBody: 'Regeneración exitosa pero el LLM no devolvió un nuevo esquema.',
    schemaNotFoundNotice: 'Archivo de esquema no encontrado. Activa el esquema para crearlo.',
    selectFolderNoMdFiles: 'No hay archivos Markdown en la carpeta: {path}',
    batchIngestSkipNotice: 'Omitiendo {skipped}/{total} archivos ya ingeridos. Ingestando {new} archivos nuevos...',
    batchIngestAllIngested: 'Los {total} archivos de esta carpeta ya han sido ingeridos.',
    batchIngestStarting: 'Ingestando {count} archivo(s) de "{folder}" — esto puede tardar varios minutos. Aparecerá un informe al finalizar.',
    batchIngestComplete: 'Ingestión por lotes completada: {success}/{total} correctas, {fail} fallidas',
    batchIngestFailedFiles: 'Archivos fallidos:',
    historyTruncated: 'Historial reducido a las últimas {max} rondas',
    historyCleared: 'Historial limpiado',

    // User Feedback Loop
    reviewedPagePreserved: 'Conservando contenido revisado por el usuario para: {}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: '¿Guardar en la Wiki?',
    querySuggestSaveDesc: 'Esta conversación contiene conocimiento valioso. ¿Guardarlo en tu Wiki?',
    querySuggestSaveYes: 'Guardar',
    querySuggestSaveNo: 'Descartar',

    // Ingestion Report
    ingestReportElapsedTime: 'Tiempo transcurrido',
    ingestReportSkippedFiles: 'Omitidos (ya ingeridos)',
    ingestReportRejectedFiles: 'Omitidos',
    rejectionReasonEmpty: 'vacío',
    rejectionReasonType: 'tipo no compatible',
    rejectionReasonDuplicate: 'contenido duplicado',
    rejectionReasonPdfUnsupported: 'el proveedor no puede leer el PDF',
    rejectionReasonMineruPageLimit: 'supera el límite de páginas de MinerU',
    rejectionReasonMineruSizeLimit: 'supera el límite de tamaño de MinerU',
    sourceRejectedEmpty: '⏭️ "{filename}" no tiene contenido para ingerir — omitido. Las notas vacías o solo con frontmatter no crean páginas wiki.',
    sourceRejectedType: '⏭️ "{filename}" no es un tipo de archivo compatible — omitido. Solo se pueden ingerir notas de texto (.md, .txt, etc.).',
    sourceRejectedDuplicate: '⏭️ "{filename}" omitido — su contenido ya está en el wiki.',
    pdfReadingInProgress: 'Leyendo PDF: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ «{filename}» omitido — tu provider o modelo actual no acepta PDF. Cambia de provider o activa «Forzar soporte de PDF» en Settings → LLM Configuration → Advanced y vuelve a intentarlo, o cambia el backend de conversión Markdown a MinerU (también maneja imágenes y documentos Office).',
    clearPdfCacheCommand: 'Vaciar caché de conversión PDF',
    pdfCacheCleared: 'Caché PDF vaciada ({count} entradas eliminadas).',
    // v1.25.0 PR3: Advanced PDF settings
    forcePdfSupportName: 'Forzar soporte de PDF',
    forcePdfSupportDesc: 'Desactivado por defecto. Activa esta opción si tu proveedor no está en la lista nativa pero puede procesar PDF. Al activarla, el PDF se enviará a tu proveedor actual; si lo rechaza, se te avisará con un mensaje. Los proveedores nativos de PDF (Anthropic / OpenAI / Bedrock) no necesitan esta opción.',
    writePdfMarkdownToVaultName: 'Escribir el Markdown convertido en el Vault',
    markdownConversionBackendName: 'Backend de conversión Markdown',
    markdownConversionBackendDesc: 'Usa la compatibilidad nativa con PDF de tu proveedor (alcance limitado, no todos los proveedores/modelos manejan PDF, consume tokens LLM). MinerU es un servicio online — rápido, gratis hasta la cuota diaria, acepta PDF/imágenes/Office — pero requiere un token de API (configúralo en el campo de abajo).',
    markdownConversionBackendNative: 'Compatibilidad PDF/imágenes del proveedor',
    markdownConversionBackendMineru: 'API online de MinerU',
    mineruApiBaseUrlName: 'URL base de la API de MinerU',
    mineruApiBaseUrlDesc: 'URL base para la API de MinerU. El valor predeterminado es https://mineru.net/api/v4. Configure una URL personalizada si utiliza un proxy, espejo o implementación autohospedada.',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'Token de API de MinerU',
    mineruApiTokenDesc: 'Obtén tu token en https://mineru.net/apiManage/token. MinerU acepta archivos de hasta 200 MB y hasta 200 páginas.',
    mineruApiTokenPlaceholder: 'Pega el token de API de MinerU',
    mineruUploadingInProgress: 'Subiendo PDF a MinerU: {filename}',
    mineruWaitingInProgress: 'Esperando la conversión de MinerU: {filename}',
    mineruDownloadingInProgress: 'Descargando el resultado de MinerU: {filename}',
    markdownConversionComplete: 'Conversión completa: {filename}',
    markdownConversionCompleteSaved: 'Conversión completa — escrito en {path}: {filename}',
    mineruPageLimitRejected: '{filename} supera el límite de {limit} páginas de MinerU — divide el archivo y reintenta',
    mineruSizeLimitRejected: '{filename} supera el límite de tamaño de {limit} MB de MinerU',
    writePdfMarkdownToVaultDesc: 'Desactivado por defecto. Cuando está activo, el resultado de cada conversión de PDF se escribe en un archivo "<basename>.pdf.md" junto al PDF original. Cuando está desactivado (arquitectura solo en caché), los resultados viven solo en la caché del plugin y no dejan artefactos en tu Vault.',

    ingestRejectedSummary: '{count} archivo(s) omitido(s) (vacío, duplicado o tipo no compatible).',
    reingestConfirmTitle: '¿Volver a ingerir este archivo?',
    reingestConfirmBody: 'El contenido de "{filename}" ya está en el wiki. ¿Volver a ingerirlo de todos modos?',
    reingestConfirmYes: 'Volver a ingerir',
    reingestConfirmNo: 'Omitir',
    lintDedupIncludeSourcesName: 'Incluir fuentes en deduplicación',
    lintDedupIncludeSourcesDesc: 'Activado por defecto. Cuando está activo, las fuentes con cuerpos idénticos se marcan como duplicados durante el lint. Desactívalo si tu corpus de fuentes genera falsos positivos.',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: 'Omitir candidatos que la fuente solo menciona',
    skipMentionOnlyCandidatesDesc: 'Desactivado por defecto. Cuando está activo, una entidad o concepto extraído cuyo nombre no aparece en el texto corrido de la nota — ausente, o solo entre paréntesis, enumeraciones o elementos de lista cortos — no recibe página ni más llamadas al modelo, y se elimina de las listas de relacionados de los demás candidatos. Funciona para idiomas de wiki con perfil de límites de palabra (alemán medido; inglés, francés, español, portugués, neerlandés estimados); para otros idiomas la ingesta informa una vez que no puede aplicarse. Déjalo desactivado en vaults tipo glosario o notas en viñetas donde cada término nombrado deba tener página.',
    createStubsForUnresolvableLinksName: 'Crear páginas de stub para enlaces sin resolver',
    createStubsForUnresolvableLinksDesc: 'Activado por defecto. Cuando «Corregir enlaces rotos» no puede resolver un enlace a ninguna página existente, escribe una página de marcador vacía y redirige el enlace hacia ella — nunca la rellena el LLM. Desactívalo para dejar esos enlaces intactos: siguen visibles en cada informe hasta que una fuente real los defina.',
    lintDedupSectionHeading: 'Deduplicación',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): texto genérico,
    // reutilizable para todas las rutas LLM. {count} es el número de
    // lotes que necesitaron reintento. No decimos "Lint completado" —
    // el reintento solo recupera este lote.
    llmRetryRecoveredToast: 'Tarea LLM: {count} lote(s) requirieron reintento por una respuesta transitoria del proveedor. Consulta la consola para más detalles. Si esto se repite, reduce Page Generation Concurrency en la configuración del proveedor.',
    ingestReportFailedGuidance: 'Estos elementos no pudieron crearse automáticamente. Puedes crear manualmente las páginas correspondientes, o reducir la granularidad de extracción y volver a ingerir el archivo fuente.',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: 'Ingestar fuente individual',
    cmdIngestFolder: 'Ingestar desde carpeta',
    cmdIngestMultipleFiles: 'Ingerir varios archivos',
    cmdQueryWiki: 'Consultar wiki',
    cmdLintWiki: 'Verificar wiki',
    cmdRegenerateIndex: 'Regenerar índice',
    cmdSuggestSchema: 'Sugerir actualizaciones del esquema',
    cmdCancelIngestion: 'Cancelar ingesta actual',
    cmdIngestActiveFile: 'Ingerir archivo actual',
    cmdViewHistory: 'Ver historial de ingesta',
    noActiveFile: 'No hay ningún archivo abierto',
    mdOnlyFile: 'Solo se pueden ingerir archivos Markdown',
    ingestSingleFileStart: 'Procesando: {filename}',
    ingestCheckingExisting: 'Comprobando archivos ya procesados...',
    lintFindingsSummary: '{total} hallazgos',

    // Ingestion status bar
    ingestionStatusBar: 'Ingiriendo... clic para cancelar',
    lintStatusBar: 'Verificando... clic para cancelar',
    ingestStatusAnalyzing: 'Ingiriendo… (clic para cancelar)',
    lintStatusAnalyzing: 'Verificando… (clic para cancelar)',
    ingestStageAnalyze: 'Analizando la fuente',
    ingestStageSummary: 'Generando el resumen',
    ingestStageEntity: 'Creando la entidad',
    ingestStageConcept: 'Creando el concepto',
    ingestStageRetry: 'Reintentando la página fallida',
    ingestStageSave: 'Guardando páginas',
    ingestStageIndex: 'Generando el índice',
    pdfStageReading: 'Leyendo el PDF',
    pdfStageConverting: 'Convirtiendo el PDF',
    pdfStageSidecar: 'Escribiendo el archivo auxiliar',
    lintStagePrep: 'Leyendo páginas',
    lintStageProgrammatic: 'Escaneando enlaces',
    lintStageAnalyzing: 'Ejecutando análisis LLM',
    lintStageDedup: 'Detectando duplicados',
    lintStageContradiction: 'Detectando contradicciones',
    ingestionCancelling: 'Cancelando — se detendrá tras el lote actual',
    ingestionCancelled: 'Ingesta cancelada',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: 'Analizando lote 1/{total}...',
    ingestBatchProgress: 'Analizando lote {current}/{total} ({entities} entidades, {concepts} conceptos hasta ahora)...',
    ingestBatchProcessed: 'Lote {current} analizado, procesando...',
    ingestAnalyzing: 'Analizando: {filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] Creando resumen...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}: {name}',
    ingestUpdating: '[{step}/{totalSteps}] Actualizando: {name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] Generando índice...',
    ingestItemTypeEntity: 'Entidad',
    ingestItemTypeConcept: 'Concepto',
    convAnalyzing: 'Analizando conversación...',
    convCheckingExisting: 'Comprobando conocimiento existente...',
    convAlreadyExists: 'Este conocimiento ya existe en el Wiki',
    convCreatingSummary: 'Creando página de resumen...',
    convGeneratingSummary: 'Generando página de resumen...',
    convSavingEntity: 'Guardando entidad: {name}',
    convSavingConcept: 'Guardando concepto: {name}',
    convGeneratingIndex: 'Generando índice...',

    // Lint Report
    lintReportTitle: 'Informe de verificación lint de la Wiki',
    lintReportSummary: 'Resumen de estado del wiki: {total} páginas en total, {aliasesMissing} páginas sin alias, {duplicates} duplicados, {deadLinks} enlaces rotos ({deadLinkFromDup} implican duplicados), {orphans} páginas huérfanas ({orphanFromDup} son duplicados), {emptyPages} páginas vacías, {ungroundedQuotes} citas sin fuente, {tagViolations} etiquetas fuera de vocabulario. Lint: {elapsedSeconds}s',

    // Advanced LLM Settings (Issues #99 / #128)
    // v1.26.0 (#382 item 2): nombre cambiado de «Configuración de parámetros
    // avanzados» a «Parámetros avanzados de LLM» — acotado al muestreo LLM,
    // para distinguirlo del panel genérico «Ajustes avanzados» inferior.
    advancedLlmModeName: 'Parámetros avanzados de LLM',
    advancedLlmModeDesc: 'El modo predeterminado sigue las recomendaciones de tu proveedor. Cambia a Personalizado solo si tienes una razón específica para anular (por ejemplo, un modelo concreto necesita una temperatura fija, o quieres suprimir la salida de razonamiento).',
    advancedSettingsDefault: 'Predeterminado (seguir al proveedor)',
    advancedSettingsCustom: 'Personalizado (anular al proveedor)',
    // v1.26.0 (#382 item 2): panel «Ajustes avanzados» inferior — el hogar
    // genérico de todos los ajustes avanzados que no son parámetros de LLM.
    advancedSettingsSection: 'Ajustes avanzados',
    showAdvancedSettingsName: 'Mostrar ajustes avanzados',
    showAdvancedSettingsDesc: 'Activar para mostrar los ajustes avanzados abajo. Al desactivar, se ocultan y se restablecen a sus valores predeterminados.',
    disableThinkingName: 'Deshabilitar pensamiento',
    disableThinkingDesc: 'Desactiva la cadena de pensamiento/razonamiento en la respuesta del modelo. Desactivado por defecto — el modelo decide si mostrar razonamiento, lo que suele dar la mejor respuesta. Actívalo solo si tu proveedor inserta texto de razonamiento bruto en la respuesta y quieres una respuesta limpia.',
    taskPoliciesPlaceholder: 'Ejemplo: extract=text:off',
    taskPoliciesName: 'Modo de salida y razonamiento por paso',
    taskPoliciesDesc: 'Una entrada por paso del pipeline, `paso=modo:razonamiento`, separadas por comas — p. ej. `extract=text:off`. Modos: `-` (sin cambio), `schema`, `json`, `text`; razonamiento: `-`, `off`, `on`, `low`, `medium`, `high`. Los nombres de paso incluyen extract, extract-retry, lemma-classify, merge-triage, source-stance, dedup, page-generate, related-page, lint-dedup (un nombre mal escrito no coincide con nada). Dejar en blanco para la base integrada (extracción en modo texto). Una entrada ilegible no se guarda.',
    // Issue #137: Notas de compatibilidad (breves; sin lista de proveedores)
    extractionTemperatureName: 'Temperatura de extracción',
    extractionTemperatureDesc: 'Controla si el modelo es más conservador o creativo al escribir páginas entity/concept. Valores bajos = más determinista y fiel; valores altos = más variado. La mayoría de los usuarios lo dejan vacío.',
    chatTemperatureName: 'Temperatura de consulta',
    chatTemperatureDesc: 'Mismo concepto que la temperatura de extracción, pero solo afecta cómo Query Wiki responde preguntas. Valores bajos = respuestas más literales; valores altos = respuestas más conversacionales. La mayoría de los usuarios lo dejan vacío.',
    repetitionPenaltyName: 'Penalización por repetición',
    repetitionPenaltyDesc: 'Evita que el modelo repita las mismas palabras o frases. Valores más altos reducen la repetición. Solo algunos proveedores de modelos locales (Ollama, LM Studio, llama.cpp) aceptan este parámetro; los proveedores en la nube lo ignoran silenciosamente. La mayoría de los usuarios lo dejan vacío. Un valor superior a 1,0 puede provocar errores en la salida del LLM durante la extracción en modelos locales pequeños: si falla una ejecución, reduzca o borre este valor.',
    repetitionPenaltyErrorHint: 'Nota: se ha establecido una penalización de repetición personalizada de {value}. Valores superiores a 1,0 pueden romper la extracción con restricciones gramaticales en modelos locales pequeños: reduzca o borre esta configuración e inténtelo de nuevo.',
    temperaturePlaceholder: 'dejar vacío = valor por defecto del proveedor',
    // v1.26.0 (#382 item 2): Umbrales de detección de duplicados
    // (solo modo avanzado personalizado).
    lintDedupJaccardLinkThresholdName: 'Similitud de enlaces duplicados',
    lintDedupJaccardLinkThresholdDesc: 'Rango 0–1 (por defecto 0,4). Dos páginas se marcan como duplicadas cuando la proporción de enlaces wiki que ambas comparten respecto a sus enlaces totales alcanza al menos este valor. Más bajo → se capturan más casi-duplicados (incluidas páginas que solo enlazan al mismo centro); más alto → solo se marcan páginas que apuntan a un conjunto casi idéntico. Sube este valor si ves falsos positivos entre páginas no relacionadas que simplemente enlazan al mismo centro. Déjalo en blanco para usar el valor por defecto.',
    lintDedupJaccardBodyGateName: 'Similitud mínima del cuerpo',
    lintDedupJaccardBodyGateDesc: 'Rango 0–1 (por defecto 0,2). Aunque dos páginas compartan enlaces wiki, solo se marcan como duplicadas si la similitud de sus textos alcanza al menos este valor. Más bajo → más candidatos llegan a la verificación del LLM; más alto → solo se marcan cuerpos casi idénticos. Sube este valor si el LLM está revisando páginas que obviamente no son duplicadas. Déjalo en blanco para usar el valor por defecto.',
    lintDedupBigramThresholdName: 'Similitud de títulos',
    lintDedupBigramThresholdDesc: 'Rango 0–1 (por defecto 0,4). Dos páginas se marcan como duplicadas cuando los caracteres de sus títulos (o alias) coinciden en al menos esta proporción. Más bajo → se capturan variantes ortográficas, erratas y traducciones del mismo concepto; más alto → solo se marcan títulos casi idénticos. Sube este valor si el LLM revisa páginas con nombres muy distintos que en realidad no son duplicadas. Déjalo en blanco para usar el valor por defecto.',
    lintDeadLinkSection: 'Enlaces rotos (detectados) [{count}]',
    lintEmptyPageSection: 'Páginas vacías (detectadas) [{count}]',
    lintOrphanSection: 'Páginas huérfanas (detectadas) [{count}]',
    lintContradictionSection: 'Contradicciones (detectadas)',
    lintDuplicateSection: 'Páginas duplicadas (detectadas)',
    lintNoIssuesFound: 'No se detectaron duplicados, enlaces rotos, páginas vacías, páginas huérfanas ni citas sin fuente.',
    lintSourceDriftSection: 'Notas fuente modificadas desde la ingesta [{count}]',
    lintSourceDriftItem: '- [[{page}]] — la nota de origen [[{note}]] fue editada después de la ingesta; la página puede estar desactualizada',
    lintContradictionMarkerSection: 'Páginas marcadas con contradicciones (triaje de fusión) [{count}]',
    lintContradictionMarkerItem: '- [[{page}]] — fuente(s) en conflicto: {sources}; tras revisar, elimine el marcador contradictions:',
    lintQuoteGroundingSection: 'Citas sin fuente (detectadas) [{count}]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: "{quote}"',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (la página no existe){dupFlag}',
    lintDeadLinkMore: '- ... {count} enlaces rotos más',
    lintEmptyPageItem: '- [[{page}]] — menos de 50 caracteres de contenido sustantivo',
    lintOrphanItem: '- [[{page}]] — ninguna otra página Wiki enlaza aquí{dupFlag}',
    lintPollutedSection: 'Páginas contaminadas (detectadas) [{count}]',
    lintPollutedItem: '- [[{page}]] → debería ser "{clean}"',
    lintSourcesNormalizedSection: 'Sources normalizadas (auto-corregidas) [{files} archivos / {entries} entradas]',
    lintSourcesNormalizedItem: 'Limpiadas {entries} entradas de sources contaminadas en {files} archivo(s) (rutas externas, extensiones .md, pipes de alias eliminados y deduplicados).',
    lintDuplicateItem: '- [[{target}]] y [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ implica página duplicada)',
    lintOrphanIsDuplicate: ' (⚠️ página duplicada)',
    lintHubLinkDensitySection: 'Problemas de densidad de enlaces en hubs (Issue #157 / #175) [{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} entrantes, {relatedCount} enlaces relacionados, distintividad {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ eliminar',
    lintHubLinkDensityReview: '🔍 revisar',
    lintHubLinkDensityKeep: '✅ mantener',
    lintHubLinkDensitySummary: 'Resumen: {strip} página(s) recomendada(s) para eliminar, {review} página(s) recomendada(s) para revisar.',
    lintHubLinkDensityNoRelated: ' (no se encontró la sección ## Related)',
    lintContradictionOpen: 'Contradicciones abiertas: {count}',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: 'Detectada',

    // Lint Analysis Prompt

    // Lint Fix Progress
    lintFixProgress: 'Corrigiendo {current}/{total}: [[{target}]]',
    lintFixDeadComplete: 'Corrección de enlaces rotos completada. Corregidos {fixed}/{total} elementos.',
    lintFillProgress: 'Expandiendo {current}/{total}: {page}',
    lintFillComplete: 'Expansión de páginas completada. Rellenadas {filled}/{total} páginas.',
    lintDeleteCompleted: '{count} stubs vacíos eliminados',
    lintDeleteFailed: 'Error al eliminar {failed}/{total} stubs vacíos (ver consola)',
    lintFillFailed: 'Falló la expansión: {page} — {error}',
    lintLinkProgress: 'Enlazando {current}/{total}: {page}',
    lintLinkComplete: 'Enlace de huérfanas completado. Enlazadas {linked} páginas.',
    lintFixNoAction: 'No se tomó ninguna acción (sin cliente)',
    lintFixIndexUpdated: 'Índice y registro de la Wiki actualizados.',
    lintPollutedFixed: 'Páginas contaminadas corregidas: {fixed}/{total}. Índice regenerado.',
    regenerateIndexCompleted: 'Índice regenerado',
    operationFailed: 'Error: ',
    lintFixAllComplete: 'Todas las correcciones completadas. Consulta el registro para más detalles.',
    lintFixAllNoChanges: 'Sin cambios — todas las fases reportaron 0 correcciones. Detalles en wiki/log.md.',
    lintFixPhasesLabel: 'fases modificadas',

    // Lint Report Modal
    lintModalActionsTitle: 'Sugerencias de corrección (requiere tokens LLM):',
    lintLogReference: 'Informe completo guardado en log.md',
    lintModalFixDeadLinks: 'Corregir enlaces rotos ({count})',
    lintModalExpandEmpty: 'Expandir páginas vacías ({count})',
    lintModalDeleteEmpty: 'Eliminar stubs vacíos ({count})',
    lintModalLinkOrphans: 'Enlazar páginas huérfanas ({count})',
    lintModalAnalyzeSchema: 'Analizar esquema',
    lintModalMergeDuplicates: 'Fusionar duplicados ({count})',
    lintModalFixAll: 'Corrección inteligente global ({count} problemas)',
    lintMergeProgress: 'Fusionando {current}/{total}: {source} → {target}',
    lintMergeComplete: 'Fusión de duplicados completada. Fusionados {merged}/{total} pares.',

    // Ingest Report Modal
    ingestReportTitle: 'Informe de ingestión',
    ingestReportSourceFile: 'Archivo fuente',
    ingestReportCreated: 'Creadas',
    ingestReportUpdated: 'Actualizadas',
    ingestReportContradictions: 'Contradicciones encontradas',
    ingestReportFailedTitle: 'Ingestión fallida',
    ingestReportErrorDetail: 'Detalle del error',
    ingestReportClose: 'Cerrar',
    ingestReportCreatedPages: 'Páginas creadas: {count}',
    ingestReportUpdatedPages: 'Páginas actualizadas: {count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki Registro de operaciones',
    logHeaderSubtitle: 'Cada ingesta, ejecución de lint y operación de mantenimiento se registra aquí automáticamente. Para una mejor visualización, usa el panel **Historial de operaciones**:',
    logHeaderShortcut: 'Cmd+P → "Ver historial de operaciones"',
    logHeaderSettingsShortcut: 'O desde Ajustes → Mantenimiento automático → Historial de operaciones',
    ingestionCreatedPages: '{count} página(s) creada(s)',
    ingestionUpdatedPages: '{count} página(s) actualizada(s)',
    ingestionNoticeHistoryHint: 'Ver historial de operaciones para más detalles',
    ingestReportEntitiesCount: '{count} entidades',
    ingestReportConceptsCount: '{count} conceptos',
    ingestReportContradictionsFound: 'Contradicciones encontradas: {count}',
    ingestReportEntityType: 'Entidad',
    ingestReportConceptType: 'Concepto',
    timeMinutes: 'min',
    timeSeconds: 'seg',

    // Advertencias de límite de tasa
    rateLimitDetected: '⚠️ Límite de tasa detectado: {count} página(s) fallaron con errores 429. Sugerencias: (1) Reducir concurrencia a {suggestedConcurrency} o 1 (serial), (2) Aumentar retraso entre lotes a {suggestedDelay}ms, (3) Cambiar a un proveedor con límites de tasa más altos.',
    rateLimitDetectedShort: '⚠️ Límite de tasa alcanzado — considere reducir la concurrencia o aumentar el retraso entre lotes en Configuración → Aceleración de ingestión.',

    longSourceNotice: '📄 "{filename}" tiene {lines} líneas ({size}). Los textos largos requieren extracción iterativa por lotes — el LLM lee el documento completo en múltiples pasadas. Esto puede tomar varios minutos. Por favor, ten paciencia.',
    longSourceNoticeShort: '📄 Archivo grande detectado ({lines} líneas). La ingestión puede tardar un poco.',

    // Panel de Historial de Ingesta (#122) — textos UI
    historyButton: 'Historial de operaciones',
    historyButtonDesc: 'Ver ingestas recientes, informes de Lint y otros cambios de tu Wiki',
    historyButtonOpen: 'Ver historial',
    historyModalTitle: 'Historial de operaciones',
    historyModalSubtitle: 'Cambios recientes de tu LLM-Wiki',
    historyEmpty: 'Aún no hay operaciones registradas. Ingesta una nota o ejecuta Lint para completar esta lista.',
    historyReadError: 'No se pudo leer el registro de operaciones: {error}',
    historyEntryKindIngest: 'Ingesta',
    historyEntryKindMaintenance: 'Mantenimiento',
    historyEntryKindFix: 'Corrección',
    historyEntryKindOther: 'Otro',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'Origen: {source}',
    historyEntrySourceUnknown: 'Ingesta sin título',
    historyEntryCreatedLabel: 'Creadas',
    historyEntryUpdatedLabel: 'Actualizadas',
    historyEntryCreatedCount: '{count} creadas',
    historyEntryUpdatedCount: '{count} actualizadas',
    historyEntryNoChanges: 'Sin cambios en páginas',
    historyEntryContradictions: '⚠️ {count} contradicción(es)',
    historyEntrySectionCreated: 'Páginas creadas',
    historyEntrySectionUpdated: 'Páginas actualizadas',
    historyEntrySectionContradictions: 'Contradicciones',
    historyEntrySectionDetails: 'Detalles',
    historyEntryOpenPage: 'Abrir',
    historyEntryDetailsNoContradictions: 'No se encontraron contradicciones',
    historySearchPlaceholder: '🔍 Buscar por título de origen o ruta de página…',
    historyFilterAll: 'Todas',
    historyFilterIngest: 'Solo ingesta',
    historyFilterMaintenance: 'Solo mantenimiento',
    historyFilterFix: 'Solo correcciones',
    historyFilterContradictions: '⚠️ Con contradicciones',
    historyRefreshButton: '⟳ Actualizar',
    historyExpandDay: 'Clic para expandir',
    historyCollapseDay: 'Clic para contraer',
    historyShowMore: 'Mostrar {count} entradas anteriores',
    historyNoMatch: 'Ninguna operación coincide con tu búsqueda/filtro.',
    historyCloseButton: 'Cerrar',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'Hallazgos del informe',
    historyKpiPages: 'Páginas',
    historyKpiDeadLinks: 'Enlaces rotos',
    historyKpiOrphans: 'Huérfanas',
    historyKpiEmpty: 'Vacías',
    historyKpiDuplicates: 'Duplicados',
    historyKpiTagViolations: 'Etiquetas',
    historyKpiUnsourced: 'Sin fuente',
    historyKpiDuration: 'Duración Lint',
    historyKpiDurationSec: '{seconds}s',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'Enlaces rotos ({count})',
    historySectionTagViolations: 'Etiquetas ({count})',
    historySectionOrphans: 'Páginas huérfanas ({count})',
    historySectionEmptyPages: 'Páginas vacías ({count})',
    historySectionLlmAnalysis: 'Análisis LLM ({count})',
    historyDeadLinkSource: 'Origen',
    historyDeadLinkTarget: 'Falta',
    historyOpenInLog: 'Abrir en log.md',
    historyShowMoreItems: 'Mostrar {count} más',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ igual',
    historyChipContradiction: 'Contradicción',
    historyChipOutdated: 'Obsoleto',
    historyChipMissing: 'Falta',
    historyChipStructure: 'Estructura',
    historySeverityHigh: 'Alta',
    historySeverityMedium: 'Media',
    historySeverityLow: 'Baja',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Tu Wiki tiene {dead} enlace(s) roto(s), {orphans} página(s) huérfana(s) y {tags} problema(s) de etiqueta. Última Lint: {duration}.',
    historyGlobalInsightClean: 'Tu Wiki está limpio — sin enlaces rotos, páginas huérfanas ni problemas de etiqueta.',
    historyGlobalInsightNoData: 'Sin informes de mantenimiento aún — ejecuta Lint.',
    historyModalHeaderTitle: 'Historial de operaciones',
    historyModalSubtitleWithCount: 'Cambios recientes de tu LLM-Wiki · {count} entradas',
    historyTimeRangeAll: 'Todo el tiempo',
    historyTimeRange1d: 'Último día',
    historyTimeRange3d: 'Últimos 3 días',
    historyTimeRange1w: 'Última semana',
    historyTimeRange1m: 'Último mes',
    historyIngestTotal: 'Páginas totales',
    historyIngestByType: 'Por tipo',
    historyIngestSource: 'Archivo de origen',
    historyIngestNoTimestamp: 'Sin marca de tiempo',
    historyIngestFirstTime: 'Primera ingesta',
    historyIngestLatestTime: 'Última ingesta',
    historyTimeRangeCustom: 'Rango personalizado',
    historyCustomRangeFrom: 'Desde',
    historyCustomRangeTo: 'Hasta',
    historyCustomRangeApply: 'Aplicar',
    historyCustomRangeClear: 'Limpiar',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki: el vault está vacío. Crea tu primera nota fuente y ejecuta Ingest para empezar.',
    welcomeNoteTierBNotice: 'Karpathy Wiki: se creó una nota Welcome. Ábrela para declarar tus dominios y elegir 2-3 notas fuente para sembrar el grafo de enlaces.',
    welcomeNoteRecreateCommand: 'Recrear nota Welcome Wiki',
    welcomeNoteRecreateCommandTooltip: 'Recrea la nota Welcome en <wikiFolder>/Welcome.md con los dominios actuales y la prueba de configuración LLM. El archivo existente se sobrescribe.',
    welcomeNoteSettingsToggle: 'Crear nota Welcome Wiki en el primer inicio',
    welcomeNoteSettingsToggleDesc: 'En la primera ejecución (cuando la carpeta wiki está vacía), crea una nota de introducción de una página en <wikiFolder>/Welcome.md. Explica qué es LLM-Wiki, te invita a declarar tu enfoque de dominio, y te guía para ingerir tus primeras 2-3 notas fuente. La nota se escribe en inglés por defecto, o en tu idioma wiki si el LLM está configurado. Desactívalo si ya conoces el plugin y no quieres la nota de introducción.',
    welcomeNoteRunConfigTest: 'Nota Welcome escrita en inglés. Abre Configuración → LLM Provider → Test Connection para localizarla en la próxima recreación.',
    welcomeNoteRecreated: 'Nota Welcome Wiki recreada en {path}',
    welcomeNoteNotRecreated: 'La nota Welcome no se recreó. Verifica la configuración del LLM.',
    welcomeNoteGenerating: 'Nota Welcome Wiki: generándose en segundo plano — aparecerá un aviso al terminar.',
    welcomeNoteGenerationFailed: 'Falló la generación de la nota Welcome Wiki: {error}',
    startupCheckWelcomePending: 'Nota Welcome: generándose en segundo plano (aparecerá un aviso al terminar).',
    welcomeNoteFileName: 'Bienvenido a Karpathy LLM Wiki',
    startupCheckWelcomeCreated: 'Nota Welcome creada en {path}',
    // v1.23.0 Phase 5.1.5: botón "Cancelar todo" del modal de selección múltiple.
    // Cancela todos los trabajos pendientes y en ejecución en la cola.
    // Los trabajos completados y fallidos se conservan para su visualización.
    cancelAllQueueJobs: 'Cancelar todo',
    // v1.23.0 Phase 5.1.5: modal de selección múltiple (cmdIngestMultipleFiles).
    // Título, sugerencia, marcador de búsqueda, botones, etiquetas de estado,
    // marcador de cola vacía.
    multiFileModalTitle: 'Ingerir múltiples archivos',
    multiFileModalHint: 'Selecciona notas fuente para ingerir. El panel derecho muestra la cola en vivo y el progreso.',
    multiFileSearchPlaceholder: 'Filtrar archivos por ruta…',
    multiFileAddToQueue: 'Agregar a la cola',
    multiFileSelectAll: 'Seleccionar todo',
    multiFileFileCount: '{count} archivo(s)',
    multiFileNoFilesAvailable: 'No hay archivos disponibles para ingerir.',
    multiFileNoFilesMatch: 'No se encontraron archivos para "{q}".',
    multiFileQueueEmpty: 'Cola vacía. Marca archivos a la izquierda para añadirlos.',
    multiFileStatusPending: 'Pendiente',
    multiFileStatusRunning: 'En curso',
    multiFileStatusCompleted: 'Completado',
    multiFileStatusFailed: 'Fallido',
    multiFileCancelAria: 'Cancelar este archivo',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: 'Ingerido',
    multiFileRowDrifted: 'Nota modificada desde la ingesta',
    startupCheckNoticeLevelName: 'Mostrar resultado de arreglos rápidos',
    startupCheckNoticeLevelDesc: 'Los QuickFixes siempre se ejecutan al iniciar el plugin (nota Welcome, estructura de carpetas, normalización de fuentes, páginas incompletas, encabezado del registro). Elige si mostrar el aviso resumen tras el inicio. El modo silencioso solo registra en la consola del desarrollador y en el panel Historial de operaciones.',
    startupCheckNoticeVisible: 'Visible (mostrar aviso)',
    startupCheckNoticeSilent: 'Silencioso (sin aviso)',
} as const;
