export const JA_TEXTS = {
    // Plugin Info
    pluginTitle: 'Karpathy LLM Wiki 設定',
    pluginIntro: '本プラグインはObsidian用に{{link}}の概念を実装しています。ノートを読み込み、AIでエンティティと概念を抽出し、Vault内に構造化された相互リンクWikiを構築します。',
    karpathyLinkText: 'Andrej KarpathyのLLM Wiki',

    // Features Section
    featuresTitle: '仕組み',
    workflow1Title: '1. 取り込み',
    workflow1Desc: 'ノートを選択 — AIがエンティティ、概念、関係を抽出してWikiページにまとめます。',
    workflow2Title: '2. 問い合わせ',
    workflow2Desc: 'Wikiとチャット — 回答は取り込んだ知識に基づいています。',
    workflow3Title: '3. 維持管理',
    workflow3Desc: '自動生成のインデックス、相互リンク、LintチェックでWikiの健全性を保ちます。',

    // Language Switcher
    languageTitle: 'インターフェース言語',
    languageDesc: '設定パネルの表示言語を選択してください。言語変更をコマンドパレットに適用するには、プラグインを再起動してください。',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // Status
    statusTitle: 'LLM Client の状態',
    llmWikiStatusSection: 'LLM-Wiki 状態',
    statusInitialized: '初期化済み',
    statusReady: 'LLM 準備完了',
    statusNotReady: 'LLM 未設定 — 上記の設定と接続テストを完了してください',
    statusNotInitialized: '未初期化',
    currentProvider: '現在のプロバイダー',

    // Provider Configuration
    providerSection: 'LLM 設定',
    providerName: 'LLM プロバイダー',
    providerDesc: '定義済みプロバイダーまたはカスタムOpenAI互換サービスを選択。Coding Plan等のバンドルの場合、カスタムOpenAI/Anthropicを選択し、プロバイダーのBase URLとAPI Keyを手動入力',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: 'APIキー。OSの資格情報マネージャーに保存され、data.jsonには書き込まれません。',
    apiKeyPlaceholder: 'API Keyを入力',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: 'SecretStorageを移行',
    apiKeyMigratedToSecretStorageSuccess: 'APIキーがSecretStorageから設定に復元されました。',
    apiKeyMigrationFailedNotice: 'SecretStorageへのAPIキー保存に失敗しました: {}',
    codexAuthName: 'ChatGPTプランにサインイン',
    codexAuthDesc: 'ChatGPTプランの利用枠を使う実験的なCodex OAuthアクセスです。OpenAI Platform APIの課金は別途行われます。',
    codexAuthSignedOut: 'サインインしていません',
    codexAuthSignedIn: 'サインイン済み',
    codexAuthBrowserButton: 'ブラウザーでサインイン',
    codexAuthDeviceButton: 'デバイスコードを使用',
    codexAuthDeviceInstructions: 'OpenAIのページでこのコードを入力してください：{}',
    codexAuthCopyCode: 'コードをコピー',
    codexAuthSignOutButton: 'サインアウト',
    codexAuthBusy: 'OpenAIの承認を待っています…',
    codexAuthFailed: 'ChatGPTの承認に失敗しました：{}',
    codexAuthQuota: 'ChatGPT Codexの利用枠に達しました。表示されたリセット期間を待ってから再試行してください。',
    codexAuthExperimental: '実験的機能：利用可否はOpenAI Codexの認証およびモデルポリシーに従います。',
    codexModelsRefreshName: 'アカウントモデル',
    codexModelsRefreshDesc: 'ログイン中の OpenAI Codex アカウントから選択可能なモデルを同期します。',
    codexModelsRefreshButton: 'アカウントモデルを更新',
    codexModelsRefreshing: '更新中...',
    codexModelsRefreshSuccess: '{} 個のアカウントモデルを同期しました。',
    codexModelsRefreshFailed: 'アカウントモデルを更新できませんでした。利用可能なフォールバック一覧を使用します。{}',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: '必須：カスタムOpenAI互換エンドポイント',
    baseUrlDescOverride: '任意：定義済みBase URLを上書き',

    // Ollama Hint
    ollamaHint: 'Ollamaはローカルで動作するため、API Keyは不要です',
    lmstudioHint: 'LM Studioはローカルで動作します。API Keyは任意です',
    maxTokensPerCallName: '1回呼び出しの最大出力トークン数',
    maxTokensPerCallDesc: 'モデルが1回の応答で生成できるトークン量を制限します。小さいコンテキストウィンドウのローカルモデルを使っていてエラーが出る場合は下げてください。クラウドモデルではデフォルト（0 = 制限なし）のままで問題ありません。',

    slugCaseName: 'ファイル名の大文字小文字',
    slugCaseDesc: '生成される Wiki ファイル名を小文字化するかどうかを制御します。大文字小文字に意味のある言語（ドイツ語の名詞など）では「保持」を推奨。',
    slugCaseLower: '小文字（デフォルト）',
    slugCasePreserve: '大文字小文字を保持',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: 'エイリアスの最小文字数',
    minAliasLengthDesc: 'これより短いエイリアス（前後の空白を除く）は Wiki ページに書き込まれません。既定値 2 では 2 文字の略語（ML、AI、UI）が使えます。大文字小文字だけが異なる 2 文字のエイリアス（Cr/CR）が溜まる場合は 3 に上げてください。範囲 2–6。',
    minAliasLengthClamped: '値が範囲外（2–6）のため {} に設定しました',

    // Model Selection
    modelSection: 'モデル選択',
    fetchModelsName: '利用可能なモデルを取得',
    fetchModelsDesc: 'プロバイダーAPIから最新のモデル一覧を取得します',
    fetchModelsButton: 'モデルを取得',
    fetchingModels: '取得中...',
    fetchSuccess: '取得成功！{}件のモデルが利用可能です',
    fetchFailed: '取得に失敗したかリストが空です。モデル名を手動で入力してください',
    fetchNotSupported: 'このプロバイダーはモデル一覧の取得に対応していません',
    fetchErrorAuth: '認証に失敗しました（HTTP 401/403）。API キーを確認するか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorEndpoint: 'エンドポイントが見つかりません（HTTP 404）。BaseURL を確認するか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorServer: 'プロバイダーサーバーエラー（HTTP 5xx）。後でもう一度お試しいただくか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorEmpty: 'このエンドポイントはモデル一覧を提供していません。モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorNetwork: 'ネットワークリクエストが失敗しました。インターネット接続、BaseURL、プロキシ設定、または API Key を確認してください。モデル ID を直接入力して「テスト接続」をクリックして検証することもできます。',

    selectModelName: 'モデルを選択',
    selectModelDesc: '{}件の利用可能なモデルから選択',
    customInputOption: 'カスタム入力...',
    customInputHint: '他のモデルを使用するには「カスタム入力...」を選択してください',

    modelName: 'モデル名',
    modelDescCustom: 'カスタムモデルを使用中（上のボタンをクリックして一覧を再取得）',
    modelDescFetchFailed: 'モデル一覧の取得に失敗しました。API キーとエンドポイント URL を確認するか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    modelInputPlaceholder: 'モデル ID を入力してテスト接続',

    switchToDropdown: 'ドロップダウン選択に切り替え',
    useDropdownButton: 'ドロップダウンを使用',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: 'モデル範囲',
    modelTaskModeDesc: 'すべてのタスクで同じモデルを使用するか、タスク別に取り込み / 保守修復 / クエリで別モデルを使用するかを選択してください。統一モデルに戻すと、非表示のタスク別モデル値は保持されます（消去されません）。',
    modelTaskModeUnified: '統一モデルを使用（デフォルト）',
    modelTaskModePerTask: 'タスクごとに異なるモデルを使用',
    perTaskIngestModelName: '取り込みモデル',
    perTaskIngestModelDesc: 'ノート・会話の取り込み、Schema 保守、ウェルカムノート生成に使用されます。',
    perTaskLintModelName: '保守修復モデル',
    perTaskLintModelDesc: 'Lint 分析、重複検出、各種修復、孤立リンクの修正に使用されます。',
    perTaskQueryModelName: 'クエリモデル',
    perTaskQueryModelDesc: 'Query Wiki チャットと Wiki 保存評価に使用されます。',

    // Test & Save
    testConnectionName: '接続テスト',
    testConnectionDesc: '設定が正常にLLM APIを呼び出せるか確認します',
    testButton: '接続テスト',
    testing: 'テスト中...',

    saveSettingsName: '設定を保存',
    saveSettingsDesc: '現在の設定を保存します',
    saveButton: '設定を保存',
    testConnectionSuccessful: '接続成功',
    testConnectionFailed: '接続失敗',
    testConnectionProvider: 'プロバイダー：',
    codexAuthRequired: '接続をテストする前にChatGPTプランへサインインしてください。',
    bedrockSsoRequired: '接続をテストする前に、設定 → Bedrock で AWS SSO サインインを実行してください。',
    bedrockIamRequired: '接続をテストする前に、設定 → Bedrock で IAM アクセスキーを入力してください。',
    bedrockAuthMethodName: '認証方式',
    bedrockAuthMethodDesc: 'API キーは Bedrock API キーを使用します。AWS SSO は IAM Identity Center の認証情報でリクエストに署名し、IAM キーは静的なアクセスキーを使用します。',
    bedrockAuthOptionApiKey: 'API キー',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'IAM キー',
    bedrockSsoStartUrlName: 'SSO スタート URL',
    bedrockSsoStartUrlDesc: '組織のポータル URL（例：https://d-xxxxxxxxx.awsapps.com/start）',
    bedrockSsoAccountIdName: 'AWS アカウント ID',
    bedrockSsoAccountIdDesc: 'ロールを引き受ける 12 桁のアカウント ID（例：123456789012）',
    bedrockSsoRoleNameName: 'ロール名',
    bedrockSsoRoleNameDesc: 'Bedrock アクセス用の IAM ロール（例：PowerUserAccess）',
    bedrockSsoLoginButton: 'AWS SSO でサインイン',
    bedrockSsoSignOutButton: 'AWS SSO からサインアウト',
    bedrockSsoStatusSignedIn: 'サインイン済み・{} に失効',
    bedrockSsoStatusSignedOut: '未サインイン',
    bedrockSsoBusy: 'サインイン中…',
    bedrockSsoUserCodeInstructions: 'AWS SSO コード:{}。リンクを開いてアクセスを承認してください。',
    bedrockSsoCopyCode: 'コードをコピー',
    bedrockSsoFailed: 'AWS SSO サインインに失敗しました:{}',
    bedrockSsoDetectedPrefill: 'アカウント/ロールを検出:{}',
    bedrockIamKeyName: 'アクセスキー ID',
    bedrockIamKeyDesc: 'IAM アクセスキーの識別子（例：AKIA…、ASIA…）',
    bedrockIamSecretName: 'シークレットアクセスキー',
    bedrockIamSecretDesc: 'このデバイスのシークレットストレージにのみ保存され、data.json には書き込まれません',
    bedrockIamSessionTokenName: 'セッショントークン（任意）',
    bedrockIamSessionTokenDesc: '一時的な認証情報（STS）の場合のみ必要です',
    bedrockIamClearButton: '保存済み IAM キーをクリア',
    bedrockIamSaveFailed: 'IAM キーの保存に失敗しました:{}',
    errorUnknown: '不明なエラー',
    savedNotice: '設定を保存しました！',

    // v1.24.0 (Bug C 3.4 / plan C): 段階的移行の通知
    queryHistoryMigrationNotice: 'Query Wiki の履歴に以前の wiki フォルダーのリンクが含まれています。新しい会話は自動的に最新のフォルダーを使用します。すべての履歴メッセージをリフレッシュするには、Query Wiki パネルを開き、その中の「履歴をクリア」ボタンをクリックしてください。',

    // v1.24.0 Issue #251: カスタム Query 命令（折りたたみ可能パネル）
    customInstructionsTitle: 'カスタム Query 命令',
    customInstructionsDesc: 'Query Wiki のすべてのチャット応答のシステムプロンプト末尾に追記される命令です。Query Wiki チャットのみに影響し、取り込み・lint・ページ生成には影響しません。',
    customInstructionsPlaceholder: '例：リサーチタスクとして扱う：広く検索、ソースを引用、事実と解釈を区別する...',
    customInstructionsApply: '適用',
    customInstructionsClear: 'クリア',
    customInstructionsCharCount: '{current}/{max} 文字',
    instructionsApplied: 'カスタム Query 命令を保存しました。',
    instructionsCleared: 'カスタム Query 命令をクリアしました。',

    // Issue #137: LLM フォールバック通知
    fallbackThinkingDialect: '思考制御：「{dialect}」方言に切り替えました（このプロバイダーは別の思考制御フィールド形式を使用します）。出力は変わりません。',
    fallbackThinkingNone: 'このプロバイダーでは思考制御を完全に無効化しました。推論コンテンツが引き続き表示される場合があります。その場合は別のモデルを試してください。',
    fallbackParamStripped: 'パラメータ「{field}」はこのプロバイダーでサポートされていません。リクエストから削除されました。動作は設定と異なる場合があります。',

    // Wiki Folder
    wikiSection: 'Wiki設定',
    wikiFolderName: 'Wiki フォルダー',
    // v1.24.0: 変更後に Obsidian の再起動が必要であることを明示（engine キャッシュと開いている Query Wiki パネルの再バインド）
    wikiFolderDesc: '生成された Wiki ページの保存先。変更後は Obsidian の再起動が必要です——engine のキャッシュと開いている Query Wiki パネルの再バインドが行われます。',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'まずAPI Keyを設定してください',
    errorNoModel: 'まずモデルを選択してください — 「モデルを取得」をクリック、または Model ID を手動入力',
    llmNotReady: 'LLMが設定されていません。設定 → Karpathy LLM Wiki でプロバイダーを設定し、モデルを取得して接続テストに合格してください。',
    errorFetchFailed: '失敗：{}',

    // Query Settings
    querySectionTitle: 'Wiki 問い合わせ設定',
    // v1.24.0: 「会話履歴の最大数」から「会話の関連記憶ラウンド数」に改名
    // 意味をより正確に表現。1 = 各ターンが独立（前文を参照しない）。
    // 設定はドロップダウンなので、プリセット値を説明に列挙する必要なし。
    // v1.24.0: maxConversationHistoryHint は未使用の i18n key でした（UI から参照なし）。
    // 推奨文を desc に統合しました。
    maxConversationHistoryName: '会話の関連記憶ラウンド数',
    maxConversationHistoryDesc: 'LLM が新しい会話で参照できる過去のラウンド数（記憶として）。1 = 各ターンが独立（前文を参照しない）；値が大きいほど、モデルがセッション前半のラウンドを覚えています。推奨：ワンショット Q&A は 1、継続的な調査は 10〜50。',
    numberRangeValidation: '1〜50の数値を入力してください',
    numberRangeClamped: '値が範囲外です（1-500）、自動的に {} に設定されました',
    // Query Modal UI
    queryModalTitle: 'Query Wiki - 対話型問い合わせ',
    queryModalPlaceholder: '質問を入力...',
    queryModalSendButton: '送信',
    queryModalStopButton: '停止',
    queryModalSaveButton: 'Wikiに保存',
    queryModalClearButton: '履歴をクリア',
    queryModalHistoryCount: '会話履歴：{}/{} ラウンド',
    queryModalStreaming: 'ストリーミング中...',
    queryModalFallbackStreaming: 'ストリーミングに対応していないため、非ストリーミングに切り替えました。お待ちください...',
    queryPhaseSearching: 'Wikiインデックスを分析し、関連ページを選別中...',
    queryPhaseFoundPages: '{count}件見つかりました：{pages}',
    queryPhaseLoadingPages: 'ページコンテンツを読み込み中...',
    queryPhaseContextReady: 'コンテキスト準備完了。回答を生成中...',
    queryPhaseGenerating: '生成中...（経過 {time}秒）',
    queryPhaseNonStreaming: '非ストリーミングモード、回答生成中...（経過 {time}秒）',
    queryModalErrorPrefix: 'エラー：',
    queryModalHint: '問い合わせはWikiの内容に基づきます。「Wikiに保存」をクリックすると、価値のある会話をWikiページとして抽出できます。',

    // v1.20.0: Query Wiki 思考ブロック折り畳み見出し
    queryThinkingSummary: '思考プロセス',
    queryThinkingSteps: 'ステップ',

    // Error Messages
    errorLLMClientNotInit: 'LLM Clientが初期化されていません。設定を保存してください。',
    errorIngestFailed: '取り込み失敗：',
    errorQueryFailed: '問い合わせ失敗：',
    fileWriteFailed: 'ファイルを作成または更新できません：{path}',

    // Success Messages
    ingestSuccess: '取り込み成功：{}ページ作成、{}ページ更新',
    querySuccess: '問い合わせ完了',
    lintSuccess: 'Wiki Lint完了',
    lintReadingPages: '{count}件のWikiページを読み込み中...',
    lintReadingPagesProgress: 'Wikiページ読み込み中：{current}/{total}...',
    lintScanningLinks: 'リンク切れをスキャン中...',
    lintScanningLinksProgress: 'リンク切れスキャン中：{current}/{total}...',
    lintCheckingDuplicates: '重複ページを確認中...',
    lintCheckingDuplicatesProgress: '重複ページを検証中：バッチ {current} ...',
    lintFixingPolluted: '汚染ページを修正中 {current}/{total}：{title} → {newTitle}',
    lintModalFixPolluted: '🧹 汚染ページを修正（{count}）',
    lintDuplicateCheckFailed: '重複検出に失敗しました — コンソールで詳細を確認してください',
    lintDuplicateCheckFailedDetail: '重複チェックが{step}で失敗：{error}',
    lintMergeItemFailed: 'マージ失敗：{source} → {target} — {error}',
    lintAliasesMissing: '別名未設定：{count}件のページに別名がありません',
    lintAliasesSection: 'エイリアス欠落ページ [{count} 件]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: '別名を補完（{count}件）',
    lintAliasesFilling: '別名生成中 {current}/{total}：{page}',
    lintAliasesFilled: '別名補完完了。{filled}/{total}ページに入力しました。',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: '語彙外タグ（検出）[{count} 件]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: '別名生成に失敗：{page} — {error}',
    lintFixItemFailed: '修復失敗：[[{target}]] — {error}',
    lintLinkItemFailed: 'リンク設定失敗：{page} — {error}',
    lintRetrying: 'エラー後再試行中（{attempt}/{max}）...',
    lintAnalyzingLLM: 'LLMがWikiの健全性を分析中...',
    saveToWikiSuccess: '会話をWikiに保存しました！',
    querySaveAlreadyExists: '注意：何も書き込まれませんでした（ナレッジは既にWikiに存在します）：',
    saveSummary: '{entities} エンティティ, {concepts} コンセプト, {pages} ページ',
    aliasAdded: 'ページ「{page}」に別名「{alias}」を追加しました',

    // Status Messages
    ingestingSources: 'ソースファイルを取り込み中...',
    queryingWiki: 'Wikiに問い合わせ中...',
    lintingWiki: 'WikiをLint中...',
    savingToWiki: '会話をWikiに保存中...',
    clearingHistory: '会話履歴をクリア中...',

    // Buttons
    ingestButton: '取り込み',
    queryButton: '問い合わせ',
    lintButton: 'Lint',
    cancelButton: 'キャンセル',

    // Links
    karpathyGistLink: 'KarpathyのLLM Wiki Gist',
    obsidianPluginAPI: 'Obsidian Plugin API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'AWS リージョン',
    bedrockRegionDesc: 'このアカウントの Amazon Bedrock リージョン。bedrock-mantle エンドポイントの URL を決定し、baseURL で上書きできません。',
    bedrockRegionHint: 'bedrock-mantle は 18 リージョンで利用可能。モデル対応はリージョンごとに異なります。',

    // Other
    availableModelsLoading: '利用可能なモデルを読み込み中...',
    noModelsAvailable: '利用可能なモデルがありません',

    // LLM Language Hint
    llmLanguageHint: '日本語で回答してください。',

    // Schema Configuration
    schemaSection: 'スキーマ設定',
    enableSchemaName: 'スキーマを有効化',
    enableSchemaDesc: 'schema/config.mdを生成し、すべてのLLMプロンプトに注入して構造化されたWiki出力を実現します',
    viewSchemaButton: 'スキーマの閲覧 / 編集',
    regenerateSchemaButton: 'デフォルトスキーマを再生成',
    schemaRegeneratedNotice: 'デフォルトスキーマを再生成しました。',
    schemaRegenerateFailed: 'スキーマの生成に失敗しました',

    // Wiki 初期化状態
    wikiInitStatusReady: 'Wiki 初期化済み',
    wikiInitStatusNotReady: 'Wiki 未初期化 — 初回取り込み時に自動作成されます',

    // Wiki Output Language
    wikiLanguageName: 'Wiki 出力言語',
    wikiLanguageDesc: '生成されるすべてのWikiページ、インデックス、ログ、問い合わせの応答がこの言語で作成されます',
    customWikiLanguageOption: 'カスタム...',
    customWikiLanguageHint: '言語名を入力してください（例：Italian、Arabic）。LLMに出力言語の指示として渡されます。',
    customWikiLanguagePlaceholder: '例：Italian',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // Extraction Settings
    extractionSectionTitle: '知識抽出',
    extractionGranularityName: '抽出粒度',
    extractionGranularityDesc: 'ソースファイルごとの抽出数を制御。高いほどページ/API消費が増加。\n精细：深度分析（100個）。標準：日常ノート（50個）。粗め：概要把握（10個）。最小：100件以上一括処理（ソースあたり約5件の上限。項目数の制限であり記述の詳細さではない）。カスタム：独自設定（最大300個）。\n提示：ファイル数が多い場合は最小/粗めを使用し時間とコストを節約。',
    extractionGranularityFine: '精细 — 深層分析（≤100件）',
    extractionGranularityStandard: '標準 — 日常ノート（≤50件）',
    extractionGranularityCoarse: '粗め — 概要（≤10件）',
    extractionGranularityMinimal: '最小 — 100+ファイル一括処理（≤5件）',
    extractionGranularityCustom: 'カスタム — 上限を独自設定（1~500）',
    customEntityLimitName: 'カスタムエンティティ上限',
    customEntityLimitDesc: 'ソースファイルごとの最大エンティティ抽出数（1-500）',
    customConceptLimitName: 'カスタム概念上限',
    customConceptLimitDesc: 'ソースファイルごとの最大概念抽出数（1-500）',

    // Issue #85 v2: タグ語彙 (chip 入力 UI, Wiki 設定内に埋め込み)
    tagVocabularyInlineDesc: 'entity/concept フロントマターのタグを管理語彙で制御します。"/" を含むネストタグは保持されます。',
    tagVocabularyModeName: 'タグ語彙設定',
    tagVocabularyModeDescDefault: 'デフォルトは組み込みタグを使用: {}。「カスタム」に切り替えると独自の語彙を定義できます。',
    tagVocabularyModeDescCustom: 'カスタム: 下で chip 入力を使って独自の entity/concept タグを定義します。Enter またはカンマで追加、× で削除。',
    tagVocabularyNotEnforcedHint: 'スキーマのヒントのみ — LLMが語彙外の型を出力する場合もあります。Lintを実行して該当ページを見つけて修正してください。',
    tagVocabularyModeDefault: 'デフォルト (組み込みサブタイプタグ)',
    tagVocabularyModeCustom: 'カスタム (ユーザー定義)',
    customEntityTagsName: 'カスタムエンティティタグ',
    customEntityTagsDesc: 'Enter またはカンマで chip 追加、× で削除。"/" を含むネストタグは保持されます。',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'カスタム概念タグ',
    customConceptTagsDesc: 'Enter またはカンマで chip 追加、× で削除。"/" を含むネストタグは保持されます。',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: '重複タグをスキップしました',

    // Ingestion Acceleration
    accelerationSectionTitle: '取り込み高速化',
    pageGenerationConcurrencyName: 'LLM 並列度',
    pageGenerationConcurrencyDesc: '取り込みおよびLint操作中の並列LLM呼び出し数。値を高くすると処理が高速化されますが、APIコストの増加やレートリミットのトリガーに注意してください。',
    concurrencyValueSingular: '現在の並列度：{}（直列 — 最も安全）',
    concurrencyValuePlural: '現在の並列度：{}（並列）',
    batchDelayName: 'バッチ遅延（ms）',
    batchDelayDesc: '並列バッチ間の遅延によりAPIレートリミットを回避します（100〜10000ms）。現在値：{}ms。429エラーが発生する場合は値を大きくしてください。',

    // Auto Maintenance
    autoMaintainSection: '自動メンテナンス',
    autoMaintainBetaBadge: 'ベータ版 — 実験機能。問題が発生する可能性があります。上級ユーザーのみ推奨。',
    autoWatchName: '監視フォルダー',
    autoWatchDesc: '監視フォルダー内で新規または変更された.mdファイルを自動検出し、通知または自動取り込みを行います',
    watchedFoldersName: '監視対象フォルダー',
    watchedFoldersDesc: '新コンテンツを監視するフォルダー。「フォルダーを追加」をクリックしてVaultから選択してください。',
    addWatchedFolderButton: 'フォルダーを追加',
    removeWatchedFolderButton: '削除',
    webClipperPresetName: 'Clippingsを監視（Web Clipper）',
    webClipperPresetDesc: 'Obsidian Web Clipperが使用するClippings/フォルダーを監視リストに追加します。ウェブクリップがWikiに自動取り込みされます。',
    noWatchedFoldersHint: '監視フォルダーが設定されていません。フォルダーを追加するかClippingsプリセットを有効にしてください。',
    autoWatchModeName: '監視モード',
    autoWatchModeDesc: '「通知のみ」はプロンプトを表示します。「自動取り込み」はサイレントに処理します。',
    watchModeNotify: '通知のみ',
    watchModeAuto: '自動取り込み',
    autoWatchDebounceName: 'チャタリング防止遅延（秒）',
    autoWatchDebounceDesc: 'ファイル変更後に取り込みをトリガーするまでの待機時間（1〜60秒）',
    periodicLintName: '定期 Lint',
    periodicLintDesc: 'スケジュールに従ってLLM Lintを実行。前回チェック以降にソースファイルの変更がある場合のみ実行します',
    periodicLintOff: 'オフ',
    periodicLintDaily: '毎日',
    periodicLintWeekly: '毎週',
    periodicLintMonthly: '毎月',
    autoSmartFixName: '自動スマート修正',
    autoSmartFixDesc: 'Lint 実行時に、レポートモーダルを表示せず自動的にすべての修正（スマート一括修正）を適用します。修正完了後もサマリーは表示されます。',
    autoSmartFixNotice: '自動スマート修正：すべての修正を適用中...',
    autoIngestLevelName: '自動取り込み通知方法',
    autoIngestLevelDesc: '自動取り込み完了時の通知方法。「通知」は一時的に表示され操作を妨げません。「モーダル」は完全なレポートを開きます。Watch モードが「通知のみ」の場合は無効です。',
    autoIngestLevelNotice: '通知（非ブロッキング）',
    autoIngestLevelModal: 'モーダル（完全レポート）',
    startupCheckName: '起動時にクイック修正を実行',
    startupCheckDesc: 'プラグイン読み込み時に低レベル書式の問題（sources フィールド、二重 wikilink）を自動修正し、Wiki ディレクトリ構造を検証します。デフォルトで有効。',
    suggestSchemaCommand: 'スキーマ更新を提案',
    autoMaintainCostWarning: '⚠️ コストのお知らせ：自動メンテナンス機能はAPIトークンを消費します。「自動取り込み」はソースファイルの変更ごとにLLM呼び出しをトリガーします。「定期Lint」はスケジュールに従ってLLMヘルスチェックを実行します（ソースの変更が検出された場合のみ）。想定外の課金を避けるため、慎重に設定してください。',

    // Notices
    startupCheckSummary: 'Wikiは{pages}ページ（{entities}エンティティ、{concepts}概念、{sources}ソース）',
    watcherActiveNotice: 'Wiki: ファイル監視有効 — 監視フォルダーをモニタリング中',
    watchIngestNotice: 'Wiki: sources/ に{count}件のファイル変更あり。「ソースの取り込み」を実行して処理してください。',
    autoIngestRunning: '{count}件の変更ファイルを自動取り込み中...',
    autoIngestComplete: '自動取り込み完了：成功 {success}件、失敗 {fail}件',
    scheduledLintRunning: 'スケジュールされたWiki Lintを実行中...',
    wikiLintStats: 'Wiki Lint: {pages}ページ（{entities}エンティティ、{concepts}概念、{sources}ソース）',
    wikiHealthStats: 'Wiki健全性: {pages}ページ（{entities}エンティティ、{concepts}概念、{sources}ソース）{indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki クイック修正完了',
    startupCheckStructureLabel: 'Wiki 構造',
    startupCheckStructureOk: '完了',
    startupCheckStructureMissing: '不完全 — 初回取り込み時に自動作成されます',
    startupCheckSourcesLabel: 'Sources 正規化',
    startupCheckSourcesClean: '既に正規化済み',
    startupCheckSourcesCleaned: '{files} ファイル、{entries} エントリを修正',
    startupCheckIncompleteClean: '未完成ページ：なし',
    startupCheckIncompleteArchived: '未完成ページ：{count} 件をアーカイブ（.trash から復元可能）',
    startupCheckDisableHint: '無効化するには 設定 → 自動メンテナンス → 起動時にクイック修正を実行',
    lintWikiStart: 'Wiki Lintを開始中...',
    lintWikiComplete: 'Wiki Lint完了',
    lintWikiFailed: 'Wiki Lint失敗',
    analyzingSchema: 'Wikiを分析し、スキーマの提案を生成中...',
    schemaSuggestionGenerated: 'スキーマの提案を生成しました。wiki/schema/suggestions.mdを確認してください',
    noSchemaUpdateNeeded: 'スキーマの更新は不要です。',
    schemaSuggestionFailed: 'スキーマの提案に失敗しました',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Schema 更新プレビュー',
    schemaDiffSummary: '+{add} / -{del} 行',
    schemaDiffRegenerateLabel: '提案を修正（任意）：',
    schemaDiffRegenerateBtn: '再生成',
    schemaDiffOpenFileBtn: 'ファイルを開く',
    schemaDiffApplyBtn: '適用',
    schemaDiffApplied: 'Schema を更新しました。バックアップ：{path}',
    schemaDiffEmptyTitle: 'LLM は変更不要と判断',
    schemaDiffFailed: 'Schema の適用に失敗：{reason}',
    schemaDiffRestoreHint: '{path} にバックアップしました。復元するには、ファイルエクスプローラーでそのファイルを "wiki/schema/config.md" にリネームしてください。最近3件のバックアップが保持されます。',
    schemaRegenerateNoBody: '再生成は成功しましたが、LLM は新しい Schema を返しませんでした。',
    schemaNotFoundNotice: 'スキーマファイルが見つかりません。スキーマを有効化して作成してください。',
    selectFolderNoMdFiles: 'フォルダー {path} にMarkdownファイルがありません',
    batchIngestSkipNotice: '取り込み済みの{skipped}/{total}ファイルをスキップ。{new}件の新ファイルを取り込み中...',
    batchIngestAllIngested: 'このフォルダー内の{total}件はすべて取り込み済みです。',
    batchIngestStarting: '「{folder}」から{count}件を取り込み中 — 数分かかる場合があります。完了後にレポートが表示されます。',
    batchIngestComplete: 'バッチ取り込み完了：成功 {success}/{total}件、失敗 {fail}件',
    batchIngestFailedFiles: '失敗したファイル：',
    historyTruncated: '履歴を直近の{max}ラウンドに切り捨てました',
    historyCleared: '履歴をクリアしました',

    // User Feedback Loop
    reviewedPagePreserved: 'ユーザーレビュー済みのコンテンツを保持：{}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: 'Wikiに保存しますか？',
    querySuggestSaveDesc: 'この会話には価値のある知識が含まれています。Wikiに保存しますか？',
    querySuggestSaveYes: '保存',
    querySuggestSaveNo: '閉じる',

    // Ingestion Report
    ingestReportElapsedTime: '経過時間',
    ingestReportSkippedFiles: 'スキップ済み（取り込み済み）',
    ingestReportRejectedFiles: 'スキップ',
    rejectionReasonEmpty: '空',
    rejectionReasonType: '非対応の形式',
    rejectionReasonDuplicate: '重複コンテンツ',
    rejectionReasonPdfUnsupported: 'プロバイダーが PDF を読み取れません',
    rejectionReasonMineruPageLimit: 'MinerU のページ数上限を超過',
    rejectionReasonMineruSizeLimit: 'MinerU のサイズ上限を超過',
    ingestReportFailedGuidance: 'これらの項目は自動作成できませんでした。対応するページを手動で作成するか、抽出粒度を下げてソースファイルを再取り込みしてください。',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: '単一ソースの取り込み',
    cmdIngestFolder: 'フォルダーからの取り込み',
    cmdIngestMultipleFiles: '複数ファイルを取り込み',
    cmdQueryWiki: 'Wikiに問い合わせ',
    cmdLintWiki: 'WikiのLint',
    cmdRegenerateIndex: 'インデックスの再生成',
    cmdSuggestSchema: 'スキーマ更新の提案',
    cmdCancelIngestion: '現在の取り込みをキャンセル',
    cmdIngestActiveFile: '現在のファイルを取り込む',
    cmdViewHistory: '取り込み履歴を表示',
    noActiveFile: '現在開いているファイルはありません',
    mdOnlyFile: 'Markdownファイルのみ取り込み可能です',
    ingestSingleFileStart: '取り込み中：{filename}',
    ingestCheckingExisting: '既に取り込み済みのファイルを確認中...',
    lintFindingsSummary: '{total} 件の指摘',

    // Ingestion status bar
    ingestionStatusBar: '取り込み中... クリックでキャンセル',
    lintStatusBar: 'チェック中... クリックでキャンセル',
    ingestStatusAnalyzing: '取り込み中… (クリックでキャンセル)',
    lintStatusAnalyzing: 'チェック中… (クリックでキャンセル)',
    ingestStageAnalyze: 'ソースを解析中',
    ingestStageSummary: '要約を生成中',
    ingestStageEntity: 'エンティティを作成中',
    ingestStageConcept: 'コンセプトを作成中',
    ingestStageRetry: '失敗したページを再試行中',
    ingestStageSave: 'ページを保存中',
    ingestStageIndex: 'インデックスを生成中',
    pdfStageReading: 'PDF を読み取り中',
    pdfStageConverting: 'PDF を変換中',
    pdfStageSidecar: 'サイドカーを書き出し中',
    lintStagePrep: 'ページを読み取り中',
    lintStageProgrammatic: 'リンクをスキャン中',
    lintStageAnalyzing: 'LLM分析を実行中',
    lintStageDedup: '重複を検出中',
    lintStageContradiction: '矛盾を検出中',
    ingestionCancelling: 'キャンセル中 — 現在のバッチ完了後に停止します',
    ingestionCancelled: '取り込みがキャンセルされました',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: 'バッチ 1/{total} を分析中...',
    ingestBatchProgress: 'バッチ {current}/{total} を分析中（エンティティ {entities}、コンセプト {concepts} まで）...',
    ingestBatchProcessed: 'バッチ {current} を分析しました。処理中...',
    ingestAnalyzing: '分析中：{filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] サマリーを作成中...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}：{name}',
    ingestUpdating: '[{step}/{totalSteps}] 更新中：{name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] インデックスを作成中...',
    ingestItemTypeEntity: 'エンティティ',
    ingestItemTypeConcept: 'コンセプト',
    convAnalyzing: '会話を分析中...',
    convCheckingExisting: '既存の知識を確認中...',
    convAlreadyExists: 'この知識は既に Wiki に存在します',
    convCreatingSummary: 'サマリーページを作成中...',
    convGeneratingSummary: 'サマリーページを生成中...',
    convSavingEntity: 'エンティティを保存中：{name}',
    convSavingConcept: 'コンセプトを保存中：{name}',
    convGeneratingIndex: 'インデックスを作成中...',

    // Lint Report
    lintReportTitle: 'Wiki Lintレポート',
    lintReportSummary: 'Wiki 状態の概要: 合計 {total} ページ、{aliasesMissing} ページにエイリアス欠落、重複 {duplicates}、デッドリンク {deadLinks}（うち {deadLinkFromDup} は重複関連）、孤立 {orphans}（うち {orphanFromDup} は重複）、空ページ {emptyPages}、根拠のない引用 {ungroundedQuotes}、語彙外タグ {tagViolations}。Lint 実行時間: {elapsedSeconds}秒',

    // Advanced LLM Settings (Issues #99 / #128)
    // v1.26.0 (#382 item 2): 名称を「高度なパラメータ設定」から
    // 「LLM 高度なパラメータ」に変更 — LLM サンプリングに特化し、
    // 下部の汎用「詳細設定」パネルと区別。
    advancedLlmModeName: 'LLM 高度なパラメータ',
    advancedLlmModeDesc: 'デフォルトモードはモデルプロバイダーが推奨する設定に従います。明確に上書きする理由がある場合（例：特定のモデルに固定温度が必要、モデルの思考出力を抑制したい）のみ、カスタムに切り替えてください。',
    advancedSettingsDefault: 'デフォルト（プロバイダーに従う）',
    advancedSettingsCustom: 'カスタム（プロバイダーを上書き）',
    // v1.26.0 (#382 item 2): 下部の「詳細設定」パネル — LLM サンプリング以外の
    // 高度なユーザー設定の汎用の場所（lint 閾値、ウェルカムノート、将来の拡張）。
    advancedSettingsSection: '詳細設定',
    showAdvancedSettingsName: '詳細設定を表示',
    showAdvancedSettingsDesc: 'オンにすると下に高度な設定が表示されます。オフにすると非表示になり、デフォルト値にリセットされます。',
    disableThinkingName: '思考を無効にする',
    disableThinkingDesc: 'モデル応答の思考過程/推論テキスト出力をオフにします。デフォルトはオフで、モデルが推論を表示するかを自分で決めるため、それが通常最も良い回答になります。プロバイダーが生の推論テキストを応答に混ぜてしまい、きれいな答えが欲しい場合にのみオンにしてください。',
    taskPoliciesPlaceholder: '例: extract=text:off',
    taskPoliciesName: 'ステップごとの出力モードと思考',
    taskPoliciesDesc: 'パイプラインの各ステップにつき 1 項目、`step=mode:thinking` 形式でカンマ区切り（例: `extract=text:off`）。モード: `-`（変更なし）、`schema`、`json`、`text`。思考: `-`、`off`、`on`、`low`、`medium`、`high`。ステップ名には extract・extract-retry・lemma-classify・merge-triage・source-stance・dedup・page-generate・related-page・lint-dedup などがあります（綴りを誤った名前は何にも一致しません）。空欄なら組み込みの既定（抽出はテキストモード）。解析できない項目は保存されません。',
    // Issue #137: 互換性に関する注意事項（簡潔；プロバイダ一覧は省略）
    extractionTemperatureName: '抽出温度',
    extractionTemperatureDesc: 'モデルがエンティティ/コンセプトページを書くときに、厳密さを優先するか創造性を優先するかを制御します。値が低いほど決定的で原文に忠実、値が高いほど変化に富みます。ほとんどのユーザーは空欄のままで問題ありません。',
    chatTemperatureName: 'クエリ温度',
    chatTemperatureDesc: '「抽出温度」と考え方は同じですが、Query Wiki の質問回答にのみ影響します。値が低いほど文字通りの回答、値が高いほど会話調になります。ほとんどのユーザーは空欄のままで問題ありません。',
    repetitionPenaltyName: '繰り返しペナルティ',
    repetitionPenaltyDesc: 'モデルが同じ単語や言い回しを繰り返すのを抑止します。値が高いほど繰り返しを減らします。このパラメータを受け付けるのは一部のローカルモデルプロバイダー（Ollama、LM Studio、llama.cpp）のみで、クラウドプロバイダーは暗黙に無視します。ほとんどのユーザーは空欄のままで問題ありません。1.0 を超える値は、小型ローカルモデルの抽出時に LLM 出力エラーを引き起こす可能性があります。実行が失敗した場合は、この値を小さくするかクリアしてください。',
    repetitionPenaltyErrorHint: '注意：カスタムの繰り返しペナルティ {value} が設定されています。1.0 を超える値は小型ローカルモデルの文法制約付き抽出を壊す可能性があります。この設定を減らすかクリアしてから再試行してください。',
    temperaturePlaceholder: '空欄 = プロバイダーのデフォルト',
    // v1.26.0 (#382 item 2): 重複検出のしきい値（カスタム詳細モードのみ）。
    lintDedupJaccardLinkThresholdName: 'リンク重複の類似度',
    lintDedupJaccardLinkThresholdDesc: '範囲 0–1（デフォルト 0.4）。2 つのページが共通して指す wiki リンクの割合が、それぞれのリンク総数のうち少なくともこの値に達している場合に重複と判定されます。下げる → 近似重複をより多く検出（同じハブへのリンクしかないページも含む）；上げる → ほぼ同じページ群へリンクしているページのみが対象になります。無関係なページが同じハブにリンクしているだけの誤検出が多い場合は、この値を上げてください。空欄でデフォルトを使用します。',
    lintDedupJaccardBodyGateName: '本文の最低類似度',
    lintDedupJaccardBodyGateDesc: '範囲 0–1（デフォルト 0.2）。2 つのページが wiki リンクを共有していても、本文の類似度（割合）が少なくともこの値に達している場合にのみ重複と判定されます。下げる → LLM の検証に回る候補が増える；上げる → 本文がほぼ同一のページのみが対象になります。明らかに重複ではないページを LLM が検証しているようなら、この値を上げてください。空欄でデフォルトを使用します。',
    lintDedupBigramThresholdName: 'タイトルの類似度',
    lintDedupBigramThresholdDesc: '範囲 0–1（デフォルト 0.4）。2 つのページのタイトル（またはエイリアス）の文字一致率が少なくともこの値に達している場合に重複と判定されます。下げる → 表記揺れ、タイポ、同じ概念の翻訳なども検出；上げる → タイトルがほぼ同一のページのみが対象になります。タイトルが大きく異なるページを LLM が検証しているようなら、この値を上げてください。空欄でデフォルトを使用します。',
    lintDeadLinkSection: 'デッドリンク（検出）[{count} 件]',
    lintEmptyPageSection: '空ページ（検出）[{count} 件]',
    lintOrphanSection: '孤立ページ（検出）[{count} 件]',
    lintContradictionSection: '矛盾（検出済み）',
    lintDuplicateSection: '重複ページ（検出済み）',
    lintNoIssuesFound: '重複、リンク切れ、空ページ、孤立ページ、または根拠のない引用は検出されませんでした。',
    lintSourceDriftSection: '取り込み後に変更されたソースノート [{count} 件]',
    lintSourceDriftItem: '- [[{page}]] — 元ノート [[{note}]] が取り込み後に編集されました。ページが古い可能性があります',
    lintContradictionMarkerSection: '矛盾マーカー付きページ（マージトリアージ）[{count} 件]',
    lintContradictionMarkerItem: '- [[{page}]] — 矛盾するソース: {sources}。確認後に contradictions: マーカーを削除してください',
    lintQuoteGroundingSection: '根拠のない引用（検出）[{count} 件]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: 「{quote}」',
    lintDeadLinkItem: '- [[{source}]] → **{target}**（ページが存在しません）{dupFlag}',
    lintDeadLinkMore: '- ... 他{count}件のリンク切れ',
    lintEmptyPageItem: '- [[{page}]] — 実質的なコンテンツが50文字未満',
    lintOrphanItem: '- [[{page}]] — 他のWikiページからリンクされていません{dupFlag}',
    lintPollutedSection: '汚染ページ（検出）[{count} 件]',
    lintPollutedItem: '- [[{page}]] → "{clean}"に修正必要',
    lintSourcesNormalizedSection: 'Sources 正規化（自動修正）[{files} ファイル / {entries} 件]',
    lintSourcesNormalizedItem: '{files} ファイル内の {entries} 件の sources エントリを修正しました（外部パス、.md 拡張子、エイリアスパイプを削除し重複排除）。',
    lintDuplicateItem: '- [[{target}]] と [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' （⚠️ 重複ページが関連）',
    lintOrphanIsDuplicate: ' （⚠️ 重複ページ）',
    lintHubLinkDensitySection: 'ハブのリンク密度の問題（Issue #157 / #175）[{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — 被リンク {inDegree}、関連リンク {relatedCount}、識別度 {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ 削除',
    lintHubLinkDensityReview: '🔍 確認',
    lintHubLinkDensityKeep: '✅ 保持',
    lintHubLinkDensitySummary: '要約：削除推奨 {strip} ページ、確認推奨 {review} ページ。',
    lintHubLinkDensityNoRelated: ' （## Related セクションが見つかりません）',
    lintContradictionOpen: '未解決の矛盾：{count}件',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: '検出済み',

    // Lint Analysis Prompt

    // Lint Fix Progress
    lintFixProgress: '修復中 {current}/{total}：[[{target}]]',
    lintFixDeadComplete: 'リンク切れ修復完了。{fixed}/{total}件を修復しました。',
    lintFillProgress: '拡充中 {current}/{total}：{page}',
    lintFillComplete: 'ページ拡充完了。{filled}/{total}ページを入力しました。',
    lintDeleteCompleted: '{count}件の空スタブを削除しました',
    lintDeleteFailed: '空 stub の削除に {failed}/{total} 件失敗（詳細はコンソール）',
    lintFillFailed: '拡充に失敗：{page} — {error}',
    lintLinkProgress: 'リンク設定中 {current}/{total}：{page}',
    lintLinkComplete: '孤立ページへのリンク完了。{linked}ページにリンクを設定しました。',
    lintFixNoAction: '操作なし（クライアント未接続）',
    lintFixIndexUpdated: 'Wikiインデックスとログを更新しました。',
    lintPollutedFixed: '汚染ページ修正済み：{fixed}/{total}。インデックス再構築済み。',
    regenerateIndexCompleted: 'インデックス再構築済み',
    operationFailed: '失敗：',
    lintFixAllComplete: 'すべての修復が完了しました。詳細はログを確認してください。',
    lintFixAllNoChanges: '変更はありません — すべてのフェーズで 0 件でした。詳細は wiki/log.md を確認してください。',
    lintFixPhasesLabel: 'フェーズが変更',

    // Lint Report Modal
    lintModalActionsTitle: '修復提案（LLMトークンを消費）：',
    lintLogReference: '完全なレポートが log.md に保存されました',
    lintModalFixDeadLinks: 'リンク切れを修復（{count}件）',
    lintModalExpandEmpty: '空ページを拡充（{count}件）',
    lintModalDeleteEmpty: '空のスタブを削除（{count}件）',
    lintModalLinkOrphans: '孤立ページにリンク（{count}件）',
    lintModalAnalyzeSchema: 'スキーマを分析',
    lintModalMergeDuplicates: '重複をマージ（{count}件）',
    lintModalFixAll: '一括スマート修復（{count}件の問題）',
    lintMergeProgress: 'マージ中 {current}/{total}：{source} → {target}',
    lintMergeComplete: '重複マージ完了。{merged}/{total}組をマージしました。',

    // Ingest Report Modal
    ingestReportTitle: '取り込みレポート',
    ingestReportSourceFile: 'ソースファイル',
    ingestReportCreated: '作成',
    ingestReportUpdated: '更新',
    ingestReportContradictions: '矛盾を発見',
    ingestReportFailedTitle: '取り込み失敗',
    ingestReportErrorDetail: 'エラー詳細',
    ingestReportClose: '閉じる',
    ingestReportCreatedPages: '作成ページ：{count}',
    ingestReportUpdatedPages: '更新ページ：{count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki 操作ログ',
    logHeaderSubtitle: '取り込み、Lint実行、メンテナンス操作はすべてここに自動記録されます。より良い表示には**操作履歴**パネルをご利用ください：',
    logHeaderShortcut: 'Cmd+P → "操作履歴を表示"',
    logHeaderSettingsShortcut: 'または 設定 → 自動メンテナンス → 操作履歴 から',
    ingestionCreatedPages: '{count} ページ作成',
    ingestionUpdatedPages: '{count} ページ更新',
    ingestionNoticeHistoryHint: '詳細は操作履歴を表示',
    ingestReportEntitiesCount: '{count}件のエンティティ',
    ingestReportConceptsCount: '{count}件の概念',
    ingestReportContradictionsFound: '矛盾を発見：{count}件',
    ingestReportEntityType: 'エンティティ',
    ingestReportConceptType: '概念',
    timeMinutes: '分',
    timeSeconds: '秒',

    // レートリミット警告
    rateLimitDetected: '⚠️ レートリミットを検出：{count}ページが429エラーで失敗しました。対処法：(1) 並列度を{suggestedConcurrency}または1（直列）に下げる、(2) バッチ遅延を{suggestedDelay}msに増やす、(3) より高いレートリミットを持つプロバイダーに切り替える。',
    rateLimitDetectedShort: '⚠️ レートリミット発生 — 設定→取り込み加速で並列度を下げるかバッチ遅延を増やすことを推奨。',

    sourceRejectedEmpty: '⏭️ 「{filename}」には取り込む内容がないためスキップしました。空のノートやフロントマターのみのノートはWikiページを生成しません。',
    sourceRejectedType: '⏭️ 「{filename}」はサポートされていないファイル形式のためスキップしました。取り込めるのはテキストノート（.md、.txt など）のみです。',
    sourceRejectedDuplicate: '⏭️ 「{filename}」をスキップしました — 内容はすでにWikiに存在します。',
    pdfReadingInProgress: 'PDF を読み込み中: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ 「{filename}」をスキップしました — 現在の provider またはモデルは PDF 入力に対応していません。Settings → LLM Configuration → Advanced で provider を切り替えるか、「PDF サポートを強制」をオンにして再試行するか、Markdown 変換バックエンドを MinerU に切り替えてください（画像と Office ドキュメントも対応）。',
    clearPdfCacheCommand: 'PDF 変換キャッシュをクリア',
    pdfCacheCleared: 'PDF キャッシュをクリアしました（{count} 件のエントリを削除）。',
    // v1.25.0 PR3: Advanced PDF settings
    forcePdfSupportName: 'PDF サポートを強制',
    forcePdfSupportDesc: 'デフォルトはオフ。プロバイダーがネイティブ対応リストにないものの PDF を処理できる場合は、このスイッチをオンにして試すことができます。オンにすると PDF が現在のプロバイダーに送られ、拒否された場合は通知で案内されます。ネイティブ PDF プロバイダー（Anthropic / OpenAI / Bedrock）では不要です。',
    writePdfMarkdownToVaultName: '変換後の Markdown を Vault に書き込む',
    markdownConversionBackendName: 'Markdown 変換バックエンド',
    markdownConversionBackendDesc: 'Native はプロバイダーの組み込み PDF サポートを使用します（範囲が限られ、すべてのプロバイダー/モデルが PDF に対応するわけではなく、LLM トークンを消費します）。MinerU はオンラインサービスで、高速・日次クォータまで無料・PDF/画像/Office に対応しますが、API トークンが必要です（下のフィールドに設定）。',
    markdownConversionBackendNative: 'プロバイダーの PDF/画像 対応',
    markdownConversionBackendMineru: 'MinerU オンライン API',
    mineruApiBaseUrlName: 'MinerU API ベース URL',
    mineruApiBaseUrlDesc: 'MinerU API のベース URL。デフォルトは https://mineru.net/api/v4 です。プロキシやミラー、セルフホスト環境を使用する場合はカスタム URL を設定してください。',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'MinerU API トークン',
    mineruApiTokenDesc: 'トークンは https://mineru.net/apiManage/token で取得してください。MinerU は最大 200 MB、最大 200 ページのファイルを受け付けます。',
    mineruApiTokenPlaceholder: 'MinerU API トークンを貼り付け',
    mineruUploadingInProgress: 'PDF を MinerU にアップロード中: {filename}',
    mineruWaitingInProgress: 'MinerU の変換を待機中: {filename}',
    mineruDownloadingInProgress: 'MinerU の結果をダウンロード中: {filename}',
    markdownConversionComplete: '変換完了: {filename}',
    markdownConversionCompleteSaved: '変換完了 — {path} に書き込みました: {filename}',
    mineruPageLimitRejected: '{filename} は MinerU の {limit} ページ上限を超えています。ファイルを分割して再試行してください',
    mineruSizeLimitRejected: '{filename} は MinerU の {limit} MB サイズ上限を超えています',
    writePdfMarkdownToVaultDesc: 'デフォルトはオフ。オンの場合、各 PDF 変換結果は元の PDF の隣に「<basename>.pdf.md」ファイルとして書き込まれます。オフの場合（キャッシュ専用アーキテクチャ）、結果はプラグインのキャッシュ内のみに存在し、Vault に実装アーティファクトを残しません。',

    ingestRejectedSummary: '{count} 個のファイルをスキップしました（空・重複・非対応形式）。',
    reingestConfirmTitle: 'このファイルを再取り込みしますか？',
    reingestConfirmBody: '「{filename}」の内容はすでにWikiに存在します。それでも再取り込みしますか？',
    reingestConfirmYes: '再取り込み',
    reingestConfirmNo: 'スキップ',
    lintDedupIncludeSourcesName: '重複検出にソースを含める',
    lintDedupIncludeSourcesDesc: 'デフォルトで有効です。有効にすると、本文が同一のソースが lint で重複としてフラグ付けされます。誤検出が多い場合は無効にしてください。',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: 'ソースが言及するだけの候補をスキップ',
    skipMentionOnlyCandidatesDesc: 'デフォルトでは無効。有効にすると、ノートの本文に名前が現れない抽出エンティティ・概念（存在しない、または括弧内・列挙・短い箇条書きのみ）はページを作成せず、追加のモデル呼び出しも行わず、他の候補の関連リストからも除外されます。単語境界プロファイルのある Wiki 言語で動作します（ドイツ語は測定済み、英・仏・西・葡・蘭語は推定）。その他の言語では、適用できないことを取り込み時に一度報告します。用語集型の保管庫や箇条書き中心のノートで、名前の挙がった語をすべてページにしたい場合は無効のままにしてください。',
    createStubsForUnresolvableLinksName: '解決できないリンクのスタブページを作成',
    createStubsForUnresolvableLinksDesc: 'デフォルトでは有効。リンク切れの修復がリンクをどの既存ページにも解決できないとき、空のプレースホルダーページを書き込み、リンクをそこへ向け直します（LLM による埋め立ては行いません）。無効にすると、そのようなリンクはそのまま残り、実際のソースが定義するまで毎回のレポートで表示され続けます。',
    lintDedupSectionHeading: '重複検出',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): 汎用的な文言、
    // すべての LLM 業務パスで再利用。{count} は再試行が必要だった
    // バッチ数。「Lint は完了しました」とは書かない — 再試行は
    // このバッチのみを回復する。
    llmRetryRecoveredToast: 'LLM タスク：{count} 件のバッチがプロバイダの一時的な応答問題により再試行を必要としました（自動回復済み）。詳細はコンソールを参照してください。頻繁に発生する場合は、Provider 設定の Page Generation Concurrency を下げてください。',
    longSourceNotice: '"📄 「{filename}」は{lines}行（{size}）です。長文は複数パスの反復抽出が必要で、LLMが全文書を分析するため数分かかる場合があります。しばらくお待ちください。"',
    longSourceNoticeShort: '"📄 大きなファイル（{lines}行）を検出しました。取り込みに時間がかかることがあります。"',

    // 取り込み履歴パネル (#122) — UI テキスト
    historyButton: '操作履歴',
    historyButtonDesc: 'LLM-Wiki の最近の取り込み・Lint レポート・その他の変更を表示',
    historyButtonOpen: '履歴を表示',
    historyModalTitle: '操作履歴',
    historyModalSubtitle: 'LLM-Wiki の最近の変更',
    historyEmpty: 'まだ操作記録がありません。ノートを取り込むか Lint を実行して記録を作成してください。',
    historyReadError: '操作ログを読み込めません：{error}',
    historyEntryKindIngest: '取り込み',
    historyEntryKindMaintenance: 'メンテナンス',
    historyEntryKindFix: '修正',
    historyEntryKindOther: 'その他',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'ソース：{source}',
    historyEntrySourceUnknown: '無題の取り込み',
    historyEntryCreatedLabel: '作成',
    historyEntryUpdatedLabel: '更新',
    historyEntryCreatedCount: '{count} 件作成',
    historyEntryUpdatedCount: '{count} 件更新',
    historyEntryNoChanges: 'ページ変更なし',
    historyEntryContradictions: '⚠️ 矛盾 {count} 件',
    historyEntrySectionCreated: '作成したページ',
    historyEntrySectionUpdated: '更新したページ',
    historyEntrySectionContradictions: '矛盾',
    historyEntrySectionDetails: '詳細',
    historyEntryOpenPage: '開く',
    historyEntryDetailsNoContradictions: '矛盾は見つかりませんでした',
    historySearchPlaceholder: '🔍 ソース名またはページパスで検索…',
    historyFilterAll: 'すべて',
    historyFilterIngest: '取り込みのみ',
    historyFilterMaintenance: 'メンテナンスのみ',
    historyFilterFix: '修正のみ',
    historyFilterContradictions: '⚠️ 矛盾あり',
    historyRefreshButton: '⟳ 更新',
    historyExpandDay: 'クリックで展開',
    historyCollapseDay: 'クリックで折りたたむ',
    historyShowMore: '古い {count} 件を表示',
    historyNoMatch: '検索/フィルタに一致する操作がありません。',
    historyCloseButton: '閉じる',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'レポート所見',
    historyKpiPages: 'ページ数',
    historyKpiDeadLinks: 'デッドリンク',
    historyKpiOrphans: '孤立',
    historyKpiEmpty: '空ページ',
    historyKpiDuplicates: '重複',
    historyKpiTagViolations: 'タグ違反',
    historyKpiUnsourced: '未出典',
    historyKpiDuration: 'Lint 時間',
    historyKpiDurationSec: '{seconds} 秒',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'デッドリンク ({count})',
    historySectionTagViolations: 'タグ違反 ({count})',
    historySectionOrphans: '孤立ページ ({count})',
    historySectionEmptyPages: '空ページ ({count})',
    historySectionLlmAnalysis: 'LLM 分析 ({count})',
    historyDeadLinkSource: '参照元',
    historyDeadLinkTarget: '欠落',
    historyOpenInLog: 'log.md で表示',
    historyShowMoreItems: '残り {count} 件を展開',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ 変化なし',
    historyChipContradiction: '矛盾',
    historyChipOutdated: '古い',
    historyChipMissing: '欠落',
    historyChipStructure: '構造',
    historySeverityHigh: '高',
    historySeverityMedium: '中',
    historySeverityLow: '低',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Wiki には {dead} 件のデッドリンク、{orphans} 件の孤立ページ、{tags} 件のタグ違反があります。前回の Lint は {duration} かかりました。',
    historyGlobalInsightClean: 'Wiki は正常です — デッドリンク、孤立ページ、タグ違反は検出されていません。',
    historyGlobalInsightNoData: 'メンテナンスレポートがまだありません — Lint を実行してください。',
    historyModalHeaderTitle: '操作履歴',
    historyModalSubtitleWithCount: 'LLM-Wiki の最近の変更 · 全 {count} 件',
    historyTimeRangeAll: '全期間',
    historyTimeRange1d: '過去 1 日',
    historyTimeRange3d: '過去 3 日',
    historyTimeRange1w: '過去 1 週間',
    historyTimeRange1m: '過去 1 か月',
    historyIngestTotal: 'ページ総数',
    historyIngestByType: 'タイプ別',
    historyIngestSource: 'ソースファイル',
    historyIngestNoTimestamp: 'タイムスタンプなし',
    historyIngestFirstTime: '最初の取り込み',
    historyIngestLatestTime: '最新の取り込み',
    historyTimeRangeCustom: 'カスタム範囲',
    historyCustomRangeFrom: '開始',
    historyCustomRangeTo: '終了',
    historyCustomRangeApply: '適用',
    historyCustomRangeClear: 'クリア',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki：vault が空です。最初のソースノートを作成して Ingest を実行してください。',
    welcomeNoteTierBNotice: 'Karpathy Wiki：Welcome note を作成しました。開いてドメインを宣言し、2-3 個のソースノートを選んでリンクグラフのシードとしてください。',
    welcomeNoteRecreateCommand: 'Wiki Welcome note を再作成',
    welcomeNoteRecreateCommandTooltip: '現在のドメインシードと LLM 設定テストで <wikiFolder>/Welcome.md に Welcome note を再作成します。既存ファイルは上書きされます。',
    welcomeNoteSettingsToggle: '初回実行時に Wiki Welcome note を作成',
    welcomeNoteSettingsToggleDesc: '初回起動時（wiki フォルダーが空のとき）に、<wikiFolder>/Welcome.md に1枚の入門ノートを自動作成します。LLM-Wiki の説明、ドメインフォーカスの宣言方法、最初の 2-3 個のソースノートの取り込み方を案内します。ノートはデフォルトで英語で書かれ、LLM が設定されていればあなたの wiki 言語で書かれます。プラグインの使い方を既に理解していて、入門ノートが不要ならオフにできます。',
    welcomeNoteRunConfigTest: 'Welcome note は英語で書き込まれました。次回の再作成時にローカライズするには、設定 → LLM Provider → Test Connection を開いてください。',
    welcomeNoteRecreated: '{path} に Wiki Welcome note を再作成しました',
    welcomeNoteNotRecreated: 'Welcome note は再作成されませんでした。LLM 設定を確認してください。',
    welcomeNoteGenerating: 'Wiki Welcome note をバックグラウンドで生成中 — 完了時に通知が表示されます。',
    welcomeNoteGenerationFailed: 'Wiki Welcome note の生成に失敗しました：{error}',
    startupCheckWelcomePending: 'Welcome note：バックグラウンドで生成中（完了時に通知が表示されます）。',
    welcomeNoteFileName: 'Karpathy LLM Wiki へようこそ',
    startupCheckWelcomeCreated: '{path} に Welcome note を作成しました',
    // v1.23.0 Phase 5.1.5: 複数ファイル取り込みモーダルの「すべてキャンセル」ボタン。
    // キュー内のすべての pending + running ジョブを一度にキャンセルします。
    // 完了済みと失敗のジョブは表示用に保持されます。
    cancelAllQueueJobs: 'すべてキャンセル',
    // v1.23.0 Phase 5.1.5: 複数ファイル取り込みモーダル (cmdIngestMultipleFiles)。
    // タイトル、ヒント、検索プレースホルダー、ボタン、状態ラベル、キュー空のプレースホルダー。
    multiFileModalTitle: '複数ファイルを取り込み',
    multiFileModalHint: '取り込むソースノートを選択してください。右側パネルにライブキューと進行状況が表示されます。',
    multiFileSearchPlaceholder: 'パスでファイルを絞り込む…',
    multiFileAddToQueue: 'キューに追加',
    multiFileSelectAll: 'すべて選択',
    multiFileFileCount: '{count} 件のファイル',
    multiFileNoFilesAvailable: '取り込み可能なファイルがありません。',
    multiFileNoFilesMatch: '"{q}" に一致するファイルはありません。',
    multiFileQueueEmpty: 'キューは空です。左側のファイルを選択してください。',
    multiFileStatusPending: '待機中',
    multiFileStatusRunning: '取り込み中',
    multiFileStatusCompleted: '完了',
    multiFileStatusFailed: '失敗',
    multiFileCancelAria: 'このファイルを取り消す',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: '取り込み済み',
    multiFileRowDrifted: '取り込み後にノートが変更されました',
    startupCheckNoticeLevelName: 'クイック修正結果の表示',
    startupCheckNoticeLevelDesc: 'QuickFixes はプラグイン起動時に常に実行されます（Welcome note、フォルダ構造、ソース正規化、不完全ページ、ログヘッダー）。起動後にサマリー通知を表示するかどうかを選択します。サイレントモードでは開発者コンソールと操作履歴パネルのみに記録されます。',
    startupCheckNoticeVisible: '表示（通知を表示）',
    startupCheckNoticeSilent: 'サイレント（通知なし）',
} as const;
