export const KO_TEXTS = {
    // Plugin Info
    pluginTitle: 'Karpathy LLM Wiki 설정',
    pluginIntro: '이 플러그인은 Obsidian에 {{link}} 개념을 구현합니다. 노트를 읽고 AI로 엔티티와 컨셉을 추출하여 볼트에 구조화된 위키를 구축합니다.',
    karpathyLinkText: 'Andrej Karpathy의 LLM Wiki',

    // Features Section
    featuresTitle: '작동 방식',
    workflow1Title: '1. 수집',
    workflow1Desc: '노트를 선택하면 AI가 엔티티, 컨셉, 관계를 위키 페이지로 추출합니다.',
    workflow2Title: '2. 질의',
    workflow2Desc: '위키와 대화하세요 — 답변은 수집된 지식에 기반합니다.',
    workflow3Title: '3. 유지',
    workflow3Desc: '자동 생성된 인덱스, 상호 링크, 린트 검사로 위키를 건강하게 유지합니다.',

    // Language Switcher
    languageTitle: '인터페이스 언어',
    languageDesc: '설정 패널에서 사용할 언어를 선택하세요. 언어 변경을 명령 팔레트에 적용하려면 플러그인을 재시작하세요.',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // Status
    statusTitle: 'LLM 클라이언트 상태',
    llmWikiStatusSection: 'LLM-Wiki 상태',
    statusInitialized: '초기화됨',
    statusReady: 'LLM 준비 완료',
    statusNotReady: 'LLM 미구성 — 위 설정을 완료하고 연결 테스트를 통과하세요',
    statusNotInitialized: '초기화되지 않음',
    currentProvider: '현재 Provider',

    // Provider Configuration
    providerSection: 'LLM 설정',
    providerName: 'LLM Provider',
    providerDesc: '사전 정의된 Provider 또는 사용자 정의 OpenAI 호환 서비스 선택. Coding Plan 등의 번들 경우, 사용자 정의 OpenAI/Anthropic 선택 후 Provider의 Base URL과 API Key 수동 입력',

    // API Key
    apiKeyName: 'API 키',
    apiKeyDesc: 'API 키. OS 자격 증명 관리자에 저장되며 data.json에는 기록되지 않습니다.',
    apiKeyPlaceholder: 'API 키 입력',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: 'SecretStorage 마이그레이션',
    apiKeyMigratedToSecretStorageSuccess: 'API 키가 SecretStorage에서 설정으로 복원되었습니다.',
    apiKeyMigrationFailedNotice: 'SecretStorage에 API 키 저장 실패: {}',
    codexAuthName: 'ChatGPT 플랜 로그인',
    codexAuthDesc: 'ChatGPT 플랜 사용량을 이용하는 실험적 Codex OAuth 액세스입니다. OpenAI Platform API 요금은 별도로 청구됩니다.',
    codexAuthSignedOut: '로그인하지 않음',
    codexAuthSignedIn: '로그인됨',
    codexAuthBrowserButton: '브라우저로 로그인',
    codexAuthDeviceButton: '기기 코드 사용',
    codexAuthDeviceInstructions: 'OpenAI 페이지에 이 코드를 입력하세요: {}',
    codexAuthCopyCode: '코드 복사',
    codexAuthSignOutButton: '로그아웃',
    codexAuthBusy: 'OpenAI 승인을 기다리는 중...',
    codexAuthFailed: 'ChatGPT 승인 실패: {}',
    codexAuthQuota: 'ChatGPT Codex 사용 한도에 도달했습니다. 표시된 재설정 기간까지 기다린 후 다시 시도하세요.',
    codexAuthExperimental: '실험적 기능: 사용 가능 여부는 OpenAI Codex 인증 및 모델 정책을 따릅니다.',
    codexModelsRefreshName: '계정 모델',
    codexModelsRefreshDesc: '로그인한 OpenAI Codex 계정에서 선택 가능한 모델을 동기화합니다.',
    codexModelsRefreshButton: '계정 모델 새로고침',
    codexModelsRefreshing: '새로고침 중...',
    codexModelsRefreshSuccess: '계정 모델 {}개를 동기화했습니다.',
    codexModelsRefreshFailed: '계정 모델을 새로고침하지 못했습니다. 사용 가능한 대체 목록을 사용합니다. {}',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: '필수: 사용자 정의 OpenAI 호환 엔드포인트',
    baseUrlDescOverride: '선택: preset Base URL 재정의',

    // Issue #723: custom request headers (shown directly below the Base URL).
    customHeadersName: '사용자 지정 헤더',
    customHeadersDesc: '한 줄에 하나씩 `이름: 값` 형식으로 입력합니다. 모든 요청에 전송되며, 빈 줄과 `#` 주석은 무시됩니다.',
    customHeadersInvalid: '{}개 줄의 형식이 잘못되어 무시됩니다.',

    // Ollama Hint
    ollamaHint: 'Ollama는 로컬에서 실행되며 API 키가 필요하지 않습니다',
    lmstudioHint: 'LM Studio는 로컬에서 실행됩니다. API 키는 선택 사항입니다',
    maxTokensPerCallName: '호출당 최대 출력 토큰 수',
    maxTokensPerCallDesc: '모델이 한 번의 응답에서 생성할 수 있는 토큰 수를 제한합니다. 작은 컨텍스트 창의 로컬 모델을 사용 중이고 오류가 발생하면 낮추세요. 클라우드 모델은 기본값(0 = 제한 없음) 그대로 두면 됩니다.',

    slugCaseName: '파일명 대소문자',
    slugCaseDesc: '생성되는 Wiki 파일명을 소문자로 변환할지 제어합니다. 대소문자가 의미 있는 언어(예: 독일어 명사)는 "유지" 권장.',
    slugCaseLower: '소문자(기본값)',
    slugCasePreserve: '대소문자 유지',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: '별칭 최소 길이',
    minAliasLengthDesc: '이보다 짧은 별칭(공백 제거 후)은 위키 페이지에 기록되지 않습니다. 기본값 2는 두 글자 약어(ML, AI, UI)를 유지합니다. 대소문자만 다른 두 글자 별칭(Cr/CR)이 쌓이는 볼트라면 3으로 올리세요. 범위 2–6.',
    minAliasLengthClamped: '값이 범위(2–6)를 벗어나 {}(으)로 설정되었습니다',

    // Model Selection
    modelSection: '모델 선택',
    fetchModelsName: '사용 가능한 모델 가져오기',
    fetchModelsDesc: 'Provider API에서 최신 모델 목록을 가져옵니다',
    fetchModelsButton: '모델 가져오기',
    fetchingModels: '가져오는 중...',
    fetchSuccess: '성공! {}개의 모델 사용 가능',
    fetchFailed: '가져오기 실패 또는 빈 목록. 모델 이름을 수동으로 입력하세요',
    fetchNotSupported: 'Provider가 모델 목록 조회를 지원하지 않습니다',
    fetchErrorAuth: '인증 실패 (HTTP 401/403). API 키를 확인하거나 모델 ID를 직접 입력한 후 테스트 연결을 클릭하여 검증하세요.',
    fetchErrorEndpoint: '엔드포인트를 찾을 수 없음 (HTTP 404). BaseURL을 확인하거나 모델 ID를 직접 입력한 후 테스트 연결을 클릭하여 검증하세요.',
    fetchErrorServer: 'Provider 서버 오류 (HTTP 5xx). 나중에 다시 시도하거나 모델 ID를 직접 입력한 후 테스트 연결을 클릭하여 검증하세요.',
    fetchErrorEmpty: '이 엔드포인트는 모델 목록을 제공하지 않습니다. 모델 ID를 직접 입력한 후 테스트 연결을 클릭하여 검증하세요.',
    fetchErrorNetwork: '네트워크 요청 실패. 인터넷 연결, BaseURL, 프록시 설정 또는 API Key를 확인하세요. 모델 ID를 직접 입력한 후 테스트 연결을 클릭하여 검증할 수도 있습니다.',

    selectModelName: '모델 선택',
    selectModelDesc: '{}개의 사용 가능한 모델 중에서 선택',
    customInputOption: '직접 입력...',
    customInputHint: '다른 모델을 사용하려면 "직접 입력..."을 선택하세요',

    modelName: '모델 이름',
    modelDescCustom: '사용자 정의 모델 사용 (위 버튼으로 목록 다시 가져오기)',
    modelDescFetchFailed: '모델 목록 가져오기 실패. API 키와 엔드포인트 URL을 확인하거나 모델 ID를 직접 입력한 후 테스트 연결을 클릭하여 검증하세요.',
    modelInputPlaceholder: '모델 ID 입력 후 테스트 연결',

    switchToDropdown: '드롭다운 선택으로 전환',
    useDropdownButton: '드롭다운 사용',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: '모델 범위',
    modelTaskModeDesc: '모든 작업에서 동일한 모델을 사용할지, 작업별로 다른 모델(수집 / 유지보수·수리 / 쿼리)을 사용할지 선택하세요. 통합 모델로 돌아가면 숨겨진 작업별 모델 값은 보존됩니다(삭제되지 않음).',
    modelTaskModeUnified: '통합 모델 사용(기본값)',
    modelTaskModePerTask: '작업별로 다른 모델 사용',
    perTaskIngestModelName: '수집 모델',
    perTaskIngestModelDesc: '노트·대화 수집, Schema 유지보수, 환영 노트 생성에 사용됩니다.',
    perTaskLintModelName: '유지보수·수리 모델',
    perTaskLintModelDesc: 'Lint 분석, 중복 감지, 다양한 수리 작업, 고아 링크 수정에 사용됩니다.',
    perTaskQueryModelName: '쿼리 모델',
    perTaskQueryModelDesc: 'Query Wiki 채팅 및 Wiki 저장 평가에 사용됩니다.',

    // Test & Save
    testConnectionName: '연결 테스트',
    testConnectionDesc: '설정이 LLM API를 성공적으로 호출할 수 있는지 확인합니다',
    testButton: '연결 테스트',
    testing: '테스트 중...',

    saveSettingsName: '설정 저장',
    saveSettingsDesc: '현재 설정을 저장합니다',
    saveButton: '설정 저장',
    testConnectionSuccessful: '연결 성공',
    testConnectionFailed: '연결 실패',
    testConnectionProvider: 'Provider: ',
    codexAuthRequired: '연결을 테스트하기 전에 ChatGPT 플랜에 로그인하세요.',
    bedrockSsoRequired: '연결을 테스트하기 전에 설정 → Bedrock에서 AWS SSO 로그인을 먼저 실행하세요.',
    bedrockIamRequired: '연결을 테스트하기 전에 설정 → Bedrock에서 IAM 액세스 키를 먼저 입력하세요.',
    bedrockAuthMethodName: '인증 방식',
    bedrockAuthMethodDesc: 'API 키는 Bedrock API 키를 사용하고, AWS SSO는 IAM Identity Center 자격 증명으로 요청에 서명하며, IAM 키는 정적 액세스 키를 사용합니다.',
    bedrockAuthOptionApiKey: 'API 키',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'IAM 키',
    bedrockSsoStartUrlName: 'SSO 시작 URL',
    bedrockSsoStartUrlDesc: '조직 포털 URL(예: https://d-xxxxxxxxx.awsapps.com/start)',
    bedrockSsoAccountIdName: 'AWS 계정 ID',
    bedrockSsoAccountIdDesc: '역할을 수행할 12자리 계정 ID(예: 123456789012)',
    bedrockSsoRoleNameName: '역할 이름',
    bedrockSsoRoleNameDesc: 'Bedrock 접근에 사용할 IAM 역할(예: PowerUserAccess)',
    bedrockSsoLoginButton: 'AWS SSO로 로그인',
    bedrockSsoSignOutButton: 'AWS SSO에서 로그아웃',
    bedrockSsoStatusSignedIn: '로그인됨 · {} 만료',
    bedrockSsoStatusSignedOut: '로그인되지 않음',
    bedrockSsoBusy: '로그인 진행 중…',
    bedrockSsoUserCodeInstructions: 'AWS SSO 코드: {}. 링크를 열고 접근을 승인하세요.',
    bedrockSsoCopyCode: '코드 복사',
    bedrockSsoFailed: 'AWS SSO 로그인 실패: {}',
    bedrockSsoDetectedPrefill: '감지된 계정/역할: {}',
    bedrockIamKeyName: '액세스 키 ID',
    bedrockIamKeyDesc: 'IAM 액세스 키 식별자(예: AKIA… 또는 ASIA…)',
    bedrockIamSecretName: '시크릿 액세스 키',
    bedrockIamSecretDesc: '이 기기의 시크릿 저장소에만 저장되며 data.json에는 절대 기록되지 않습니다',
    bedrockIamSessionTokenName: '세션 토큰(선택)',
    bedrockIamSessionTokenDesc: '임시 자격 증명(STS)에만 필요합니다',
    bedrockIamClearButton: '저장된 IAM 키 지우기',
    bedrockIamSaveFailed: 'IAM 키 저장 실패: {}',
    errorUnknown: '알 수 없는 오류',
    savedNotice: '설정이 저장되었습니다!',

    // v1.24.0 (Bug C 3.4 / plan C): 점진적 마이그레이션 알림
    queryHistoryMigrationNotice: 'Query Wiki 기록에 이전 wiki 폴더의 링크가 포함되어 있습니다. 새 대화는 자동으로 최신 폴더를 사용합니다. 모든 기록 메시지를 새로 고치려면 Query Wiki 패널을 열고 그 안의 "기록 지우기" 버튼을 클릭하세요.',

    // v1.24.0 Issue #251: 사용자 지정 Query 지시문 (접을 수 있는 패널)
    customInstructionsTitle: '사용자 지정 Query 지시문',
    customInstructionsDesc: '모든 Query Wiki 시스템 프롬프트 끝에 추가되는 영구 지시문입니다. Query Wiki 채팅에만 영향을 주며, 수집·lint·페이지 생성에는 영향을 주지 않습니다.',
    customInstructionsPlaceholder: '예: 연구 작업으로 처리: 넓게 검색, 출처 인용, 사실과 해석 구분...',
    customInstructionsApply: '적용',
    customInstructionsClear: '지우기',
    customInstructionsCharCount: '{current}/{max} 자',
    instructionsApplied: '사용자 지정 Query 지시문이 저장되었습니다.',
    instructionsCleared: '사용자 지정 Query 지시문이 지워졌습니다.',

    // Issue #137: LLM 폴백 알림
    fallbackThinkingDialect: '사고 제어: "{dialect}" 방언으로 전환됨(이 공급자는 다른 사고 제어 필드 형식을 사용함). 출력은 변경되지 않음.',
    fallbackThinkingNone: '이 공급자에 대해 사고 제어가 완전히 비활성화되었습니다. 추론 콘텐츠가 여전히 나타날 수 있습니다; 이 경우 다른 모델을 시도하세요.',
    fallbackParamStripped: '매개변수 "{field}"는(은) 이 공급자에서 지원되지 않습니다. 요청에서 제거되었습니다; 동작은 구성과 다를 수 있습니다.',

    // Wiki Folder
    wikiSection: 'Wiki 설정',
    wikiFolderName: '위키 폴더',
    // v1.24.0: 변경 후 Obsidian 재시작이 필요함을 명시 (engine 캐시와 열린 Query Wiki 패널 재바인딩)
    wikiFolderDesc: '생성된 위키 페이지의 저장 위치. 변경 후 Obsidian를 재시작해야 합니다——engine 캐시와 열려 있는 Query Wiki 패널을 다시 바인딩해야 합니다.',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'API 키를 먼저 설정하세요',
    errorNoModel: '먼저 모델을 선택하세요 — [모델 가져오기]를 클릭하거나 Model ID를 직접 입력하세요',
    llmNotReady: 'LLM이 구성되지 않았습니다. 설정 → Karpathy LLM Wiki에서 제공자를 구성하고 모델을 가져온 후 연결 테스트를 통과하세요.',
    errorFetchFailed: '실패: {}',

    // Query Settings
    querySectionTitle: '위키 질의 설정',
    // v1.24.0: "최대 대화 기록"에서 "대화 연관 기억 라운드 수"로 이름 변경
    // 의미가 더 정확함. 1 = 각 턴이 독립적 (이전 문맥 참조 안 함).
    // 설정은 드롭다운이므로 사전 설정 값을 설명에 나열할 필요 없음.
    // v1.24.0: maxConversationHistoryHint은 사용되지 않는 i18n key였습니다.
    // 권장 문구를 desc에 통합했습니다.
    maxConversationHistoryName: '대화 연관 기억 라운드 수',
    maxConversationHistoryDesc: 'LLM이 새 대화에서 볼 수 있는 과거 라운드 수 (기억으로). 1 = 각 턴이 독립적 (이전 문맥 참조 안 함); 값이 클수록 모델이 세션 초반의 라운드를 기억합니다. 추천: 일회성 Q&A는 1, 지속적 연구는 10~50.',
    numberRangeValidation: '1-50 사이의 숫자를 입력하세요',
    numberRangeClamped: '값이 범위를 초과했습니다 (1-500), 자동으로 {}으로 설정되었습니다',

    // Query Modal UI
    queryModalTitle: '위키 질의 - 대화형 질의',
    queryModalPlaceholder: '질문을 입력하세요...',
    queryModalSendButton: '전송',
    queryModalStopButton: '중지',
    queryModalSaveButton: '위키에 저장',
    queryModalClearButton: '기록 지우기',
    queryModalHistoryCount: '대화 기록: {}/{} 라운드',
    queryModalStreaming: '스트리밍 중...',
    queryModalFallbackStreaming: '스트리밍을 지원하지 않아 논스트리밍으로 전환되었습니다. 잠시 기다려주세요...',
    queryPhaseSearching: '위키 인덱스 분석 중, 관련 페이지 선택 중...',
    queryPhaseFoundPages: '{count}개의 페이지 발견: {pages}',
    queryPhaseLoadingPages: '페이지 콘텐츠 로딩 중...',
    queryPhaseContextReady: '컨텍스트 준비 완료. 답변 생성 중...',
    queryPhaseGenerating: '생성 중... (경과 {time}초)',
    queryPhaseNonStreaming: '논스트리밍 모드, 응답 생성 중... (경과 {time}초)',
    queryModalErrorPrefix: '오류: ',
    queryModalHint: '위키 콘텐츠 기반 질의입니다. "위키에 저장"을 클릭하면 가치 있는 대화를 위키 페이지로 추출할 수 있습니다.',

    // v1.20.0: Query Wiki 사고 블록 접기 요약
    queryThinkingSummary: '사고 과정',
    queryThinkingSteps: '단계',

    // Error Messages
    errorLLMClientNotInit: 'LLM 클라이언트가 초기화되지 않았습니다. 설정을 저장하세요.',
    errorIngestFailed: '수집 실패: ',
    errorQueryFailed: '질의 실패: ',
    fileWriteFailed: '파일을 만들거나 업데이트할 수 없습니다: {path}',

    // Success Messages
    ingestSuccess: '수집 완료: {} 페이지 생성, {} 페이지 업데이트',
    querySuccess: '질의 완료',
    lintSuccess: '위키 린트 완료',
    lintReadingPages: '{count}개의 위키 페이지 읽는 중...',
    lintReadingPagesProgress: '위키 페이지 읽는 중: {current}/{total}...',
    lintScanningLinks: '깨진 링크 검사 중...',
    lintScanningLinksProgress: '깨진 링크 검사 중: {current}/{total}...',
    lintCheckingDuplicates: '중복 페이지 확인 중...',
    lintCheckingDuplicatesProgress: '중복 페이지 확인 중: 배치 {current} ...',
    lintFixingPolluted: '오염 페이지 수정 중 {current}/{total}: {title} → {newTitle}',
    lintModalFixPolluted: '🧹 오염 페이지 수정 ({count})',
    lintDuplicateCheckFailed: '중복 감지 실패 — 자세한 내용은 콘솔을 확인하세요',
    lintDuplicateCheckFailedDetail: '중복 확인 실패 ({step}): {error}',
    lintMergeItemFailed: '병합 실패: {source} → {target} — {error}',
    lintAliasesMissing: '별칭 누락: {count}개의 페이지에 별칭이 없습니다',
    lintAliasesSection: '별칭 누락 페이지 [{count}개]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: '별칭 완성 ({count})',
    lintAliasesFilling: '별칭 생성 {current}/{total}: {page}',
    lintAliasesFilled: '별칭 완성 완료. {filled}/{total} 페이지 채움.',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: '어휘 외 태그 (감지됨) [{count}개]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: '별칭 생성 실패: {page} — {error}',
    lintFixItemFailed: '수정 실패: [[{target}]] — {error}',
    lintLinkItemFailed: '링크 실패: {page} — {error}',
    lintRetrying: '오류 후 재시도 ({attempt}/{max})...',
    lintAnalyzingLLM: 'LLM이 위키 건강 상태 분석 중...',
    saveToWikiSuccess: '대화가 위키에 저장되었습니다!',
    querySaveAlreadyExists: '알림: 아무것도 저장되지 않았습니다(Wiki에 이미 지식이 존재함):',
    saveSummary: '{entities} 개체, {concepts} 개념, {pages} 페이지',
    aliasAdded: '페이지 \'{page}\'에 별칭 \'{alias}\' 추가됨',

    // Status Messages
    ingestingSources: '소스 수집 중...',
    queryingWiki: '위키 질의 중...',
    lintingWiki: '위키 린트 중...',
    savingToWiki: '대화를 위키에 저장 중...',
    clearingHistory: '대화 기록 지우는 중...',

    // Buttons
    ingestButton: '수집',
    queryButton: '질의',
    lintButton: '린트',
    cancelButton: '취소',

    // Links
    karpathyGistLink: 'Karpathy의 LLM Wiki Gist',
    obsidianPluginAPI: 'Obsidian 플러그인 API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'AWS 리전',
    bedrockRegionDesc: '이 계정의 Amazon Bedrock 리전. bedrock-mantle 엔드포인트 URL을 결정하며 baseURL로 재정의할 수 없습니다.',
    bedrockRegionHint: 'bedrock-mantle은 18개 리전에서 사용 가능; 리전별로 모델 지원 범위가 다릅니다.',

    // Other
    availableModelsLoading: '사용 가능한 모델 로딩 중...',
    noModelsAvailable: '사용 가능한 모델 없음',

    // LLM Language Hint
    llmLanguageHint: 'Please answer in Korean.',

    // Schema Configuration
    schemaSection: '스키마 설정',
    enableSchemaName: '스키마 활성화',
    enableSchemaDesc: '스키마/config.md를 생성하여 모든 LLM 프롬프트에 주입, 구조화된 위키 출력 지원',
    viewSchemaButton: '스키마 보기 / 편집',
    regenerateSchemaButton: '기본 스키마 재생성',
    schemaRegeneratedNotice: '기본 스키마가 재생성되었습니다.',
    schemaRegenerateFailed: '스키마 생성 실패',

    // Wiki 초기화 상태
    wikiInitStatusReady: 'Wiki 초기화 완료',
    wikiInitStatusNotReady: 'Wiki 초기화되지 않음 — 첫 번째 수집 시 자동 생성',

    // Wiki Output Language
    wikiLanguageName: '위키 출력 언어',
    wikiLanguageDesc: '생성된 모든 위키 페이지, 인덱스, 로그, 질의 응답에 이 언어가 사용됩니다',
    customWikiLanguageOption: '사용자 정의...',
    customWikiLanguageHint: '언어 이름을 입력하세요 (예: Italian, Arabic). LLM에 출력 언어 지시문으로 전달됩니다.',
    customWikiLanguagePlaceholder: '예: Italian',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // Extraction Settings
    extractionSectionTitle: '추출',
    extractionGranularityName: '추출 세분화',
    extractionGranularityDesc: '소스 파일당 추출 수 제어. 높을수록 페이지/API 소비 증가.\n세밀: 심층 분석. 표준: 일상 노트. 굵음: 빠른 개요. 최소: 100개 이상 일괄 처리(소스당 약 5개 항목 제한 — 세부 정보가 아님). 사용자 지정: 자체 설정 (최대 300개).\n팁: 파일이 많은 폴더는 최소/굵음 사용으로 시간 및 비용 절감.',
    extractionGranularityFine: '세밀 — 심층 분석 (≤100개)',
    extractionGranularityStandard: '표준 — 일상 노트 (≤50개)',
    extractionGranularityCoarse: '굵음 — 빠른 개요 (≤10개)',
    extractionGranularityMinimal: '최소 — 100+ 파일 일괄 처리 (≤5개)',
    extractionGranularityCustom: '사용자 지정 — 자체 상한 설정 (1~500)',
    customEntityLimitName: '사용자 지정 엔티티 상한',
    customEntityLimitDesc: '소스 파일당 최대 엔티티 추출 수 (1-500)',
    customConceptLimitName: '사용자 지정 컨셉 상한',
    customConceptLimitDesc: '소스 파일당 최대 컨셉 추출 수 (1-500)',

    // Issue #85 v2: 태그 어휘 (chip 입력 UI, Wiki 설정에 임베드)
    tagVocabularyInlineDesc: 'entity/concept frontmatter 태그의 관리 어휘입니다. "/"가 있는 중첩 태그는 보존됩니다.',
    tagVocabularyModeName: '태그 어휘 설정',
    tagVocabularyModeDescDefault: '기본값은 내장 태그 사용: {}. "사용자 지정"으로 전환하면 자체 어휘를 정의할 수 있습니다.',
    tagVocabularyModeDescCustom: '사용자 지정: 아래에서 chip 입력을 사용해 자체 entity/concept 태그를 정의하세요. Enter 또는 쉼표로 추가, ×로 삭제.',
    tagVocabularyNotEnforcedHint: '스키마 힌트일 뿐 — LLM이 어휘 밖 타입을 출력할 수도 있습니다. Lint를 실행해 해당 페이지를 찾아 수정하세요.',
    tagVocabularyModeDefault: '기본 (내장 서브타입 태그)',
    tagVocabularyModeCustom: '사용자 지정 (사용자 정의)',
    customEntityTagsName: '사용자 지정 엔티티 태그',
    customEntityTagsDesc: 'Enter 또는 쉼표로 chip 추가, ×로 삭제. "/"가 있는 중첩 태그는 보존됩니다.',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: '사용자 지정 컨셉 태그',
    customConceptTagsDesc: 'Enter 또는 쉼표로 chip 추가, ×로 삭제. "/"가 있는 중첩 태그는 보존됩니다.',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: '중복 태그 건너뜀',

    // Ingestion Acceleration
    accelerationSectionTitle: '수집 가속화',
    pageGenerationConcurrencyName: 'LLM 동시성',
    pageGenerationConcurrencyDesc: '수집 및 Lint 작업 중 병렬 LLM 호출 수. 값이 높을수록 처리가 빨라지지만 API 비용이 증가하고 속도 제한이 발생할 수 있습니다.',
    concurrencyValueSingular: '현재 동시성: {} (직렬 — 가장 안전)',
    concurrencyValuePlural: '현재 동시성: {} (병렬)',
    batchDelayName: '배치 지연 (ms)',
    batchDelayDesc: 'API 속도 제한 방지를 위한 병렬 배치 간 지연 (100-10000ms). 현재값: {}ms. 429 오류가 발생하면 값을 높이세요.',

    // Auto Maintenance
    autoMaintainSection: '자동 유지보수',
    autoMaintainBetaBadge: 'BETA — 실험적 기능. 문제가 있을 수 있습니다. 고급 사용자에게만 권장.',
    autoWatchName: '폴더 감시',
    autoWatchDesc: '감시 폴더에서 새롭거나 변경된 .md 파일을 자동으로 감지하여 알림 또는 자동 수집',
    watchedFoldersName: '감시 폴더',
    watchedFoldersDesc: '새 콘텐츠를 감시할 폴더. "폴더 추가"를 클릭하여 볼트에서 선택하세요.',
    addWatchedFolderButton: '폴더 추가',
    removeWatchedFolderButton: '제거',
    webClipperPresetName: '클리핑 감시 (Web Clipper)',
    webClipperPresetDesc: 'Obsidian Web Clipper가 사용하는 Clippings/ 폴더를 감시 목록에 추가합니다. 웹 클립이 자동으로 위키에 수집됩니다.',
    noWatchedFoldersHint: '설정된 폴더가 없습니다. 폴더를 추가하거나 Clippings 프리셋을 활성화하세요.',
    autoWatchModeName: '감시 모드',
    autoWatchModeDesc: '"알림만"은 프롬프트를 표시합니다. "자동 수집"은 자동으로 처리합니다.',
    watchModeNotify: '알림만',
    watchModeAuto: '자동 수집',
    autoWatchDebounceName: '디바운스 지연 (초)',
    autoWatchDebounceDesc: '파일 변경 후 수집 트리거까지 대기 시간 (1-60초)',
    periodicLintName: '정기 린트',
    periodicLintDesc: '일정에 따라 LLM 린트 실행, 마지막 확인 이후 소스 파일이 변경된 경우에만',
    periodicLintOff: '끄기',
    periodicLintDaily: '매일',
    periodicLintWeekly: '매주',
    periodicLintMonthly: '매월',
    autoSmartFixName: '자동 스마트 수정',
    autoSmartFixDesc: 'Lint 실행 시 보고서 모달 없이 모든 수정(스마트 일괄 수정)을 자동으로 적용합니다. 수정 완료 후 요약은 계속 표시됩니다.',
    autoSmartFixNotice: '자동 스마트 수정: 모든 수정 적용 중...',

    autoIngestLevelName: '자동 수집 알림 방식',
    autoIngestLevelDesc: '자동 수집 완료 시 알림 방식입니다. "알림"은 일시적으로 표시되며 작업을 방해하지 않습니다. "모달"은 전체 보고서를 엽니다. Watch 모드가 "알림만"인 경우 비활성화됩니다.',
    autoIngestLevelNotice: '알림 (비차단)',
    autoIngestLevelModal: '모달 (전체 보고서)',
    startupCheckName: '시작 시 빠른 수정 실행',
    startupCheckDesc: '플러그인 로딩 시低级 형식 문제(sources 필드, 이중 wikilink)를 자동 수정하고 Wiki 폴더 구조를 검증합니다. 기본 활성화.',
    suggestSchemaCommand: '스키마 업데이트 제안',
    autoMaintainCostWarning: '⚠️ 비용 알림: 자동 유지보수 기능은 API 토큰을 소비합니다. "자동 수집"은 소스 파일 변경 시마다 LLM 호출을 트리거합니다. "정기 린트"는 일정에 따라 LLM 건강 검사를 실행합니다 (소스 변경 감지 시에만). 예상치 못한 요금을 피하기 위해 신중하게 설정하세요.',

    // Notices
    startupCheckSummary: '위키에 {pages}개의 페이지가 있습니다 ({entities} 엔티티, {concepts} 컨셉, {sources} 소스)',
    watcherActiveNotice: 'Wiki: 파일 감시 활성화 — 감시 폴더 모니터링 중',
    watchIngestNotice: 'Wiki: sources/에서 {count}개의 파일이 변경되었습니다. "소스 수집"을 실행하여 처리하세요.',
    autoIngestRunning: '{count}개의 변경 파일 자동 수집 중...',
    autoIngestComplete: '자동 수집 완료: {success} 성공, {fail} 실패',
    scheduledLintRunning: '일정된 위키 린트 실행 중...',
    wikiLintStats: '위키 린트: {pages}개의 페이지 ({entities} 엔티티, {concepts} 컨셉, {sources} 소스)',
    wikiHealthStats: '위키 건강: {pages}개의 페이지 ({entities} 엔티티, {concepts} 컨셉, {sources} 소스){indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki 빠른 수정 완료',
    startupCheckStructureLabel: 'Wiki구조',
    startupCheckStructureOk: '완료',
    startupCheckStructureMissing: '불완전 — 첫 수집 시 자동 생성',
    startupCheckSourcesLabel: 'Sources 정규화',
    startupCheckSourcesClean: '이미 정규화됨',
    startupCheckSourcesCleaned: '{files}개 파일, {entries}개 항목 정리',
    startupCheckIncompleteClean: '미완성 페이지: 없음',
    startupCheckIncompleteArchived: '미완성 페이지: {count}개 아카이브 (.trash에서 복원 가능)',
    startupCheckDisableHint: '비활성화하려면 설정 → 자동 유지보수 → 시작 시 빠른 수정 실행',
    lintWikiStart: '위키 린트 시작 중...',
    lintWikiComplete: '위키 린트 완료',
    lintWikiFailed: '위키 린트 실패',
    analyzingSchema: '위키 분석 및 스키마 제안 생성 중...',
    schemaSuggestionGenerated: '스키마 제안이 생성되었습니다. wiki/schema/suggestions.md를 확인하세요',
    noSchemaUpdateNeeded: '스키마 업데이트가 필요하지 않습니다.',
    schemaSuggestionFailed: '스키마 제안 실패',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Schema 업데이트 미리보기',
    schemaDiffSummary: '+{add} / -{del} 줄',
    schemaDiffRegenerateLabel: '제안 수정 (선택):',
    schemaDiffRegenerateBtn: '재생성',
    schemaDiffOpenFileBtn: '파일 열기',
    schemaDiffApplyBtn: '적용',
    schemaDiffApplied: 'Schema 업데이트됨. 백업: {path}',
    schemaDiffEmptyTitle: 'LLM이 변경 불필요라고 판단',
    schemaDiffFailed: 'Schema 적용 실패: {reason}',
    schemaDiffRestoreHint: '{path}에 백업되었습니다. 복원하려면 파일 탐색기에서 해당 파일을 "wiki/schema/config.md"로 이름을 바꾸세요. 최근 백업 3개가 유지됩니다.',
    schemaRegenerateNoBody: '재생성은 성공했지만 LLM이 새 Schema를 반환하지 않았습니다.',
    schemaNotFoundNotice: '스키마 파일을 찾을 수 없습니다. 스키마를 활성화하여 생성하세요.',
    selectFolderNoMdFiles: '폴더에 Markdown 파일이 없습니다: {path}',
    batchIngestSkipNotice: '이미 수집된 {skipped}/{total} 파일 건너뜁니다. {new}개의 새 파일 수집 중...',
    batchIngestAllIngested: '이 폴더의 {total}개 파일은 모두 이미 수집되었습니다.',
    batchIngestStarting: '"{folder}"에서 {count}개의 파일 수집 중 — 몇 분 정도 소요될 수 있습니다. 완료 시 보고서가 표시됩니다.',
    batchIngestComplete: '배치 수집 완료: {success}/{total} 성공, {fail} 실패',
    batchIngestFailedFiles: '실패한 파일:',
    historyTruncated: '최근 {max} 라운드로 기록이 잘렸습니다',
    historyCleared: '기록이 지워졌습니다',

    // User Feedback Loop
    reviewedPagePreserved: '사용자 검토 콘텐츠 보존: {}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: '위키에 저장하시겠습니까?',
    querySuggestSaveDesc: '이 대화에는 가치 있는 지식이 포함되어 있습니다. 위키에 저장하시겠습니까?',
    querySuggestSaveYes: '저장',
    querySuggestSaveNo: '취소',

    // Ingestion Report
    ingestReportElapsedTime: '경과 시간',
    ingestReportSkippedFiles: '건너뜀 (이미 수집됨)',
    ingestReportRejectedFiles: '건너뜀',
    rejectionReasonEmpty: '비어 있음',
    rejectionReasonType: '지원되지 않는 형식',
    rejectionReasonDuplicate: '중복 콘텐츠',
    rejectionReasonPdfUnsupported: '공급자가 PDF를 읽을 수 없음',
    rejectionReasonMineruPageLimit: 'MinerU 페이지 제한 초과',
    rejectionReasonMineruSizeLimit: 'MinerU 크기 제한 초과',
    sourceRejectedEmpty: '⏭️ 「{filename}」에 가져올 내용이 없어 건너뛰었습니다. 비어 있거나 프론트매터만 있는 노트는 위키 페이지를 만들지 않습니다.',
    sourceRejectedType: '⏭️ 「{filename}」은(는) 지원되지 않는 파일 형식이라 건너뛰었습니다. 텍스트 노트(.md, .txt 등)만 가져올 수 있습니다.',
    sourceRejectedDuplicate: '⏭️ 「{filename}」을(를) 건너뛰었습니다 — 내용이 이미 위키에 있습니다.',
    pdfReadingInProgress: 'PDF 읽는 중: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ 「{filename}」을(를) 건너뛰었습니다 — 현재 provider 또는 모델이 PDF 입력을 지원하지 않습니다. Settings → LLM Configuration → Advanced에서 provider를 변경하거나 「PDF 지원 강제」를 켜고 다시 시도하거나, Markdown 변환 백엔드를 MinerU로 전환하세요(이미지 및 Office 문서도 지원).',
    clearPdfCacheCommand: 'PDF 변환 캐시 지우기',
    pdfCacheCleared: 'PDF 캐시를 지웠습니다({count}개 항목 제거됨).',
    // v1.25.0 PR3: Advanced PDF settings
    forcePdfSupportName: 'PDF 지원 강제',
    forcePdfSupportDesc: '기본값은 꺼짐. provider가 네이티브 지원 목록에 없지만 PDF를 처리할 수 있다면, 이 스위치를 켜서 시도해 볼 수 있습니다. 켜면 PDF가 현재 provider로 전송되며, 거부되면 알림으로 안내됩니다. 네이티브 PDF provider(Anthropic / OpenAI / Bedrock)는 이 설정이 필요 없습니다.',
    writePdfMarkdownToVaultName: '변환된 Markdown을 Vault에 기록',
    analyzeEmbeddedImagesName: 'Markdown 수집 중 포함된 이미지 분석',
    saveEmbeddedImageEvidenceName: '포함된 이미지 시각 증거를 출처 페이지에 저장',
    saveEmbeddedImageEvidenceDesc: '기본값은 꺼짐입니다. 활성화하면 검토를 위해 각 이미지의 인접 텍스트와 시각 모델 증거를 출처 페이지의 접을 수 있는 섹션에 저장합니다.',
    analyzeEmbeddedImagesDesc: '기본값은 꺼짐입니다. 활성화하면 적격 로컬 이미지를 모두 20 MiB 패키지로 분석하며, 각 이미지는 10 MiB까지입니다. 원격 이미지는 다운로드하지 않습니다.',
    markdownConversionBackendName: 'Markdown 변환 백엔드',
    markdownConversionBackendDesc: 'Native는 제공업체의 내장 PDF 지원을 사용합니다(범위가 제한적이며 모든 제공업체/모델이 PDF를 처리하는 것은 아니며 LLM 토큰을 소비합니다). MinerU는 온라인 서비스로 — 빠르고, 일일 할당량까지 무료이며, PDF/이미지/Office를 지원합니다 — 하지만 API 토큰이 필요합니다(아래 필드에 설정).',
    markdownConversionBackendNative: '제공업체 PDF/이미지 지원',
    markdownConversionBackendMineru: 'MinerU 온라인 API',
    mineruApiBaseUrlName: 'MinerU API 기본 URL',
    mineruApiBaseUrlDesc: 'MinerU API의 기본 URL입니다. 기본값은 https://mineru.net/api/v4입니다. 프록시, 미러 또는 자체 호스팅 배포를 사용하는 경우 사용자 지정 URL을 설정하세요.',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'MinerU API 토큰',
    mineruApiTokenDesc: 'https://mineru.net/apiManage/token에서 토큰을 받으세요. MinerU는 최대 200 MB, 최대 200 페이지 파일을 지원합니다.',
    mineruApiTokenPlaceholder: 'MinerU API 토큰 붙여넣기',
    mineruUploadingInProgress: 'MinerU에 PDF 업로드 중: {filename}',
    mineruWaitingInProgress: 'MinerU 변환 대기 중: {filename}',
    mineruDownloadingInProgress: 'MinerU 결과 다운로드 중: {filename}',
    markdownConversionComplete: '변환 완료: {filename}',
    markdownConversionCompleteSaved: '변환 완료 — {path}에 저장됨: {filename}',
    mineruPageLimitRejected: '{filename}이(가) MinerU의 {limit}페이지 제한을 초과했습니다 — 파일을 분할한 후 다시 시도하세요',
    mineruSizeLimitRejected: '{filename}이(가) MinerU의 {limit}MB 크기 제한을 초과했습니다',
    writePdfMarkdownToVaultDesc: '기본값은 꺼짐. 켜면 각 PDF 변환 결과가 원본 PDF 옆에 「<basename>.pdf.md」 파일로 기록됩니다. 꺼져 있으면(캐시 전용 아키텍처) 결과는 플러그인 캐시에만 남고 Vault에는 구현 아티팩트를 남기지 않습니다.',

    ingestRejectedSummary: '{count}개 파일을 건너뛰었습니다(비어 있음, 중복 또는 미지원 형식).',
    reingestConfirmTitle: '이 파일을 다시 가져올까요?',
    reingestConfirmBody: '「{filename}」의 내용이 이미 위키에 있습니다. 그래도 다시 가져올까요?',
    reingestConfirmYes: '다시 가져오기',
    reingestConfirmNo: '건너뛰기',
    lintDedupIncludeSourcesName: '중복 검사에 소스 포함',
    lintDedupIncludeSourcesDesc: '기본값은 켜짐. 켜져 있으면 본문이 동일한 소스가 lint에서 중복으로 표시됩니다. 소스 모음집에서 오탐이 많으면 끄세요.',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: '소스가 언급만 하는 후보 건너뛰기',
    skipMentionOnlyCandidatesDesc: '기본값은 꺼짐. 켜면 노트 본문에 이름이 나타나지 않는 추출 엔티티·개념(없거나 괄호·열거·짧은 목록 항목 안에만 있는 경우)은 페이지를 만들지 않고 추가 모델 호출도 하지 않으며, 다른 후보의 관련 목록에서도 제거됩니다. 단어 경계 프로필이 있는 위키 언어에서 동작합니다(독일어 측정됨; 영어·프랑스어·스페인어·포르투갈어·네덜란드어는 추정). 다른 언어에서는 적용할 수 없다고 수집 시 한 번 알립니다. 용어집형 볼트나 글머리 기호 위주의 노트에서 언급된 모든 용어를 페이지로 만들고 싶다면 꺼 두세요.',
    createStubsForUnresolvableLinksName: '해결되지 않는 링크의 스텁 페이지 만들기',
    createStubsForUnresolvableLinksDesc: '기본값은 켜짐. 깨진 링크 수정이 링크를 어떤 기존 페이지로도 해결하지 못하면 빈 자리 표시 페이지를 작성하고 링크를 그쪽으로 다시 연결합니다(LLM으로 채우지 않음). 끄면 이런 링크는 그대로 유지되어 실제 소스가 정의할 때까지 매번 보고서에 표시됩니다.',
    lintDedupSectionHeading: '중복 검사',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): 범용 문구, 모든 LLM
    // 비즈니스 경로에서 재사용 가능. {count}는 재시도가 필요했던 배치
    // 수입니다. "Lint 완료" 라고 말하지 않음 — 재시도는 이 배치만
    // 복구합니다.
    llmRetryRecoveredToast: 'LLM 작업: {count}개 배치가 provider의 일시적 응답 문제로 재시도가 필요했습니다 (자동 복구됨). 자세한 내용은 콘솔을 참조하세요. 반복되면 Provider 설정에서 Page Generation Concurrency를 낮추세요.',
    ingestReportFailedGuidance: '이 항목은 자동으로 생성되지 않았습니다. 해당하는 페이지를 수동으로 생성하거나 추출 세분화를 낮추고 소스 파일을 다시 수집할 수 있습니다.',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: '단일 소스 수집',
    cmdIngestFolder: '폴더에서 수집',
    cmdIngestMultipleFiles: '여러 파일 수집',
    cmdQueryWiki: '위키 질의',
    cmdLintWiki: '위키 린트',
    cmdRegenerateIndex: '인덱스 재생성',
    cmdSuggestSchema: '스키마 업데이트 제안',
    cmdCancelIngestion: '현재 수집 취소',
    cmdIngestActiveFile: '현재 파일 수집',
    cmdViewHistory: '수집 이력 보기',
    noActiveFile: '열려 있는 파일이 없습니다',
    mdOnlyFile: 'Markdown 파일만 수집할 수 있습니다',
    ingestSingleFileStart: '수집 중: {filename}',
    ingestCheckingExisting: '이미 수집된 파일 확인 중...',
    lintFindingsSummary: '발견 {total}건',

    // Ingestion status bar
    ingestionStatusBar: '수집 중... 클릭하여 취소',
    lintStatusBar: '점검 중... 클릭하여 취소',
    ingestStatusAnalyzing: '수집 중… (클릭하여 취소)',
    lintStatusAnalyzing: '점검 중… (클릭하여 취소)',
    // v1.25.11 PATCH #169 — fine-grained stage hints for the status bar.
    // These labels are ADD-only emission sandwiched between the page name
    // and the always-visible base label (e.g. "My Note · Generating summary ·
    // Ingesting… (click to cancel)"). They never replace the base label, so
    // the cancel affordance is preserved through every long-running stage.
    ingestStageAnalyze: '소스 분석 중',
    ingestStageSummary: '요약 생성 중',
    ingestStageEntity: '엔티티 생성 중',
    ingestStageConcept: '컨셉 생성 중',
    ingestStageRetry: '실패한 페이지 재시도 중',
    ingestStageSave: '페이지 저장 중',
    ingestStageIndex: '인덱스 생성 중',
    pdfStageReading: 'PDF 읽는 중',
    pdfStageConverting: 'PDF 변환 중',
    pdfStageSidecar: '사이드카 파일 쓰는 중',
    lintStagePrep: '페이지 읽는 중',
    lintStageProgrammatic: '링크 스캔 중',
    lintStageAnalyzing: 'LLM 분석 실행 중',
    lintStageDedup: '중복 감지 중',
    lintStageContradiction: '모순 감지 중',
    ingestionCancelling: '취소 중 — 현재 배치 완료 후 중지됩니다',
    ingestionCancelled: '수집이 취소되었습니다',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: '배치 1/{total} 분석 중...',
    ingestBatchProgress: '배치 {current}/{total} 분석 중（엔티티 {entities}개, 컨셉 {concepts}개까지）...',
    ingestBatchProcessed: '배치 {current} 분석 완료, 처리 중...',
    ingestAnalyzing: '분석 중: {filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] 요약 생성 중...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}: {name}',
    ingestUpdating: '[{step}/{totalSteps}] 업데이트 중: {name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] 인덱스 생성 중...',
    ingestItemTypeEntity: '엔티티',
    ingestItemTypeConcept: '컨셉',
    convAnalyzing: '대화 분석 중...',
    convCheckingExisting: '기존 지식 확인 중...',
    convAlreadyExists: '이 지식은 이미 Wiki에 존재합니다',
    convCreatingSummary: '요약 페이지 생성 중...',
    convGeneratingSummary: '요약 페이지 생성 중...',
    convSavingEntity: '엔티티 저장 중: {name}',
    convSavingConcept: '컨셉 저장 중: {name}',
    convGeneratingIndex: '인덱스 생성 중...',

    // Lint Report
    lintReportTitle: '위키 린트 보고서',
    lintReportSummary: 'Wiki 상태 개요: 총 {total}페이지, {aliasesMissing}페이지 별칭 누락, 중복 {duplicates}개, 데드 링크 {deadLinks}개 ({deadLinkFromDup}개 중복 관련), 고아 {orphans}개 ({orphanFromDup}개 중복), 빈 페이지 {emptyPages}개, 출처 없는 인용 {ungroundedQuotes}개, 어휘 외 태그 {tagViolations}개. Lint 소요: {elapsedSeconds}초',

    // Advanced LLM Settings (Issues #99 / #128)
    // v1.26.0 (#382 item 2): 이름을 "고급 매개변수 설정"에서 "LLM 고급 매개변수"로
    // 변경 — LLM 샘플링에 한정하고 하단의 범용 "고급 설정" 패널과 구분.
    advancedLlmModeName: 'LLM 고급 매개변수',
    advancedLlmModeDesc: '기본 모드는 모델 공급자가 권장하는 설정을 따릅니다. 명시적으로 재정의할 이유가 있을 때(예: 특정 모델에 고정 온도가 필요하거나, 모델의 사고 출력을 끄고 싶을 때)만 사용자 정의로 전환하세요.',
    advancedSettingsDefault: '기본값 (공급자 따름)',
    advancedSettingsCustom: '사용자 정의 (공급자 재정의)',
    // v1.26.0 (#382 item 2): 하단의 "고급 설정" 패널 — LLM 샘플링이 아닌
    // 모든 고급 사용자 설정의 범용 위치(lint 임계값, 웰컴 노트, 향후 확장).
    advancedSettingsSection: '고급 설정',
    showAdvancedSettingsName: '고급 설정 표시',
    showAdvancedSettingsDesc: '켜면 아래 고급 설정이 표시됩니다. 끄면 숨겨지고 기본값으로 재설정됩니다.',
    disableThinkingName: '생각 비활성화',
    disableThinkingDesc: '모델 응답의 사고 연쇄/추론 텍스트 출력을 끕니다. 기본값은 꺼져 있으며, 모델이 추론 표시 여부를 스스로 결정하는데, 이 경우가 보통 가장 좋은 답을 줍니다. 공급자가 응답에 원본 추론 텍스트를 섞어 넣고 깔끔한 답을 원할 때만 켜세요.',
    taskPoliciesPlaceholder: '예: extract=text:off',
    taskPoliciesName: '단계별 출력 모드와 사고',
    taskPoliciesDesc: '파이프라인 단계마다 한 항목, `step=mode:thinking` 형식을 쉼표로 구분 — 예: `extract=text:off`. 모드: `-`(유지), `schema`, `json`, `text`; 사고: `-`, `off`, `on`, `low`, `medium`, `high`. 단계 이름에는 extract, extract-retry, lemma-classify, merge-triage, source-stance, dedup, page-generate, related-page, lint-dedup 등이 있습니다(잘못 입력한 이름은 아무것과도 일치하지 않음). 비워 두면 기본 설정(추출은 텍스트 모드). 해석할 수 없는 항목은 저장되지 않습니다.',
    // Issue #137: 호환성 안내 (간결하게; 공급자 목록 생략)
    extractionTemperatureName: '추출 온도',
    extractionTemperatureDesc: '모델이 entity/concept 페이지를 작성할 때 엄격함을 우선할지 창의성을 우선할지 제어합니다. 값이 낮을수록 결정적이고 원본에 충실하며, 값이 높을수록 변화가 많아집니다. 대부분의 사용자는 비워 둡니다.',
    chatTemperatureName: '쿼리 온도',
    chatTemperatureDesc: '「추출 온도」와 같은 개념이지만 Query Wiki 질문 응답에만 영향을 줍니다. 값이 낮을수록 글자 그대로 답하고, 값이 높을수록 대화체로 답합니다. 대부분의 사용자는 비워 둡니다.',
    repetitionPenaltyName: '반복 패널티',
    repetitionPenaltyDesc: '모델이 같은 단어나 문구를 반복하는 것을 억제합니다. 값이 높을수록 반복이 줄어듭니다. 이 파라미터를 받는 것은 일부 로컬 모델 공급자(Ollama, LM Studio, llama.cpp)뿐이며, 클라우드 공급자는 조용히 무시합니다. 대부분의 사용자는 비워 둡니다. 1.0을 초과하는 값은 소규모 로컬 모델의 추출 중 LLM 출력 오류를 일으킬 수 있습니다. 실행이 실패하면 이 값을 줄이거나 비우세요.',
    repetitionPenaltyErrorHint: '참고: 사용자 지정 반복 페널티 {value}가 설정되어 있습니다. 1.0을 초과하는 값은 소규모 로컬 모델의 문법 제약 추출을 깨뜨릴 수 있습니다. 이 설정을 줄이거나 비우고 다시 시도하세요.',
    temperaturePlaceholder: '비워 두면 = 제공자 기본값',
    // v1.26.0 (#382 item 2): 중복 감지 임계값 (고급 사용자 지정 모드 전용).
    lintDedupJaccardLinkThresholdName: '링크 중복 유사도',
    lintDedupJaccardLinkThresholdDesc: '범위 0–1 (기본값 0.4). 두 페이지가 공통으로 가리키는 wiki 링크의 비율이 각자의 링크 총수 중 최소 이 값에 도달하면 중복으로 표시됩니다. 낮춤 → 근사 중복을 더 많이 포착 (같은 허브만 링크하는 페이지 포함); 높임 → 거의 같은 페이지 묶음을 가리키는 페이지만 표시됩니다. 서로 관련 없는 페이지가 같은 허브만 링크한다는 이유로 오탐이 발생하는 경우 이 값을 높이세요. 비워 두면 기본값을 사용합니다.',
    lintDedupJaccardBodyGateName: '본문 최소 유사도',
    lintDedupJaccardBodyGateDesc: '범위 0–1 (기본값 0.2). 두 페이지가 wiki 링크를 공유하더라도 본문 유사도(비율)가 최소 이 값에 도달해야만 중복으로 표시됩니다. 낮춤 → LLM 검증으로 넘어가는 후보가 늘어남; 높임 → 본문이 거의 동일한 페이지만 표시됩니다. 명백히 중복이 아닌 페이지를 LLM이 검증하고 있다면 이 값을 높이세요. 비워 두면 기본값을 사용합니다.',
    lintDedupBigramThresholdName: '제목 유사도',
    lintDedupBigramThresholdDesc: '범위 0–1 (기본값 0.4). 두 페이지 제목 (또는 별칭)의 문자 일치율이 최소 이 값에 도달하면 중복으로 표시됩니다. 낮춤 → 철자 변형, 오타, 같은 개념의 번역까지 포착; 높임 → 제목이 거의 동일한 페이지만 표시됩니다. 제목이 크게 다르지만 실제로는 중복이 아닌 페이지를 LLM이 검증하고 있다면 이 값을 높이세요. 비워 두면 기본값을 사용합니다.',
    lintDeadLinkSection: '데드 링크 (감지됨) [{count}개]',
    lintEmptyPageSection: '빈 페이지 (감지됨) [{count}개]',
    lintOrphanSection: '고아 페이지 (감지됨) [{count}개]',
    lintContradictionSection: '모순 (감지됨)',
    lintDuplicateSection: '중복 페이지 (감지됨)',
    lintNoIssuesFound: '중복, 깨진 링크, 빈 페이지, 고아 페이지 또는 출처 없는 인용이 감지되지 않았습니다.',
    lintSourceDriftSection: '수집 후 변경된 소스 노트 [{count}개]',
    lintSourceDriftItem: '- [[{page}]] — 원본 노트 [[{note}]]가 수집 후 수정되었습니다. 페이지가 오래되었을 수 있습니다',
    lintContradictionMarkerSection: '모순 마커가 있는 페이지 (병합 분류) [{count}개]',
    lintContradictionMarkerItem: '- [[{page}]] — 충돌하는 소스: {sources}. 검토 후 contradictions: 마커를 제거하세요',
    lintQuoteGroundingSection: '출처 없는 인용 (감지됨) [{count}개]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: "{quote}"',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (페이지가 존재하지 않음){dupFlag}',
    lintDeadLinkMore: '- ... {count}개의 깨진 링크 추가',
    lintEmptyPageItem: '- [[{page}]] — 실질적인 콘텐츠가 50자 미만',
    lintOrphanItem: '- [[{page}]] — 다른 위키 페이지에서 링크하지 않음{dupFlag}',
    lintPollutedSection: '오염 페이지 (감지됨) [{count}개]',
    lintPollutedItem: '- [[{page}]] → "{clean}"(으)로 수정 필요',
    lintSourcesNormalizedSection: 'Sources 정규화 (자동 수정) [{files}개 파일 / {entries}개 항목]',
    lintSourcesNormalizedItem: '{files}개 파일에서 {entries}개의 sources 항목을 정리했습니다 (외부 경로, .md 확장자, 별칭 파이프 제거 및 중복 제거).',
    lintDuplicateItem: '- [[{target}]] 및 [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ 중복 페이지 관련)',
    lintOrphanIsDuplicate: ' (⚠️ 중복 페이지)',
    lintHubLinkDensitySection: '허브 링크 밀도 문제 (Issue #157 / #175) [{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree}개 인바운드, {relatedCount}개 관련 링크, 식별도 {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ 제거',
    lintHubLinkDensityReview: '🔍 검토',
    lintHubLinkDensityKeep: '✅ 유지',
    lintHubLinkDensitySummary: '요약: 제거 권장 {strip}페이지, 검토 권장 {review}페이지.',
    lintHubLinkDensityNoRelated: ' (## Related 섹션을 찾을 수 없음)',
    lintContradictionOpen: '해결되지 않은 모순: {count}개',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: '감지됨',

    // Lint Analysis Prompt

    // Lint Fix Progress
    lintFixProgress: '수정 중 {current}/{total}: [[{target}]]',
    lintFixDeadComplete: '깨진 링크 수정 완료. {fixed}/{total} 항목 수정.',
    lintFillProgress: '확장 중 {current}/{total}: {page}',
    lintFillComplete: '페이지 확장 완료. {filled}/{total} 페이지 채움.',
    lintDeleteCompleted: '{count}개의 빈 스텁 삭제됨',
    lintDeleteFailed: '빈 stub 삭제 실패 {failed}/{total}개 (자세한 내용은 콘솔 참조)',
    lintFillFailed: '확장 실패: {page} — {error}',
    lintLinkProgress: '링크 중 {current}/{total}: {page}',
    lintLinkComplete: '고아 링크 완료. {linked} 페이지 링크됨.',
    lintFixNoAction: '조치 없음 (클라이언트 없음)',
    lintFixIndexUpdated: '위키 인덱스 및 로그가 업데이트되었습니다.',
    lintPollutedFixed: '오염된 페이지 수정 완료: {fixed}/{total}. 인덱스 재생성됨.',
    regenerateIndexCompleted: '인덱스 재생성됨',
    operationFailed: '실패: ',
    lintFixAllComplete: '모든 수정이 완료되었습니다. 자세한 내용은 로그를 확인하세요.',
    lintFixAllNoChanges: '변경 없음 — 모든 단계에서 0건이 보고되었습니다. 자세한 내용은 wiki/log.md를 확인하세요.',
    lintFixPhasesLabel: '단계가 수정됨',

    // Lint Report Modal
    lintModalActionsTitle: '수정 제안 (LLM 토큰 필요):',
    lintLogReference: '전체 보고서가 log.md에 저장되었습니다',
    lintModalFixDeadLinks: '깨진 링크 수정 ({count})',
    lintModalExpandEmpty: '빈 페이지 확장 ({count})',
    lintModalDeleteEmpty: '빈 스텁 삭제 ({count})',
    lintModalLinkOrphans: '고아 페이지 링크 ({count})',
    lintModalAnalyzeSchema: '스키마 분석',
    lintModalMergeDuplicates: '중복 병합 ({count})',
    lintModalFixAll: '스마트 전체 수정 ({count} 이슈)',
    lintMergeProgress: '병합 중 {current}/{total}: {source} → {target}',
    lintMergeComplete: '중복 병합 완료. {merged}/{total} 쌍 병합.',

    // Ingest Report Modal
    ingestReportTitle: '수집 보고서',
    ingestReportSourceFile: '소스 파일',
    ingestReportCreated: '생성됨',
    ingestReportUpdated: '업데이트됨',
    ingestReportContradictions: '모순 발견',
    ingestReportFailedTitle: '수집 실패',
    ingestReportErrorDetail: '오류 상세',
    ingestReportClose: '닫기',
    ingestReportCreatedPages: '생성된 페이지: {count}',
    ingestReportUpdatedPages: '업데이트된 페이지: {count}',
    ingestReportEmbeddedImages: '포함된 이미지: {discovered}개 발견, {queued}개 대기열, {sent}개 전송, {analyzed}개 분석. {packages}개 패키지, GIF 첫 프레임 {gifs}개 변환, 실패 {failed}개',
    ingestReportEmbeddedEvidenceSaved: '시각 증거가 출처 페이지에 저장되었습니다',
    ingestReportEmbeddedImageSkipped: '건너뛴 포함 이미지',
    embeddedImagesVisionUnsupported: '이 엔드포인트가 이미지 분석을 거부했습니다. 텍스트 수집은 계속됩니다. 비전 지원 모델로 전환하거나 포함 이미지 분석을 끄세요.',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki 작업 기록',
    logHeaderSubtitle: '모든 수집, Lint 실행 및 유지보수 작업이 여기에 자동 기록됩니다. 더 나은 보기를 위해 **작업 기록** 패널을 사용하세요:',
    logHeaderShortcut: 'Cmd+P → "작업 기록 보기"',
    logHeaderSettingsShortcut: '또는 설정 → 자동 유지보수 → 작업 기록에서',
    ingestionCreatedPages: '{count} 페이지 생성됨',
    ingestionUpdatedPages: '{count} 페이지 업데이트됨',
    ingestionNoticeHistoryHint: '자세한 내용은 작업 기록 보기',
    ingestReportEntitiesCount: '{count} 엔티티',
    ingestReportConceptsCount: '{count} 컨셉',
    ingestReportContradictionsFound: '모순 발견: {count}',
    ingestReportEntityType: '엔티티',
    ingestReportConceptType: '컨셉',
    timeMinutes: '분',
    timeSeconds: '초',

    // 속도 제한 경고
    rateLimitDetected: '⚠️ 속도 제한 감지: {count}개 페이지가 429 오류로 실패했습니다. 권장 조치: (1) 동시성을 {suggestedConcurrency} 또는 1(직렬)로 낮추기, (2) 배치 지연을 {suggestedDelay}ms로 늘리기, (3) 더 높은 속도 제한을 가진 제공업체로 전환.',
    rateLimitDetectedShort: '⚠️ 속도 제한 발생 — 설정 → 수집 가속에서 동시성을 낮추거나 배치 지연을 늘리는 것이 좋습니다.',

    longSourceNotice: '📄 "{filename}" 파일은 {lines}줄({size})입니다. 긴 텍스트는 반복 일괄 추출이 필요하며 LLM이 전체 문서를 여러 번 분석하므로 몇 분이 걸릴 수 있습니다. 잠시만 기다려 주세요.',
    longSourceNoticeShort: '📄 대용량 파일 감지({lines}줄). 수집에 다소 시간이 걸릴 수 있습니다.',

    // 수집 이력 패널 (#122) — UI 텍스트
    historyButton: '작업 기록',
    historyButtonDesc: 'LLM-Wiki의 최근 수집, Lint 보고서 및 기타 변경 사항 보기',
    historyButtonOpen: '기록 보기',
    historyModalTitle: '작업 기록',
    historyModalSubtitle: 'LLM-Wiki의 최근 변경 사항',
    historyEmpty: '기록된 작업이 없습니다. 노트를 수집하거나 Lint를 실행하여 이 목록을 채우세요.',
    historyReadError: '작업 로그를 읽을 수 없습니다: {error}',
    historyEntryKindIngest: '수집',
    historyEntryKindMaintenance: '유지보수',
    historyEntryKindFix: '수정',
    historyEntryKindOther: '기타',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: '소스: {source}',
    historyEntrySourceUnknown: '이름 없는 수집',
    historyEntryCreatedLabel: '생성됨',
    historyEntryUpdatedLabel: '업데이트됨',
    historyEntryCreatedCount: '{count}개 생성',
    historyEntryUpdatedCount: '{count}개 업데이트',
    historyEntryNoChanges: '페이지 변경 없음',
    historyEntryContradictions: '⚠️ 모순 {count}건',
    historyEntrySectionCreated: '생성된 페이지',
    historyEntrySectionUpdated: '업데이트된 페이지',
    historyEntrySectionContradictions: '모순',
    historyEntrySectionDetails: '세부 정보',
    historyEntryOpenPage: '열기',
    historyEntryDetailsNoContradictions: '모순이 발견되지 않았습니다',
    historySearchPlaceholder: '🔍 소스 제목 또는 페이지 경로로 검색…',
    historyFilterAll: '모두',
    historyFilterIngest: '수집만',
    historyFilterMaintenance: '유지보수만',
    historyFilterFix: '수정만',
    historyFilterContradictions: '⚠️ 모순 포함',
    historyRefreshButton: '⟳ 새로 고침',
    historyExpandDay: '클릭하여 펼치기',
    historyCollapseDay: '클릭하여 접기',
    historyShowMore: '이전 항목 {count}개 보기',
    historyNoMatch: '검색/필터에 일치하는 작업이 없습니다.',
    historyCloseButton: '닫기',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: '보고서 결과',
    historyKpiPages: '페이지',
    historyKpiDeadLinks: '끊긴 링크',
    historyKpiOrphans: '고아',
    historyKpiEmpty: '빈 페이지',
    historyKpiDuplicates: '중복',
    historyKpiTagViolations: '태그 문제',
    historyKpiUnsourced: '출처 없음',
    historyKpiDuration: 'Lint 시간',
    historyKpiDurationSec: '{seconds}초',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: '끊긴 링크 ({count})',
    historySectionTagViolations: '태그 위반 ({count})',
    historySectionOrphans: '고아 페이지 ({count})',
    historySectionEmptyPages: '빈 페이지 ({count})',
    historySectionLlmAnalysis: 'LLM 분석 ({count})',
    historyDeadLinkSource: '출처',
    historyDeadLinkTarget: '누락',
    historyOpenInLog: 'log.md에서 보기',
    historyShowMoreItems: '나머지 {count}개 펼치기',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ 동일',
    historyChipContradiction: '모순',
    historyChipOutdated: '오래됨',
    historyChipMissing: '누락',
    historyChipStructure: '구조',
    historySeverityHigh: '높음',
    historySeverityMedium: '중간',
    historySeverityLow: '낮음',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Wiki에 끊긴 링크 {dead}개, 고아 페이지 {orphans}개, 태그 문제 {tags}개가 있습니다. 최근 Lint는 {duration} 소요.',
    historyGlobalInsightClean: 'Wiki 상태가 양호합니다 — 끊긴 링크, 고아 페이지, 태그 문제가 감지되지 않았습니다.',
    historyGlobalInsightNoData: '유지보수 보고서가 아직 없습니다 — Lint를 실행하세요.',
    historyModalHeaderTitle: '작업 기록',
    historyModalSubtitleWithCount: 'LLM-Wiki의 최근 변경 · 총 {count}개',
    historyTimeRangeAll: '전체 기간',
    historyTimeRange1d: '최근 1일',
    historyTimeRange3d: '최근 3일',
    historyTimeRange1w: '최근 1주',
    historyTimeRange1m: '최근 1개월',
    historyIngestTotal: '총 페이지',
    historyIngestByType: '유형별',
    historyIngestSource: '소스 파일',
    historyIngestNoTimestamp: '타임스탬프 없음',
    historyIngestFirstTime: '첫 수집',
    historyIngestLatestTime: '최근 수집',
    historyTimeRangeCustom: '사용자 지정 범위',
    historyCustomRangeFrom: '시작',
    historyCustomRangeTo: '종료',
    historyCustomRangeApply: '적용',
    historyCustomRangeClear: '지우기',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki: vault가 비어 있습니다. 첫 번째 소스 노트를 만들고 Ingest를 실행하여 시작하세요.',
    welcomeNoteTierBNotice: 'Karpathy Wiki: Welcome 노트를 만들었습니다. 열어 도메인을 선언하고 링크 그래프의 시드로 사용할 2-3 개 소스 노트를 선택하세요.',
    welcomeNoteRecreateCommand: 'Wiki Welcome 노트 재생성',
    welcomeNoteRecreateCommandTooltip: '현재 도메인 시드와 LLM 구성 테스트로 <wikiFolder>/Welcome.md에 Welcome 노트를 재생성합니다. 기존 파일은 덮어씁니다.',
    welcomeNoteSettingsToggle: '첫 실행 시 Wiki Welcome 노트 생성',
    welcomeNoteSettingsToggleDesc: '최초 실행 시(wiki 폴더가 비어 있을 때) <wikiFolder>/Welcome.md 에 한 페이지짜리 입문 노트를 자동으로 생성합니다. LLM-Wiki 가 무엇인지 설명하고, 도메인 포커스를 선언하도록 안내하며, 처음 2-3 개 소스 노트 수집법을 알려줍니다. 노트는 기본적으로 영어로 작성되며, LLM 이 설정되어 있으면 wiki 언어로 작성됩니다. 플러그인 사용법을 이미 알고 있어서 입문 노트가 필요 없다면 끌 수 있습니다.',
    welcomeNoteRunConfigTest: 'Welcome 노트가 영어로 작성되었습니다. 다음 재생성 시 현지화하려면 설정 → LLM Provider → Test Connection을 여세요.',
    welcomeNoteRecreated: '{path}에 Wiki Welcome 노트를 재생성했습니다',
    welcomeNoteNotRecreated: 'Welcome 노트가 재생성되지 않았습니다. LLM 설정을 확인하세요.',
    welcomeNoteGenerating: 'Wiki Welcome 노트를 백그라운드에서 생성 중 — 완료 시 알림이 표시됩니다.',
    welcomeNoteGenerationFailed: 'Wiki Welcome 노트 생성 실패: {error}',
    startupCheckWelcomePending: 'Welcome 노트: 백그라운드에서 생성 중(완료 시 알림이 표시됩니다).',
    welcomeNoteFileName: 'Karpathy LLM Wiki에 오신 것을 환영합니다',
    startupCheckWelcomeCreated: '{path}에 Welcome 노트가 생성되었습니다',
    // v1.23.0 Phase 5.1.5: 다중 파일 수집 모달의 "모두 취소" 버튼.
    // 대기열의 모든 pending + running 작업을 한 번에 취소합니다.
    // 완료 및 실패한 작업은 표시용으로 유지됩니다.
    cancelAllQueueJobs: '모두 취소',
    // v1.23.0 Phase 5.1.5: 다중 파일 수집 모달(cmdIngestMultipleFiles).
    // 제목, 안내, 검색 입력, 버튼, 상태 레이블, 빈 큐 안내.
    multiFileModalTitle: '다중 파일 수집',
    multiFileModalHint: '수집할 소스 노트를 선택하세요. 오른쪽 패널에 실시간 큐와 진행률이 표시됩니다.',
    multiFileSearchPlaceholder: '경로로 파일 필터링…',
    multiFileAddToQueue: '큐에 추가',
    multiFileSelectAll: '모두 선택',
    multiFileFileCount: '파일 {count}개',
    multiFileNoFilesAvailable: '수집 가능한 파일이 없습니다.',
    multiFileNoFilesMatch: '"{q}"와(과) 일치하는 파일이 없습니다.',
    multiFileQueueEmpty: '큐가 비어 있습니다. 왼쪽에서 파일을 선택하세요.',
    multiFileStatusPending: '대기 중',
    multiFileStatusRunning: '수집 중',
    multiFileStatusCompleted: '완료됨',
    multiFileStatusFailed: '실패함',
    multiFileCancelAria: '이 파일 취소',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: '수집됨',
    multiFileRowDrifted: '수집 후 노트가 변경됨',
    startupCheckNoticeLevelName: '빠른 수정 결과 표시',
    startupCheckNoticeLevelDesc: 'QuickFixes는 플러그인 시작 시 항상 실행됩니다(Welcome 노트, 폴더 구조, 소스 정규화, 불완전한 페이지, 로그 헤더). 시작 후 요약 알림을 표시할지 선택합니다. 무음 모드는 개발자 콘솔 및 작업 기록 패널에만 기록됩니다.',
    startupCheckNoticeVisible: '표시(알림 표시)',
    startupCheckNoticeSilent: '무음(알림 없음)',
} as const;
