export const PT_TEXTS = {
    // Plugin Info
    pluginTitle: 'Configurações do Karpathy LLM Wiki',
    pluginIntro: 'Este plug-in implementa o conceito de {{link}} para o Obsidian. Ele lê suas notas, usa IA para extrair entidades, conceitos e relações, e constrói uma Wiki estruturada e interligada no seu vault.',
    karpathyLinkText: 'LLM Wiki de Andrej Karpathy',

    // Features Section
    featuresTitle: 'Como funciona',
    workflow1Title: '1. Ingerir',
    workflow1Desc: 'Selecione uma nota — a IA extrai entidades, conceitos e relações para páginas da Wiki.',
    workflow2Title: '2. Consultar',
    workflow2Desc: 'Converse com sua Wiki — as respostas são baseadas no seu conhecimento ingerido.',
    workflow3Title: '3. Manter',
    workflow3Desc: 'Índice gerado automaticamente, links cruzados e verificações de qualidade mantêm a Wiki saudável.',

    // Language Switcher
    languageTitle: 'Idioma da interface',
    languageDesc: 'Selecione seu idioma preferido para o painel de configurações. Reinicie o plugin para aplicar as alterações de idioma à paleta de comandos.',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // Status
    statusTitle: 'Status do LLM Client',
    llmWikiStatusSection: 'Status do LLM-Wiki',
    statusInitialized: 'Inicializado',
    statusReady: 'LLM pronto',
    statusNotReady: 'LLM não configurado — complete a configuração acima e passe no teste de conexão',
    statusNotInitialized: 'Não inicializado',
    currentProvider: 'Provedor atual',

    // Provider Configuration
    providerSection: 'Configuração LLM',
    providerName: 'Provedor LLM',
    providerDesc: 'Selecione um provedor predefinido ou serviço personalizado compatível com OpenAI. Para Coding Plan ou bundles similares: escolha Custom OpenAI/Anthropic, insira manualmente o Base URL e API Key do provedor',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: 'Chave de API. Guardada no gerenciador de credenciais do sistema, não em data.json.',
    apiKeyPlaceholder: 'Insira a API Key',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: 'Migrar SecretStorage',
    apiKeyMigratedToSecretStorageSuccess: 'API Key restaurada do SecretStorage para as configurações.',
    apiKeyMigrationFailedNotice: 'Falha ao salvar a API Key no SecretStorage: {}',
    codexAuthName: 'Início de sessão no plano ChatGPT',
    codexAuthDesc: 'Acesso experimental ao Codex por OAuth usando a franquia do seu plano ChatGPT. A cobrança da API da OpenAI Platform permanece separada.',
    codexAuthSignedOut: 'Sessão não iniciada',
    codexAuthSignedIn: 'Sessão iniciada',
    codexAuthBrowserButton: 'Iniciar sessão com o navegador',
    codexAuthDeviceButton: 'Usar código do dispositivo',
    codexAuthDeviceInstructions: 'Insira este código na página da OpenAI: {}',
    codexAuthCopyCode: 'Copiar código',
    codexAuthSignOutButton: 'Terminar sessão',
    codexAuthBusy: 'Aguardando autorização da OpenAI...',
    codexAuthFailed: 'Falha na autorização do ChatGPT: {}',
    codexAuthQuota: 'A franquia do ChatGPT Codex foi atingida. Aguarde o período de redefinição exibido e tente novamente.',
    codexAuthExperimental: 'Experimental: a disponibilidade segue as políticas de autenticação e modelos do OpenAI Codex.',
    codexModelsRefreshName: 'Modelos da conta',
    codexModelsRefreshDesc: 'Sincroniza os modelos selecionáveis da conta OpenAI Codex conectada.',
    codexModelsRefreshButton: 'Atualizar modelos da conta',
    codexModelsRefreshing: 'Atualizando...',
    codexModelsRefreshSuccess: '{} modelos da conta sincronizados.',
    codexModelsRefreshFailed: 'Não foi possível atualizar os modelos da conta; a lista alternativa disponível será usada. {}',

    // Base URL
    baseUrlName: 'URL base da API',
    baseUrlDescCustom: 'Obrigatório: endpoint personalizado compatível com OpenAI',
    baseUrlDescOverride: 'Opcional: substituir URL base predefinida',

    // Ollama Hint
    ollamaHint: 'O Ollama roda localmente, não requer API Key',
    lmstudioHint: 'O LM Studio roda localmente, API Key é opcional',
    maxTokensPerCallName: 'Máx. tokens de saída por chamada',
    maxTokensPerCallDesc: 'Limita quantos tokens o modelo pode gerar numa única resposta. Reduza se usar um modelo local com janela de contexto pequena e vir erros. Para modelos na nuvem, mantenha o padrão (0 = sem limite).',

    slugCaseName: 'Capitalização de nomes de arquivo',
    slugCaseDesc: "Controla se os nomes de arquivo Wiki gerados são convertidos para minúsculas. Recomenda-se 'Preservar' para idiomas onde maiúsculas são significativas (ex. substantivos alemães).",
    slugCaseLower: 'Minúsculas (padrão)',
    slugCasePreserve: 'Preservar capitalização',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: 'Comprimento mínimo de alias',
    minAliasLengthDesc: 'Aliases mais curtos (após remover espaços) não são escritos nas páginas do wiki. O valor 2 mantém abreviações de duas letras (ML, IA, UI) utilizáveis; aumente para 3 se o seu cofre acumula aliases de duas letras que diferem apenas em maiúsculas (Cr/CR). Intervalo 2–6.',
    minAliasLengthClamped: 'Valor fora do intervalo (2–6), definido para {}',

    // Model Selection
    modelSection: 'Seleção de modelo',
    fetchModelsName: 'Buscar modelos disponíveis',
    fetchModelsDesc: 'Obter a lista mais recente de modelos da API do provedor',
    fetchModelsButton: 'Buscar modelos',
    fetchingModels: 'Buscando...',
    fetchSuccess: 'Sucesso! {} modelos disponíveis',
    fetchFailed: 'Falha ou lista vazia. Insira o nome do modelo manualmente',
    fetchNotSupported: 'O provedor não suporta consulta à lista de modelos',
    fetchErrorAuth: 'Falha de autenticação (HTTP 401/403). Verifique a chave API, ou insira um ID de modelo e clique em Testar conexão.',
    fetchErrorEndpoint: 'Endpoint não encontrado (HTTP 404). Verifique a URL do endpoint, ou insira um ID de modelo e clique em Testar conexão.',
    fetchErrorServer: 'Erro do servidor do provedor (HTTP 5xx). Tente novamente mais tarde, ou insira um ID de modelo e clique em Testar conexão.',
    fetchErrorEmpty: 'Este endpoint não expõe lista de modelos. Insira um ID de modelo e clique em Testar conexão.',
    fetchErrorNetwork: 'Falha na requisição de rede. Verifique sua conexão com a internet, URL do endpoint, configurações de proxy ou chave da API. Você também pode inserir um ID de modelo e clicar em Testar conexão.',

    selectModelName: 'Selecionar modelo',
    selectModelDesc: 'Escolha entre {} modelos disponíveis',
    customInputOption: 'Entrada personalizada...',
    customInputHint: 'Para usar outros modelos, selecione "Entrada personalizada..."',

    modelName: 'Nome do modelo',
    modelDescCustom: 'Usando modelo personalizado (clique no botão acima para buscar a lista novamente)',
    modelDescFetchFailed: 'Falha ao buscar lista de modelos. Verifique a chave API e URL do endpoint, ou insira um ID de modelo e clique em Testar conexão.',
    modelInputPlaceholder: 'Insira o ID do modelo e teste a conexão',

    switchToDropdown: 'Alternar para seleção por lista',
    useDropdownButton: 'Usar lista suspensa',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: 'Escopo do modelo',
    modelTaskModeDesc: 'Escolha se todas as tarefas usam o mesmo modelo ou se usa modelos diferentes por tarefa (ingestão / manutenção e reparo / consulta). Os valores por tarefa ocultos são preservados ao voltar para o modelo unificado.',
    modelTaskModeUnified: 'Usar modelo unificado (padrão)',
    modelTaskModePerTask: 'Usar modelos diferentes por tarefa',
    perTaskIngestModelName: 'Modelo de ingestão',
    perTaskIngestModelDesc: 'Usado para ingerir notas, conversas, manutenção do esquema e geração da nota de boas-vindas.',
    perTaskLintModelName: 'Modelo de manutenção e reparo',
    perTaskLintModelDesc: 'Usado para análise Lint, detecção de duplicatas, execuções de reparo e correção de links órfãos.',
    perTaskQueryModelName: 'Modelo de consulta',
    perTaskQueryModelDesc: 'Usado para o chat Query Wiki e avaliação de salvamento no Wiki.',

    // Test & Save
    testConnectionName: 'Testar conexão',
    testConnectionDesc: 'Validar se a configuração consegue chamar a API LLM com sucesso',
    testButton: 'Testar conexão',
    testing: 'Testando...',

    saveSettingsName: 'Salvar configurações',
    saveSettingsDesc: 'Salvar a configuração atual',
    saveButton: 'Salvar configurações',
    testConnectionSuccessful: 'Conexão bem-sucedida',
    testConnectionFailed: 'Conexão falhou',
    testConnectionProvider: 'Provedor: ',
    codexAuthRequired: 'Inicie sessão no plano ChatGPT antes de testar a conexão.',
    bedrockSsoRequired: 'Inicie sessão com o AWS SSO (Configurações → Bedrock) antes de testar a conexão.',
    bedrockIamRequired: 'Introduza as suas chaves de acesso do IAM (Configurações → Bedrock) antes de testar a conexão.',
    bedrockAuthMethodName: 'Autenticação',
    bedrockAuthMethodDesc: 'Chave de API usa uma chave de API do Bedrock; o AWS SSO assina pedidos com credenciais do IAM Identity Center; as chaves IAM usam chaves de acesso estáticas.',
    bedrockAuthOptionApiKey: 'Chave de API',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'Chaves IAM',
    bedrockSsoStartUrlName: 'URL inicial do SSO',
    bedrockSsoStartUrlDesc: 'URL do portal da sua organização, por ex. https://d-xxxxxxxxx.awsapps.com/start',
    bedrockSsoAccountIdName: 'ID da conta AWS',
    bedrockSsoAccountIdDesc: 'Conta de 12 dígitos cuja função será assumida, por ex. 123456789012',
    bedrockSsoRoleNameName: 'Nome da função',
    bedrockSsoRoleNameDesc: 'Função IAM a assumir para o acesso ao Bedrock, por ex. PowerUserAccess',
    bedrockSsoLoginButton: 'Iniciar sessão com AWS SSO',
    bedrockSsoSignOutButton: 'Terminar sessão do AWS SSO',
    bedrockSsoStatusSignedIn: 'Sessão iniciada · expira {}',
    bedrockSsoStatusSignedOut: 'Sessão não iniciada',
    bedrockSsoBusy: 'Sessão em curso…',
    bedrockSsoUserCodeInstructions: 'Código AWS SSO: {}. Abra a ligação e aprove o acesso.',
    bedrockSsoCopyCode: 'Copiar código',
    bedrockSsoFailed: 'Falha ao iniciar sessão com AWS SSO: {}',
    bedrockSsoDetectedPrefill: 'Conta/função detetada: {}',
    bedrockIamKeyName: 'ID da chave de acesso',
    bedrockIamKeyDesc: 'Identificador da chave de acesso do IAM, por ex. AKIA… ou ASIA…',
    bedrockIamSecretName: 'Chave de acesso secreta',
    bedrockIamSecretDesc: 'Guardada apenas no armazém de segredos deste dispositivo — nunca em data.json',
    bedrockIamSessionTokenName: 'Token de sessão (opcional)',
    bedrockIamSessionTokenDesc: 'Necessário apenas para credenciais temporárias (STS)',
    bedrockIamClearButton: 'Limpar chaves IAM guardadas',
    bedrockIamSaveFailed: 'Falha ao guardar as chaves IAM: {}',
    errorUnknown: 'Erro desconhecido',
    savedNotice: 'Configurações salvas!',

    // v1.24.0 (Bug C 3.4 / plan C): notificação de migração gradual
    queryHistoryMigrationNotice: 'O histórico do Query Wiki contém links de uma pasta wiki anterior. As novas consultas usam automaticamente a pasta mais recente. Para atualizar todas as mensagens armazenadas, abra o painel do Query Wiki e clique no botão "Limpar histórico" que está lá.',

    // v1.24.0 Issue #251: instruções de Query personalizadas (painel recolhível)
    customInstructionsTitle: 'Instruções de Query personalizadas',
    customInstructionsDesc: 'Instruções persistentes adicionadas ao final do prompt do sistema do Query Wiki. Afetam apenas o chat do Query Wiki; ingestão, lint e geração de páginas não são afetados.',
    customInstructionsPlaceholder: 'ex.: tratar como tarefa de pesquisa: buscar amplamente, citar fontes, separar fatos de interpretação...',
    customInstructionsApply: 'Aplicar',
    customInstructionsClear: 'Limpar',
    customInstructionsCharCount: '{current}/{max} caracteres',
    instructionsApplied: 'Instruções de Query personalizadas salvas.',
    instructionsCleared: 'Instruções de Query personalizadas removidas.',

    // Issue #137: Avisos de fallback de LLM
    fallbackThinkingDialect: 'Controle de pensamento: alternado para o dialeto "{dialect}" (este provedor usa um formato diferente). A saída permanece inalterada.',
    fallbackThinkingNone: 'Controle de pensamento totalmente desativado para este provedor. Conteúdo de raciocínio ainda pode aparecer; se isso acontecer, tente outro modelo.',
    fallbackParamStripped: 'O parâmetro "{field}" não é compatível com este provedor. Removido da requisição; o comportamento pode diferir da configuração.',

    // Wiki Folder
    wikiSection: 'Configuração do Wiki',
    wikiFolderName: 'Pasta Wiki',
    // v1.24.0: indica que é necessário reiniciar o Obsidian após a alteração
    // (os caches do motor e os painéis abertos do Query Wiki precisam ser religados).
    wikiFolderDesc: 'Local para as páginas geradas da Wiki. Reinicie o Obsidian após a alteração — os caches do motor e os painéis abertos do Query Wiki precisam ser religados.',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'Configure a API Key primeiro',
    errorNoModel: 'Selecione primeiro um modelo — clique em "Buscar modelos" ou insira um Model ID manualmente',
    llmNotReady: 'LLM não está configurado. Vá para Configurações → Karpathy LLM Wiki para configurar seu provedor e passar no teste de conexão.',
    errorFetchFailed: 'Falha: {}',

    // Query Settings
    querySectionTitle: 'Configuração de consulta Wiki',
    // v1.24.0: renomeado de "Histórico máximo de conversa" para
    // "Rodadas de memória de conversa" para maior clareza.
    // 1 = cada turno independente (sem memória entre turnos).
    // A configuração é um menu suspenso, não precisa listar predefinições.
    // v1.24.0: maxConversationHistoryHint era uma chave i18n sem uso;
    // a recomendação foi integrada à descrição.
    maxConversationHistoryName: 'Rodadas de memória de conversa',
    maxConversationHistoryDesc: 'Quantas rodadas de conversa anteriores o LLM vê como memória. 1 = cada turno independente (sem memória entre turnos); valores mais altos permitem ao modelo lembrar turnos anteriores da sessão. Recomendado: 1 para Q&A pontual, 10–50 para pesquisa contínua.',
    numberRangeValidation: 'Insira um número entre 1 e 50',
    numberRangeClamped: 'Valor fora do intervalo (1-500), automaticamente definido como {}',
    // Query Modal UI
    queryModalTitle: 'Consultar Wiki — Consulta conversacional',
    queryModalPlaceholder: 'Insira sua pergunta...',
    queryModalSendButton: 'Enviar',
    queryModalStopButton: 'Parar',
    queryModalSaveButton: 'Salvar na Wiki',
    queryModalClearButton: 'Limpar histórico',
    queryModalHistoryCount: 'Histórico de conversa: {}/{} rodadas',
    queryModalStreaming: 'Transmissão em andamento...',
    queryModalFallbackStreaming: 'Transmissão não suportada, alternando para modo não transmissivo. Aguarde...',
    queryPhaseSearching: 'Analisando índice da Wiki, selecionando páginas relevantes...',
    queryPhaseFoundPages: '{count} página(s) encontrada(s): {pages}',
    queryPhaseLoadingPages: 'Carregando conteúdo das páginas...',
    queryPhaseContextReady: 'Contexto pronto. Gerando resposta...',
    queryPhaseGenerating: 'Gerando... ({time}s decorrido)',
    queryPhaseNonStreaming: 'Modo não transmissivo, gerando resposta... ({time}s decorrido)',
    queryModalErrorPrefix: 'Erro: ',
    queryModalHint: 'Consultas baseadas no conteúdo da Wiki. Clique em "Salvar na Wiki" para extrair conversas valiosas como páginas.',

    // v1.20.0: Resumo do bloco de raciocínio colapsável do Query Wiki
    queryThinkingSummary: 'Processo de raciocínio',
    queryThinkingSteps: 'passos',

    // Error Messages
    errorLLMClientNotInit: 'LLM Client não inicializado. Salve as configurações.',
    errorIngestFailed: 'Falha na ingestão: ',
    errorQueryFailed: 'Falha na consulta: ',
    fileWriteFailed: 'Não foi possível criar ou atualizar o ficheiro: {path}',

    // Success Messages
    ingestSuccess: 'Ingestão bem-sucedida: {} páginas criadas, {} páginas atualizadas',
    querySuccess: 'Consulta concluída',
    lintSuccess: 'Verificação da Wiki concluída',
    lintReadingPages: 'Lendo {count} páginas da Wiki...',
    lintReadingPagesProgress: 'Lendo páginas da Wiki: {current}/{total}...',
    lintScanningLinks: 'Verificando links quebrados...',
    lintScanningLinksProgress: 'Verificando links quebrados: {current}/{total}...',
    lintCheckingDuplicates: 'Verificando páginas duplicadas...',
    lintCheckingDuplicatesProgress: 'Verificando duplicados: lote {current} ...',
    lintFixingPolluted: 'Reparando página contaminada {current}/{total}: {title} → {newTitle}',
    lintModalFixPolluted: '🧹 Reparar páginas contaminadas ({count})',
    lintDuplicateCheckFailed: 'Detecção de duplicatas falhou — consulte o console para detalhes',
    lintDuplicateCheckFailedDetail: 'Verificação de duplicatas falhou em {step}: {error}',
    lintMergeItemFailed: 'Falha na mesclagem: {source} → {target} — {error}',
    lintAliasesMissing: 'Aliases ausentes: {count} página(s) sem aliases',
    lintAliasesSection: 'Páginas sem aliases [{count}]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: 'Completar aliases ({count})',
    lintAliasesFilling: 'Gerando aliases {current}/{total}: {page}',
    lintAliasesFilled: 'Completar aliases concluído. Preenchidas {filled}/{total} páginas.',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: 'Tags fora do vocabulário (detectadas) [{count}]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: 'Falha ao gerar aliases: {page} — {error}',
    lintFixItemFailed: 'Falha na correção: [[{target}]] — {error}',
    lintLinkItemFailed: 'Falha ao linkar: {page} — {error}',
    lintRetrying: 'Tentando novamente ({attempt}/{max}) após erro...',
    lintAnalyzingLLM: 'LLM analisando saúde da Wiki...',
    saveToWikiSuccess: 'Conversa salva na Wiki!',
    querySaveAlreadyExists: 'Aviso: nada foi escrito (o conhecimento já existe na Wiki):',
    saveSummary: '{entities} entidades, {concepts} conceitos, {pages} páginas',
    aliasAdded: 'Alias \'{alias}\' adicionado à página \'{page}\'',

    // Status Messages
    ingestingSources: 'Ingerindo fontes...',
    queryingWiki: 'Consultando Wiki...',
    lintingWiki: 'Verificando Wiki...',
    savingToWiki: 'Salvando conversa na Wiki...',
    clearingHistory: 'Limpando histórico de conversa...',

    // Buttons
    ingestButton: 'Ingerir',
    queryButton: 'Consultar',
    lintButton: 'Verificar',
    cancelButton: 'Cancelar',

    // Links
    karpathyGistLink: 'Gist do LLM Wiki do Karpathy',
    obsidianPluginAPI: 'API de plug-ins do Obsidian',
    anthropicSDK: 'SDK da Anthropic',
    openaiSDK: 'SDK da OpenAI',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'Região AWS',
    bedrockRegionDesc: 'Região do Amazon Bedrock para esta conta. Determina a URL do endpoint bedrock-mantle; não pode ser substituída via baseURL.',
    bedrockRegionHint: 'bedrock-mantle está disponível em 18 regiões; a cobertura de modelos varia conforme a região.',

    // Other
    availableModelsLoading: 'Carregando modelos disponíveis...',
    noModelsAvailable: 'Nenhum modelo disponível',

    // LLM Language Hint
    llmLanguageHint: 'Please answer in Portuguese.',

    // Schema Configuration
    schemaSection: 'Configuração do Schema',
    enableSchemaName: 'Ativar Schema',
    enableSchemaDesc: 'Gerar e injetar schema/config.md em todos os prompts LLM para saída estruturada da Wiki',
    viewSchemaButton: 'Ver / editar Schema',
    regenerateSchemaButton: 'Regenerar Schema padrão',
    schemaRegeneratedNotice: 'Schema padrão regenerado.',
    schemaRegenerateFailed: 'Falha na geração do Schema',

    // Status de inicialização do Wiki
    wikiInitStatusReady: 'Wiki inicializado',
    wikiInitStatusNotReady: 'Wiki não inicializado — será criado automaticamente na primeira ingestão',

    // Wiki Output Language
    wikiLanguageName: 'Idioma de saída da Wiki',
    wikiLanguageDesc: 'Todas as páginas da Wiki, índice, log e respostas de consulta gerados usam este idioma',
    customWikiLanguageOption: 'Personalizado...',
    customWikiLanguageHint: 'Insira um nome de idioma (ex.: Italiano, Árabe). Ele será passado ao LLM como diretiva de idioma de saída.',
    customWikiLanguagePlaceholder: 'Ex.: Italiano',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // Extraction Settings
    extractionSectionTitle: 'Extração',
    extractionGranularityName: 'Granularidade da extração',
    extractionGranularityDesc: 'Controla extrações por arquivo fonte. Maior = mais páginas/tokens API.\nFina: análise profunda. Padrão: notas diárias. Grosseira: visão rápida. Mínima: processamento 100+ arquivos (limita itens por fonte, ~5 — não o detalhe por item). Personalizada: limites próprios (até 500).\nDica: Use Mínima/Grosseira para pastas com muitos arquivos para economizar tempo e custo.',
    extractionGranularityFine: 'Fina — análise profunda (≤100 itens)',
    extractionGranularityStandard: 'Padrão — notas diárias (≤50 itens)',
    extractionGranularityCoarse: 'Grosseira — visão rápida (≤10 itens)',
    extractionGranularityMinimal: 'Mínima — processamento em lote 100+ arquivos (≤5 itens)',
    extractionGranularityCustom: 'Personalizada — Definir seus próprios limites (1~500)',
    customEntityLimitName: 'Limite personalizado de entidades',
    customEntityLimitDesc: 'Número máximo de entidades a extrair por arquivo fonte (1-500)',
    customConceptLimitName: 'Limite personalizado de conceitos',
    customConceptLimitDesc: 'Número máximo de conceitos a extrair por arquivo fonte (1-500)',

    // Issue #85 v2: Vocabulário de tags (entrada por chips, integrado em Configuração Wiki)
    tagVocabularyInlineDesc: 'Vocabulário controlado para tags frontmatter de entity e concept. Tags aninhadas do Obsidian com "/" são preservadas.',
    tagVocabularyModeName: 'Configuração do vocabulário de tags',
    tagVocabularyModeDescDefault: 'Padrão usa tags embutidas: {}. Mude para "Personalizado" para definir seu próprio vocabulário.',
    tagVocabularyModeDescCustom: 'Personalizado: defina abaixo suas próprias tags de entity e concept pela entrada por chips — Enter ou vírgula para adicionar, × para remover.',
    tagVocabularyNotEnforcedHint: 'Apenas uma sugestão de esquema — o LLM ainda pode emitir tipos fora do vocabulário. Execute o Lint para localizar e corrigir essas páginas.',
    tagVocabularyModeDefault: 'Padrão (subtipos embutidos)',
    tagVocabularyModeCustom: 'Personalizado (definido pelo usuário)',
    customEntityTagsName: 'Tags de entidade personalizadas',
    customEntityTagsDesc: 'Enter ou vírgula para adicionar um chip, × para remover. Tags aninhadas com "/" são preservadas.',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'Tags de conceito personalizadas',
    customConceptTagsDesc: 'Enter ou vírgula para adicionar um chip, × para remover. Tags aninhadas com "/" são preservadas.',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: 'Tag duplicada ignorada',

    // Ingestion Acceleration
    accelerationSectionTitle: 'Aceleração da ingestão',
    pageGenerationConcurrencyName: 'Paralelismo LLM',
    pageGenerationConcurrencyDesc: 'Número de chamadas LLM em paralelo durante ingestão e operações de lint. Valores mais altos aceleram o processamento, mas aumentam custos de API e podem acionar limites de taxa.',
    concurrencyValueSingular: 'Concorrência atual: {} (serial — mais seguro)',
    concurrencyValuePlural: 'Concorrência atual: {} (paralelo)',
    batchDelayName: 'Atraso entre lotes (ms)',
    batchDelayDesc: 'Atraso entre lotes paralelos para evitar limitação de taxa da API (100-10000 ms). Atual: {}ms. Aumente se observar erros 429.',

    // Auto Maintenance
    autoMaintainSection: 'Manutenção automática',
    autoMaintainBetaBadge: 'BETA — Recurso experimental. Pode apresentar problemas. Recomendado apenas para usuários avançados.',
    autoWatchName: 'Pastas monitoradas',
    autoWatchDesc: 'Detectar automaticamente arquivos .md novos ou alterados nas pastas monitoradas e notificar ou ingerir automaticamente',
    watchedFoldersName: 'Pastas monitoradas',
    watchedFoldersDesc: 'Pastas a monitorar para novo conteúdo. Clique em "Adicionar pasta" para selecionar no seu vault.',
    addWatchedFolderButton: 'Adicionar pasta',
    removeWatchedFolderButton: 'Remover',
    webClipperPresetName: 'Monitorar Clippings (Web Clipper)',
    webClipperPresetDesc: 'Adicionar a pasta Clippings/ usada pelo Obsidian Web Clipper à lista de monitoramento. Seus recortes web serão ingeridos automaticamente na Wiki.',
    noWatchedFoldersHint: 'Nenhuma pasta configurada. Adicione uma pasta ou ative o preset Clippings.',
    autoWatchModeName: 'Modo de monitoramento',
    autoWatchModeDesc: '"Somente notificar" exibe um aviso. "Ingerir automaticamente" processa silenciosamente.',
    watchModeNotify: 'Somente notificar',
    watchModeAuto: 'Ingerir automaticamente',
    autoWatchDebounceName: 'Atraso de debounce (segundos)',
    autoWatchDebounceDesc: 'Tempo de espera antes de acionar a ingestão após alteração de arquivo (1-60 segundos)',
    periodicLintName: 'Verificação periódica',
    periodicLintDesc: 'Executar verificação LLM agendada, somente quando arquivos fonte foram alterados desde a última verificação',
    periodicLintOff: 'Desativado',
    periodicLintDaily: 'Diariamente',
    periodicLintWeekly: 'Semanalmente',
    periodicLintMonthly: 'Mensalmente',
    autoSmartFixName: 'Correção inteligente automática',
    autoSmartFixDesc: 'Quando o lint for executado, aplica automaticamente todas as correções (Smart Fix All) sem exibir o modal de relatório. O resumo das correções ainda é exibido ao concluir.',
    autoSmartFixNotice: 'Correção inteligente automática: aplicando todas as correções...',
    autoIngestLevelName: 'Notificação de ingestão automática',
    autoIngestLevelDesc: 'Como notificar quando a ingestão automática for concluída. "Aviso" (transitório) não bloqueia. "Modal" abre o relatório completo. Desativado quando o Modo Watch é "Apenas notificar".',
    autoIngestLevelNotice: 'Aviso (não bloqueante)',
    autoIngestLevelModal: 'Modal (relatório completo)',
    startupCheckName: 'Executar correções rápidas na inicialização',
    startupCheckDesc: 'Corrige automaticamente problemas de formato de baixo nível (campo sources, wikilinks duplamente aninhados) ao carregar o plug-in. Verifica a estrutura de pastas do Wiki. Ativado por padrão.',
    suggestSchemaCommand: 'Sugerir atualizações de Schema',
    autoMaintainCostWarning: '⚠️ Aviso de custo: Recursos de manutenção automática consomem tokens de API. "Ingerir automaticamente" aciona chamadas LLM em cada alteração de arquivo fonte. "Verificação periódica" executa verificações de saúde LLM agendadas (somente quando alterações são detectadas). Configure com cuidado para evitar cobranças inesperadas.',

    // Notices
    startupCheckSummary: 'A Wiki tem {pages} páginas ({entities} entidades, {concepts} conceitos, {sources} fontes)',
    watcherActiveNotice: 'Wiki: monitor de arquivos ativo — monitorando pastas selecionadas',
    watchIngestNotice: 'Wiki: {count} arquivo(s) alterado(s) em sources/. Execute "Ingerir fontes" para processar.',
    autoIngestRunning: 'Ingerindo automaticamente {count} arquivo(s) alterado(s)...',
    autoIngestComplete: 'Ingestão automática concluída: {success} bem-sucedido(s), {fail} falha(s)',
    scheduledLintRunning: 'Executando verificação agendada da Wiki...',
    wikiLintStats: 'Verificação da Wiki: {pages} páginas ({entities} entidades, {concepts} conceitos, {sources} fontes)',
    wikiHealthStats: 'Saúde da Wiki: {pages} páginas ({entities} entidades, {concepts} conceitos, {sources} fontes){indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Correções rápidas Wiki concluídas',
    startupCheckStructureLabel: 'Estrutura Wiki',
    startupCheckStructureOk: 'completa',
    startupCheckStructureMissing: 'incompleta — será criada automaticamente na primeira ingestão',
    startupCheckSourcesLabel: 'Sources normalizados',
    startupCheckSourcesClean: 'já limpo',
    startupCheckSourcesCleaned: '{files} arquivo(s), {entries} entrada(s) limpa(s)',
    startupCheckIncompleteClean: 'páginas incompletas: nenhuma',
    startupCheckIncompleteArchived: 'páginas incompletas: {count} arquivada(s) (recuperável de .trash)',
    startupCheckDisableHint: 'Para desativar: Configurações → Manutenção automática → Executar correções rápidas na inicialização',
    lintWikiStart: 'Iniciando verificação da Wiki...',
    lintWikiComplete: 'Verificação da Wiki concluída',
    lintWikiFailed: 'Verificação da Wiki falhou',
    analyzingSchema: 'Analisando Wiki e gerando sugestões de Schema...',
    schemaSuggestionGenerated: 'Sugestões de Schema geradas. Consulte wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: 'Nenhuma atualização de Schema necessária.',
    schemaSuggestionFailed: 'Falha ao gerar sugestões de Schema',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Pré-visualização de atualização do Schema',
    schemaDiffSummary: '+{add} / -{del} linhas',
    schemaDiffRegenerateLabel: 'Refinar a sugestão (opcional):',
    schemaDiffRegenerateBtn: 'Regenerar',
    schemaDiffOpenFileBtn: 'Abrir arquivo',
    schemaDiffApplyBtn: 'Aplicar',
    schemaDiffApplied: 'Schema atualizado. Backup: {path}',
    schemaDiffEmptyTitle: 'LLM não recomenda alterações',
    schemaDiffFailed: 'Falha ao aplicar o Schema: {reason}',
    schemaDiffRestoreHint: 'Backup salvo em {path}. Para restaurar, renomeie esse arquivo para "wiki/schema/config.md" no explorador de arquivos. Os 3 backups mais recentes são mantidos.',
    schemaRegenerateNoBody: 'Regeneração bem-sucedida mas o LLM não retornou um novo Schema.',
    schemaNotFoundNotice: 'Arquivo de Schema não encontrado. Ative o Schema para criá-lo.',
    selectFolderNoMdFiles: 'Nenhum arquivo Markdown na pasta: {path}',
    batchIngestSkipNotice: 'Ignorando {skipped}/{total} arquivos já ingeridos. Ingerindo {new} novos arquivos...',
    batchIngestAllIngested: 'Todos os {total} arquivos desta pasta já foram ingeridos.',
    batchIngestStarting: 'Ingerindo {count} arquivo(s) de "{folder}" — isso pode levar alguns minutos. Um relatório aparecerá ao concluir.',
    batchIngestComplete: 'Ingestão em lote concluída: {success}/{total} bem-sucedido(s), {fail} falha(s)',
    batchIngestFailedFiles: 'Arquivos com falha:',
    historyTruncated: 'Histórico truncado para as últimas {max} rodadas',
    historyCleared: 'Histórico limpo',

    // User Feedback Loop
    reviewedPagePreserved: 'Preservando conteúdo revisado pelo usuário para: {}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: 'Salvar na Wiki?',
    querySuggestSaveDesc: 'Esta conversa contém conhecimento valioso. Deseja salvar na sua Wiki?',
    querySuggestSaveYes: 'Salvar',
    querySuggestSaveNo: 'Dispensar',

    // Ingestion Report
    ingestReportElapsedTime: 'Tempo decorrido',
    ingestReportSkippedFiles: 'Ignorados (já ingeridos)',
    ingestReportRejectedFiles: 'Ignorados',
    rejectionReasonEmpty: 'vazio',
    rejectionReasonType: 'tipo não suportado',
    rejectionReasonDuplicate: 'conteúdo duplicado',
    rejectionReasonPdfUnsupported: 'o provedor não consegue ler o PDF',
    rejectionReasonMineruPageLimit: 'excede o limite de páginas do MinerU',
    rejectionReasonMineruSizeLimit: 'excede o limite de tamanho do MinerU',
    sourceRejectedEmpty: '⏭️ "{filename}" não tem conteúdo para ingerir — ignorado. Notas vazias ou apenas com frontmatter não criam páginas wiki.',
    sourceRejectedType: '⏭️ "{filename}" não é um tipo de arquivo compatível — ignorado. Apenas notas de texto (.md, .txt, etc.) podem ser ingeridas.',
    sourceRejectedDuplicate: '⏭️ "{filename}" ignorado — seu conteúdo já está no wiki.',
    pdfReadingInProgress: 'Lendo PDF: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ «{filename}» ignorado — o seu provedor ou modelo atual não aceita PDF. Troque de provedor ou ative «Forçar suporte a PDF» em Settings → LLM Configuration → Advanced e tente novamente, ou troque o backend de conversão Markdown para MinerU (também aceita imagens e documentos Office).',
    clearPdfCacheCommand: 'Limpar cache de conversão PDF',
    pdfCacheCleared: 'Cache de PDF limpo ({count} entradas removidas).',
    // v1.25.0 PR3: Advanced PDF settings
    forcePdfSupportName: 'Forçar suporte a PDF',
    forcePdfSupportDesc: 'Desativado por padrão. Ative esta opção se o seu provedor não está na lista nativa, mas mesmo assim consegue processar PDFs. Ao ativar, o PDF será enviado ao seu provedor atual; se for rejeitado, você verá um aviso. Provedores PDF nativos (Anthropic / OpenAI / Bedrock) não precisam desta opção.',
    writePdfMarkdownToVaultName: 'Gravar o Markdown convertido no Vault',
    markdownConversionBackendName: 'Backend de conversão Markdown',
    markdownConversionBackendDesc: 'Use o suporte nativo a PDF do seu provedor (escopo limitado, nem todo provedor/modelo processa PDF, consome tokens LLM). MinerU é um serviço online — rápido, gratuito até a cota diária, aceita PDF/imagens/Office — mas requer um token de API (defina no campo abaixo).',
    markdownConversionBackendNative: 'Suporte a PDF/imagens do provedor',
    markdownConversionBackendMineru: 'API online do MinerU',
    mineruApiBaseUrlName: 'URL base da API MinerU',
    mineruApiBaseUrlDesc: 'URL base para a API MinerU. O padrão é https://mineru.net/api/v4. Configure uma URL personalizada se usar um proxy, espelho ou implantação auto-hospedada.',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'Token da API do MinerU',
    mineruApiTokenDesc: 'Obtenha seu token em https://mineru.net/apiManage/token. MinerU aceita arquivos de até 200 MB e até 200 páginas.',
    mineruApiTokenPlaceholder: 'Cole o token da API do MinerU',
    mineruUploadingInProgress: 'Enviando PDF ao MinerU: {filename}',
    mineruWaitingInProgress: 'Aguardando a conversão do MinerU: {filename}',
    mineruDownloadingInProgress: 'Baixando o resultado do MinerU: {filename}',
    markdownConversionComplete: 'Conversão concluída: {filename}',
    markdownConversionCompleteSaved: 'Conversão concluída — gravado em {path}: {filename}',
    mineruPageLimitRejected: '{filename} excede o limite de {limit} páginas do MinerU — divida o arquivo e tente novamente',
    mineruSizeLimitRejected: '{filename} excede o limite de tamanho de {limit} MB do MinerU',
    writePdfMarkdownToVaultDesc: 'Desativado por padrão. Quando ativo, o resultado de cada conversão de PDF é gravado em um arquivo “<basename>.pdf.md” ao lado do PDF de origem. Quando desativado (arquitetura somente em cache), os resultados vivem apenas no cache do plugin e não deixam artefatos no seu Vault.',

    ingestRejectedSummary: '{count} arquivo(s) ignorado(s) (vazio, duplicado ou tipo não compatível).',
    reingestConfirmTitle: 'Reingerir este arquivo?',
    reingestConfirmBody: 'O conteúdo de "{filename}" já está no wiki. Reingerir mesmo assim?',
    reingestConfirmYes: 'Reingerir',
    reingestConfirmNo: 'Ignorar',
    lintDedupIncludeSourcesName: 'Incluir fontes na deduplicação',
    lintDedupIncludeSourcesDesc: 'Ativado por padrão. Quando ativado, fontes com corpos idênticos são sinalizadas como duplicatas durante o lint. Desative se o seu corpus de fontes gerar falsos positivos.',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: 'Ignorar candidatos que a fonte apenas menciona',
    skipMentionOnlyCandidatesDesc: 'Desativado por padrão. Quando ativado, uma entidade ou conceito extraído cujo nome não aparece no texto corrido da nota — ausente, ou apenas entre parênteses, enumerações ou itens de lista curtos — não recebe página nem mais chamadas ao modelo, e é removido das listas de relacionados dos outros candidatos. Funciona para idiomas de wiki com perfil de limites de palavra (alemão medido; inglês, francês, espanhol, português, neerlandês estimados); para outros idiomas a ingestão informa uma vez que não pode ser aplicada. Deixe desativado em vaults tipo glossário ou notas em tópicos onde cada termo citado deva virar página.',
    createStubsForUnresolvableLinksName: 'Criar páginas de stub para links não resolvidos',
    createStubsForUnresolvableLinksDesc: 'Ativado por padrão. Quando «Corrigir links quebrados» não consegue resolver um link para nenhuma página existente, escreve uma página de marcador vazia e reaponta o link para ela — nunca preenchida pelo LLM. Desative para deixar esses links intactos: continuam visíveis em cada relatório até que uma fonte real os defina.',
    lintDedupSectionHeading: 'Deduplicação',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): texto genérico,
    // reutilizável para todas as rotas de negócio LLM. {count} é o
    // número de lotes que precisaram de nova tentativa. Não dizemos
    // "Lint concluído" — a nova tentativa recupera apenas este lote.
    llmRetryRecoveredToast: 'Tarefa LLM: {count} lote(s) precisaram de nova tentativa devido a uma resposta transitória do provedor. Veja o console para detalhes. Se isso se repetir, reduza Page Generation Concurrency nas configurações do provedor.',
    ingestReportFailedGuidance: 'Estes itens não puderam ser criados automaticamente. Você pode criar as páginas manualmente ou reduzir a granularidade da extração e reingerir o arquivo fonte.',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: 'Ingerir fonte individual',
    cmdIngestFolder: 'Ingerir de pasta',
    cmdIngestMultipleFiles: 'Ingerir vários ficheiros',
    cmdQueryWiki: 'Consultar Wiki',
    cmdLintWiki: 'Verificar Wiki',
    cmdRegenerateIndex: 'Regenerar índice',
    cmdSuggestSchema: 'Sugerir atualizações de Schema',
    cmdCancelIngestion: 'Cancelar ingestão atual',
    cmdIngestActiveFile: 'Ingerir arquivo atual',
    cmdViewHistory: 'Ver histórico de ingestão',
    noActiveFile: 'Nenhum arquivo aberto',
    mdOnlyFile: 'Apenas arquivos Markdown podem ser ingeridos',
    ingestSingleFileStart: 'Ingerindo: {filename}',
    ingestCheckingExisting: 'Verificando arquivos já ingeridos...',
    lintFindingsSummary: '{total} descobertas',

    // Ingestion status bar
    ingestionStatusBar: 'Ingerindo... clique para cancelar',
    lintStatusBar: 'Verificando... clique para cancelar',
    ingestStatusAnalyzing: 'Ingerindo… (clique para cancelar)',
    lintStatusAnalyzing: 'Verificando… (clique para cancelar)',
    ingestStageAnalyze: 'Analisando a fonte',
    ingestStageSummary: 'Gerando o resumo',
    ingestStageEntity: 'Criando a entidade',
    ingestStageConcept: 'Criando o conceito',
    ingestStageRetry: 'Tentando novamente a página com falha',
    ingestStageSave: 'Salvando páginas',
    ingestStageIndex: 'Gerando o índice',
    pdfStageReading: 'Lendo o PDF',
    pdfStageConverting: 'Convertendo o PDF',
    pdfStageSidecar: 'Escrevendo o arquivo secundário',
    lintStagePrep: 'Lendo páginas',
    lintStageProgrammatic: 'Verificando links',
    lintStageAnalyzing: 'Executando análise LLM',
    lintStageDedup: 'Detectando duplicatas',
    lintStageContradiction: 'Detectando contradições',
    ingestionCancelling: 'Cancelando — irá parar após o lote atual',
    ingestionCancelled: 'Ingestão cancelada',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: 'Analisando lote 1/{total}...',
    ingestBatchProgress: 'Analisando lote {current}/{total} ({entities} entidades, {concepts} conceitos até agora)...',
    ingestBatchProcessed: 'Lote {current} analisado, processando...',
    ingestAnalyzing: 'Analisando: {filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] Criando resumo...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}: {name}',
    ingestUpdating: '[{step}/{totalSteps}] Atualizando: {name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] Gerando índice...',
    ingestItemTypeEntity: 'Entidade',
    ingestItemTypeConcept: 'Conceito',
    convAnalyzing: 'Analisando conversa...',
    convCheckingExisting: 'Verificando conhecimento existente...',
    convAlreadyExists: 'Este conhecimento já existe no Wiki',
    convCreatingSummary: 'Criando página de resumo...',
    convGeneratingSummary: 'Gerando página de resumo...',
    convSavingEntity: 'Salvando entidade: {name}',
    convSavingConcept: 'Salvando conceito: {name}',
    convGeneratingIndex: 'Gerando índice...',

    // Lint Report
    lintReportTitle: 'Relatório de verificação da Wiki',
    lintReportSummary: 'Visão geral do wiki: {total} páginas no total, {aliasesMissing} sem aliases, {duplicates} duplicados, {deadLinks} links quebrados ({deadLinkFromDup} envolvem duplicados), {orphans} órfãs ({orphanFromDup} são duplicados), {emptyPages} vazias, {ungroundedQuotes} citações sem fonte, {tagViolations} tags fora do vocabulário. Lint: {elapsedSeconds}s',

    // Advanced LLM Settings (Issues #99 / #128)
    // v1.26.0 (#382 item 2): nome alterado de «Configuração de parâmetros
    // avançados» para «Parâmetros LLM avançados» — restrito à amostragem LLM,
    // para distingui-lo do painel genérico «Configurações avançadas» abaixo.
    advancedLlmModeName: 'Parâmetros LLM avançados',
    advancedLlmModeDesc: 'O modo padrão segue as recomendações do seu provedor. Mude para Personalizado apenas se tiver uma razão específica para substituir (por exemplo, um modelo específico precisa de temperatura fixa, ou você quer suprimir a saída de raciocínio).',
    advancedSettingsDefault: 'Padrão (seguir o provedor)',
    advancedSettingsCustom: 'Personalizado (substituir o provedor)',
    // v1.26.0 (#382 item 2): painel «Configurações avançadas» abaixo — o local
    // genérico para todas as configurações avançadas que não são parâmetros LLM.
    advancedSettingsSection: 'Configurações avançadas',
    showAdvancedSettingsName: 'Mostrar configurações avançadas',
    showAdvancedSettingsDesc: 'Ative para mostrar as configurações avançadas abaixo. Desativar oculta-as e redefine-as para os valores padrão.',
    disableThinkingName: 'Desabilitar pensamento',
    disableThinkingDesc: 'Desativa a cadeia de pensamento/raciocínio na resposta do modelo. Desativado por predefinição — o modelo decide se mostra raciocínio, o que geralmente dá a melhor resposta. Ative apenas se o seu provedor inserir texto de raciocínio bruto na resposta e você quiser uma resposta limpa.',
    taskPoliciesPlaceholder: 'Exemplo: extract=text:off',
    taskPoliciesName: 'Modo de saída e raciocínio por etapa',
    taskPoliciesDesc: 'Uma entrada por etapa do pipeline, `etapa=modo:raciocinio`, separadas por vírgulas — p. ex. `extract=text:off`. Modos: `-` (inalterado), `schema`, `json`, `text`; raciocínio: `-`, `off`, `on`, `low`, `medium`, `high`. Os nomes de etapa incluem extract, extract-retry, lemma-classify, merge-triage, source-stance, dedup, page-generate, related-page, lint-dedup (um nome mal escrito não corresponde a nada). Deixe em branco para a base integrada (extração em modo texto). Uma entrada ilegível não é guardada.',
    // Issue #137: Avisos de compatibilidade (breves; sem lista de provedores)
    extractionTemperatureName: 'Temperatura de extração',
    extractionTemperatureDesc: 'Controla se o modelo é mais conservador ou criativo ao escrever páginas entity/concept. Valores baixos = mais determinístico e fiel; valores altos = mais variado. A maioria dos usuários deixa vazio.',
    chatTemperatureName: 'Temperatura de consulta',
    chatTemperatureDesc: 'Mesmo conceito que a temperatura de extração, mas só afeta como o Query Wiki responde a perguntas. Valores baixos = respostas mais literais; valores altos = respostas mais conversacionais. A maioria dos usuários deixa vazio.',
    repetitionPenaltyName: 'Penalidade de repetição',
    repetitionPenaltyDesc: 'Impede o modelo de repetir as mesmas palavras ou frases. Valores mais altos reduzem a repetição. Apenas alguns provedores de modelos locais (Ollama, LM Studio, llama.cpp) aceitam este parâmetro; provedores em nuvem ignoram-no silenciosamente. A maioria dos usuários deixa vazio. Um valor acima de 1,0 pode causar erros na saída do LLM durante a extração em modelos locais pequenos — se uma execução falhar, reduza ou limpe este valor.',
    repetitionPenaltyErrorHint: 'Nota: uma penalidade de repetição personalizada de {value} está definida. Valores acima de 1,0 podem quebrar a extração com restrição gramatical em modelos locais pequenos — reduza ou limpe esta configuração e tente novamente.',
    temperaturePlaceholder: 'deixar vazio = padrão do provedor',
    // v1.26.0 (#382 item 2): Limiares de detecção de duplicados
    // (somente modo avançado personalizado).
    lintDedupJaccardLinkThresholdName: 'Similaridade de links duplicados',
    lintDedupJaccardLinkThresholdDesc: 'Intervalo 0–1 (padrão 0,4). Duas páginas são sinalizadas como duplicadas quando a proporção de links wiki que compartilham em relação aos links totais atinge pelo menos este valor. Mais baixo → mais quase-duplicados são captados (incluindo páginas que apenas apontam para o mesmo hub); mais alto → apenas páginas que apontam para um conjunto quase idêntico são sinalizadas. Aumente este valor se vir falsos positivos entre páginas não relacionadas que simplesmente apontam para o mesmo hub. Deixe em branco para usar o padrão.',
    lintDedupJaccardBodyGateName: 'Similaridade mínima do corpo',
    lintDedupJaccardBodyGateDesc: 'Intervalo 0–1 (padrão 0,2). Mesmo que duas páginas compartilhem links wiki, elas só são sinalizadas como duplicadas se a similaridade dos seus textos atingir pelo menos este valor. Mais baixo → mais candidatos passam para a verificação do LLM; mais alto → apenas corpos quase idênticos são sinalizados. Aumente este valor se o LLM estiver revisando páginas que claramente não são duplicadas. Deixe em branco para usar o padrão.',
    lintDedupBigramThresholdName: 'Similaridade de títulos',
    lintDedupBigramThresholdDesc: 'Intervalo 0–1 (padrão 0,4). Duas páginas são sinalizadas como duplicadas quando os caracteres dos seus títulos (ou aliases) coincidem pelo menos nesta proporção. Mais baixo → variantes ortográficas, erros de digitação e traduções do mesmo conceito são captados; mais alto → apenas títulos quase idênticos são sinalizados. Aumente este valor se o LLM revisar páginas com nomes muito diferentes que não são realmente duplicadas. Deixe em branco para usar o padrão.',
    lintDeadLinkSection: 'Links quebrados (detectados) [{count}]',
    lintEmptyPageSection: 'Páginas vazias (detectadas) [{count}]',
    lintOrphanSection: 'Páginas órfãs (detectadas) [{count}]',
    lintContradictionSection: 'Contradições (detectadas)',
    lintDuplicateSection: 'Páginas duplicadas (detectadas)',
    lintNoIssuesFound: 'Nenhuma duplicata, link quebrado, página vazia, página órfã ou citação sem fonte detectada.',
    lintSourceDriftSection: 'Notas de origem alteradas desde a ingestão [{count}]',
    lintSourceDriftItem: '- [[{page}]] — a nota de origem [[{note}]] foi editada após a ingestão; a página pode estar desatualizada',
    lintContradictionMarkerSection: 'Páginas marcadas com contradições (triagem de mesclagem) [{count}]',
    lintContradictionMarkerItem: '- [[{page}]] — fonte(s) em conflito: {sources}; após a revisão, remova o marcador contradictions:',
    lintQuoteGroundingSection: 'Citações sem fonte (detectadas) [{count}]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: "{quote}"',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (página inexistente){dupFlag}',
    lintDeadLinkMore: '- ... mais {count} links quebrados',
    lintEmptyPageItem: '- [[{page}]] — menos de 50 caracteres de conteúdo substantivo',
    lintOrphanItem: '- [[{page}]] — nenhuma outra página da Wiki linka aqui{dupFlag}',
    lintPollutedSection: 'Páginas poluídas (detectadas) [{count}]',
    lintPollutedItem: '- [[{page}]] → deveria ser "{clean}"',
    lintSourcesNormalizedSection: 'Sources normalizadas (auto-corrigidas) [{files} arquivos / {entries} entradas]',
    lintSourcesNormalizedItem: 'Limpou {entries} entradas de sources poluídas em {files} arquivo(s) (caminhos externos, extensões .md, pipes de alias removidos e deduplicados).',
    lintDuplicateItem: '- [[{target}]] e [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ envolve página duplicada)',
    lintOrphanIsDuplicate: ' (⚠️ página duplicada)',
    lintHubLinkDensitySection: 'Problemas de densidade de links em hubs (Issue #157 / #175) [{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} entradas, {relatedCount} links relacionados, distintividade {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ remover',
    lintHubLinkDensityReview: '🔍 revisar',
    lintHubLinkDensityKeep: '✅ manter',
    lintHubLinkDensitySummary: 'Resumo: {strip} página(s) recomendada(s) para remoção, {review} página(s) recomendada(s) para revisão.',
    lintHubLinkDensityNoRelated: ' (seção ## Related não encontrada)',
    lintContradictionOpen: 'Contradições abertas: {count}',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: 'Detectado',

    // Lint Analysis Prompt

    // Lint Fix Progress
    lintFixProgress: 'Corrigindo {current}/{total}: [[{target}]]',
    lintFixDeadComplete: 'Correção de links quebrados concluída. {fixed}/{total} itens corrigidos.',
    lintFillProgress: 'Expandindo {current}/{total}: {page}',
    lintFillComplete: 'Expansão de páginas concluída. {filled}/{total} páginas preenchidas.',
    lintDeleteCompleted: '{count} stubs vazios excluídos',
    lintDeleteFailed: 'Falha ao excluir {failed}/{total} stubs vazios (ver console)',
    lintFillFailed: 'Falha ao expandir: {page} — {error}',
    lintLinkProgress: 'Linkando {current}/{total}: {page}',
    lintLinkComplete: 'Links de páginas órfãs concluídos. {linked} páginas linkadas.',
    lintFixNoAction: 'Nenhuma ação realizada (sem client)',
    lintFixIndexUpdated: 'Índice e log da Wiki atualizados.',
    lintPollutedFixed: 'Páginas poluídas corrigidas: {fixed}/{total}. Índice regenerado.',
    regenerateIndexCompleted: 'Índice regenerado',
    operationFailed: 'Falha: ',
    lintFixAllComplete: 'Todas as correções concluídas. Consulte o log para detalhes.',
    lintFixAllNoChanges: 'Nenhuma alteração — todas as fases reportaram 0 correções. Detalhes em wiki/log.md.',
    lintFixPhasesLabel: 'fases modificadas',

    // Lint Report Modal
    lintModalActionsTitle: 'Sugestões de correção (requer tokens LLM):',
    lintLogReference: 'Relatório completo salvo em log.md',
    lintModalFixDeadLinks: 'Corrigir links quebrados ({count})',
    lintModalExpandEmpty: 'Expandir páginas vazias ({count})',
    lintModalDeleteEmpty: 'Excluir stubs vazios ({count})',
    lintModalLinkOrphans: 'Linkar páginas órfãs ({count})',
    lintModalAnalyzeSchema: 'Analisar Schema',
    lintModalMergeDuplicates: 'Mesclar duplicatas ({count})',
    lintModalFixAll: 'Correção inteligente de tudo ({count} problemas)',
    lintMergeProgress: 'Mesclando {current}/{total}: {source} → {target}',
    lintMergeComplete: 'Mesclagem de duplicatas concluída. {merged}/{total} pares mesclados.',

    // Ingest Report Modal
    ingestReportTitle: 'Relatório de ingestão',
    ingestReportSourceFile: 'Arquivo fonte',
    ingestReportCreated: 'Criadas',
    ingestReportUpdated: 'Atualizadas',
    ingestReportContradictions: 'Contradições encontradas',
    ingestReportFailedTitle: 'Falha ao ingerir',
    ingestReportErrorDetail: 'Detalhe do erro',
    ingestReportClose: 'Fechar',
    ingestReportCreatedPages: 'Páginas criadas: {count}',
    ingestReportUpdatedPages: 'Páginas atualizadas: {count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki Registro de operações',
    logHeaderSubtitle: 'Cada ingestão, execução de lint e operação de manutenção é registrada aqui automaticamente. Para uma melhor visualização, use o painel **Histórico de operações**:',
    logHeaderShortcut: 'Cmd+P → "Ver histórico de operações"',
    logHeaderSettingsShortcut: 'Ou em Configurações → Manutenção automática → Histórico de operações',
    ingestionCreatedPages: '{count} página(s) criada(s)',
    ingestionUpdatedPages: '{count} página(s) atualizada(s)',
    ingestionNoticeHistoryHint: 'Ver histórico de operações para mais detalhes',
    ingestReportEntitiesCount: '{count} entidades',
    ingestReportConceptsCount: '{count} conceitos',
    ingestReportContradictionsFound: 'Contradições encontradas: {count}',
    ingestReportEntityType: 'Entidade',
    ingestReportConceptType: 'Conceito',
    timeMinutes: 'min',
    timeSeconds: 's',

    // Avisos de limite de taxa
    rateLimitDetected: '⚠️ Limite de taxa detectado: {count} página(s) falharam com erros 429. Sugestões: (1) Reduzir concorrência para {suggestedConcurrency} ou 1 (serial), (2) Aumentar atraso entre lotes para {suggestedDelay}ms, (3) Mudar para um provedor com limites de taxa mais altos.',
    rateLimitDetectedShort: '⚠️ Limite de taxa atingido — considere reduzir a concorrência ou aumentar o atraso entre lotes em Configurações → Aceleração de ingestão.',

    longSourceNotice: '📄 "{filename}" tem {lines} linhas ({size}). Textos longos requerem extração iterativa em lotes — o LLM lê o documento completo em múltiplas passagens. Isso pode levar vários minutos. Por favor, tenha paciência.',
    longSourceNoticeShort: '📄 Arquivo grande detectado ({lines} linhas). A ingestão pode demorar um pouco.',

    // Painel de Histórico de Ingestão (#122) — textos da UI
    historyButton: 'Histórico de operações',
    historyButtonDesc: 'Ver ingestões recentes, relatórios de Lint e outras alterações do seu Wiki',
    historyButtonOpen: 'Ver histórico',
    historyModalTitle: 'Histórico de operações',
    historyModalSubtitle: 'Alterações recentes do seu LLM-Wiki',
    historyEmpty: 'Nenhuma operação registrada ainda. Ingira uma nota ou execute Lint para preencher esta lista.',
    historyReadError: 'Não foi possível ler o registro de operações: {error}',
    historyEntryKindIngest: 'Ingestão',
    historyEntryKindMaintenance: 'Manutenção',
    historyEntryKindFix: 'Correção',
    historyEntryKindOther: 'Outro',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'Origem: {source}',
    historyEntrySourceUnknown: 'Ingestão sem título',
    historyEntryCreatedLabel: 'Criadas',
    historyEntryUpdatedLabel: 'Atualizadas',
    historyEntryCreatedCount: '{count} criadas',
    historyEntryUpdatedCount: '{count} atualizadas',
    historyEntryNoChanges: 'Sem alterações em páginas',
    historyEntryContradictions: '⚠️ {count} contradição(ões)',
    historyEntrySectionCreated: 'Páginas criadas',
    historyEntrySectionUpdated: 'Páginas atualizadas',
    historyEntrySectionContradictions: 'Contradições',
    historyEntrySectionDetails: 'Detalhes',
    historyEntryOpenPage: 'Abrir',
    historyEntryDetailsNoContradictions: 'Nenhuma contradição encontrada',
    historySearchPlaceholder: '🔍 Buscar por título de origem ou caminho de página…',
    historyFilterAll: 'Todas',
    historyFilterIngest: 'Apenas ingestão',
    historyFilterMaintenance: 'Apenas manutenção',
    historyFilterFix: 'Apenas correções',
    historyFilterContradictions: '⚠️ Com contradições',
    historyRefreshButton: '⟳ Atualizar',
    historyExpandDay: 'Clique para expandir',
    historyCollapseDay: 'Clique para recolher',
    historyShowMore: 'Mostrar {count} entradas mais antigas',
    historyNoMatch: 'Nenhuma operação corresponde à sua busca/filtro.',
    historyCloseButton: 'Fechar',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'Achados do relatório',
    historyKpiPages: 'Páginas',
    historyKpiDeadLinks: 'Links mortos',
    historyKpiOrphans: 'Órfãs',
    historyKpiEmpty: 'Vazias',
    historyKpiDuplicates: 'Duplicadas',
    historyKpiTagViolations: 'Tags',
    historyKpiUnsourced: 'Sem fonte',
    historyKpiDuration: 'Tempo Lint',
    historyKpiDurationSec: '{seconds}s',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'Links mortos ({count})',
    historySectionTagViolations: 'Tags ({count})',
    historySectionOrphans: 'Páginas órfãs ({count})',
    historySectionEmptyPages: 'Páginas vazias ({count})',
    historySectionLlmAnalysis: 'Análise LLM ({count})',
    historyDeadLinkSource: 'Origem',
    historyDeadLinkTarget: 'Faltando',
    historyOpenInLog: 'Abrir em log.md',
    historyShowMoreItems: 'Mostrar mais {count}',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ igual',
    historyChipContradiction: 'Contradição',
    historyChipOutdated: 'Desatualizado',
    historyChipMissing: 'Faltando',
    historyChipStructure: 'Estrutura',
    historySeverityHigh: 'Alta',
    historySeverityMedium: 'Média',
    historySeverityLow: 'Baixa',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Seu Wiki tem {dead} link(s) morto(s), {orphans} página(s) órfã(s) e {tags} problema(s) de tag. Última Lint: {duration}.',
    historyGlobalInsightClean: 'Seu Wiki está limpo — sem links mortos, páginas órfãs ou problemas de tag.',
    historyGlobalInsightNoData: 'Sem relatórios de manutenção ainda — execute Lint.',
    historyModalHeaderTitle: 'Histórico de operações',
    historyModalSubtitleWithCount: 'Alterações recentes do seu LLM-Wiki · {count} entradas',
    historyTimeRangeAll: 'Todo o período',
    historyTimeRange1d: 'Último dia',
    historyTimeRange3d: 'Últimos 3 dias',
    historyTimeRange1w: 'Última semana',
    historyTimeRange1m: 'Último mês',
    historyIngestTotal: 'Total de páginas',
    historyIngestByType: 'Por tipo',
    historyIngestSource: 'Arquivo de origem',
    historyIngestNoTimestamp: 'Sem carimbo de tempo',
    historyIngestFirstTime: 'Primeira ingestão',
    historyIngestLatestTime: 'Última ingestão',
    historyTimeRangeCustom: 'Intervalo personalizado',
    historyCustomRangeFrom: 'De',
    historyCustomRangeTo: 'Até',
    historyCustomRangeApply: 'Aplicar',
    historyCustomRangeClear: 'Limpar',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki: o vault está vazio. Crie sua primeira nota-fonte e execute Ingest para começar.',
    welcomeNoteTierBNotice: 'Karpathy Wiki: nota Welcome criada. Abra-a para declarar seus domínios e escolher 2-3 notas-fonte para semear o grafo de links.',
    welcomeNoteRecreateCommand: 'Recriar nota Welcome do Wiki',
    welcomeNoteRecreateCommandTooltip: 'Recria a nota Welcome em <wikiFolder>/Welcome.md com os seeds de domínio atuais e o teste de configuração LLM. O arquivo existente é sobrescrito.',
    welcomeNoteSettingsToggle: 'Criar nota Welcome do Wiki no primeiro arranque',
    welcomeNoteSettingsToggleDesc: 'Na primeira execução (quando a pasta wiki está vazia), cria uma nota de introdução de uma página em <wikiFolder>/Welcome.md. Explica o que é o LLM-Wiki, convida-o a declarar o seu foco de domínio, e guia-o na ingestão das primeiras 2-3 notas fonte. A nota é escrita em inglês por predefinição, ou no seu idioma wiki se o LLM estiver configurado. Desative se já conhece o plugin e não quer a nota de introdução.',
    welcomeNoteRunConfigTest: 'Nota Welcome escrita em inglês. Abre Definições → LLM Provider → Test Connection para a localizar na próxima recriação.',
    welcomeNoteRecreated: 'Nota Welcome do Wiki recriada em {path}',
    welcomeNoteNotRecreated: 'A nota Welcome não foi recriada. Verifica a configuração do LLM.',
    welcomeNoteGenerating: 'Nota Welcome do Wiki: a ser gerada em segundo plano — aparecerá um aviso quando terminar.',
    welcomeNoteGenerationFailed: 'Falha ao gerar a nota Welcome do Wiki: {error}',
    startupCheckWelcomePending: 'Nota Welcome: a ser gerada em segundo plano (aparecerá um aviso quando terminar).',
    welcomeNoteFileName: 'Bem-vindo ao Karpathy LLM Wiki',
    startupCheckWelcomeCreated: 'Nota Welcome criada em {path}',
    // v1.23.0 Phase 5.1.5: botão "Cancelar tudo" do modal de seleção múltipla.
    // Cancela todos os trabalhos pendentes e em execução na fila.
    // Os trabalhos concluídos e falhados são preservados para visualização.
    cancelAllQueueJobs: 'Cancelar tudo',
    // v1.23.0 Phase 5.1.5: modal de seleção múltipla (cmdIngestMultipleFiles).
    // Título, dica, placeholder de pesquisa, botões, rótulos de estado,
    // placeholder de fila vazia.
    multiFileModalTitle: 'Ingerir vários ficheiros',
    multiFileModalHint: 'Seleciona notas de origem para ingerir. O painel direito mostra a fila em tempo real e o progresso.',
    multiFileSearchPlaceholder: 'Filtrar ficheiros por caminho…',
    multiFileAddToQueue: 'Adicionar à fila',
    multiFileSelectAll: 'Selecionar tudo',
    multiFileFileCount: '{count} ficheiro(s)',
    multiFileNoFilesAvailable: 'Nenhum ficheiro disponível para ingerir.',
    multiFileNoFilesMatch: 'Nenhum ficheiro encontrado para "{q}".',
    multiFileQueueEmpty: 'Fila vazia. Marca ficheiros à esquerda para adicionar.',
    multiFileStatusPending: 'Pendente',
    multiFileStatusRunning: 'Em execução',
    multiFileStatusCompleted: 'Concluído',
    multiFileStatusFailed: 'Falhou',
    multiFileCancelAria: 'Cancelar este ficheiro',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: 'Ingerido',
    multiFileRowDrifted: 'Nota alterada desde a ingestão',
    startupCheckNoticeLevelName: 'Mostrar resultado das correções rápidas',
    startupCheckNoticeLevelDesc: 'Os QuickFixes são sempre executados no arranque do plugin (nota Welcome, estrutura de pastas, normalização de fontes, páginas incompletas, cabeçalho do registo). Escolhe se queres mostrar o aviso de resumo após o arranque. O modo silencioso apenas regista na consola do programador e no painel Histórico de Operações.',
    startupCheckNoticeVisible: 'Visível (mostrar aviso)',
    startupCheckNoticeSilent: 'Silencioso (sem aviso)',
} as const;
