// v1.26.0: Полный русский перевод интерфейса плагина (667 ключей).
// Перевод выполнен ИИ; рекомендуется проверка носителем русского языка
// перед публикацией. Не стесняйтесь отправлять PR с улучшениями.

export const RU_TEXTS = {
    // Информация о плагине
    pluginTitle: 'Настройки Karpathy LLM Wiki',
    pluginIntro: 'Этот плагин реализует концепцию {{link}} для Obsidian. Он читает ваши заметки, использует ИИ для извлечения сущностей и концепций и создаёт структурированную, взаимосвязанную Wiki в вашем хранилище.',
    karpathyLinkText: 'LLM Wiki Андрея Карпатого',

    // Раздел возможностей
    featuresTitle: 'Как это работает',
    workflow1Title: '1. Импорт',
    workflow1Desc: 'Выберите заметку — ИИ извлечёт сущности, концепции и связи в Wiki-страницы.',
    workflow2Title: '2. Запрос',
    workflow2Desc: 'Общайтесь с вашей Wiki — ответы основаны на импортированных знаниях.',
    workflow3Title: '3. Поддержка',
    workflow3Desc: 'Авто-сгенерированный индекс, перекрёстные ссылки и проверки lint поддерживают Wiki в здоровом состоянии.',

    // Переключатель языка
    languageTitle: 'Язык интерфейса',
    languageDesc: 'Выберите предпочтительный язык для панели настроек. Перезапустите плагин, чтобы применить изменения языка к палитре команд.',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // Статус
    statusTitle: 'Статус LLM-клиента',
    llmWikiStatusSection: 'Статус LLM-Wiki',
    statusInitialized: 'Инициализировано',
    statusNotInitialized: 'Не инициализировано',
    statusReady: 'LLM готова',
    statusNotReady: 'LLM не настроена — завершите настройку и пройдите проверку подключения',
    currentProvider: 'Текущий провайдер',

    // Конфигурация провайдера
    providerSection: 'Конфигурация LLM',
    providerName: 'Провайдер LLM',
    providerDesc: 'Выберите предопределённого провайдера или собственный OpenAI-совместимый сервис. Для Coding Plan или подобных пакетов выберите Custom OpenAI/Anthropic и введите Base URL и API Key провайдера вручную',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: 'API-ключ. Хранится в системном менеджере учётных данных — не в data.json.',
    apiKeyPlaceholder: 'Введите API Key',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: 'Мигрировать в Secret Storage',
    apiKeyMigratedToSecretStorageSuccess: 'API-ключ восстановлен из SecretStorage в настройки.',
    apiKeyMigrationFailedNotice: 'Не удалось сохранить API-ключ в SecretStorage: {}',
    codexAuthName: 'Вход через ChatGPT Plan',
    codexAuthDesc: 'Экспериментальный доступ через Codex OAuth с использованием лимита вашего тарифа ChatGPT. Биллинг OpenAI Platform API ведётся отдельно.',
    codexAuthSignedOut: 'Не выполнен вход',
    codexAuthSignedIn: 'Выполнен вход',
    codexAuthBrowserButton: 'Войти через браузер',
    codexAuthDeviceButton: 'Использовать код устройства',
    codexAuthDeviceInstructions: 'Введите этот код на странице OpenAI: {}',
    codexAuthCopyCode: 'Скопировать код',
    codexAuthSignOutButton: 'Выйти',
    codexAuthBusy: 'Ожидание авторизации OpenAI...',
    codexAuthFailed: 'Авторизация ChatGPT не удалась: {}',
    codexAuthQuota: 'Лимит ChatGPT Codex исчерпан. Дождитесь указанного периода сброса и повторите попытку.',
    codexAuthExperimental: 'Экспериментально: доступность зависит от политик аутентификации и моделей OpenAI Codex.',
    codexModelsRefreshName: 'Модели аккаунта',
    codexModelsRefreshDesc: 'Синхронизировать видимые в выпадающем списке модели из вашего аккаунта OpenAI Codex.',
    codexModelsRefreshButton: 'Обновить модели аккаунта',
    codexModelsRefreshing: 'Обновление...',
    codexModelsRefreshSuccess: 'Синхронизировано {} моделей аккаунта.',
    codexModelsRefreshFailed: 'Не удалось обновить модели аккаунта; используется резервный список. {}',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: 'Обязательно: собственный OpenAI-совместимый эндпоинт',
    baseUrlDescOverride: 'Необязательно: переопределить предустановленный Base URL',

    // Подсказка Ollama
    ollamaHint: 'Ollama работает локально, API Key не требуется',
    // Подсказка LM Studio
    lmstudioHint: 'LM Studio работает локально, API Key необязателен',

    // Лимит выполнения LLM
    maxTokensPerCallName: 'Макс. выходных токенов за вызов',
    maxTokensPerCallDesc: 'Ограничивает количество токенов, которые модель может сгенерировать за один ответ. Уменьшите, если используете локальную модель с маленьким контекстным окном и видите ошибки. Оставьте значение по умолчанию (0 = без ограничения) для облачных моделей.',

    // Issue #111: регистр slug
    slugCaseName: 'Регистр имени файла',
    slugCaseDesc: 'Управляет тем, переводятся ли имена файлов Wiki в нижний регистр. «Сохранять» рекомендуется для языков, где нижний регистр меняет значение (например, немецкие существительные).',
    slugCaseLower: 'Нижний регистр (по умолчанию)',
    slugCasePreserve: 'Сохранять регистр',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: 'Минимальная длина псевдонима',
    minAliasLengthDesc: 'Более короткие псевдонимы (после обрезки пробелов) не записываются на страницы вики. Значение 2 сохраняет двухбуквенные сокращения (ML, AI, UI); поднимите до 3, если в хранилище накапливаются двухбуквенные псевдонимы, различающиеся только регистром (Cr/CR). Диапазон 2–6.',
    minAliasLengthClamped: 'Значение вне диапазона (2–6), установлено {}',

    // Выбор модели
    modelSection: 'Выбор модели',
    fetchModelsName: 'Получить доступные модели',
    fetchModelsDesc: 'Получить последний список моделей из API провайдера',
    fetchModelsButton: 'Получить модели',
    fetchingModels: 'Загрузка...',
    fetchSuccess: 'Успешно! Доступно {} моделей',
    fetchFailed: 'Не удалось получить список или он пуст, пожалуйста, введите имя модели вручную',
    fetchNotSupported: 'Провайдер не поддерживает запрос списка моделей',
    fetchErrorAuth: 'Ошибка аутентификации (HTTP 401/403). Проверьте ваш API Key или введите Model ID ниже и нажмите «Проверить подключение».',
    fetchErrorEndpoint: 'Эндпоинт не найден (HTTP 404). Проверьте BaseURL или введите Model ID и нажмите «Проверить подключение».',
    fetchErrorServer: 'Ошибка сервера провайдера (HTTP 5xx). Повторите попытку позже или введите Model ID и нажмите «Проверить подключение».',
    fetchErrorEmpty: 'У провайдера нет эндпоинта списка моделей. Введите Model ID ниже и нажмите «Проверить подключение».',
    fetchErrorNetwork: 'Сбой сетевого запроса. Проверьте интернет-соединение, BaseURL, настройки прокси или ключ API. Также можно ввести Model ID ниже и нажать «Проверить подключение».',

    selectModelName: 'Выберите модель',
    selectModelDesc: 'Выберите из {} доступных моделей',
    customInputOption: 'Пользовательский ввод...',
    customInputHint: 'Чтобы использовать другие модели, выберите «Пользовательский ввод...»',

    modelName: 'Имя модели',
    modelDescCustom: 'Используется пользовательская модель (нажмите кнопку выше, чтобы обновить список)',
    modelDescFetchFailed: 'Не удалось получить список моделей. Проверьте API Key и URL эндпоинта или введите Model ID ниже и нажмите «Проверить подключение».',
    modelInputPlaceholder: 'Введите Model ID, затем «Проверить подключение»',

    switchToDropdown: 'Переключиться на выпадающий список',
    useDropdownButton: 'Использовать выпадающий список',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: 'Область модели',
    modelTaskModeDesc: 'Выберите, использовать ли одну модель для всех задач или отдельные модели для каждой задачи (импорт / lint / запрос). Скрытые значения per-task сохраняются при переключении обратно в единый режим.',
    modelTaskModeUnified: 'Использовать единую модель (по умолчанию)',
    modelTaskModePerTask: 'Использовать разные модели для каждой задачи',
    perTaskIngestModelName: 'Модель импорта',
    perTaskIngestModelDesc: 'Используется для импорта заметок, бесед, поддержки схемы и создания приветственной заметки.',
    perTaskLintModelName: 'Модель lint',
    perTaskLintModelDesc: 'Используется для анализа lint, обнаружения дубликатов, выполнения fix-* и исправления висячих ссылок.',
    perTaskQueryModelName: 'Модель запросов',
    perTaskQueryModelDesc: 'Используется для чата Query Wiki и оценки сохранения в Wiki.',

    // Тест и сохранение
    testConnectionName: 'Проверить подключение',
    testConnectionDesc: 'Проверить, что конфигурация может успешно вызвать API LLM',
    testButton: 'Проверить подключение',
    testing: 'Проверка...',

    saveSettingsName: 'Сохранить настройки',
    saveSettingsDesc: 'Сохранить текущую конфигурацию',
    saveButton: 'Сохранить настройки',
    savedNotice: 'Настройки сохранены!',

    // v1.24.0 (Bug C 3.4 / plan C): постепенное уведомление о миграции — показывается
    // при запуске или после изменения wikiFolder в середине сессии, когда история
    // чата содержит ссылки из предыдущей папки Wiki.
    queryHistoryMigrationNotice: 'История запросов Wiki содержит ссылки из предыдущей папки Wiki. Новые запросы теперь автоматически используют последнюю папку. Чтобы обновить все сохранённые сообщения, откройте панель Query Wiki и нажмите там кнопку «Очистить историю».',

    // v1.24.0 Issue #251: сворачиваемая панель Custom Query Instructions
    customInstructionsTitle: 'Пользовательские инструкции для запросов',
    customInstructionsDesc: 'Постоянные инструкции, добавляемые к каждому системному промпту Query Wiki. Влияют только на чат Query Wiki; импорт, lint и генерация страниц не затрагиваются.',
    customInstructionsPlaceholder: 'Например: «Рассматривай это как исследование: ищи широко, цитируй источники, отделяй факты от интерпретации...»',
    customInstructionsApply: 'Применить',
    customInstructionsClear: 'Очистить',
    customInstructionsCharCount: '{current}/{max} символов',
    instructionsApplied: 'Пользовательские инструкции для запросов сохранены.',
    instructionsCleared: 'Пользовательские инструкции для запросов очищены.',

    // Проверка подключения
    testConnectionSuccessful: 'Подключение успешно',
    testConnectionFailed: 'Подключение не удалось',
    testConnectionProvider: 'Провайдер: ',
    codexAuthRequired: 'Войдите в ChatGPT Plan перед проверкой подключения.',
    bedrockSsoRequired: 'Перед проверкой подключения выполните вход через AWS SSO (Настройки → Bedrock).',
    bedrockIamRequired: 'Перед проверкой подключения введите ключи доступа IAM (Настройки → Bedrock).',
    bedrockAuthMethodName: 'Аутентификация',
    bedrockAuthMethodDesc: '«Ключ API» использует ключ API Bedrock; «AWS SSO» подписывает запросы учётными данными IAM Identity Center; «Ключи IAM» используют статические ключи доступа.',
    bedrockAuthOptionApiKey: 'Ключ API',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'Ключи IAM',
    bedrockSsoStartUrlName: 'Начальный URL SSO',
    bedrockSsoStartUrlDesc: 'URL портала вашей организации, напр. https://d-xxxxxxxxx.awsapps.com/start',
    bedrockSsoAccountIdName: 'ID аккаунта AWS',
    bedrockSsoAccountIdDesc: '12-значный ID аккаунта, чья роль будет принята, напр. 123456789012',
    bedrockSsoRoleNameName: 'Имя роли',
    bedrockSsoRoleNameDesc: 'Роль IAM для доступа к Bedrock, напр. PowerUserAccess',
    bedrockSsoLoginButton: 'Войти через AWS SSO',
    bedrockSsoSignOutButton: 'Выйти из AWS SSO',
    bedrockSsoStatusSignedIn: 'Вход выполнен · истекает {}',
    bedrockSsoStatusSignedOut: 'Не выполнен вход',
    bedrockSsoBusy: 'Выполняется вход…',
    bedrockSsoUserCodeInstructions: 'Код AWS SSO: {}. Откройте ссылку и подтвердите доступ.',
    bedrockSsoCopyCode: 'Скопировать код',
    bedrockSsoFailed: 'Не удалось войти через AWS SSO: {}',
    bedrockSsoDetectedPrefill: 'Обнаружены аккаунт/роль: {}',
    bedrockIamKeyName: 'ID ключа доступа',
    bedrockIamKeyDesc: 'Идентификатор ключа доступа IAM, напр. AKIA… или ASIA…',
    bedrockIamSecretName: 'Секретный ключ доступа',
    bedrockIamSecretDesc: 'Хранится только в хранилище секретов этого устройства — никогда в data.json',
    bedrockIamSessionTokenName: 'Токен сессии (необязательно)',
    bedrockIamSessionTokenDesc: 'Требуется только для временных учётных данных (STS)',
    bedrockIamClearButton: 'Очистить сохранённые ключи IAM',
    bedrockIamSaveFailed: 'Не удалось сохранить ключи IAM: {}',
    errorUnknown: 'Неизвестная ошибка',

    // Issue #137: уведомления LLM-fallback (показываются, когда во время запроса
    // срабатывает fallback диалекта thinking или удаление параметра).
    fallbackThinkingDialect: 'Управление мышлением: переключение на диалект «{dialect}» (этот провайдер использует другой формат управления мышлением). Вывод не изменился.',
    fallbackThinkingNone: 'Управление мышлением полностью отключено для этого провайдера. Содержимое рассуждений всё ещё может появляться; в таком случае попробуйте другую модель.',
    fallbackParamStripped: 'Параметр «{field}» не поддерживается этим провайдером. Удалён из запроса; поведение может отличаться от настроенного.',

    // Статус инициализации Wiki
    wikiInitStatusReady: 'Wiki инициализирована',
    wikiInitStatusNotReady: 'Wiki не инициализирована — будет автоматически создана при первом импорте',

    // Папка Wiki
    wikiSection: 'Конфигурация Wiki',
    wikiFolderName: 'Папка Wiki',
    // v1.24.0: добавлена подсказка «перезапустите Obsidian», потому что wikiFolder
    // влияет на кэши движка и панели Query Wiki, которые не перепривязываются
    // полностью при изменении настроек.
    wikiFolderDesc: 'Расположение сгенерированных страниц Wiki. Перезапустите Obsidian после изменения — кэши движка и открытые панели Query Wiki должны перепривязаться.',
    wikiFolderPlaceholder: 'wiki',

    // Ошибки
    errorNoApiKey: 'Пожалуйста, сначала настройте API Key',
    errorNoModel: 'Пожалуйста, сначала выберите модель — нажмите «Получить модели» или введите Model ID вручную',
    llmNotReady: 'LLM не настроена. Перейдите в Настройки → Karpathy LLM Wiki, чтобы настроить провайдера, получить доступные модели и пройти проверку подключения.',
    errorFetchFailed: 'Не удалось: {}',

    // Настройки запросов
    querySectionTitle: 'Конфигурация запросов Wiki',
    // v1.24.0: переименовано из «Max Conversation History» для уточнения
    // семантики — это ограничение окна памяти, а не жёсткий лимит хранения
    // (сама история — скользящий буфер). 1 = каждый ход независим
    // (без межходовой памяти). UI настроек — выпадающий список пресетов, поэтому
    // список «presets: 1/10/30/50/100/500» в описании не нужен.
    // v1.24.0: maxConversationHistoryHint был мёртвым ключом i18n (никогда
    // не использовался в UI); текст рекомендации теперь живёт внутри desc.
    maxConversationHistoryName: 'Раунды памяти беседы',
    maxConversationHistoryDesc: 'Сколько прошлых раундов беседы LLM видит как память. 1 = каждый ход независим (без межходовой памяти); более высокие значения позволяют модели помнить более ранние ходы сессии. Рекомендуется: 1 для одноразовых вопросов, 10–50 для продолжающегося исследования.',
    numberRangeValidation: 'Пожалуйста, введите число от 1 до 50',
    numberRangeClamped: 'Значение превышает диапазон (1-500), автоматически установлено {}',

    // UI модального окна запросов
    queryModalTitle: 'Query Wiki — диалоговый запрос',
    queryModalPlaceholder: 'Введите вопрос...',
    queryModalSendButton: 'Отправить',
    queryModalStopButton: 'Стоп',
    queryModalSaveButton: 'Сохранить в Wiki',
    queryModalClearButton: 'Очистить историю',
    queryModalHistoryCount: 'История беседы: {}/{} раундов',
    queryModalStreaming: 'Потоковая передача...',
    queryModalFallbackStreaming: 'Потоковая передача не поддерживается, переключение на непотоковый режим. Подождите...',
    queryPhaseSearching: 'Анализ индекса Wiki, выбор релевантных страниц...',
    queryPhaseFoundPages: 'Найдено {count} стр.: {pages}',
    queryPhaseLoadingPages: 'Загрузка содержимого страниц...',
    queryPhaseContextReady: 'Контекст готов. Генерация ответа...',
    queryPhaseGenerating: 'Генерация... (прошло {time} с)',
    queryPhaseNonStreaming: 'Непотоковый режим, генерация ответа... (прошло {time} с)',
    queryModalErrorPrefix: 'Ошибка: ',
    queryModalHint: 'Запросы на основе содержимого Wiki. Нажмите «Сохранить в Wiki», чтобы извлечь ценные беседы как страницы Wiki.',

    // v1.20.0: сворачиваемое summary блока мышления Query Wiki
    queryThinkingSummary: 'Процесс мышления',
    queryThinkingSteps: 'шагов',

    // Сообщения об ошибках
    errorLLMClientNotInit: 'LLM-клиент не инициализирован. Пожалуйста, сохраните настройки.',
    errorIngestFailed: 'Ошибка импорта: ',
    errorQueryFailed: 'Ошибка запроса: ',
    fileWriteFailed: 'Не удалось создать или обновить файл: {path}',

    // Сообщения об успехе
    ingestSuccess: 'Импорт успешен: {} страниц создано, {} страниц обновлено',
    querySuccess: 'Запрос завершён',
    lintSuccess: 'Lint Wiki завершён',
    lintReadingPages: 'Чтение {count} страниц Wiki...',
    lintReadingPagesProgress: 'Чтение страниц Wiki: {current}/{total}...',
    lintScanningLinks: 'Сканирование мёртвых ссылок...',
    lintScanningLinksProgress: 'Сканирование мёртвых ссылок: {current}/{total}...',
    lintCheckingDuplicates: 'Проверка дублирующихся страниц...',
    lintCheckingDuplicatesProgress: 'Проверка дубликатов: пакет {current} ...',
    lintFixingPolluted: 'Исправление загрязнённой страницы {current}/{total}: {title} → {newTitle}',
    lintModalFixPolluted: '🧹 Исправить загрязнённые страницы ({count})',
    lintDuplicateCheckFailed: 'Обнаружение дубликатов не удалось — см. подробности в консоли',
    lintDuplicateCheckFailedDetail: 'Проверка дубликатов не удалась на {step}: {error}',
    lintMergeItemFailed: 'Слияние не удалось: {source} → {target} — {error}',
    lintAliasesMissing: 'Отсутствуют псевдонимы: {count} стр. без псевдонимов',
    lintAliasesSection: 'Страницы без псевдонимов [{count}]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: 'Заполнить псевдонимы ({count})',
    lintAliasesFilling: 'Генерация псевдонимов {current}/{total}: {page}',
    lintAliasesFilled: 'Заполнение псевдонимов завершено. Заполнено {filled}/{total} стр.',
    lintAliasesFillFailed: 'Не удалось сгенерировать псевдоним: {page} — {error}',
    // Issue #85 v7: уведомления о retag при нарушении тегов
    lintTagViolationFiring: 'Повторная разметка {current}/{total}: {path}',
    lintTagViolationFailed: 'Не удалось повторно разметить {path}: {error}',
    lintTagViolationFixed: 'Повторная разметка завершена. Исправлено {fixed}/{total} стр.',
    lintTagViolationFixedNone: 'Повторная разметка завершена. Никакие страницы не нуждались в исправлении (LLM сохранил текущие теги).',
    lintTagViolationSection: 'Страницы с тегами вне словаря [{count}]',
    lintTagViolationItem: '- [[{path}]] — недопустимо: {tags}',
    lintTagViolationRetagBtn: '🏷️ Повторно разметить {count} стр. с помощью LLM',
    lintFixItemFailed: 'Исправление не удалось: [[{target}]] — {error}',
    lintLinkItemFailed: 'Привязка не удалась: {page} — {error}',
    lintRetrying: 'Повтор ({attempt}/{max}) после ошибки...',
    lintAnalyzingLLM: 'LLM анализирует здоровье Wiki...',
    saveToWikiSuccess: 'Беседа сохранена в Wiki!',
    querySaveAlreadyExists: 'Примечание: ничего не записано (знание уже существует в Wiki):',
    saveSummary: '{entities} сущностей, {concepts} концепций, {pages} страниц',
    aliasAdded: 'Псевдоним «{alias}» добавлен на страницу «{page}»',

    // Сообщения статуса
    ingestingSources: 'Импорт источников...',
    queryingWiki: 'Запрос к Wiki...',
    lintingWiki: 'Проверка Wiki...',
    savingToWiki: 'Сохранение беседы в Wiki...',
    clearingHistory: 'Очистка истории беседы...',

    // Кнопки
    ingestButton: 'Импорт',
    queryButton: 'Запрос',
    lintButton: 'Lint',
    cancelButton: 'Отмена',

    // Ссылки
    karpathyGistLink: 'Gist Карпатого по LLM Wiki',
    obsidianPluginAPI: 'API плагинов Obsidian',
    anthropicSDK: 'SDK Anthropic',
    openaiSDK: 'SDK OpenAI',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'Регион AWS',
    bedrockRegionDesc: 'Регион Amazon Bedrock для этого аккаунта. Определяет URL эндпоинта bedrock-mantle; не может быть переопределён через baseURL.',
    bedrockRegionHint: 'bedrock-mantle доступен в 18 регионах; покрытие моделей варьируется по регионам.',

    // Прочее
    availableModelsLoading: 'Загрузка доступных моделей...',
    noModelsAvailable: 'Нет доступных моделей',

    // Подсказка языка LLM
    llmLanguageHint: 'Пожалуйста, отвечайте на английском.',

    // Конфигурация схемы
    schemaSection: 'Конфигурация схемы',
    enableSchemaName: 'Включить схему',
    enableSchemaDesc: 'Генерировать и внедрять schema/config.md во все промпты LLM для структурированного вывода Wiki',
    viewSchemaButton: 'Просмотр / редактирование схемы',
    regenerateSchemaButton: 'Перегенерировать схему по умолчанию',
    schemaRegeneratedNotice: 'Схема по умолчанию перегенерирована.',
    schemaRegenerateFailed: 'Не удалось сгенерировать схему',

    // Язык вывода Wiki
    wikiLanguageName: 'Язык вывода Wiki',
    wikiLanguageDesc: 'Все сгенерированные страницы Wiki, индекс, журнал и ответы на запросы используют этот язык',
    customWikiLanguageOption: 'Пользовательский...',
    customWikiLanguageHint: 'Введите название языка (например, итальянский, арабский). Оно будет передано LLM как директива о языке вывода.',
    customWikiLanguagePlaceholder: 'например, итальянский',

    // Метки индекса и журнала (по языкам)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // Настройки извлечения
    extractionSectionTitle: 'Извлечение',
    extractionGranularityName: 'Гранулярность извлечения',
    extractionGranularityDesc: 'Управляет количеством сущностей/концепций, извлекаемых из каждого исходного файла. Выше = больше страниц, больше токенов API.\nFine: глубокий анализ. Standard: повседневные заметки. Coarse: быстрый обзор. Minimal: пакет из 100+ файлов (лимит записей на источник, ~5 — не глубина каждой). Custom: задайте свои пределы (до 500).\nСовет: используйте Minimal/Coarse для папок с множеством файлов, чтобы сэкономить время и деньги.',
    extractionGranularityFine: 'Fine — глубокий анализ (≤100 элементов)',
    extractionGranularityStandard: 'Standard — повседневные заметки (≤50 элементов)',
    extractionGranularityCoarse: 'Coarse — быстрый обзор (≤10 элементов)',
    extractionGranularityMinimal: 'Minimal — пакет из 100+ файлов (≤5 элементов)',
    extractionGranularityCustom: 'Custom — задайте свои пределы (1~500)',
    customEntityLimitName: 'Пользовательский лимит сущностей',
    customEntityLimitDesc: 'Максимальное количество сущностей, извлекаемых из одного исходного файла (1-500)',
    customConceptLimitName: 'Пользовательский лимит концепций',
    customConceptLimitDesc: 'Максимальное количество концепций, извлекаемых из одного исходного файла (1-500)',

    // Issue #85 v2: словарь тегов (chip input UX, встроен в конфигурацию Wiki)
    tagVocabularyInlineDesc: 'Контролируемый словарь для frontmatter тегов сущностей и концепций. Вложенные теги Obsidian с «/» сохраняются.',
    tagVocabularyModeName: 'Конфигурация словаря тегов',
    tagVocabularyModeDescDefault: 'По умолчанию используются встроенные теги: {}. Переключитесь на Custom, чтобы определить свои.',
    tagVocabularyModeDescCustom: 'Custom: определите свои теги сущностей и концепций ниже. Используйте chip input — Enter или запятая для добавления, × для удаления.',
    // v1.25.10 PATCH Issue #368 — уточнение, не принуждение. Пользовательский
    // словарь — это ПОДСКАЗКА ДЛЯ СХЕМЫ для LLM, а не шлюз при записи. Маленькие/локальные
    // модели всё ещё могут выдавать типы вне словаря; диагностика lint «out-of-vocabulary type»
    // обнаруживает такие страницы для проверки.
    tagVocabularyNotEnforcedHint: 'Только подсказка для схемы — LLM всё ещё может выдавать типы вне словаря. Запустите Lint, чтобы найти и исправить такие страницы.',
    tagVocabularyModeDefault: 'По умолчанию (встроенные подтипы)',
    tagVocabularyModeCustom: 'Пользовательский (определяется пользователем)',
    customEntityTagsName: 'Пользовательские теги сущностей',
    customEntityTagsDesc: 'Нажмите Enter или запятую, чтобы добавить chip. Нажмите × для удаления. Вложенные теги с «/» сохраняются.',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'Пользовательские теги концепций',
    customConceptTagsDesc: 'Нажмите Enter или запятую, чтобы добавить chip. Нажмите × для удаления. Вложенные теги с «/» сохраняются.',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: 'Дублирующий тег пропущен',

    // Ускорение импорта
    accelerationSectionTitle: 'Ускорение импорта',
    pageGenerationConcurrencyName: 'Параллелизм LLM',
    pageGenerationConcurrencyDesc: 'Количество параллельных вызовов LLM во время импорта и lint. Более высокие значения ускоряют обработку, но увеличивают затраты API и могут вызвать ограничения скорости.',
    concurrencyValueSingular: 'Текущий параллелизм: {} (последовательный — самый безопасный)',
    concurrencyValuePlural: 'Текущий параллелизм: {} (параллельный)',
    batchDelayName: 'Задержка пакета (мс)',
    batchDelayDesc: 'Задержка между параллельными пакетами для предотвращения ограничения скорости API (100-10000 мс). Текущая: {} мс. Увеличьте, если видите ошибки 429.',

    // Автоматическое обслуживание
    autoMaintainSection: 'Автоматическое обслуживание',
    autoMaintainBetaBadge: 'BETA — Экспериментальная функция. Возможны проблемы. Рекомендуется только опытным пользователям.',
    autoWatchName: 'Отслеживаемые папки',
    autoWatchDesc: 'Автоматически обнаруживать новые или изменённые .md файлы в отслеживаемых папках и уведомлять или автоматически импортировать',
    watchedFoldersName: 'Отслеживаемые папки',
    watchedFoldersDesc: 'Папки для отслеживания нового содержимого. Нажмите «Добавить папку», чтобы выбрать из вашего хранилища.',
    addWatchedFolderButton: 'Добавить папку',
    removeWatchedFolderButton: 'Удалить',
    webClipperPresetName: 'Отслеживать вырезки (Web Clipper)',
    webClipperPresetDesc: 'Добавить папку Clippings/, используемую Obsidian Web Clipper, в список отслеживания. Ваши веб-вырезки будут автоматически импортированы в Wiki.',
    noWatchedFoldersHint: 'Папки не настроены. Добавьте папку или включите пресет Clippings.',
    autoWatchModeName: 'Режим отслеживания',
    autoWatchModeDesc: '«Только уведомлять» показывает подсказку. «Авто-импорт» обрабатывает молча.',
    watchModeNotify: 'Только уведомлять',
    watchModeAuto: 'Авто-импорт',
    autoWatchDebounceName: 'Задержка дебаунса (секунды)',
    autoWatchDebounceDesc: 'Время ожидания перед запуском импорта после изменения файла (1-60 секунд)',
    periodicLintName: 'Периодический Lint',
    periodicLintDesc: 'Запускать LLM lint по расписанию, только когда исходные файлы изменились с последней проверки',
    periodicLintOff: 'Выкл',
    periodicLintDaily: 'Ежедневно',
    periodicLintWeekly: 'Еженедельно',
    periodicLintMonthly: 'Ежемесячно',
    autoSmartFixName: 'Авто Smart Fix',
    autoSmartFixDesc: 'Когда lint запускается, автоматически применять все исправления (Smart Fix All) без показа модального окна отчёта. Сводка исправлений всё ещё показывается по завершении.',
    autoSmartFixNotice: 'Авто Smart Fix: применение всех исправлений...',

    autoIngestLevelName: 'Уведомление об авто-импорте',
    autoIngestLevelDesc: 'Как уведомлять о завершении авто-импорта. «Notice» (временное) неблокирующее. «Modal» открывает полный отчёт. Отключено, когда режим отслеживания «Только уведомлять».',
    autoIngestLevelNotice: 'Notice (неблокирующее)',
    autoIngestLevelModal: 'Modal (полный отчёт)',
    startupCheckName: 'Запускать быстрые исправления при старте',
    startupCheckDesc: 'Авто-исправление проблем низкоуровневого форматирования (источники, дважды вложенные ссылки) при загрузке плагина. Проверяет структуру папки Wiki. По умолчанию ВКЛ.',
    startupCheckNoticeLevelName: 'Показывать результат быстрых исправлений',
    startupCheckNoticeLevelDesc: 'QuickFixes всегда запускаются при старте плагина (приветственная заметка, структура папок, нормализация источников, неполные страницы, заголовок журнала). Выберите, показывать ли сводный Notice после старта. Тихий режим логирует только в консоль разработчика и панель истории операций.',
    startupCheckNoticeVisible: 'Видимо (показать Notice)',
    startupCheckNoticeSilent: 'Тихо (без Notice)',
    suggestSchemaCommand: 'Предложить обновления схемы',
    autoMaintainCostWarning: '⚠️ Уведомление о стоимости: функции автоматического обслуживания потребляют токены API. «Авто-импорт» запускает вызовы LLM при каждом изменении исходного файла. «Периодический Lint» запускает проверки здоровья LLM по расписанию (только когда обнаружены изменения источников). Настраивайте осторожно, чтобы избежать неожиданных расходов.',

    // Уведомления
    startupCheckSummary: 'Wiki содержит {pages} стр. ({entities} сущностей, {concepts} концепций, {sources} источников)',
    watcherActiveNotice: 'Wiki: наблюдатель файлов активен — мониторинг отслеживаемых папок',
    watchIngestNotice: 'Wiki: {count} файл(ов) изменились в sources/. Запустите «Импорт источников» для обработки.',

    // Подробности быстрых исправлений при старте (Issue #81)
    startupCheckTitle: 'Быстрые исправления Wiki завершены',
    startupCheckStructureLabel: 'Структура Wiki',
    startupCheckStructureOk: 'завершена',
    startupCheckStructureMissing: 'не завершена — будет автоматически создана при первом импорте',
    startupCheckSourcesLabel: 'Источники нормализованы',
    startupCheckSourcesClean: 'уже чисто',
    startupCheckSourcesCleaned: 'очищено {files} файл(ов), {entries} записей',
    startupCheckIncompleteClean: 'неполные страницы: нет',
    startupCheckIncompleteArchived: 'неполные страницы: архивировано {count} (восстановимо из .trash)',
    startupCheckDisableHint: 'Чтобы отключить, перейдите в Настройки → Автоматическое обслуживание → Запускать быстрые исправления при старте',
    autoIngestRunning: 'Авто-импорт {count} изменённых файл(ов)...',
    autoIngestComplete: 'Авто-импорт завершён: {success} успешно, {fail} не удалось',
    scheduledLintRunning: 'Запуск запланированного lint Wiki...',
    wikiLintStats: 'Lint Wiki: {pages} стр. ({entities} сущностей, {concepts} концепций, {sources} источников)',
    wikiHealthStats: 'Здоровье Wiki: {pages} стр. ({entities} сущностей, {concepts} концепций, {sources} источников){indexStatus}',
    lintWikiStart: 'Запуск lint Wiki...',
    lintWikiComplete: 'Lint Wiki завершён',
    lintWikiFailed: 'Lint Wiki не удался',
    analyzingSchema: 'Анализ Wiki и генерация предложений по схеме...',
    schemaSuggestionGenerated: 'Предложения по схеме сгенерированы, см. wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: 'Обновления схемы не требуются.',
    schemaSuggestionFailed: 'Не удалось предложить схему',
    // v1.22.0 #97: Модальное окно Schema diff — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Предпросмотр обновления схемы',
    schemaDiffSummary: '+{add} / -{del} строк',
    schemaDiffRegenerateLabel: 'Уточнить предложение (необязательно):',
    schemaDiffRegenerateBtn: 'Перегенерировать',
    schemaDiffOpenFileBtn: 'Открыть файл',
    schemaDiffApplyBtn: 'Применить',
    schemaDiffApplied: 'Схема обновлена. Резервная копия: {path}',
    schemaDiffEmptyTitle: 'Изменения не рекомендуются',
    schemaDiffFailed: 'Не удалось применить схему: {reason}',
    schemaDiffRestoreHint: 'Резервная копия сохранена в {path}. Чтобы восстановить, переименуйте этот файл обратно в «wiki/schema/config.md» в вашем файловом менеджере. Последние 3 резервные копии сохраняются.',
    schemaRegenerateNoBody: 'Регенерация успешна, но LLM не вернула новое тело.',
    schemaNotFoundNotice: 'Файл схемы не найден. Включите схему, чтобы создать его.',
    selectFolderNoMdFiles: 'Нет файлов Markdown в папке: {path}',
    batchIngestSkipNotice: 'Пропуск {skipped}/{total} уже импортированных файлов. Импорт {new} новых файлов...',
    batchIngestAllIngested: 'Все {total} файлов в этой папке уже импортированы.',
    batchIngestStarting: 'Импорт {count} файл(ов) из «{folder}» — это может занять несколько минут. По завершении появится отчёт.',
    batchIngestComplete: 'Пакетный импорт завершён: {success}/{total} успешно, {fail} не удалось',
    batchIngestFailedFiles: 'Не удалось импортировать:',
    historyTruncated: 'История обрезана до последних {max} раундов',
    historyCleared: 'История очищена',

    // Цикл обратной связи с пользователем
    reviewedPagePreserved: 'Сохранение проверенного пользователем содержимого для: {}',

    // Обратная связь Query-to-Wiki
    querySuggestSaveTitle: 'Сохранить в Wiki?',
    querySuggestSaveDesc: 'Эта беседа содержит ценные знания. Сохранить её в вашу Wiki?',
    querySuggestSaveYes: 'Сохранить',
    querySuggestSaveNo: 'Отклонить',

    // Отчёт об импорте
    ingestReportElapsedTime: 'Затраченное время',
    ingestReportSkippedFiles: 'Пропущено (уже импортировано)',
    ingestReportRejectedFiles: 'Пропущено',
    rejectionReasonEmpty: 'пусто',
    rejectionReasonType: 'неподдерживаемый тип',
    rejectionReasonDuplicate: 'дублирующееся содержимое',
    rejectionReasonPdfUnsupported: 'провайдер не может прочитать PDF',
    rejectionReasonMineruPageLimit: 'превышает лимит страниц MinerU',
    rejectionReasonMineruSizeLimit: 'превышает лимит размера MinerU',
    ingestReportFailedGuidance: 'Эти элементы не удалось создать автоматически. Вы можете вручную создать соответствующие страницы или снизить гранулярность извлечения и повторно импортировать исходный файл.',

    // Имена команд (предложный регистр по правилу 1 Obsidian Bot)
    cmdIngestSource: 'Импорт одного источника',
    cmdIngestFolder: 'Импорт из папки',
    cmdIngestMultipleFiles: 'Импорт нескольких файлов',
    cmdQueryWiki: 'Запрос к Wiki',
    cmdLintWiki: 'Lint Wiki',
    cmdRegenerateIndex: 'Перегенерировать индекс',
    cmdSuggestSchema: 'Предложить обновления схемы',
    cmdCancelIngestion: 'Отменить текущий импорт',
    cmdIngestActiveFile: 'Импорт текущего файла',
    cmdViewHistory: 'Просмотр истории операций',
    noActiveFile: 'В настоящее время ни один файл не открыт',
    mdOnlyFile: 'Можно импортировать только файлы Markdown',
    ingestSingleFileStart: 'Обработка: {filename}',
    ingestCheckingExisting: 'Проверка уже обработанных файлов...',
    lintFindingsSummary: 'найдено {total}',

    // Строка статуса импорта
    ingestionStatusBar: 'Импорт... нажмите для отмены',
    lintStatusBar: 'Lint... нажмите для отмены',
    ingestStatusAnalyzing: 'Импорт… (нажмите для отмены)',
    lintStatusAnalyzing: 'Lint… (нажмите для отмены)',
    // v1.25.11 PATCH #169 — детальные подсказки стадий для строки статуса.
    // Эти метки добавляются между именем страницы и всегда видимой базовой меткой
    // (например, «My Note · Generating summary · Ingesting… (click to cancel)»).
    // Они никогда не заменяют базовую метку, поэтому возможность отмены
    // сохраняется на каждой длительной стадии.
    ingestStageAnalyze: 'Анализ источника',
    ingestStageSummary: 'Генерация резюме',
    ingestStageEntity: 'Создание сущности',
    ingestStageConcept: 'Создание концепции',
    ingestStageRetry: 'Повтор неудачной страницы',
    ingestStageSave: 'Сохранение страниц',
    ingestStageIndex: 'Генерация индекса',
    pdfStageReading: 'Чтение PDF',
    pdfStageConverting: 'Конвертация PDF',
    pdfStageSidecar: 'Запись sidecar',
    lintStagePrep: 'Чтение страниц',
    lintStageProgrammatic: 'Сканирование ссылок',
    lintStageAnalyzing: 'Запуск LLM-анализа',
    lintStageDedup: 'Обнаружение дубликатов',
    lintStageContradiction: 'Обнаружение противоречий',
    ingestionCancelling: 'Отмена — остановится после завершения текущего пакета',
    ingestionCancelled: 'Импорт отменён',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: 'Анализ партии 1/{total}...',
    ingestBatchProgress: 'Анализ партии {current}/{total} ({entities} сущностей, {concepts} концепций пока)...',
    ingestBatchProcessed: 'Партия {current} проанализирована, обработка...',
    ingestAnalyzing: 'Анализ: {filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] Создание сводки...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}: {name}',
    ingestUpdating: '[{step}/{totalSteps}] Обновление: {name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] Создание индекса...',
    ingestItemTypeEntity: 'Сущность',
    ingestItemTypeConcept: 'Концепция',
    convAnalyzing: 'Анализ разговора...',
    convCheckingExisting: 'Проверка существующих знаний...',
    convAlreadyExists: 'Эти знания уже существуют в Wiki',
    convCreatingSummary: 'Создание страницы сводки...',
    convGeneratingSummary: 'Генерация страницы сводки...',
    convSavingEntity: 'Сохранение сущности: {name}',
    convSavingConcept: 'Сохранение концепции: {name}',
    convGeneratingIndex: 'Создание индекса...',

    // Отчёт Lint
    lintReportTitle: 'Отчёт lint Wiki',
    lintReportSummary: 'Обзор состояния Wiki: всего {total} стр., {aliasesMissing} стр. без псевдонимов, {duplicates} дублирующихся стр., {deadLinks} мёртвых ссылок ({deadLinkFromDup} связаны с дубликатами), {orphans} висячих стр. ({orphanFromDup} являются дубликатами), {emptyPages} пустых стр., {ungroundedQuotes} неподтверждённых цитат, {tagViolations} тегов вне словаря. Lint занял: {elapsedSeconds} с',

    // Расширенные настройки LLM (v1.20.0: по умолчанию = без специфичных для провайдера переопределений).
    // v1.26.0 (#382 item 2): переименовано advancedSettingsModeName →
    // advancedLlmModeName, чтобы метка относилась к параметрам выборки LLM и не
    // путалась с общей нижней панелью «Advanced settings».
    advancedLlmModeName: 'Расширенные параметры LLM',
    advancedLlmModeDesc: 'Режим по умолчанию следует рекомендациям провайдера модели. Переключайтесь на Custom только при наличии конкретной причины для переопределения (например: конкретной модели нужна фиксированная температура, или вы хотите подавить вывод рассуждений модели).',
    advancedSettingsDefault: 'По умолчанию (следовать провайдеру)',
    advancedSettingsCustom: 'Пользовательский (переопределить провайдера)',
    // v1.26.0 (#382 item 2): нижняя панель «Advanced settings» — общий
    // дом для всех расширенных настроек, которые НЕ являются параметрами выборки LLM
    // (они живут под advancedLlmModeName выше). Выкл по умолчанию; переключатель
    // показывает пороги lint, приветственную заметку и будущие ручки.
    advancedSettingsSection: 'Расширенные настройки',
    showAdvancedSettingsName: 'Показать расширенные настройки',
    showAdvancedSettingsDesc: 'Включите, чтобы показать расширенные настройки ниже. Выключение скрывает их и сбрасывает на значения по умолчанию.',
    disableThinkingName: 'Отключить мышление',
    disableThinkingDesc: 'Отключить цепочку рассуждений / вывод мышления модели в её ответе. По умолчанию выкл — модель решает, показывать ли рассуждения, и обычно это даёт лучший ответ. Включайте это только если ваш провайдер вываливает сырой текст рассуждений в ответ, и вы хотите чистый ответ.',
    taskPoliciesPlaceholder: 'Пример: extract=text:off',
    taskPoliciesName: 'Режим вывода и рассуждение по шагам',
    taskPoliciesDesc: 'По одной записи на шаг конвейера, `шаг=режим:рассуждение`, через запятую — например `extract=text:off`. Режимы: `-` (без изменений), `schema`, `json`, `text`; рассуждение: `-`, `off`, `on`, `low`, `medium`, `high`. Имена шагов включают extract, extract-retry, lemma-classify, merge-triage, source-stance, dedup, page-generate, related-page, lint-dedup (имя с опечаткой не совпадёт ни с чем). Пусто — встроенная основа (извлечение в текстовом режиме). Нечитаемая запись не сохраняется.',
    // Issue #137: подсказки совместимости для расширенных настроек (короткие; без
    // списка провайдеров, чтобы избежать бремени обслуживания при их изменении).
    extractionTemperatureName: 'Температура извлечения',
    extractionTemperatureDesc: 'Управляет тем, насколько модель креативна vs точна при написании страниц сущностей/концепций. Более низкие числа = более детерминированно и фактически; более высокие числа = более разнообразно. Большинство пользователей оставляют это пустым.',
    chatTemperatureName: 'Температура запросов',
    chatTemperatureDesc: 'Та же идея, что и температура извлечения, но влияет только на то, как Query Wiki отвечает на вопросы. Более низкие числа = более буквальные ответы; более высокие числа = более разговорные. Большинство пользователей оставляют это пустым.',
    repetitionPenaltyName: 'Штраф за повторение',
    repetitionPenaltyDesc: 'Не одобряет повторение моделью тех же слов или фраз. Более высокие числа означают меньше повторений. Только определённые провайдеры локальных моделей (Ollama, LM Studio, llama.cpp) принимают это; облачные провайдеры будут молча игнорировать. Большинство пользователей оставляют это пустым. Значение выше 1,0 может вызывать ошибки вывода LLM при извлечении на небольших локальных моделях — если выполнение завершится неудачей, уменьшите или очистите это значение.',
    repetitionPenaltyErrorHint: 'Примечание: установлено пользовательское значение штрафа за повторение {value}. Значения выше 1,0 могут нарушить извлечение с ограничением грамматики на небольших локальных моделях — уменьшите или очистите этот параметр и повторите попытку.',
    temperaturePlaceholder: 'оставьте пустым = по умолчанию провайдера',
    // v1.26.0 (#382 item 2): переопределения порогов lint dedup (нижняя
    // панель «Advanced settings», переключатель showAdvancedSettings вкл). Заполнитель
    // «leave blank» выше используется повторно, чтобы строка ввода читалась
    // так же, как строки температуры в разделе Advanced.
    lintDedupJaccardLinkThresholdName: 'Сходство дублирующихся ссылок',
    lintDedupJaccardLinkThresholdDesc: 'Диапазон 0–1 (по умолчанию 0,4). Две страницы помечаются как дубликаты, когда wiki-ссылки, на которые они обе указывают, перекрываются как минимум на эту долю. Ниже → обнаруживает больше почти-дубликатов (включая страницы, которые просто ссылаются на общие хабы); выше → помечает только страницы, которые указывают почти на один и тот же набор страниц. Увеличьте, если видите ложные срабатывания между страницами, которые случайно ссылаются на один и тот же хаб. Оставьте пустым для значения по умолчанию.',
    lintDedupJaccardBodyGateName: 'Минимальное сходство тела',
    lintDedupJaccardBodyGateDesc: 'Диапазон 0–1 (по умолчанию 0,2). Даже если две страницы разделяют wiki-ссылки, они помечаются как дубликаты только когда их текст тела как минимум настолько похож (в долях). Ниже → больше кандидатов проходит на проверку LLM; выше → помечаются только почти идентичные тела. Увеличьте, если LLM спрашивают о страницах, которые явно не являются дубликатами. Оставьте пустым для значения по умолчанию.',
    lintDedupBigramThresholdName: 'Сходство заголовков',
    lintDedupBigramThresholdDesc: 'Диапазон 0–1 (по умолчанию 0,4). Две страницы помечаются как дубликаты, когда символы в их заголовках (или псевдонимах) перекрываются как минимум на эту долю. Ниже → обнаруживает варианты написания, опечатки и переводы одной и той же концепции; выше → помечает только почти идентичные заголовки. Увеличьте, если LLM проверяет страницы с очень разными именами, которые на самом деле не дубликаты. Оставьте пустым для значения по умолчанию.',
    lintDeadLinkSection: 'Мёртвые ссылки (обнаружено) [{count}]',
    lintEmptyPageSection: 'Пустые страницы (обнаружено) [{count}]',
    lintOrphanSection: 'Висячие страницы (обнаружено) [{count}]',
    lintContradictionSection: 'Противоречия (обнаружено)',
    lintDuplicateSection: 'Дублирующиеся страницы (обнаружено)',
    lintPollutedSection: 'Загрязнённые страницы (обнаружено) [{count}]',
    lintPollutedItem: '- [[{page}]] → должно быть «{clean}»',
    lintSourcesNormalizedSection: 'Источники нормализованы (авто-исправлено) [{files} файлов / {entries} записей]',
    lintSourcesNormalizedItem: 'Очищено {entries} загрязнённых записей источников в {files} файл(ах) (внешние пути, расширения .md, псевдонимы pipes удалены и дедуплицированы).',
    lintNoIssuesFound: 'Дубликатов, мёртвых ссылок, пустых страниц, висячих страниц или неподтверждённых цитат не обнаружено.',
    lintSourceDriftSection: 'Исходные заметки изменены после импорта [{count}]',
    lintSourceDriftItem: '- [[{page}]] — исходная заметка [[{note}]] была изменена после импорта; страница может быть устаревшей',
    lintContradictionMarkerSection: 'Страницы с маркером противоречий (триаж слияния) [{count}]',
    lintContradictionMarkerItem: '- [[{page}]] — конфликтующие источники: {sources}; после проверки удалите маркер contradictions:',
    lintQuoteGroundingSection: 'Неподтверждённые цитаты (обнаружено) [{count}]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: «{quote}»',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (страница не существует){dupFlag}',
    lintDeadLinkMore: '- ... ещё {count} мёртвых ссылок',
    lintEmptyPageItem: '- [[{page}]] — менее 50 символов содержательного текста',
    lintOrphanItem: '- [[{page}]] — никакие другие страницы Wiki не ссылаются сюда{dupFlag}',
    lintDuplicateItem: '- [[{target}]] и [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ затрагивает дублирующуюся страницу)',
    lintOrphanIsDuplicate: ' (⚠️ дублирующаяся страница)',
    lintHubLinkDensitySection: 'Проблемы плотности хаб-ссылок (Issue #157 / #175) [{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} входящих, {relatedCount} связанных ссылок, отличительность {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ удалить',
    lintHubLinkDensityReview: '🔍 проверить',
    lintHubLinkDensityKeep: '✅ оставить',
    lintHubLinkDensitySummary: 'Сводка: {strip} стр. рекомендовано для удаления, {review} стр. рекомендовано для проверки.',
    lintHubLinkDensityNoRelated: ' (раздел ## Related не найден)',
    lintContradictionOpen: 'Открытые противоречия: {count}',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: 'Обнаружено',

    // Промпт Lint-анализа

    // Прогресс исправления Lint
    lintFixProgress: 'Исправление {current}/{total}: [[{target}]]',
    lintFixDeadComplete: 'Исправление мёртвых ссылок завершено. Исправлено {fixed}/{total} элементов.',
    lintFillProgress: 'Расширение {current}/{total}: {page}',
    lintFillComplete: 'Расширение страниц завершено. Заполнено {filled}/{total} стр.',
    lintDeleteCompleted: 'Удалено {count} пустых заглушек',
    lintDeleteFailed: 'Не удалось удалить {failed}/{total} пустых заглушек (см. подробности в консоли)',
    lintFillFailed: 'Не удалось расширить: {page} — {error}',
    lintLinkProgress: 'Привязка {current}/{total}: {page}',
    lintLinkComplete: 'Привязка висячих страниц завершена. Привязано {linked} стр.',
    lintFixNoAction: 'Действие не предпринято (нет клиента)',
    lintFixIndexUpdated: 'Индекс Wiki и журнал обновлены.',
    lintFixAllComplete: 'Все исправления завершены. См. подробности в журнале.',
    lintFixAllNoChanges: 'Никаких изменений не было сделано — все фазы сообщили о 0 исправлений. Проверьте wiki/log.md для подробностей.',
    lintFixPhasesLabel: 'фаз изменено',
    lintPollutedFixed: 'Загрязнённые страницы исправлены: {fixed}/{total}. Индекс перегенерирован.',
    regenerateIndexCompleted: 'Индекс перегенерирован',
    operationFailed: 'Не удалось: ',

    // Модальное окно отчёта Lint
    lintModalActionsTitle: 'Предложения исправлений (требуются токены LLM):',
    lintLogReference: 'Полный отчёт сохранён в log.md',
    lintModalFixDeadLinks: 'Исправить мёртвые ссылки ({count})',
    lintModalExpandEmpty: 'Расширить пустые страницы ({count})',
    lintModalDeleteEmpty: 'Удалить пустые заглушки ({count})',
    lintModalLinkOrphans: 'Привязать висячие страницы ({count})',
    lintModalAnalyzeSchema: 'Анализ схемы',
    lintModalMergeDuplicates: 'Объединить дубликаты ({count})',
    lintModalFixAll: 'Smart fix всех ({count} проблем)',
    lintMergeProgress: 'Слияние {current}/{total}: {source} → {target}',
    lintMergeComplete: 'Слияние дубликатов завершено. Объединено {merged}/{total} пар.',

    // Модальное окно отчёта об импорте
    ingestReportTitle: 'Отчёт об импорте',
    ingestReportSourceFile: 'Исходный файл',
    ingestReportCreated: 'Создано',
    ingestReportUpdated: 'Обновлено',
    ingestReportContradictions: 'Найдены противоречия',
    ingestReportFailedTitle: 'Не удалось импортировать',
    ingestReportErrorDetail: 'Подробности ошибки',
    ingestReportClose: 'Закрыть',
    ingestReportCreatedPages: 'Создано страниц: {count}',
    ingestReportUpdatedPages: 'Обновлено страниц: {count}',
    // v1.22.2: содержимое заголовка log.md (подсказка панели истории операций)
    logHeaderTitle: 'Журнал операций Wiki',
    logHeaderSubtitle: 'Каждый импорт, запуск lint и операция обслуживания автоматически записываются сюда. Для лучшего опыта используйте панель **Operation History**:',
    logHeaderShortcut: 'Cmd+P → «View operation history»',
    logHeaderSettingsShortcut: 'Или откройте из Настройки → Автоматическое обслуживание → История операций',
    // v1.22.2: краткие метки сводки импорта для Notice (без модального окна)
    ingestionCreatedPages: '{count} стр. создано',
    ingestionUpdatedPages: '{count} стр. обновлено',
    ingestionNoticeHistoryHint: 'Просмотрите историю операций для подробностей.',
    ingestReportEntitiesCount: '{count} сущностей',
    ingestReportConceptsCount: '{count} концепций',
    ingestReportContradictionsFound: 'Найдены противоречия: {count}',
    ingestReportEntityType: 'Сущность',
    ingestReportConceptType: 'Концепция',
    timeMinutes: 'мин',
    timeSeconds: 'сек',

    // Предупреждения об ограничении скорости
    rateLimitDetected: '⚠️ Обнаружено ограничение скорости: {count} стр. не удались с ошибками 429. Попробуйте: (1) Снизить параллелизм до {suggestedConcurrency} или 1 (последовательно), (2) Увеличить задержку пакета до {suggestedDelay} мс, (3) Переключиться на провайдера с более высокими лимитами скорости.',
    rateLimitDetectedShort: '⚠️ Достигнут лимит скорости — рассмотрите снижение параллелизма или увеличение задержки пакета в Настройки → Ускорение импорта.',

    // Предупреждение о длинном источнике
    sourceRejectedEmpty: '⏭️ «{filename}» не имеет содержимого для импорта — пропущено. Пустые заметки или заметки только с frontmatter не создают страниц Wiki.',
    sourceRejectedType: '⏭️ «{filename}» — неподдерживаемый тип файла — пропущено. Импортировать можно только текстовые заметки (например, .md, .txt).',
    sourceRejectedDuplicate: '⏭️ «{filename}» пропущено — его содержимое уже в Wiki.',
    // v1.25.0 PDF Level 1 (cache-only architecture)
    pdfReadingInProgress: 'Чтение PDF: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ «{filename}» пропущено — ваш текущий провайдер или модель не принимает PDF-вход. Переключите провайдера или откройте Настройки → Конфигурация LLM → Расширенные и включите «Force PDF support», чтобы попробовать всё равно, или переключите бэкенд конвертации Markdown на MinerU (также обрабатывает изображения и документы Office).',
    clearPdfCacheCommand: 'Очистить кэш конвертации PDF',
    pdfCacheCleared: 'Кэш PDF очищен ({count} записей удалено).',
    // v1.25.0 PR3: расширенные настройки PDF
    forcePdfSupportName: 'Принудительная поддержка PDF',
    forcePdfSupportDesc: 'Выкл по умолчанию. Включите, если ваш провайдер не указан как нативный, но всё же может обрабатывать PDF-файлы. Когда вкл, PDF будет отправлен вашему текущему провайдеру — если будет отклонён, вы увидите чёткое уведомление. Нативным PDF-провайдерам (Anthropic / OpenAI / Bedrock) это не нужно.',
    writePdfMarkdownToVaultName: 'Записать конвертированный Markdown в хранилище',
    writePdfMarkdownToVaultDesc: 'Выкл по умолчанию. Когда вкл, каждый результат конвертации PDF записывается в файл «<basename>.pdf.md» рядом с исходным PDF. Когда выкл (архитектура только-кэш), результаты живут только в кэше плагина и не оставляют артефактов в вашем хранилище.',
    markdownConversionBackendName: 'Способ конвертации Markdown',
    markdownConversionBackendDesc: 'Используйте встроенную поддержку PDF вашего провайдера (ограниченная область применения, не все провайдеры/модели работают с PDF, расходует токены LLM). MinerU — это онлайн-сервис — быстрый, бесплатный до дневной квоты, принимает PDF/изображения/Office — но требует токен API (укажите его в поле ниже).',
    markdownConversionBackendNative: 'Поддержка PDF/изображений провайдером',
    markdownConversionBackendMineru: 'Онлайн API MinerU',
    mineruApiBaseUrlName: 'Базовый URL API MinerU',
    mineruApiBaseUrlDesc: 'Базовый URL для API MinerU. По умолчанию: https://mineru.net/api/v4. Укажите свой URL при использовании прокси, зеркала или собственного сервера.',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'Токен API MinerU',
    mineruApiTokenDesc: 'Получите токен на https://mineru.net/apiManage/token. MinerU принимает файлы до 200 МБ и до 200 страниц.',
    mineruApiTokenPlaceholder: 'Вставьте токен API MinerU',
    mineruUploadingInProgress: 'Загрузка PDF в MinerU: {filename}',
    mineruWaitingInProgress: 'Ожидание конвертации MinerU: {filename}',
    mineruDownloadingInProgress: 'Загрузка результата MinerU: {filename}',
    markdownConversionComplete: 'Конвертация завершена: {filename}',
    markdownConversionCompleteSaved: 'Конвертация завершена — записано в {path}: {filename}',
    mineruPageLimitRejected: '{filename} превышает лимит MinerU в {limit} страниц — разделите файл и повторите попытку',
    mineruSizeLimitRejected: '{filename} превышает лимит размера MinerU в {limit} МБ',
    ingestRejectedSummary: '{count} файл(ов) пропущено (пусто, дубликат или неподдерживаемый тип).',
    reingestConfirmTitle: 'Повторно импортировать этот файл?',
    reingestConfirmBody: 'Содержимое «{filename}» уже в Wiki. Повторно импортировать?',
    reingestConfirmYes: 'Повторно импортировать',
    reingestConfirmNo: 'Пропустить',
    lintDedupIncludeSourcesName: 'Включать источники в дедупликацию',
    lintDedupIncludeSourcesDesc: 'Включено по умолчанию. Если включено, источники с идентичным содержимым помечаются как дубликаты во время lint. Отключите, если ваш корпус источников даёт ложные срабатывания.',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: 'Пропускать кандидатов, которых источник лишь упоминает',
    skipMentionOnlyCandidatesDesc: 'По умолчанию выключено. Если включено, извлечённая сущность или концепция, имя которой не встречается в связном тексте заметки — отсутствует или есть только в скобках, перечислениях или коротких пунктах списка — не получает страницы и дальнейших вызовов модели и удаляется из списков связанных у других кандидатов. Работает для языков вики с профилем границ слов (немецкий измерен; английский, французский, испанский, португальский, нидерландский оценочно); для других языков инжест один раз сообщает, что не может примениться. Оставьте выключенным для хранилищ типа глоссария или заметок-списков, где каждый названный термин должен стать страницей.',
    createStubsForUnresolvableLinksName: 'Создавать страницы-заглушки для неразрешённых ссылок',
    createStubsForUnresolvableLinksDesc: 'По умолчанию включено. Когда «Исправить мёртвые ссылки» не может разрешить ссылку ни на одну существующую страницу, создаётся пустая страница-заглушка и ссылка переносится на неё — никогда не заполняется LLM. Выключите, чтобы оставлять такие ссылки нетронутыми: они остаются видимыми в каждом отчёте, пока их не определит реальный источник.',
    lintDedupSectionHeading: 'Дедупликация',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): общая формулировка,
    // пригодная для повторного использования во всех LLM-путях.
    // {count} — число пакетов, потребовавших повтора. Не пишем
    // "Lint завершён" — повтор восстанавливает только этот пакет.
    llmRetryRecoveredToast: 'Задача LLM: {count} пакет(ов) потребовали повтора из-за временной проблемы с ответом провайдера (автоматически восстановлено). Подробности в консоли. Если это повторяется, уменьшите Page Generation Concurrency в настройках провайдера.',
    longSourceNotice: '📄 «{filename}» содержит {lines} строк ({size}). Длинные тексты требуют итеративного пакетного извлечения — LLM читает полный документ за несколько проходов. Это может занять несколько минут. Пожалуйста, будьте терпеливы.',
    longSourceNoticeShort: '📄 Обнаружен большой файл ({lines} строк). Импорт может занять некоторое время.',

    // Панель истории импорта (#122) — ключи UI
    historyButton: 'История операций',
    historyButtonDesc: 'Просмотр недавних импортов, отчётов lint и других изменений, которые претерпела ваша Wiki',
    historyButtonOpen: 'Просмотр истории',
    historyModalTitle: 'История операций',
    historyModalSubtitle: 'Недавние операции из вашей LLM-Wiki',
    historyEmpty: 'Операции ещё не записаны. Импортируйте заметку или запустите Lint, чтобы заполнить этот список.',
    historyReadError: 'Не удалось прочитать журнал операций: {error}',
    historyEntryKindIngest: 'Импорт',
    historyEntryKindMaintenance: 'Обслуживание',
    historyEntryKindFix: 'Исправление',
    historyEntryKindOther: 'Операция',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'Источник: {source}',
    historyEntrySourceUnknown: 'Импорт без названия',
    historyEntryCreatedLabel: 'Создано',
    historyEntryUpdatedLabel: 'Обновлено',
    historyEntryCreatedCount: '{count} создано',
    historyEntryUpdatedCount: '{count} обновлено',
    historyEntryNoChanges: 'Без изменений страниц',
    historyEntryContradictions: '⚠️ {count} противоречие(й)',
    historyEntrySectionCreated: 'Созданные страницы',
    historyEntrySectionUpdated: 'Обновлённые страницы',
    historyEntrySectionContradictions: 'Противоречия',
    historyEntrySectionDetails: 'Подробности',
    historyEntrySectionReport: 'Результаты отчёта',
    historyEntryOpenPage: 'Открыть',
    historyEntryDetailsNoContradictions: 'Противоречий не найдено',
    historySearchPlaceholder: '🔍 Поиск по заголовку источника или пути страницы…',
    historyFilterAll: 'Все',
    historyFilterIngest: 'Только импорт',
    historyFilterMaintenance: 'Только обслуживание',
    historyFilterFix: 'Только исправления',
    historyFilterContradictions: '⚠️ Есть противоречия',
    historyRefreshButton: '⟳ Обновить',
    historyExpandDay: 'Нажмите для раскрытия',
    historyCollapseDay: 'Нажмите для сворачивания',
    historyShowMore: 'Показать {count} более старых записей',
    historyNoMatch: 'Никакие операции не соответствуют вашему поиску/фильтру.',
    historyCloseButton: 'Закрыть',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    // Метки KPI (панель истории операций v2)
    historyKpiPages: 'Стр.',
    historyKpiDeadLinks: 'Мёртвые ссылки',
    historyKpiOrphans: 'Висячие',
    historyKpiEmpty: 'Пустые',
    historyKpiDuplicates: 'Дубликаты',
    historyKpiTagViolations: 'Проблемы с тегами',
    historyKpiUnsourced: 'Без источника',
    historyKpiDuration: 'Время Lint',
    historyKpiDurationSec: '{seconds} с',
    // История операций v3 — богатый рендеринг секций
    historySectionDeadLinks: 'Мёртвые ссылки ({count})',
    historySectionTagViolations: 'Проблемы с тегами ({count})',
    historySectionOrphans: 'Висячие страницы ({count})',
    historySectionEmptyPages: 'Пустые страницы ({count})',
    historySectionLlmAnalysis: 'LLM-анализ ({count})',
    historyDeadLinkSource: 'Источник',
    historyDeadLinkTarget: 'Отсутствует',
    historyOpenInLog: 'Открыть в log.md',
    historyShowMoreItems: 'Показать ещё {count}',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ без изменений',
    historyChipContradiction: 'Противоречие',
    historyChipOutdated: 'Устарело',
    historyChipMissing: 'Отсутствует',
    historyChipStructure: 'Структура',
    historySeverityHigh: 'Высокая',
    historySeverityMedium: 'Средняя',
    historySeverityLow: 'Низкая',
    historyPageTypeEntity: '📦 сущность',
    historyPageTypeConcept: '💡 концепция',
    historyPageTypeSource: '📄 источник',
    historyGlobalInsight: 'Ваша Wiki имеет {dead} мёртвую(ых) ссылку(и), {orphans} висячую(их) стр. и {tags} проблему(ы) с тегами. Последний Lint занял {duration}.',
    historyGlobalInsightClean: 'Ваша Wiki чиста — мёртвых ссылок, висячих стр. или проблем с тегами не обнаружено.',
    historyGlobalInsightNoData: 'Отчётов об обслуживании ещё нет — запустите Lint, чтобы заполнить.',
    // v3.1 — заголовок модального окна, подзаголовок с количеством, фильтр временного диапазона
    historyModalHeaderTitle: 'История операций',
    historyModalSubtitleWithCount: 'Недавние операции из вашей LLM-Wiki · {count} записей',
    historyTimeRangeAll: 'За всё время',
    historyTimeRange1d: 'За последний день',
    historyTimeRange3d: 'За последние 3 дня',
    historyTimeRange1w: 'За последнюю неделю',
    historyTimeRange1m: 'За последний месяц',
    // v3.1 — карточки метрик импорта
    historyIngestTotal: 'Всего страниц',
    historyIngestByType: 'По типу',
    historyIngestSource: 'Исходный файл',
    historyIngestNoTimestamp: 'Без метки времени',
    historyIngestFirstTime: 'Первый импорт',
    historyIngestLatestTime: 'Последний импорт',
    historyTimeRangeCustom: 'Пользовательский диапазон',
    historyCustomRangeFrom: 'От',
    historyCustomRangeTo: 'До',
    historyCustomRangeApply: 'Применить',
    historyCustomRangeClear: 'Очистить',
    // v1.23.0 — приветственная заметка при первом запуске (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki: хранилище пусто. Создайте первую исходную заметку и запустите Импорт, чтобы начать.',
    welcomeNoteTierBNotice: 'Karpathy Wiki: создана приветственная заметка. Откройте её, чтобы объявить ваши домены и выбрать 2-3 исходные заметки для заполнения графа ссылок.',
    welcomeNoteRecreateCommand: 'Пересоздать приветственную заметку Wiki',
    welcomeNoteRecreateCommandTooltip: 'Пересоздать приветственную заметку по адресу <wikiFolder>/Welcome.md с текущими доменными сидами и тестом конфигурации LLM. Существующий файл перезаписывается.',
    welcomeNoteSettingsToggle: 'Создавать приветственную заметку Wiki при первом запуске',
    welcomeNoteSettingsToggleDesc: 'При самом первом запуске (когда папка Wiki пуста) создать одностраничную ознакомительную заметку по адресу <wikiFolder>/Welcome.md. Она объясняет, что делает LLM-Wiki, просит объявить ваш доменный фокус и проводит через импорт первых 2-3 исходных заметок. Заметка пишется на английском по умолчанию или на вашем языке Wiki, если LLM настроена. Отключите это, если вы уже знаете, как работает плагин, и не хотите, чтобы ознакомительная заметка загромождала ваше хранилище.',
    welcomeNoteRunConfigTest: 'Приветственная заметка написана на английском. Откройте Настройки → Провайдер LLM → Проверить подключение, чтобы локализовать её при следующем пересоздании.',
    welcomeNoteRecreated: 'Приветственная заметка Wiki пересоздана по адресу {path}',
    welcomeNoteNotRecreated: 'Приветственная заметка Wiki не была пересоздана. Проверьте конфигурацию LLM.',
    welcomeNoteGenerating: 'Приветственная заметка Wiki: генерация в фоне — вы получите уведомление по завершении.',
    welcomeNoteGenerationFailed: 'Не удалось сгенерировать приветственную заметку Wiki: {error}',
    welcomeNoteFileName: 'Добро пожаловать в Karpathy LLM Wiki',
    startupCheckWelcomePending: 'Приветственная заметка: генерация в фоне (вы получите уведомление по завершении).',
    startupCheckWelcomeCreated: 'Приветственная заметка создана по адресу {path}',
    // v1.23.0 Phase 5.1.5: модальное окно Multi-File Suggest (cmdIngestMultipleFiles).
    // Заголовок, подсказка, заполнитель поиска, кнопки действий,
    // метки статуса и заполнитель пустой очереди модального окна живут здесь. Метки
    // статуса также используются как ключи атрибутов данных для
    // `updateLeftPaneSelections`, поэтому они должны оставаться стабильными английскими строками.
    multiFileModalTitle: 'Импорт нескольких файлов',
    multiFileModalHint: 'Выберите исходные заметки для импорта. Правая панель показывает живую очередь импорта и прогресс.',
    multiFileSearchPlaceholder: 'Фильтровать файлы по пути…',
    multiFileAddToQueue: 'Добавить в очередь',
    multiFileSelectAll: 'Выбрать все',
    multiFileFileCount: '{count} файл(ов)',
    multiFileNoFilesAvailable: 'Нет файлов для импорта.',
    multiFileNoFilesMatch: 'Никакие файлы не соответствуют «{q}».',
    multiFileQueueEmpty: 'Очередь пуста. Отметьте файлы слева, чтобы добавить их.',
    multiFileStatusPending: 'В ожидании',
    multiFileStatusRunning: 'Выполняется',
    multiFileStatusCompleted: 'Завершено',
    multiFileStatusFailed: 'Не удалось',
    multiFileCancelAria: 'Отменить этот файл',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: 'Импортировано',
    multiFileRowDrifted: 'Заметка изменена после импорта',
    // v1.23.0 Phase 5.1.5: кнопка действия модального окна Multi-File Suggest,
    // которая удаляет каждое задание в ожидании и выполнении из очереди
    // импорта. Завершённые и неудачные задания сохраняются, чтобы пользователь
    // всё ещё видел, что произошло.
    cancelAllQueueJobs: 'Отменить все',
} as const;
