export const ZH_HANT_TEXTS = {
    // 插件信息
    pluginTitle: 'Karpathy LLM Wiki 設定',
    pluginIntro: '本外掛為 Obsidian 實現了 {{link}} 概念。它讀取你的筆記，用 AI 提取實體和概念，在 Vault 中構建結構化、互聯的知識庫。',
    karpathyLinkText: 'Andrej Karpathy 的 LLM Wiki',

    // 功能部分
    featuresTitle: '使用方式',
    workflow1Title: '1. 攝入 (Ingest)',
    workflow1Desc: '選擇筆記 → AI 提取實體、概念、關係 → 生成 Wiki 頁面。',
    workflow2Title: '2. 查詢 (Query)',
    workflow2Desc: '與 Wiki 對話，答案基於你已攝入的知識，而非通用知識。',
    workflow3Title: '3. 維護 (Maintain)',
    workflow3Desc: '自動生成索引、交叉連結、健康檢查，保持 Wiki 整潔。',

    // 语言切换
    languageTitle: '介面語言',
    languageDesc: '選擇設定面板的顯示語言。重啟外掛以將語言更改應用到命令面板。',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // 状态
    statusTitle: 'LLM Client 狀態',
    llmWikiStatusSection: 'LLM-Wiki 狀態',
    statusInitialized: '已初始化',
    statusReady: 'LLM 已就緒',
    statusNotReady: 'LLM 未配置 — 請完成上方設定並透過連線測試',
    statusNotInitialized: '未初始化',
    currentProvider: '當前提供商',

    // Provider 设置
    providerSection: 'LLM 配置',
    providerName: 'LLM Provider',
    providerDesc: '選擇預定義提供商或自定義 OpenAI 相容服務。對於 Coding Plan 等套餐，建議選擇自定義 OpenAI/Anthropic 並手工填寫對應 URL 和 API Key',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: 'API 金鑰。儲存在作業系統憑證管理員中,不寫入 data.json。',
    apiKeyPlaceholder: '輸入 API Key',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: '遷移 SecretStorage',
    apiKeyMigratedToSecretStorageSuccess: 'API Key 已從 SecretStorage 還原到設定。',
    apiKeyMigrationFailedNotice: '無法將 API Key 保存到 SecretStorage：{}',
    codexAuthName: '登入 ChatGPT 方案',
    codexAuthDesc: '透過實驗性的 Codex OAuth 使用 ChatGPT 方案額度。OpenAI Platform API 仍會另外計費。',
    codexAuthSignedOut: '未登入',
    codexAuthSignedIn: '已登入',
    codexAuthBrowserButton: '使用瀏覽器登入',
    codexAuthDeviceButton: '使用裝置代碼',
    codexAuthDeviceInstructions: '在 OpenAI 頁面輸入此代碼：{}',
    codexAuthCopyCode: '複製代碼',
    codexAuthSignOutButton: '登出',
    codexAuthBusy: '正在等待 OpenAI 授權…',
    codexAuthFailed: 'ChatGPT 授權失敗：{}',
    codexAuthQuota: 'ChatGPT Codex 額度已用完。請等待顯示的重設時間後再試一次。',
    codexAuthExperimental: '實驗性功能：可用性取決於 OpenAI Codex 的驗證與模型政策。',
    codexModelsRefreshName: '帳戶可用模型',
    codexModelsRefreshDesc: '從目前登入的 OpenAI Codex 帳戶同步可選模型。',
    codexModelsRefreshButton: '重新整理帳戶模型',
    codexModelsRefreshing: '正在重新整理…',
    codexModelsRefreshSuccess: '已同步 {} 個帳戶模型。',
    codexModelsRefreshFailed: '帳戶模型重新整理失敗，目前使用可用的備用清單。{}',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: '必填：自定義 OpenAI 相容服務的 endpoint',
    baseUrlDescOverride: '可選：覆蓋預設的 Base URL',

    // Issue #723: custom request headers (shown directly below the Base URL).
    customHeadersName: '自訂請求標頭',
    customHeadersDesc: '每行一項 `名稱: 值`。每次請求都會送出；空行與 `#` 註解會被忽略。',
    customHeadersInvalid: '{} 行格式無效，將被忽略。',

    // Ollama 提示
    ollamaHint: 'Ollama 本地執行，無需 API Key',
    lmstudioHint: 'LM Studio 本地執行，API Key 可選',
    maxTokensPerCallName: '每次呼叫的最大輸出 Token 數',
    maxTokensPerCallDesc: '限制模型單次回應能產生的 Token 數量。如果你用本地小上下文視窗模型且遇到報錯，可以調低。雲端模型保持預設（0 = 不限制）即可。',

    slugCaseName: '檔名大小寫',
    slugCaseDesc: '控制生成的 Wiki 檔名是否轉為小寫。對於大小寫有語義的語言（如德語名詞），建議選擇“保留”。',
    slugCaseLower: '小寫（預設）',
    slugCasePreserve: '保留大小寫',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: '別名最小長度',
    minAliasLengthDesc: '短於此長度的別名（去除首尾空白後）不會寫入 wiki 頁面。預設值 2 保留兩字母縮寫（ML、AI、UI）；若庫中累積了僅大小寫不同的兩字母別名（Cr/CR），可調到 3。範圍 2–6。',
    minAliasLengthClamped: '數值超出範圍（2–6），已設為 {}',

    // 模型选择
    modelSection: '模型選擇',
    fetchModelsName: '獲取可用模型',
    fetchModelsDesc: '從 Provider API 獲取最新的模型列表',
    fetchModelsButton: '獲取模型列表',
    fetchingModels: '獲取中...',
    fetchSuccess: '獲取成功！共 {} 個可用模型',
    fetchFailed: '獲取失敗或列表為空，請手動輸入模型名稱',
    fetchNotSupported: '該 Provider 不支援模型列表查詢',
    fetchErrorAuth: '認證失敗（HTTP 401/403）。請檢查 API Key 是否正確，或直接輸入模型 ID 後點選測試連線進行驗證。',
    fetchErrorEndpoint: '接入點未找到（HTTP 404）。請檢查 BaseURL 是否正確，或直接輸入模型 ID 後點選測試連線。',
    fetchErrorServer: 'Provider 服務端錯誤（HTTP 5xx）。稍後重試，或直接輸入模型 ID 後點選測試連線。',
    fetchErrorEmpty: '該接入點不支援列出模型列表。請直接輸入模型 ID 後點選測試連線進行驗證。',
    fetchErrorNetwork: '網路請求失敗。請檢查網路連線、BaseURL、代理設定或 API Key。您也可以直接輸入模型 ID 後點選測試連線進行驗證。',

    selectModelName: '選擇模型',
    selectModelDesc: '從 {} 個可用模型中選擇',
    customInputOption: '自定義輸入...',
    customInputHint: '如需使用其他模型，請選擇"自定義輸入..."',

    modelName: '模型名稱',
    modelDescCustom: '當前使用自定義模型（可重新獲取列表）',
    modelDescFetchFailed: '模型列表獲取失敗。請檢查 API Key 和接入點 URL，或直接輸入模型 ID 後點選測試連線進行驗證。',
    modelInputPlaceholder: '輸入模型 ID，然後點選測試連線',

    switchToDropdown: '切換到下拉選擇',
    useDropdownButton: '使用下拉選擇',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: '模型作用範圍',
    modelTaskModeDesc: '選擇所有任務使用同一個模型，還是按任務分別使用不同模型（擷取 / 維護修復 / 查詢）。切換回統一模型時，已填的分任務模型會被保留而不會被清空。',
    modelTaskModeUnified: '使用統一模型（預設）',
    modelTaskModePerTask: '為不同任務使用不同模型',
    perTaskIngestModelName: '擷取模型',
    perTaskIngestModelDesc: '用於擷取筆記、對話、Schema 維護以及歡迎筆記生成。',
    perTaskLintModelName: '維護修復模型',
    perTaskLintModelDesc: '用於 Lint 分析、重複偵測、各種修復任務以及孤兒連結修正。',
    perTaskQueryModelName: '查詢模型',
    perTaskQueryModelDesc: '用於 Query Wiki 對話與儲存到 Wiki 評估。',

    // 测试 & 保存
    testConnectionName: '測試連線',
    testConnectionDesc: '驗證配置能否成功呼叫 LLM API',
    testButton: '測試連線',
    testing: '測試中...',

    saveSettingsName: '儲存設定',
    saveSettingsDesc: '儲存當前配置',
    saveButton: '儲存設定',
    testConnectionSuccessful: '連線成功',
    testConnectionFailed: '連線失敗',
    testConnectionProvider: '提供商：',
    codexAuthRequired: '測試連線前，請先登入 ChatGPT 方案。',
    bedrockSsoRequired: '測試連線前，請先在 設定 → Bedrock 中完成 AWS SSO 登入。',
    bedrockIamRequired: '測試連線前，請先在 設定 → Bedrock 中輸入您的 IAM 存取金鑰。',
    bedrockAuthMethodName: '驗證方式',
    bedrockAuthMethodDesc: 'API 金鑰使用 Bedrock API 金鑰；AWS SSO 使用 IAM Identity Center 憑證對請求簽章；IAM 金鑰使用靜態存取金鑰。',
    bedrockAuthOptionApiKey: 'API 金鑰',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'IAM 金鑰',
    bedrockSsoStartUrlName: 'SSO 起始 URL',
    bedrockSsoStartUrlDesc: '您組織的入口網站 URL，例如 https://d-xxxxxxxxx.awsapps.com/start',
    bedrockSsoAccountIdName: 'AWS 帳戶 ID',
    bedrockSsoAccountIdDesc: '要擔任角色的 12 位帳戶 ID，例如 123456789012',
    bedrockSsoRoleNameName: '角色名稱',
    bedrockSsoRoleNameDesc: '用於 Bedrock 存取的 IAM 角色，例如 PowerUserAccess',
    bedrockSsoLoginButton: '使用 AWS SSO 登入',
    bedrockSsoSignOutButton: '登出 AWS SSO',
    bedrockSsoStatusSignedIn: '已登入 · {} 到期',
    bedrockSsoStatusSignedOut: '尚未登入',
    bedrockSsoBusy: '正在登入…',
    bedrockSsoUserCodeInstructions: 'AWS SSO 驗證碼：{}。請開啟連結並核准存取。',
    bedrockSsoCopyCode: '複製驗證碼',
    bedrockSsoFailed: 'AWS SSO 登入失敗：{}',
    bedrockSsoDetectedPrefill: '偵測到帳戶/角色：{}',
    bedrockIamKeyName: '存取金鑰 ID',
    bedrockIamKeyDesc: 'IAM 存取金鑰識別，例如 AKIA… 或 ASIA…',
    bedrockIamSecretName: '私密存取金鑰',
    bedrockIamSecretDesc: '僅儲存在本裝置的金鑰存放區中，絕不會寫入 data.json',
    bedrockIamSessionTokenName: '工作階段權杖（選填）',
    bedrockIamSessionTokenDesc: '僅臨時憑證（STS）需要',
    bedrockIamClearButton: '清除已儲存的 IAM 金鑰',
    bedrockIamSaveFailed: 'IAM 金鑰儲存失敗：{}',
    errorUnknown: '未知錯誤',
    savedNotice: '設定已儲存！',

    // v1.24.0 (Bug C 3.4 / plan C): 漸進式遷移通知
    queryHistoryMigrationNotice: 'Query Wiki 歷史紀錄中含有舊 wiki 目錄的連結。新的對話已自動使用最新目錄。如需重整所有歷史訊息，請開啟 Query Wiki 面板並點選其中的「清除紀錄」按鈕。',

    // v1.24.0 Issue #251: 自訂 Query 指令（可折疊面板）
    customInstructionsTitle: '自訂 Query 指令',
    customInstructionsDesc: '每次 Query Wiki 對話都會在系統提示字串末尾附加這些指令。僅影響 Query Wiki 聊天；不會影響擷取、lint 與頁面生成。',
    customInstructionsPlaceholder: '例如：將此視為研究任務：廣泛搜尋、引用來源、區分事實與詮釋...',
    customInstructionsApply: '套用',
    customInstructionsClear: '清除',
    customInstructionsCharCount: '{current}/{max} 字元',
    instructionsApplied: '自訂 Query 指令已儲存。',
    instructionsCleared: '自訂 Query 指令已清除。',

    // Issue #137: LLM 回退通知（请求中触发 thinking-dialect 回退或字段剥离时显示）
    fallbackThinkingDialect: '思考控制：已切換至 "{dialect}" 方言（該提供商使用不同的思考控制欄位格式）。輸出內容不受影響。',
    fallbackThinkingNone: '該提供商已完全關閉思考控制。模型仍可能產生推理內容；若出現，請嘗試其他模型。',
    fallbackParamStripped: '引數 "{field}" 不被該提供商支援。已從請求中移除；行為可能與配置不同。',

    // Wiki 文件夹
    wikiSection: 'Wiki 配置',
    wikiFolderName: 'Wiki 資料夾',
    // v1.24.0: 提示需重啟 Obsidian 以讓 engine 快取和開啟的 Query Wiki 面板重新綁定
    wikiFolderDesc: '存放生成的 Wiki 頁面。修改後需重啟 Obsidian 才能生效——engine 快取和已開啟的 Query Wiki 面板需要重新綁定。',
    wikiFolderPlaceholder: 'wiki',

    // 错误
    errorNoApiKey: '請先配置 API Key',
    errorNoModel: '請先選擇模型 — 點擊「獲取模型列表」，或手動輸入 Model ID',
    llmNotReady: 'LLM 尚未配置。請前往 設定 → Karpathy LLM Wiki 完成 Provider 配置、獲取模型列表並透過連線測試。',
    errorFetchFailed: '獲取失敗：{}',

    // Query 设置
    querySectionTitle: 'Wiki 查詢配置',
    // v1.24.0: 將「對話歷史上限」重命名為「對話關聯記憶輪數」，更貼切語義
    // 1 = 每輪對話獨立（不關聯前文）。設定為下拉選單，無需列出預設值。
    // v1.24.0: maxConversationHistoryHint 為死 i18n key（UI 無引用），推薦文案已併入 desc。
    maxConversationHistoryName: '對話關聯記憶輪數',
    maxConversationHistoryDesc: 'LLM 在新對話中可見的過往輪次數（作為記憶）。1 = 每輪對話獨立（不關聯前文）；數值越高，模型能記住會話中越早的輪次。推薦：一次性問答選 1；持續性研究選 10–50。',
    numberRangeValidation: '請輸入1-50之間的數字',
    numberRangeClamped: '數值超出範圍（1-500），已自動設定為 {}',

    // Query Modal UI
    queryModalTitle: 'Query Wiki - 對話式查詢',
    queryModalPlaceholder: '輸入問題...',
    queryModalSendButton: '傳送',
    queryModalStopButton: '停止',
    queryModalSaveButton: '儲存到Wiki',
    queryModalClearButton: '清空歷史',
    queryModalHistoryCount: '對話歷史: {}/{} 輪',
    queryModalStreaming: '流式生成中...',
    queryModalFallbackStreaming: '端點不支援流式傳輸，已回退至非流式模式，請耐心等待...',
    queryPhaseSearching: '正在分析 Wiki 索引，查詢相關資料...',
    queryPhaseFoundPages: '找到 {count} 個資料：{pages}',
    queryPhaseLoadingPages: '正在載入頁面內容...',
    queryPhaseContextReady: '資料就緒，正在生成回覆...',
    queryPhaseGenerating: '正在生成回覆...（已等待 {time}s）',
    queryPhaseNonStreaming: '非流式模式，生成中，請耐心等待...（已等待 {time}s）',
    queryModalErrorPrefix: '錯誤：',
    queryModalHint: '查詢基於Wiki內容。點選"儲存到Wiki"可將有價值對話提煉為Wiki頁面。',

    // v1.20.0: Query Wiki 思考内容折叠摘要
    queryThinkingSummary: '思考過程',
    queryThinkingSteps: '步',

    // 错误消息
    errorLLMClientNotInit: 'LLM Client 未初始化。請儲存設定。',
    errorIngestFailed: '攝入失敗：',
    errorQueryFailed: '查詢失敗：',
    fileWriteFailed: '無法建立或更新檔案：{path}',

    // 成功消息
    ingestSuccess: '攝入成功：建立{}頁，更新{}頁',
    querySuccess: '查詢完成',
    lintSuccess: 'Wiki 維護完成',
    lintReadingPages: '正在讀取 {count} 個 Wiki 頁面...',
    lintReadingPagesProgress: '正在讀取 Wiki 頁面：{current}/{total}...',
    lintScanningLinks: '正在掃描斷鏈...',
    lintScanningLinksProgress: '正在掃描斷鏈：{current}/{total}...',
    lintCheckingDuplicates: '正在檢查重複頁面...',
    lintCheckingDuplicatesProgress: '正在校驗重複項：批次 {current} ...',
    lintFixingPolluted: '正在修復汙染頁面 {current}/{total}：{title} → {newTitle}',
    lintModalFixPolluted: '🧹 修復汙染頁面（{count}）',
    lintDuplicateCheckFailed: '重複檢測失敗 — 詳見控制檯',
    lintDuplicateCheckFailedDetail: '重複檢測在{step}失敗：{error}',
    lintMergeItemFailed: '合併失敗：{source} → {target} — {error}',
    lintAliasesMissing: '檢測到 {count} 個頁面缺少別名',
    lintAliasesSection: '缺失別名的頁面（程式檢測）[共 {count} 個]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: '補全別名（{count}）',
    lintAliasesFilling: '生成別名 {current}/{total}：{page}',
    lintAliasesFilled: '別名補全完成。已填充 {filled}/{total} 頁。',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: '標籤越界（程式檢測）[共 {count} 個]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: '別名生成失敗：{page} — {error}',
    lintFixItemFailed: '修復失敗：[[{target}]] — {error}',
    lintLinkItemFailed: '連結失敗：{page} — {error}',
    lintRetrying: '出錯後重試中（{attempt}/{max}）...',
    lintAnalyzingLLM: 'LLM 正在分析 Wiki 健康狀態...',
    saveToWikiSuccess: '對話已儲存到Wiki！',
    querySaveAlreadyExists: '提示：未寫入任何內容（該知識已存在於 Wiki 中）：',
    saveSummary: '{entities} 個實體, {concepts} 個概念, {pages} 個頁面',
    aliasAdded: '已為頁面\'{page}\'新增別名\'{alias}\'',

    // 状态消息
    ingestingSources: '正在攝入原始檔...',
    queryingWiki: '正在查詢 Wiki...',
    lintingWiki: '正在維護 Wiki...',
    savingToWiki: '正在儲存對話到Wiki...',
    clearingHistory: '清空對話歷史...',

    // 按钮
    ingestButton: '攝入',
    queryButton: '查詢',
    lintButton: '維護',
    cancelButton: '取消',

    // 链接
    karpathyGistLink: 'Karpathy\'s LLM Wiki Gist',
    obsidianPluginAPI: 'Obsidian Plugin API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'AWS 區域',
    bedrockRegionDesc: '本帳號所在的 Amazon Bedrock 區域。驅動 bedrock-mantle 端點 URL；不能透過 baseURL 覆寫。',
    bedrockRegionHint: 'bedrock-mantle 在 18 個區域可用；各區域模型覆蓋範圍不同。',

    // 其他
    availableModelsLoading: '載入可用模型...',
    noModelsAvailable: '無可用模型',

    // LLM 语言提示
    llmLanguageHint: '請用中文回答。',

    // Schema 配置
    schemaSection: 'Schema 配置',
    enableSchemaName: '啟用 Schema',
    enableSchemaDesc: '生成 schema/config.md 並注入到所有 LLM 提示詞中，指導 Wiki 結構化輸出',
    viewSchemaButton: '檢視 / 編輯 Schema',
    regenerateSchemaButton: '重新生成預設 Schema',
    schemaRegeneratedNotice: '預設 Schema 已重新生成。',
    schemaRegenerateFailed: 'Schema 生成失敗',

    // Wiki 初始化状态
    wikiInitStatusReady: 'Wiki 已初始化',
    wikiInitStatusNotReady: 'Wiki 未初始化 — 將在首次攝入時自動建立',

    // Wiki 输出语言
    wikiLanguageName: 'Wiki 輸出語言',
    wikiLanguageDesc: '所有生成的 Wiki 頁面、索引、日誌和查詢回覆均使用此語言',
    customWikiLanguageOption: '自定義...',
    customWikiLanguageHint: '輸入語言名稱（如 Italian、Arabic），將作為輸出語言指令傳遞給 LLM。',
    customWikiLanguagePlaceholder: '例如：Italian',

    // 索引 & 日志标签（各语言）
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自動生成的知識庫目錄', entities: '實體', concepts: '概念', sources: '來源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // 知识提取
    extractionSectionTitle: '知識提取',
    extractionGranularityName: '提取顆粒度',
    extractionGranularityDesc: '控制每篇原始檔提取的實體/概念數量。越高 = 生成頁面越多，API消耗越大。\n精細：單篇深度。標準：日常筆記。粗放：快速概覽。極簡：批次100+檔案（限制每篇條目數約5條，而非單條細節）。自定義：自行設定（最高300個）。\n提示：批次處理大量檔案時，建議使用極簡或粗放以節省時間和成本。',
    extractionGranularityFine: '精細 — 單篇深度分析（≤100個）',
    extractionGranularityStandard: '標準 — 日常筆記（≤50個）',
    extractionGranularityCoarse: '粗放 — 快速概覽（≤10個）',
    extractionGranularityMinimal: '極簡 — 批次100+檔案（≤5個）',
    extractionGranularityCustom: '自定義 — 自行設定上限（1~500）',
    customEntityLimitName: '自定義實體上限',
    customEntityLimitDesc: '每篇原始檔最多提取的實體數量（1-500）',
    customConceptLimitName: '自定義概念上限',
    customConceptLimitDesc: '每篇原始檔最多提取的概念數量（1-500）',

    // Issue #85 v2: 标签词汇表 (chip input 交互, 嵌入 Wiki 配置)
    tagVocabularyInlineDesc: '為 entity 和 concept frontmatter 標籤設定受控詞彙。Obsidian 巢狀標籤 "/" 會被保留。',
    tagVocabularyModeName: '標籤（Tags)詞彙表配置',
    tagVocabularyModeDescDefault: '預設使用內建標籤: {}。切換到"自定義"可定義您自己的詞彙。',
    tagVocabularyModeDescCustom: '自定義：在下方使用 chip 輸入定義您自己的 entity 與 concept 標籤。回車或逗號新增, × 刪除。',
    tagVocabularyNotEnforcedHint: '僅作為架構提示——LLM 仍可能輸出詞彙外的類型。請執行 Lint 來查找並修復這些頁面。',
    tagVocabularyModeDefault: '預設 (內建子型別標籤)',
    tagVocabularyModeCustom: '自定義 (使用者定義)',
    customEntityTagsName: '自定義實體標籤',
    customEntityTagsDesc: '按回車或逗號新增 chip, 點 × 刪除。巢狀標籤 "/" 會被保留。',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: '自定義概念標籤',
    customConceptTagsDesc: '按回車或逗號新增 chip, 點 × 刪除。巢狀標籤 "/" 會被保留。',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: '重複標籤已跳過',

    // 摄入加速
    accelerationSectionTitle: '攝入加速',
    pageGenerationConcurrencyName: 'LLM 併發度',
    pageGenerationConcurrencyDesc: '攝入和 Lint 操作中的並行 LLM 呼叫數。數值越高處理越快，但會增加 API 消耗並可能觸發限流。',
    concurrencyValueSingular: '當前併發度：{}（序列 — 最安全）',
    concurrencyValuePlural: '當前併發度：{}（並行）',
    batchDelayName: '批次延遲 (ms)',
    batchDelayDesc: '並行批次間的延遲，防止 API 限流（100-10000ms）。當前值：{}ms。如遇 429 錯誤請增大此值。',

    // 自动维护
    autoMaintainSection: '自動維護',
    autoMaintainBetaBadge: 'BETA 測試 — 實驗性功能，可能存在問題，僅建議高階使用者使用。',
    autoWatchName: '監聽資料夾',
    autoWatchDesc: '自動檢測監聽列表中資料夾的新增或變更 .md 檔案，通知或自動攝入',
    watchedFoldersName: '監聽資料夾列表',
    watchedFoldersDesc: '監聽新內容的資料夾。點選「新增資料夾」從倉庫中選擇。',
    addWatchedFolderButton: '新增資料夾',
    removeWatchedFolderButton: '移除',
    webClipperPresetName: '監聽 Clippings（Web Clipper）',
    webClipperPresetDesc: '將 Obsidian Web Clipper 使用的 Clippings/ 資料夾加入監聽列表。網頁剪藏內容將自動攝入 Wiki。',
    noWatchedFoldersHint: '尚未配置監聽資料夾。請新增資料夾或啟用 Clippings 預設。',
    autoWatchModeName: '監聽模式',
    autoWatchModeDesc: '"僅通知"顯示提示。"自動攝入"靜默處理。',
    watchModeNotify: '僅通知',
    watchModeAuto: '自動攝入',
    autoWatchDebounceName: '防抖延遲 (秒)',
    autoWatchDebounceDesc: '檔案變更後等待多久觸發攝入 (1-60秒)',
    periodicLintName: '定時維護',
    periodicLintDesc: '定期檢查 Wiki 健康狀況，有原始檔變更時才執行 LLM 維護',
    periodicLintOff: '關閉',
    periodicLintDaily: '每天',
    periodicLintWeekly: '每週',
    periodicLintMonthly: '每月',
    autoSmartFixName: '自動智慧修復',
    autoSmartFixDesc: '執行 Lint 時，自動執行所有修復（智慧一鍵修復），無需顯示報告彈窗。修復完成後仍會顯示摘要。',
    autoSmartFixNotice: '自動智慧修復：正在應用所有修復...',

    autoIngestLevelName: '自動攝入通知方式',
    autoIngestLevelDesc: '自動攝入完成時的通知方式。「通知」短暫顯示不阻斷操作。「詳細報告」開啟完整報告彈窗。Watch 模式為「僅通知」時此選項無效。',
    autoIngestLevelNotice: '通知（不阻斷）',
    autoIngestLevelModal: '詳細報告（彈窗）',
    startupCheckName: '啟動時執行快速修復',
    startupCheckDesc: '外掛載入時自動修復低階格式問題（sources 欄位、雙層 wikilink），並驗證 Wiki 目錄結構。預設開啟。',
    suggestSchemaCommand: '建議 Schema 更新',
    autoMaintainCostWarning: '⚠️ 費用提醒：自動維護功能會消耗 API Token。"自動攝入"模式在每次原始檔變更時觸發 LLM 呼叫。"定時維護"定期執行 LLM 健康檢查（僅在有新變更時執行）。請謹慎配置以避免意外費用。',

    // 通知
    startupCheckSummary: 'Wiki 共 {pages} 頁（{entities} 個實體、{concepts} 個概念、{sources} 個來源）',
    watcherActiveNotice: 'Wiki: 檔案監聽已啟動 — 正在監控指定資料夾',
    watchIngestNotice: 'Wiki: sources/ 中有 {count} 個檔案變更。請執行"攝入原始檔"處理。',
    autoIngestRunning: '正在自動攝入 {count} 個變更檔案...',
    autoIngestComplete: '自動攝入完成：成功 {success}，失敗 {fail}',
    scheduledLintRunning: '正在執行定時 Wiki 維護...',
    wikiLintStats: 'Wiki 維護: 共 {pages} 頁（{entities} 實體, {concepts} 概念, {sources} 來源）',
    wikiHealthStats: 'Wiki 健康: 共 {pages} 頁（{entities} 實體, {concepts} 概念, {sources} 來源）{indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki 快速修復完成',
    startupCheckStructureLabel: 'Wiki 結構',
    startupCheckStructureOk: '完整',
    startupCheckStructureMissing: '不完整 — 將在首次攝入時自動建立',
    startupCheckSourcesLabel: 'Sources 歸一化',
    startupCheckSourcesClean: '已規範',
    startupCheckSourcesCleaned: '清理了 {files} 個檔案，{entries} 處條目',
    startupCheckIncompleteClean: '未完成頁面：無',
    startupCheckIncompleteArchived: '未完成頁面：歸檔了 {count} 個（可從 .trash 恢復）',
    startupCheckDisableHint: '如需關閉，前往 設定 → 自動維護 → 啟動時執行快速修復',
    lintWikiStart: '開始維護 wiki...',
    lintWikiComplete: '維護完成',
    lintWikiFailed: '維護失敗',
    analyzingSchema: '正在分析 Wiki 並生成 Schema 建議...',
    schemaSuggestionGenerated: 'Schema 建議已生成，請檢視 wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: '未檢測到 Schema 需要更新。',
    schemaSuggestionFailed: 'Schema 建議生成失敗',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Schema 更新預覽',
    schemaDiffSummary: '+{add} / -{del} 行',
    schemaDiffRegenerateLabel: '改進建議（可選）：',
    schemaDiffRegenerateBtn: '重新生成',
    schemaDiffOpenFileBtn: '開啟檔案',
    schemaDiffApplyBtn: '套用',
    schemaDiffApplied: 'Schema 已更新。備份：{path}',
    schemaDiffEmptyTitle: 'LLM 建議無需修改',
    schemaDiffFailed: 'Schema 套用失敗：{reason}',
    schemaDiffRestoreHint: '已備份到 {path}。若需恢復，請在檔案總管中將該檔案重新命名為 "wiki/schema/config.md"。系統會保留最近 3 個備份。',
    schemaRegenerateNoBody: '重新生成成功，但 LLM 未傳回新的 Schema。',
    schemaNotFoundNotice: 'Schema 檔案未找到。啟用 Schema 功能以建立它。',
    selectFolderNoMdFiles: '資料夾 {path} 中沒有 Markdown 檔案',
    batchIngestSkipNotice: '跳過 {skipped}/{total} 個已攝入檔案。正在攝入 {new} 個新檔案...',
    batchIngestAllIngested: '該資料夾中的所有 {total} 個檔案均已攝入。',
    batchIngestStarting: '正在從 "{folder}" 攝入 {count} 個檔案 — 可能需要數分鐘。完成後會顯示報告。',
    batchIngestComplete: '批次攝入完成: 成功 {success}/{total}, 失敗 {fail}',
    batchIngestFailedFiles: '失敗的檔案:',
    historyTruncated: '歷史已截斷至最近 {max} 輪對話',
    historyCleared: '歷史已清空',

    // 用户反馈闭环
    reviewedPagePreserved: '已保留使用者審閱內容: {}',

    // Query 回流
    querySuggestSaveTitle: '儲存到 Wiki？',
    querySuggestSaveDesc: '此對話包含有價值的知識點，是否儲存到 Wiki？',
    querySuggestSaveYes: '儲存',
    querySuggestSaveNo: '忽略',

    // 摄入报告
    ingestReportElapsedTime: '耗時',
    ingestReportSkippedFiles: '跳過（已攝入）',
    ingestReportRejectedFiles: '已跳過',
    rejectionReasonEmpty: '空內容',
    rejectionReasonType: '不支援的型別',
    rejectionReasonDuplicate: '重複內容',
    rejectionReasonPdfUnsupported: '供應商無法讀取 PDF',
    rejectionReasonMineruPageLimit: '超過 MinerU 頁數上限',
    rejectionReasonMineruSizeLimit: '超過 MinerU 大小上限',
    ingestReportFailedGuidance: '這些條目未能自動建立。您可手動建立對應頁面，或降低提取顆粒度後重新攝入原始檔。',

    // 命令名称（sentence case 遵循 Obsidian Bot 规则）
    cmdIngestSource: '攝入單個原始檔',
    cmdIngestFolder: '從資料夾攝入',
    cmdIngestMultipleFiles: '多選檔案攝入',
    cmdQueryWiki: '查詢 Wiki',
    cmdLintWiki: '維護 Wiki',
    cmdRegenerateIndex: '重新生成索引',
    cmdSuggestSchema: '建議 Schema 更新',
    cmdCancelIngestion: '取消當前提取',
    cmdIngestActiveFile: '攝入當前檔案',
    cmdViewHistory: '檢視攝入歷史',
    noActiveFile: '當前沒有開啟的檔案',
    mdOnlyFile: '僅支援攝入 Markdown 檔案',
    ingestSingleFileStart: '正在攝入：{filename}',
    ingestCheckingExisting: '正在檢查已攝入的檔案...',
    lintFindingsSummary: '共 {total} 處發現',

    // Ingestion status bar
    ingestionStatusBar: '提取中... 點選取消',
    lintStatusBar: '維護中... 點選取消',
    ingestStatusAnalyzing: '提取中… (點選取消)',
    lintStatusAnalyzing: '維護中… (點選取消)',
    ingestStageAnalyze: '正在分析來源',
    ingestStageSummary: '正在產生摘要',
    ingestStageEntity: '正在建立實體',
    ingestStageConcept: '正在建立概念',
    ingestStageRetry: '正在重試失敗的頁面',
    ingestStageSave: '正在儲存頁面',
    ingestStageIndex: '正在產生索引',
    pdfStageReading: '正在讀取 PDF',
    pdfStageConverting: '正在轉換 PDF',
    pdfStageSidecar: '正在寫入側車檔案',
    lintStagePrep: '正在讀取頁面',
    lintStageProgrammatic: '正在掃描連結',
    lintStageAnalyzing: '正在執行 LLM 分析',
    lintStageDedup: '正在偵測重複',
    lintStageContradiction: '正在偵測衝突',
    ingestionCancelling: '正在取消 — 當前批次完成後將停止',
    ingestionCancelled: '提取已取消',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: '正在分析批次 1/{total}...',
    ingestBatchProgress: '正在分析批次 {current}/{total}（已提取 {entities} 個實體、{concepts} 個概念）...',
    ingestBatchProcessed: '已完成批次 {current}，正在處理...',
    ingestAnalyzing: '正在分析：{filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] 正在產生摘要...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}：{name}',
    ingestUpdating: '[{step}/{totalSteps}] 正在更新：{name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] 正在產生索引...',
    ingestItemTypeEntity: '實體',
    ingestItemTypeConcept: '概念',
    convAnalyzing: '正在分析對話...',
    convCheckingExisting: '正在檢查既有知識...',
    convAlreadyExists: '此知識已存在於 Wiki',
    convCreatingSummary: '正在建立摘要頁...',
    convGeneratingSummary: '正在產生摘要頁...',
    convSavingEntity: '正在儲存實體：{name}',
    convSavingConcept: '正在儲存概念：{name}',
    convGeneratingIndex: '正在產生索引...',

    // 维护报告
    lintReportTitle: 'Wiki 維護報告',
    lintReportSummary: 'Wiki 狀態概覽：共 {total} 個頁面，{aliasesMissing} 個缺失別名，重複 {duplicates} 個，斷鏈 {deadLinks} 個（其中 {deadLinkFromDup} 個涉及重複頁面），孤立 {orphans} 個（其中 {orphanFromDup} 個是重複頁面），空洞 {emptyPages} 個，無來源引證 {ungroundedQuotes} 個，標籤越界 {tagViolations} 個。本次 Lint 耗時 {elapsedSeconds} 秒',

    // Advanced LLM Settings (Issues #99 / #128)
    // v1.26.0 (#382 item 2): 名稱由「高階引數設定」改為「LLM 高階參數」，
    // 明確這是 LLM 取樣參數，與底部通用的「進階設定」面板區分。
    advancedLlmModeName: 'LLM 高階參數',
    advancedLlmModeDesc: '預設模式遵循模型提供商的推薦設定。僅當你有明確理由覆蓋時才切到自定義（例如：某個模型需要固定溫度，或者你想關閉模型的思考輸出）。',
    advancedSettingsDefault: '預設（遵循提供商）',
    advancedSettingsCustom: '自定義（覆蓋提供商）',
    // v1.26.0 (#382 item 2): 底部「進階設定」面板 — 所有非 LLM 取樣參數的
    // 進階使用者設定的通用歸屬（lint 閾值、歡迎頁、未來擴展）。
    advancedSettingsSection: '進階設定',
    showAdvancedSettingsName: '顯示進階設定',
    showAdvancedSettingsDesc: '開啟後顯示下方的高階設定；關閉後會隱藏這些設定並重設為預設值。',
    disableThinkingName: '關閉思考',
    disableThinkingDesc: '關閉模型回應中的思維鏈/推理過程輸出。預設關閉 —— 由模型自己決定是否顯示推理，這樣通常能得到最好的回答。只有當你的提供商把原始推理文字塞進回應、而你希望得到一個乾淨的答案時，才打開它。',
    taskPoliciesPlaceholder: '範例：extract=text:off',
    taskPoliciesName: '按步驟設定輸出模式與思考',
    taskPoliciesDesc: '每個流程步驟一項，格式 `步驟=模式:思考`，以逗號分隔，例如 `extract=text:off`。模式：`-`（不變）、`schema`、`json`、`text`；思考：`-`、`off`、`on`、`low`、`medium`、`high`。步驟名稱包括 extract、extract-retry、lemma-classify、merge-triage、source-stance、dedup、page-generate、related-page、lint-dedup（拼錯的名稱不會比對到任何步驟）。留空使用內建基準（擷取步驟為文字模式）。無法解析的條目不會儲存。',
    // Issue #137: 兼容性提示（简短；不列举 provider，避免维护负担）
    extractionTemperatureName: '提取溫度',
    extractionTemperatureDesc: '控制模型在寫實體/概念頁時是偏嚴謹還是偏創意。數值越低越確定、越忠於原文；數值越高變化越多。大多數使用者留空即可。',
    chatTemperatureName: '查詢溫度',
    chatTemperatureDesc: '和「提取溫度」思路相同，但只影響 Query Wiki 回答問題的方式。數值越低回答越字面化；數值越高越像在聊天。大多數使用者留空即可。',
    repetitionPenaltyName: '重複懲罰',
    repetitionPenaltyDesc: '阻止模型反覆說相同的字詞。數值越高越能減少重複。只有部分本地模型提供商（Ollama、LM Studio、llama.cpp）接受這個參數；雲端提供商會靜默忽略。大多數使用者留空即可。數值高於 1.0 可能導致提取時 LLM 輸出錯誤（小模型在語法約束下易失敗）——若運行失敗，請減小或清空此值。',
    repetitionPenaltyErrorHint: '注意：已設定自訂重複懲罰值 {value}。高於 1.0 的值可能破壞小型本地模型的語法約束提取——請減小或清空此設定後重試。',
    temperaturePlaceholder: '留空 = 使用提供商預設',
    // v1.26.0 (#382 item 2): 重複偵測閾值（僅自訂進階模式）。
    lintDedupJaccardLinkThresholdName: '連結重複相似度',
    lintDedupJaccardLinkThresholdDesc: '範圍 0–1（預設 0.4）。兩個頁面共同指向的 wiki 連結佔各自連結集合的比例達到該值時，被標記為重複。調低 → 更多「只是都連結到同一中心頁」的近似重複會被納入；調高 → 只標記指向幾乎相同頁面的頁面。若看到不相關頁面恰好連結到同一中心頁造成的誤報，可調高此項。留空使用預設值。',
    lintDedupJaccardBodyGateName: '內文最低相似度',
    lintDedupJaccardBodyGateDesc: '範圍 0–1（預設 0.2）。即使兩個頁面共用 wiki 連結，內文相似度（依比例）至少達到該值時才會被標記為重複。調低 → 更多候選進入 LLM 複核；調高 → 只標記內文幾乎相同的頁面。若 LLM 被頻繁要求複核明顯不是重複的頁面，可調高此項。留空使用預設值。',
    lintDedupBigramThresholdName: '標題相似度',
    lintDedupBigramThresholdDesc: '範圍 0–1（預設 0.4）。兩個頁面標題（或別名）的字元重合度達到該值時，被標記為重複。調低 → 拼字變體、筆誤、同一概念的不同翻譯都會納入；調高 → 只標記標題幾乎相同的頁面。若 LLM 被要求複核標題差異很大、明顯不是重複的頁面，可調高此項。留空使用預設值。',
    lintDeadLinkSection: '斷鏈（程式檢測）[共 {count} 個]',
    lintEmptyPageSection: '空洞頁面（程式檢測）[共 {count} 個]',
    lintOrphanSection: '孤立頁面（程式檢測）[共 {count} 個]',
    lintContradictionSection: '矛盾（程式檢測）',
    lintDeadLinkItem: '- [[{source}]] → **{target}**（頁面不存在）{dupFlag}',
    lintDeadLinkMore: '- ... 共 {count} 處斷鏈',
    lintEmptyPageItem: '- [[{page}]] — 內容不足 50 字元',
    lintOrphanItem: '- [[{page}]] — 無其他 Wiki 頁面連結至此{dupFlag}',
    lintDeadLinkAffectedByDup: ' （⚠️ 涉及重複頁面）',
    lintOrphanIsDuplicate: ' （⚠️ 重複頁面）',
    lintHubLinkDensitySection: '樞紐頁面連結密度問題（Issue #157 / #175）[{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} 個入鏈，{relatedCount} 個相關連結，區分度 {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ 建議剝離',
    lintHubLinkDensityReview: '🔍 建議覆核',
    lintHubLinkDensityKeep: '✅ 保留',
    lintHubLinkDensitySummary: '摘要：{strip} 個頁面建議剝離，{review} 個頁面建議覆核。',
    lintHubLinkDensityNoRelated: ' （未找到 ## Related 區塊）',
    lintNoIssuesFound: '未檢測到重複、斷鏈、空洞、孤立頁面或無來源引證。',
    lintSourceDriftSection: '匯入後已變更的來源筆記 [共 {count} 個]',
    lintSourceDriftItem: '- [[{page}]] — 原始筆記 [[{note}]] 在匯入後被編輯，頁面內容可能已過時',
    lintContradictionMarkerSection: '帶有矛盾標記的頁面（合併分流）[共 {count} 個]',
    lintContradictionMarkerItem: '- [[{page}]] — 衝突來源：{sources}；審閱後請移除 contradictions: 標記',
    lintQuoteGroundingSection: '無來源引證（程式檢測）[共 {count} 個]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}："{quote}"',
    lintContradictionOpen: '未解決的矛盾：{count} 個',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: '待處理',

    // 维护分析 Prompt

    // 维护修复进度
    lintFixProgress: '修復斷鏈 {current}/{total}：[[{target}]]',
    lintFixDeadComplete: '斷鏈修復完成。已修復 {fixed}/{total} 項。',
    lintFillProgress: '擴充空洞 {current}/{total}：{page}',
    lintFillComplete: '頁面擴充完成。已填充 {filled}/{total} 頁。',
    lintDeleteCompleted: '已刪除 {count} 個空洞頁面',
    lintDeleteFailed: '刪除失敗 {failed}/{total} 個空白 stub（詳情見控制檯）',
    lintFillFailed: '擴充失敗：{page} — {error}',
    lintLinkProgress: '連結孤立 {current}/{total}：{page}',
    lintLinkComplete: '孤立頁面連結完成。已連結 {linked} 頁。',
    lintFixNoAction: '未執行操作（無 client）',
    lintFixIndexUpdated: 'Wiki 索引和日誌已更新。',
    lintPollutedFixed: '已修復汙染頁面：{fixed}/{total}。索引已重建。',
    regenerateIndexCompleted: '索引已重建',
    operationFailed: '失敗：',
    lintFixAllComplete: '所有修復已完成。詳情見日誌。',
    lintFixAllNoChanges: '未做任何修改 — 所有階段回報 0 修復。詳情見 wiki/log.md。',
    lintFixPhasesLabel: '個階段已修改',

    // 维护报告弹窗
    lintModalActionsTitle: '修復建議（需消耗LLM Token）：',
    lintLogReference: '完整報告已儲存至 log.md',
    lintModalFixDeadLinks: '修復斷鏈（{count}）',
    lintModalExpandEmpty: '擴充空洞頁面（{count}）',
    lintModalDeleteEmpty: '刪除空洞頁面（{count}）',
    lintModalLinkOrphans: '連結孤立頁面（{count}）',
    lintModalAnalyzeSchema: '分析 Schema',
    lintModalMergeDuplicates: '合併重複頁面（{count}）',
    lintModalFixAll: '一鍵修復所有問題（{count}）',
    lintDuplicateSection: '重複頁面（程式檢測）',
    lintPollutedSection: '汙染頁面（程式檢測）[共 {count} 個]',
    lintPollutedItem: '- [[{page}]] → 應為 "{clean}"',
    lintSourcesNormalizedSection: 'Sources 已歸一化（自動修復）[共 {files} 個檔案 / {entries} 處]',
    lintSourcesNormalizedItem: '清理了 {files} 個檔案中的 {entries} 處 sources 條目（已移除外部路徑、.md 字尾、別名管道，並去重）。',
    lintDuplicateItem: '- [[{target}]] 與 [[{source}]] — {reason}',
    lintMergeProgress: '合併 {current}/{total}：{source} → {target}',
    lintMergeComplete: '重複頁面合併完成。已合併 {merged}/{total} 對。',

    // 摄入报告弹窗
    ingestReportTitle: '攝入報告',
    ingestReportSourceFile: '原始檔',
    ingestReportCreated: '已建立',
    ingestReportUpdated: '已更新',
    ingestReportContradictions: '發現矛盾',
    ingestReportFailedTitle: '未能攝入',
    ingestReportErrorDetail: '錯誤詳情',
    ingestReportClose: '關閉',
    ingestReportCreatedPages: '建立頁面：{count}',
    ingestReportUpdatedPages: '更新頁面：{count}',
    ingestReportEmbeddedImages: '內嵌圖片：發現 {discovered} 張，排隊 {queued} 張，傳送 {sent} 張，成功分析 {analyzed} 張；共 {packages} 包，GIF 首幀轉換 {gifs} 張，失敗 {failed} 包',
    ingestReportEmbeddedEvidenceSaved: '圖片視覺證據已儲存到來源頁',
    ingestReportEmbeddedImageSkipped: '已略過的內嵌圖片',
    embeddedImagesVisionUnsupported: '目前端點拒絕圖片分析。文字攝入將繼續；請改用支援視覺的模型或關閉內嵌圖片分析。',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki 操作日誌',
    logHeaderSubtitle: '每次攝入、Lint 運行和維護操作都會自動記錄在這裡。推薦使用**操作歷史**面板獲得更好的可視化呈現：',
    logHeaderShortcut: 'Cmd+P → "檢視操作歷史"',
    logHeaderSettingsShortcut: '或從 設定 → 自動維護 → 操作歷史 進入',
    ingestionCreatedPages: '{count} 個頁面已建立',
    ingestionUpdatedPages: '{count} 個頁面已更新',
    ingestionNoticeHistoryHint: '檢視操作歷史以了解詳情',
    ingestReportEntitiesCount: '{count} 個實體',
    ingestReportConceptsCount: '{count} 個概念',
    ingestReportContradictionsFound: '發現矛盾：{count}',
    ingestReportEntityType: '實體',
    ingestReportConceptType: '概念',
    timeMinutes: '分',
    timeSeconds: '秒',

    // 速率限制警告
    rateLimitDetected: '⚠️ 檢測到速率限制：{count} 個頁面因 429 錯誤失敗。建議：(1) 降低併發度至 {suggestedConcurrency} 或 1（序列），(2) 增大批次延遲至 {suggestedDelay}ms，(3) 切換到速率限制更高的提供商。',
    rateLimitDetectedShort: '⚠️ 觸發速率限制 — 建議在設定 → 攝入加速中降低併發度或增大批次延遲。',

    // 长文本摄入提示
    sourceRejectedEmpty: '⏭️ "{filename}" 沒有可提取的內容，已跳過。空筆記或僅含 frontmatter 的筆記不會生成 Wiki 頁面。',
    sourceRejectedType: '⏭️ "{filename}" 不是受支援的檔案型別，已跳過。僅可提取文字筆記（如 .md、.txt）。',
    sourceRejectedDuplicate: '⏭️ "{filename}" 已跳過——其內容已存在於 Wiki 中。',
    pdfReadingInProgress: '正在讀取 PDF: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ 「{filename}」已跳過——目前的 provider 或模型不支援 PDF 輸入。可在 Settings → LLM Configuration → Advanced 切換 provider，或開啟「強制啟用 PDF 支援」再試一次，或切換 Markdown 轉換後端為 MinerU（同時支援圖片和 Office 文件）。',
    clearPdfCacheCommand: '清除 PDF 轉換快取',
    pdfCacheCleared: 'PDF 快取已清除（{count} 個條目已移除）。',
    // v1.25.0 PR3: Advanced PDF settings
    forcePdfSupportName: '強制啟用 PDF 支援',
    forcePdfSupportDesc: '預設關閉。如果你的 provider 不在原生支援清單中，但其實可以處理 PDF，可以打開這個開關試試。打開後 PDF 會送給目前的 provider，若被拒絕，會用提示通知你。原生支援 PDF 的 provider（Anthropic / OpenAI / Bedrock）不需要這個開關。',
    writePdfMarkdownToVaultName: '將轉換後的 Markdown 寫入 Vault',
    analyzeEmbeddedImagesName: '在 Markdown 攝入時分析嵌入圖片',
    analyzeEmbeddedImagesDesc: '預設關閉。開啟後會分包分析所有符合條件的本地圖片，每包最多 20 MiB、單張最大 10 MiB；絕不下載遠端圖片。',
    saveEmbeddedImageEvidenceName: '將內嵌圖片視覺證據儲存到來源頁',
    saveEmbeddedImageEvidenceDesc: '預設關閉。開啟後會在來源頁的摺疊章節儲存每張圖片的鄰近文字和視覺模型證據，方便核對。',
    markdownConversionBackendName: 'Markdown 轉換後端',
    markdownConversionBackendDesc: 'Native 使用 provider 自帶的 PDF 支援（範圍有限，並非所有 provider/model 都支援 PDF，消耗 LLM tokens）。MinerU 是線上服務——速度快、按日配額免費、支援 PDF/圖片/Office——但需要 API Token（於下方欄位填寫）。',
    markdownConversionBackendNative: 'Provider PDF/圖片 支援',
    markdownConversionBackendMineru: 'MinerU 線上 API',
    mineruApiBaseUrlName: 'MinerU 服務位址',
    mineruApiBaseUrlDesc: 'MinerU API 服務基礎位址，預設為 https://mineru.net/api/v4。若使用代理、鏡像或自建私有化服務可於此自訂。',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'MinerU API Token',
    mineruApiTokenDesc: '於 https://mineru.net/apiManage/token 取得你的 Token。MinerU 接受最大 200 MB、最多 200 頁的檔案。',
    mineruApiTokenPlaceholder: '貼上 MinerU API Token',
    mineruUploadingInProgress: '正在上傳 PDF 至 MinerU：{filename}',
    mineruWaitingInProgress: '正在等待 MinerU 解析：{filename}',
    mineruDownloadingInProgress: '正在下載 MinerU 解析結果：{filename}',
    markdownConversionComplete: '轉換完成：{filename}',
    markdownConversionCompleteSaved: '轉換完成 — 已寫入 {path}：{filename}',
    mineruPageLimitRejected: '{filename} 超過 MinerU 的 {limit} 頁上限，請拆分檔案後重試',
    mineruSizeLimitRejected: '{filename} 超過 MinerU 的 {limit} MB 大小上限',
    writePdfMarkdownToVaultDesc: '預設關閉。開啟後，每次 PDF 轉換的結果會寫入源 PDF 旁邊的「<原名>.pdf.md」檔案。關閉時，轉換結果僅儲存在插件快取，不在你的 Vault 中留下實作產物。',

    ingestRejectedSummary: '已跳過 {count} 個檔案（空檔案、重複或不支援的型別）。',
    reingestConfirmTitle: '重新提取該檔案？',
    reingestConfirmBody: '"{filename}" 的內容已存在於 Wiki 中。仍要重新提取嗎？',
    reingestConfirmYes: '重新提取',
    reingestConfirmNo: '跳過',
    lintDedupIncludeSourcesName: '在去重中包含來源',
    lintDedupIncludeSourcesDesc: '預設開啟。開啟後，內文相同的來源在 lint 階段會被標記為重複。若你的來源語料產生過多誤報，可關閉此選項。',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: '跳過來源僅提及的候選',
    skipMentionOnlyCandidatesDesc: '預設關閉。開啟後，擷取出的實體或概念若其名稱未出現在筆記內文中（完全未出現，或僅出現在括號、列舉或簡短清單項目中），將不產生頁面、不再呼叫模型，並從其他候選的相關清單中移除。適用於具有詞邊界設定檔的 Wiki 語言（德語已量測；英語、法語、西班牙語、葡萄牙語、荷蘭語為估計）；其他語言在擷取時會提示一次無法套用。若你的庫是術語表風格或筆記以要點為主、希望每個被點名的術語都成為頁面，請保持關閉。',
    createStubsForUnresolvableLinksName: '為無法解析的連結建立佔位頁',
    createStubsForUnresolvableLinksDesc: '預設開啟。當「修復斷鏈」無法把連結解析到任何現有頁面時，會寫入一個空的佔位頁並把連結改指向它——絕不由 LLM 填充。關閉後此類連結保持原樣：它們在每次 lint 報告中保持可見，直到有真實來源定義它們。',
    lintDedupSectionHeading: '去重偵測',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): 通用 Toast 文案，
    // 復用於所有 LLM 業務路徑。{count} 是觸發重試的批次數量。注意：
    // 不要在此承諾「任務已完成」——本次重試僅恢復本批次，同一掃描
    // 的其他批次可能仍在進行中。
    llmRetryRecoveredToast: 'LLM 任務：{count} 個批次因 provider 臨時回應問題觸發重試（已自動恢復）。詳見主控台。若頻繁出現，請考慮在 Provider 設定中降低 Page Generation Concurrency。',
    longSourceNotice: '📄 "{filename}" 包含 {lines} 行（{size}）。長文字需要多輪迭代提取，LLM 將完整讀取文件進行多次分析，耗時可能較長，請耐心等待。',
    longSourceNoticeShort: '📄 檢測到大檔案（{lines} 行），攝入可能需要較長時間。',

    // 摄入历史面板 (#122) — UI 文案
    historyButton: '操作歷史',
    historyButtonDesc: '檢視 LLM-Wiki 最近的攝入、Lint 報告和其他變更記錄',
    historyButtonOpen: '檢視歷史',
    historyModalTitle: '操作歷史',
    historyModalSubtitle: 'LLM-Wiki 最近的變更記錄',
    historyEmpty: '暫無操作記錄。攝入筆記或執行 Lint 以填充此列表。',
    historyReadError: '無法讀取操作日誌：{error}',
    historyEntryKindIngest: '攝入',
    historyEntryKindMaintenance: '維護',
    historyEntryKindFix: '修復',
    historyEntryKindOther: '其他',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: '來源：{source}',
    historyEntrySourceUnknown: '未命名攝入',
    historyEntryCreatedLabel: '已建立',
    historyEntryUpdatedLabel: '已更新',
    historyEntryCreatedCount: '新建 {count} 個',
    historyEntryUpdatedCount: '更新 {count} 個',
    historyEntryNoChanges: '無頁面變更',
    historyEntryContradictions: '⚠️ {count} 處矛盾',
    historyEntrySectionCreated: '建立的頁面',
    historyEntrySectionUpdated: '更新的頁面',
    historyEntrySectionContradictions: '矛盾',
    historyEntrySectionDetails: '詳情',
    historyEntryOpenPage: '開啟',
    historyEntryDetailsNoContradictions: '未發現矛盾',
    historySearchPlaceholder: '🔍 按來源標題或頁面路徑搜尋…',
    historyFilterAll: '全部',
    historyFilterIngest: '僅攝入',
    historyFilterMaintenance: '僅維護報告',
    historyFilterFix: '僅修復',
    historyFilterContradictions: '⚠️ 含矛盾',
    historyRefreshButton: '⟳ 重新整理',
    historyExpandDay: '點選展開',
    historyCollapseDay: '點選收起',
    historyShowMore: '顯示更早的 {count} 條',
    historyNoMatch: '沒有操作匹配您的搜尋/篩選條件。',
    historyCloseButton: '關閉',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: '報告發現',
    historyKpiPages: '頁面數',
    historyKpiDeadLinks: '斷鏈',
    historyKpiOrphans: '孤立',
    historyKpiEmpty: '空洞',
    historyKpiDuplicates: '重複',
    historyKpiTagViolations: '標籤問題',
    historyKpiUnsourced: '無來源',
    historyKpiDuration: 'Lint 耗時',
    historyKpiDurationSec: '{seconds} 秒',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: '斷鏈 ({count})',
    historySectionTagViolations: '標籤越界 ({count})',
    historySectionOrphans: '孤立頁面 ({count})',
    historySectionEmptyPages: '空洞頁面 ({count})',
    historySectionLlmAnalysis: 'LLM 分析 ({count})',
    historyDeadLinkSource: '來源',
    historyDeadLinkTarget: '缺失',
    historyOpenInLog: '在 log.md 中檢視',
    historyShowMoreItems: '展開剩餘 {count} 項',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ 持平',
    historyChipContradiction: '矛盾',
    historyChipOutdated: '過時',
    historyChipMissing: '缺失',
    historyChipStructure: '結構',
    historySeverityHigh: '高',
    historySeverityMedium: '中',
    historySeverityLow: '低',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: '您的 Wiki 當前有 {dead} 個斷鏈、{orphans} 個孤立頁面、{tags} 個標籤問題。最近一次 Lint 耗時 {duration}。',
    historyGlobalInsightClean: '您的 Wiki 當前狀態良好——沒有斷鏈、孤立頁面或標籤問題。',
    historyGlobalInsightNoData: '暫無維護報告——執行 Lint 以生成。',
    historyModalHeaderTitle: '操作歷史',
    historyModalSubtitleWithCount: 'LLM-Wiki 最近的變更記錄 · 共 {count} 條',
    historyTimeRangeAll: '全部時間',
    historyTimeRange1d: '近 1 天',
    historyTimeRange3d: '近 3 天',
    historyTimeRange1w: '近 1 周',
    historyTimeRange1m: '近 1 個月',
    historyIngestTotal: '頁面總數',
    historyIngestByType: '按型別分佈',
    historyIngestSource: '來原始檔',
    historyIngestNoTimestamp: '無時間戳',
    historyIngestFirstTime: '首次攝入',
    historyIngestLatestTime: '最近攝入',
    historyTimeRangeCustom: '自定義範圍',
    historyCustomRangeFrom: '起始',
    historyCustomRangeTo: '結束',
    historyCustomRangeApply: '應用',
    historyCustomRangeClear: '清除',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki：vault 為空。請建立你的第一個 source note 並執行 Ingest 以開始使用。',
    welcomeNoteTierBNotice: 'Karpathy Wiki：已建立 Welcome note。開啟它以宣告你的領域並選擇 2-3 個 source note 來為連結圖提供種子。',
    welcomeNoteRecreateCommand: '重建 Wiki Welcome note',
    welcomeNoteRecreateCommandTooltip: '使用目前的 domain seed 和 LLM 配置測試在 <wikiFolder>/Welcome.md 重新建立 Welcome note。已存在的檔案將被覆蓋。',
    welcomeNoteSettingsToggle: '首次執行時建立 Wiki Welcome note',
    welcomeNoteSettingsToggleDesc: '首次執行（wiki 資料夾為空時），自動在 <wikiFolder>/Welcome.md 建立一頁入門筆記。它會說明 LLM-Wiki 是什麼、引導你宣告領域聚焦，並教你擷取前 2-3 條來源筆記。筆記預設用英文寫入，若 LLM 已設定則用你的 wiki 語言。如果已經熟悉外掛用法不想多這一頁，可以關掉。',
    welcomeNoteRunConfigTest: 'Welcome note 已用英文寫入。開啟 設定 → LLM Provider → Test Connection 以便下次重建時本地化。',
    welcomeNoteRecreated: '已重新建立 Wiki Welcome note 於 {path}',
    welcomeNoteNotRecreated: 'Welcome note 未重新建立。請檢查 LLM 設定。',
    welcomeNoteGenerating: 'Wiki Welcome note 正在背景產生中 — 完成後會顯示通知。',
    welcomeNoteGenerationFailed: 'Wiki Welcome note 產生失敗：{error}',
    startupCheckWelcomePending: 'Welcome note：正在背景產生中（完成後會顯示通知）。',
    welcomeNoteFileName: '歡迎使用 Karpathy LLM Wiki',
    startupCheckWelcomeCreated: 'Welcome note 已建立於 {path}',
    // v1.23.0 Phase 5.1.5: 多檔案攝入 Modal 的「全部取消」按鈕。一次取消
    // 佇列中所有 pending + running 任務。Completed / failed 保留可見。
    cancelAllQueueJobs: '全部取消',
    // v1.23.0 Phase 5.1.5: 多檔案攝入 Modal 的標題、提示、搜尋框佔位、
    // 按鈕、狀態文字、佇列空佔位。
    multiFileModalTitle: '多檔案攝入',
    multiFileModalHint: '選擇來源筆記加入佇列。右側面板即時顯示佇列與進度。',
    multiFileSearchPlaceholder: '依路徑篩選檔案…',
    multiFileAddToQueue: '加入佇列',
    multiFileSelectAll: '全選',
    multiFileFileCount: '{count} 個檔案',
    multiFileNoFilesAvailable: '暫無可攝入的檔案。',
    multiFileNoFilesMatch: '未匹配到「{q}」。',
    multiFileQueueEmpty: '佇列為空。勾選左側檔案即可加入。',
    multiFileStatusPending: '等待中',
    multiFileStatusRunning: '攝入中',
    multiFileStatusCompleted: '已完成',
    multiFileStatusFailed: '已失敗',
    multiFileCancelAria: '取消該檔案',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: '已攝入',
    multiFileRowDrifted: '攝入後筆記已修改',
    startupCheckNoticeLevelName: '顯示快速修復結果',
    startupCheckNoticeLevelDesc: '快速修復在外掛啟動時始終執行（Welcome note、資料夾結構、來源正規化、不完整頁面、日誌標頭）。選擇啟動後是否顯示摘要通知。靜默模式僅記錄到開發者控制台與操作歷史面板。',
    startupCheckNoticeVisible: '顯示（彈出通知）',
    startupCheckNoticeSilent: '靜默（無通知）',
} as const;
