export const ZH_TEXTS = {
    // 插件信息
    pluginTitle: 'Karpathy LLM Wiki 设置',
    pluginIntro: '本插件为 Obsidian 实现了 {{link}} 概念。它读取你的笔记，用 AI 提取实体和概念，在 Vault 中构建结构化、互联的知识库。',
    karpathyLinkText: 'Andrej Karpathy 的 LLM Wiki',

    // 功能部分
    featuresTitle: '使用方式',
    workflow1Title: '1. 摄入 (Ingest)',
    workflow1Desc: '选择笔记 → AI 提取实体、概念、关系 → 生成 Wiki 页面。',
    workflow2Title: '2. 查询 (Query)',
    workflow2Desc: '与 Wiki 对话，答案基于你已摄入的知识，而非通用知识。',
    workflow3Title: '3. 维护 (Maintain)',
    workflow3Desc: '自动生成索引、交叉链接、健康检查，保持 Wiki 整洁。',

    // 语言切换
    languageTitle: '界面语言',
    languageDesc: '选择设置面板的显示语言。重启插件以将语言更改应用到命令面板。',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',
    languageRu: 'Русский',

    // 状态
    statusTitle: 'LLM Client 状态',
    llmWikiStatusSection: 'LLM-Wiki 状态',
    statusInitialized: '已初始化',
    statusReady: 'LLM 已就绪',
    statusNotReady: 'LLM 未配置 — 请完成上方设置并通过连接测试',
    statusNotInitialized: '未初始化',
    currentProvider: '当前提供商',

    // Provider 设置
    providerSection: 'LLM 配置',
    providerName: 'LLM Provider',
    providerDesc: '选择预定义提供商或自定义 OpenAI 兼容服务。对于 Coding Plan 等套餐，建议选择自定义 OpenAI/Anthropic 并手工填写对应 URL 和 API Key',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: 'API 密钥。存储在操作系统凭据管理器中，不写入 data.json。',
    apiKeyPlaceholder: '输入 API Key',
    // v1.25.4 #339: SecretStorage migration repair + failure Notice
    apiKeyMigrateToSecretStorageButton: '迁移 SecretStorage',
    apiKeyMigratedToSecretStorageSuccess: 'API Key 已从 SecretStorage 还原到设置。',
    apiKeyMigrationFailedNotice: '无法将 API Key 保存到 SecretStorage：{}',
    codexAuthName: '登录 ChatGPT 套餐',
    codexAuthDesc: '通过实验性的 Codex OAuth 使用 ChatGPT 套餐额度。OpenAI Platform API 仍单独计费。',
    codexAuthSignedOut: '未登录',
    codexAuthSignedIn: '已登录',
    codexAuthBrowserButton: '使用浏览器登录',
    codexAuthDeviceButton: '使用设备代码',
    codexAuthDeviceInstructions: '在 OpenAI 页面输入此代码：{}',
    codexAuthCopyCode: '复制代码',
    codexAuthSignOutButton: '退出登录',
    codexAuthBusy: '正在等待 OpenAI 授权…',
    codexAuthFailed: 'ChatGPT 授权失败：{}',
    codexAuthQuota: 'ChatGPT Codex 额度已用尽。请等待显示的重置时间后重试。',
    codexAuthExperimental: '实验性功能：可用性取决于 OpenAI Codex 的身份验证和模型政策。',
    codexModelsRefreshName: '账户可用模型',
    codexModelsRefreshDesc: '从当前登录的 OpenAI Codex 账户同步可选择模型。',
    codexModelsRefreshButton: '刷新账户模型',
    codexModelsRefreshing: '正在刷新…',
    codexModelsRefreshSuccess: '已同步 {} 个账户模型。',
    codexModelsRefreshFailed: '账户模型刷新失败，当前使用可用的后备列表。{}',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: '必填：自定义 OpenAI 兼容服务的 endpoint',
    baseUrlDescOverride: '可选：覆盖预设的 Base URL',

    // Ollama 提示
    ollamaHint: 'Ollama 本地运行，无需 API Key',
    lmstudioHint: 'LM Studio 本地运行，API Key 可选',
    maxTokensPerCallName: '每次调用的最大输出 Token 数',
    maxTokensPerCallDesc: '限制模型单次响应能生成的 Token 数量。如果你用本地小上下文窗口模型且遇到报错，可以调低。云端模型保持默认（0 = 不限制）即可。',

    slugCaseName: '文件名大小写',
    slugCaseDesc: '控制生成的 Wiki 文件名是否转为小写。对于大小写有语义的语言（如德语名词），建议选择“保留”。',
    slugCaseLower: '小写（默认）',
    slugCasePreserve: '保留大小写',
    // Minimum alias length (Advanced settings, next to slug case).
    minAliasLengthName: '别名最小长度',
    minAliasLengthDesc: '短于此长度的别名（去除首尾空格后）不会写入 wiki 页面。默认值 2 保留两字母缩写（ML、AI、UI）；若库中积累了仅大小写不同的两字母别名（Cr/CR），可调到 3。范围 2–6。',
    minAliasLengthClamped: '数值超出范围（2–6），已设为 {}',

    // 模型选择
    modelSection: '模型选择',
    fetchModelsName: '获取可用模型',
    fetchModelsDesc: '从 Provider API 获取最新的模型列表',
    fetchModelsButton: '获取模型列表',
    fetchingModels: '获取中...',
    fetchSuccess: '获取成功！共 {} 个可用模型',
    fetchFailed: '获取失败或列表为空，请手动输入模型名称',
    fetchNotSupported: '该 Provider 不支持模型列表查询',
    fetchErrorAuth: '认证失败（HTTP 401/403）。请检查 API Key 是否正确，或直接输入模型 ID 后点击测试连接进行验证。',
    fetchErrorEndpoint: '接入点未找到（HTTP 404）。请检查 BaseURL 是否正确，或直接输入模型 ID 后点击测试连接。',
    fetchErrorServer: 'Provider 服务端错误（HTTP 5xx）。稍后重试，或直接输入模型 ID 后点击测试连接。',
    fetchErrorEmpty: '该接入点不支持列出模型列表。请直接输入模型 ID 后点击测试连接进行验证。',
    fetchErrorNetwork: '网络请求失败。请检查网络连接、BaseURL、代理设置或 API Key。您也可以直接输入模型 ID 后点击测试连接进行验证。',

    selectModelName: '选择模型',
    selectModelDesc: '从 {} 个可用模型中选择',
    customInputOption: '自定义输入...',
    customInputHint: '如需使用其他模型，请选择"自定义输入..."',

    modelName: '模型名称',
    modelDescCustom: '当前使用自定义模型（可重新获取列表）',
    modelDescFetchFailed: '模型列表获取失败。请检查 API Key 和接入点 URL，或直接输入模型 ID 后点击测试连接进行验证。',
    modelInputPlaceholder: '输入模型 ID，然后点击测试连接',

    switchToDropdown: '切换到下拉选择',
    useDropdownButton: '使用下拉选择',

    // v1.24.0 #208: per-task model picker
    modelTaskModeName: '模型作用域',
    modelTaskModeDesc: '选择所有任务使用同一个模型，还是按任务分别使用不同模型（摄取 / 维护修复 / 查询）。切换回统一模型时，已填的分任务模型会被保留而不会被清空。',
    modelTaskModeUnified: '使用统一模型（默认）',
    modelTaskModePerTask: '为不同任务使用不同模型',
    perTaskIngestModelName: '摄取模型',
    perTaskIngestModelDesc: '用于摄取笔记、对话、Schema 维护以及欢迎笔记生成。',
    perTaskLintModelName: '维护修复模型',
    perTaskLintModelDesc: '用于 Lint 分析、重复检测、各种修复任务以及孤儿链接修正。',
    perTaskQueryModelName: '查询模型',
    perTaskQueryModelDesc: '用于 Query Wiki 对话与保存到 Wiki 评估。',

    // 测试 & 保存
    testConnectionName: '测试连接',
    testConnectionDesc: '验证配置能否成功调用 LLM API',
    testButton: '测试连接',
    testing: '测试中...',

    saveSettingsName: '保存设置',
    saveSettingsDesc: '保存当前配置',
    saveButton: '保存设置',
    testConnectionSuccessful: '连接成功',
    testConnectionFailed: '连接失败',
    testConnectionProvider: '提供商：',
    codexAuthRequired: '测试连接前，请先登录 ChatGPT 套餐。',
    bedrockSsoRequired: '测试连接前，请先在 设置 → Bedrock 中完成 AWS SSO 登录。',
    bedrockIamRequired: '测试连接前，请先在 设置 → Bedrock 中输入您的 IAM 访问密钥。',
    bedrockAuthMethodName: '认证方式',
    bedrockAuthMethodDesc: 'API 密钥使用 Bedrock API 密钥；AWS SSO 使用 IAM Identity Center 凭据对请求签名；IAM 密钥使用静态访问密钥。',
    bedrockAuthOptionApiKey: 'API 密钥',
    bedrockAuthOptionSso: 'AWS SSO',
    bedrockAuthOptionIam: 'IAM 密钥',
    bedrockSsoStartUrlName: 'SSO 起始 URL',
    bedrockSsoStartUrlDesc: '您组织的门户 URL，例如 https://d-xxxxxxxxx.awsapps.com/start',
    bedrockSsoAccountIdName: 'AWS 账户 ID',
    bedrockSsoAccountIdDesc: '要代入角色的 12 位账户 ID，例如 123456789012',
    bedrockSsoRoleNameName: '角色名称',
    bedrockSsoRoleNameDesc: '用于 Bedrock 访问的 IAM 角色，例如 PowerUserAccess',
    bedrockSsoLoginButton: '使用 AWS SSO 登录',
    bedrockSsoSignOutButton: '退出 AWS SSO',
    bedrockSsoStatusSignedIn: '已登录 · {} 到期',
    bedrockSsoStatusSignedOut: '未登录',
    bedrockSsoBusy: '正在登录…',
    bedrockSsoUserCodeInstructions: 'AWS SSO 验证码：{}。请打开链接并批准访问。',
    bedrockSsoCopyCode: '复制验证码',
    bedrockSsoFailed: 'AWS SSO 登录失败：{}',
    bedrockSsoDetectedPrefill: '检测到账户/角色：{}',
    bedrockIamKeyName: '访问密钥 ID',
    bedrockIamKeyDesc: 'IAM 访问密钥标识，例如 AKIA… 或 ASIA…',
    bedrockIamSecretName: '秘密访问密钥',
    bedrockIamSecretDesc: '仅保存在本设备的密钥存储中，绝不会写入 data.json',
    bedrockIamSessionTokenName: '会话令牌（可选）',
    bedrockIamSessionTokenDesc: '仅临时凭据（STS）需要',
    bedrockIamClearButton: '清除已保存的 IAM 密钥',
    bedrockIamSaveFailed: 'IAM 密钥保存失败：{}',
    errorUnknown: '未知错误',
    savedNotice: '设置已保存！',

    // v1.24.0 (Bug C 3.4 / plan C): 渐进迁移通知
    queryHistoryMigrationNotice: 'Query Wiki 历史记录中包含来自旧 wiki 目录的链接。新对话已自动使用最新目录。如需刷新所有历史消息，请打开 Query Wiki 面板并点击其中的”清除历史”按钮。',

    // v1.24.0 Issue #251: 自定义 Query 指令（可折叠面板）
    customInstructionsTitle: '自定义 Query 指令',
    customInstructionsDesc: '每次 Query Wiki 对话都会在系统提示末尾附加这些指令。仅影响 Query Wiki 聊天；不影响摄取、lint 和页面生成。',
    customInstructionsPlaceholder: '例如：将其视为研究任务：广泛搜索、引用来源、区分事实与解读...',
    customInstructionsApply: '应用',
    customInstructionsClear: '清除',
    customInstructionsCharCount: '{current}/{max} 字符',
    instructionsApplied: '自定义 Query 指令已保存。',
    instructionsCleared: '自定义 Query 指令已清除。',

    // Issue #137: LLM 回退通知（请求中触发 thinking-dialect 回退或字段剥离时显示）
    fallbackThinkingDialect: '思考控制：已切换至 "{dialect}" 方言（该提供商使用不同的思考控制字段格式）。输出内容不受影响。',
    fallbackThinkingNone: '该提供商已完全关闭思考控制。模型仍可能产生推理内容；若出现，请尝试其他模型。',
    fallbackParamStripped: '参数 "{field}" 不被该提供商支持。已从请求中移除；行为可能与配置不同。',

    // Wiki 文件夹
    wikiSection: 'Wiki 配置',
    wikiFolderName: 'Wiki 文件夹',
    // v1.24.0: 提示需重启 Obsidian 以让 engine 缓存和打开的 Query Wiki 面板重新绑定
    wikiFolderDesc: '存放生成的 Wiki 页面。修改后需重启 Obsidian 才能生效——engine 缓存和已打开的 Query Wiki 面板需要重新绑定。',
    wikiFolderPlaceholder: 'wiki',

    // 错误
    errorNoApiKey: '请先配置 API Key',
    errorNoModel: '请先选择模型 — 点击"获取模型列表"，或手动输入 Model ID',
    llmNotReady: 'LLM 尚未配置。请前往 设置 → Karpathy LLM Wiki 完成 Provider 配置、获取模型列表并通过连接测试。',
    errorFetchFailed: '获取失败：{}',

    // Query 设置
    querySectionTitle: 'Wiki 查询配置',
    // v1.24.0: 由"对话历史上限"重命名为"对话关联记忆轮数"，更准确地表达语义
    // ——这是 LLM 的记忆窗口，不是硬性存储上限（历史记录本身就是滚动更新）。
    // 1 = 每轮对话独立（不关联）。设置项为下拉框，无需在描述中列出预设值。
    // v1.24.0: maxConversationHistoryHint 是死 i18n key（UI 代码无引用），
    // 推荐文案已合并入 desc。
    maxConversationHistoryName: '对话关联记忆轮数',
    maxConversationHistoryDesc: 'LLM 在新对话中可见的过往轮次数（作为记忆）。1 = 每轮对话独立（不关联前文）；数值越高，模型能记住会话中越早的轮次。推荐：一次性问答选 1；持续性研究选 10–50。',
    numberRangeValidation: '请输入1-50之间的数字',
    numberRangeClamped: '数值超出范围（1-500），已自动设定为 {}',

    // Query Modal UI
    queryModalTitle: 'Query Wiki - 对话式查询',
    queryModalPlaceholder: '输入问题...',
    queryModalSendButton: '发送',
    queryModalStopButton: '停止',
    queryModalSaveButton: '保存到Wiki',
    queryModalClearButton: '清空历史',
    queryModalHistoryCount: '对话历史: {}/{} 轮',
    queryModalStreaming: '流式生成中...',
    queryModalFallbackStreaming: '端点不支持流式传输，已回退至非流式模式，请耐心等待...',
    queryPhaseSearching: '正在分析 Wiki 索引，查找相关资料...',
    queryPhaseFoundPages: '找到 {count} 个资料：{pages}',
    queryPhaseLoadingPages: '正在加载页面内容...',
    queryPhaseContextReady: '资料就绪，正在生成回复...',
    queryPhaseGenerating: '正在生成回复...（已等待 {time}s）',
    queryPhaseNonStreaming: '非流式模式，生成中，请耐心等待...（已等待 {time}s）',
    queryModalErrorPrefix: '错误：',
    queryModalHint: '查询基于Wiki内容。点击"保存到Wiki"可将有价值对话提炼为Wiki页面。',

    // v1.20.0: Query Wiki 思考内容折叠摘要
    queryThinkingSummary: '思考过程',
    queryThinkingSteps: '步',

    // 错误消息
    errorLLMClientNotInit: 'LLM Client 未初始化。请保存设置。',
    errorIngestFailed: '摄入失败：',
    errorQueryFailed: '查询失败：',
    fileWriteFailed: '无法创建或更新文件：{path}',

    // 成功消息
    ingestSuccess: '摄入成功：创建{}页，更新{}页',
    querySuccess: '查询完成',
    lintSuccess: 'Wiki 维护完成',
    lintReadingPages: '正在读取 {count} 个 Wiki 页面...',
    lintReadingPagesProgress: '正在读取 Wiki 页面：{current}/{total}...',
    lintScanningLinks: '正在扫描断链...',
    lintScanningLinksProgress: '正在扫描断链：{current}/{total}...',
    lintCheckingDuplicates: '正在检查重复页面...',
    lintCheckingDuplicatesProgress: '正在校验重复项：批次 {current} ...',
    lintFixingPolluted: '正在修复污染页面 {current}/{total}：{title} → {newTitle}',
    lintModalFixPolluted: '🧹 修复污染页面（{count}）',
    lintDuplicateCheckFailed: '重复检测失败 — 详见控制台',
    lintDuplicateCheckFailedDetail: '重复检测在{step}失败：{error}',
    lintMergeItemFailed: '合并失败：{source} → {target} — {error}',
    lintAliasesMissing: '检测到 {count} 个页面缺少别名',
    lintAliasesSection: '缺失别名的页面（程序检测）[共 {count} 个]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: '补全别名（{count}）',
    lintAliasesFilling: '生成别名 {current}/{total}：{page}',
    lintAliasesFilled: '别名补全完成。已填充 {filled}/{total} 页。',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: '标签越界（程序检测）[共 {count} 个]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: '别名生成失败：{page} — {error}',
    lintFixItemFailed: '修复失败：[[{target}]] — {error}',
    lintLinkItemFailed: '链接失败：{page} — {error}',
    lintRetrying: '出错后重试中（{attempt}/{max}）...',
    lintAnalyzingLLM: 'LLM 正在分析 Wiki 健康状态...',
    saveToWikiSuccess: '对话已保存到Wiki！',
    querySaveAlreadyExists: '提示：未写入任何内容（该知识已存在于 Wiki 中）：',
    saveSummary: '{entities} 个实体, {concepts} 个概念, {pages} 个页面',
    aliasAdded: '已为页面\'{page}\'添加别名\'{alias}\'',

    // 状态消息
    ingestingSources: '正在摄入源文件...',
    queryingWiki: '正在查询 Wiki...',
    lintingWiki: '正在维护 Wiki...',
    savingToWiki: '正在保存对话到Wiki...',
    clearingHistory: '清空对话历史...',

    // 按钮
    ingestButton: '摄入',
    queryButton: '查询',
    lintButton: '维护',
    cancelButton: '取消',

    // 链接
    karpathyGistLink: 'Karpathy\'s LLM Wiki Gist',
    obsidianPluginAPI: 'Obsidian Plugin API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // v1.24.1 PATCH Bedrock Stage 1
    bedrockRegionName: 'AWS 区域',
    bedrockRegionDesc: '本账户所在的 Amazon Bedrock 区域。驱动 bedrock-mantle 端点 URL；不能通过 baseURL 覆盖。',
    bedrockRegionHint: 'bedrock-mantle 在 18 个区域可用；各区域模型覆盖范围不同。',

    // 其他
    availableModelsLoading: '加载可用模型...',
    noModelsAvailable: '无可用模型',

    // LLM 语言提示
    llmLanguageHint: '请用中文回答。',

    // Schema 配置
    schemaSection: 'Schema 配置',
    enableSchemaName: '启用 Schema',
    enableSchemaDesc: '生成 schema/config.md 并注入到所有 LLM 提示词中，指导 Wiki 结构化输出',
    viewSchemaButton: '查看 / 编辑 Schema',
    regenerateSchemaButton: '重新生成默认 Schema',
    schemaRegeneratedNotice: '默认 Schema 已重新生成。',
    schemaRegenerateFailed: 'Schema 生成失败',

    // Wiki 初始化状态
    wikiInitStatusReady: 'Wiki 已初始化',
    wikiInitStatusNotReady: 'Wiki 未初始化 — 将在首次摄入时自动创建',

    // Wiki 输出语言
    wikiLanguageName: 'Wiki 输出语言',
    wikiLanguageDesc: '所有生成的 Wiki 页面、索引、日志和查询回复均使用此语言',
    customWikiLanguageOption: '自定义...',
    customWikiLanguageHint: '输入语言名称（如 Italian、Arabic），将作为输出语言指令传递给 LLM。',
    customWikiLanguagePlaceholder: '例如：Italian',

    // 索引 & 日志标签（各语言）
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },

    // 知识提取
    extractionSectionTitle: '知识提取',
    extractionGranularityName: '提取颗粒度',
    extractionGranularityDesc: '控制每篇源文件提取的实体/概念数量。越高 = 生成页面越多，API消耗越大。\n精细：单篇深度。标准：日常笔记。粗放：快速概览。极简：批量100+文件（限制每篇条目数约5条，而非单条细节）。自定义：自行设定（最高300个）。\n提示：批量处理大量文件时，建议使用极简或粗放以节省时间和成本。',
    extractionGranularityFine: '精细 — 单篇深度分析（≤100个）',
    extractionGranularityStandard: '标准 — 日常笔记（≤50个）',
    extractionGranularityCoarse: '粗放 — 快速概览（≤10个）',
    extractionGranularityMinimal: '极简 — 批量100+文件（≤5个）',
    extractionGranularityCustom: '自定义 — 自行设定上限（1~500）',
    customEntityLimitName: '自定义实体上限',
    customEntityLimitDesc: '每篇源文件最多提取的实体数量（1-500）',
    customConceptLimitName: '自定义概念上限',
    customConceptLimitDesc: '每篇源文件最多提取的概念数量（1-500）',

    // Issue #85 v2: 标签词汇表 (chip input 交互, 嵌入 Wiki 配置)
    tagVocabularyInlineDesc: '为 entity 和 concept frontmatter 标签设置受控词汇。Obsidian 嵌套标签 "/" 会被保留。',
    tagVocabularyModeName: '标签（Tags)词汇表配置',
    tagVocabularyModeDescDefault: '默认使用内置标签: {}。切换到"自定义"可定义您自己的词汇。',
    tagVocabularyModeDescCustom: '自定义：在下方使用 chip 输入定义您自己的 entity 与 concept 标签。回车或逗号添加, × 删除。',
    tagVocabularyNotEnforcedHint: '仅作为模式提示——LLM 仍可能输出词表外的类型。请运行 Lint 来查找并修复这些页面。',
    tagVocabularyModeDefault: '默认 (内置子类型标签)',
    tagVocabularyModeCustom: '自定义 (用户定义)',
    customEntityTagsName: '自定义实体标签',
    customEntityTagsDesc: '按回车或逗号添加 chip, 点 × 删除。嵌套标签 "/" 会被保留。',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: '自定义概念标签',
    customConceptTagsDesc: '按回车或逗号添加 chip, 点 × 删除。嵌套标签 "/" 会被保留。',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: '重复标签已跳过',

    // 摄入加速
    accelerationSectionTitle: '摄入加速',
    pageGenerationConcurrencyName: 'LLM 并发度',
    pageGenerationConcurrencyDesc: '摄入和 Lint 操作中的并行 LLM 调用数。数值越高处理越快，但会增加 API 消耗并可能触发限流。',
    concurrencyValueSingular: '当前并发度：{}（串行 — 最安全）',
    concurrencyValuePlural: '当前并发度：{}（并行）',
    batchDelayName: '批次延迟 (ms)',
    batchDelayDesc: '并行批次间的延迟，防止 API 限流（100-10000ms）。当前值：{}ms。如遇 429 错误请增大此值。',

    // 自动维护
    autoMaintainSection: '自动维护',
    autoMaintainBetaBadge: 'BETA 测试 — 实验性功能，可能存在问题，仅建议高级用户使用。',
    autoWatchName: '监听文件夹',
    autoWatchDesc: '自动检测监听列表中文件夹的新增或变更 .md 文件，通知或自动摄入',
    watchedFoldersName: '监听文件夹列表',
    watchedFoldersDesc: '监听新内容的文件夹。点击「添加文件夹」从仓库中选择。',
    addWatchedFolderButton: '添加文件夹',
    removeWatchedFolderButton: '移除',
    webClipperPresetName: '监听 Clippings（Web Clipper）',
    webClipperPresetDesc: '将 Obsidian Web Clipper 使用的 Clippings/ 文件夹加入监听列表。网页剪藏内容将自动摄入 Wiki。',
    noWatchedFoldersHint: '尚未配置监听文件夹。请添加文件夹或启用 Clippings 预设。',
    autoWatchModeName: '监听模式',
    autoWatchModeDesc: '"仅通知"显示提示。"自动摄入"静默处理。',
    watchModeNotify: '仅通知',
    watchModeAuto: '自动摄入',
    autoWatchDebounceName: '防抖延迟 (秒)',
    autoWatchDebounceDesc: '文件变更后等待多久触发摄入 (1-60秒)',
    periodicLintName: '定时维护',
    periodicLintDesc: '定期检查 Wiki 健康状况，有源文件变更时才执行 LLM 维护',
    periodicLintOff: '关闭',
    periodicLintDaily: '每天',
    periodicLintWeekly: '每周',
    periodicLintMonthly: '每月',
    autoSmartFixName: '自动智能修复',
    autoSmartFixDesc: '运行 Lint 时，自动执行所有修复（智能一键修复），无需显示报告弹窗。修复完成后仍会显示摘要。',
    autoSmartFixNotice: '自动智能修复：正在应用所有修复...',

    autoIngestLevelName: '自动摄入通知方式',
    autoIngestLevelDesc: '自动摄入完成时的通知方式。"通知"短暂显示不阻断操作。"详细报告"打开完整报告弹窗。Watch 模式为"仅通知"时此选项无效。',
    autoIngestLevelNotice: '通知（不阻断）',
    autoIngestLevelModal: '详细报告（弹窗）',
    startupCheckName: '启动时执行快速修复',
    startupCheckDesc: '插件加载时自动修复低级格式问题（sources 字段、双层 wikilink），并验证 Wiki 目录结构。默认开启。',
    suggestSchemaCommand: '建议 Schema 更新',
    autoMaintainCostWarning: '⚠️ 费用提醒：自动维护功能会消耗 API Token。"自动摄入"模式在每次源文件变更时触发 LLM 调用。"定时维护"定期运行 LLM 健康检查（仅在有新变更时执行）。请谨慎配置以避免意外费用。',

    // 通知
    startupCheckSummary: 'Wiki 共 {pages} 页（{entities} 个实体、{concepts} 个概念、{sources} 个来源）',
    watcherActiveNotice: 'Wiki: 文件监听已启动 — 正在监控指定文件夹',
    watchIngestNotice: 'Wiki: sources/ 中有 {count} 个文件变更。请执行"摄入源文件"处理。',
    autoIngestRunning: '正在自动摄入 {count} 个变更文件...',
    autoIngestComplete: '自动摄入完成：成功 {success}，失败 {fail}',
    scheduledLintRunning: '正在执行定时 Wiki 维护...',
    wikiLintStats: 'Wiki 维护: 共 {pages} 页（{entities} 实体, {concepts} 概念, {sources} 来源）',
    wikiHealthStats: 'Wiki 健康: 共 {pages} 页（{entities} 实体, {concepts} 概念, {sources} 来源）{indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki 快速修复完成',
    startupCheckStructureLabel: 'Wiki 结构',
    startupCheckStructureOk: '完整',
    startupCheckStructureMissing: '不完整 — 将在首次摄入时自动创建',
    startupCheckSourcesLabel: 'Sources 归一化',
    startupCheckSourcesClean: '已规范',
    startupCheckSourcesCleaned: '清理了 {files} 个文件，{entries} 处条目',
    startupCheckIncompleteClean: '未完成页面：无',
    startupCheckIncompleteArchived: '未完成页面：归档了 {count} 个（可从 .trash 恢复）',
    startupCheckDisableHint: '如需关闭，前往 设置 → 自动维护 → 启动时执行快速修复',
    lintWikiStart: '开始维护 wiki...',
    lintWikiComplete: '维护完成',
    lintWikiFailed: '维护失败',
    analyzingSchema: '正在分析 Wiki 并生成 Schema 建议...',
    schemaSuggestionGenerated: 'Schema 建议已生成，请查看 wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: '未检测到 Schema 需要更新。',
    schemaSuggestionFailed: 'Schema 建议生成失败',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Schema 更新预览',
    schemaDiffSummary: '+{add} / -{del} 行',
    schemaDiffRegenerateLabel: '改进建议（可选）：',
    schemaDiffRegenerateBtn: '重新生成',
    schemaDiffOpenFileBtn: '打开文件',
    schemaDiffApplyBtn: '应用',
    schemaDiffApplied: 'Schema 已更新。备份：{path}',
    schemaDiffEmptyTitle: 'LLM 建议无需修改',
    schemaDiffFailed: 'Schema 应用失败：{reason}',
    schemaDiffRestoreHint: '已备份到 {path}。若需恢复，请在文件管理器中将该文件重命名为 "wiki/schema/config.md"。系统会保留最近 3 个备份。',
    schemaRegenerateNoBody: '重新生成成功，但 LLM 未返回新的 Schema。',
    schemaNotFoundNotice: 'Schema 文件未找到。启用 Schema 功能以创建它。',
    selectFolderNoMdFiles: '文件夹 {path} 中没有 Markdown 文件',
    batchIngestSkipNotice: '跳过 {skipped}/{total} 个已摄入文件。正在摄入 {new} 个新文件...',
    batchIngestAllIngested: '该文件夹中的所有 {total} 个文件均已摄入。',
    batchIngestStarting: '正在从 "{folder}" 摄入 {count} 个文件 — 可能需要数分钟。完成后会显示报告。',
    batchIngestComplete: '批量摄入完成: 成功 {success}/{total}, 失败 {fail}',
    batchIngestFailedFiles: '失败的文件:',
    historyTruncated: '历史已截断至最近 {max} 轮对话',
    historyCleared: '历史已清空',

    // 用户反馈闭环
    reviewedPagePreserved: '已保留用户审阅内容: {}',

    // Query 回流
    querySuggestSaveTitle: '保存到 Wiki？',
    querySuggestSaveDesc: '此对话包含有价值的知识点，是否保存到 Wiki？',
    querySuggestSaveYes: '保存',
    querySuggestSaveNo: '忽略',

    // 摄入报告
    ingestReportElapsedTime: '耗时',
    ingestReportSkippedFiles: '跳过（已摄入）',
    ingestReportRejectedFiles: '已跳过',
    rejectionReasonEmpty: '空内容',
    rejectionReasonType: '不支持的类型',
    rejectionReasonDuplicate: '重复内容',
    rejectionReasonPdfUnsupported: '提供商无法读取 PDF',
    rejectionReasonMineruPageLimit: '超过 MinerU 页数上限',
    rejectionReasonMineruSizeLimit: '超过 MinerU 大小上限',
    ingestReportFailedGuidance: '这些条目未能自动创建。您可手动创建对应页面，或降低提取颗粒度后重新摄入源文件。',

    // 命令名称（sentence case 遵循 Obsidian Bot 规则）
    cmdIngestSource: '摄入单个源文件',
    cmdIngestFolder: '从文件夹摄入',
    cmdIngestMultipleFiles: '多选文件摄入',
    cmdQueryWiki: '查询 Wiki',
    cmdLintWiki: '维护 Wiki',
    cmdRegenerateIndex: '重新生成索引',
    cmdSuggestSchema: '建议 Schema 更新',
    cmdCancelIngestion: '取消当前提取',
    cmdIngestActiveFile: '摄入当前文件',
    cmdViewHistory: '查看摄入历史',
    noActiveFile: '当前没有打开的文件',
    mdOnlyFile: '仅支持摄入 Markdown 文件',
    ingestSingleFileStart: '正在摄入：{filename}',
    ingestCheckingExisting: '正在检查已摄入的文件...',
    lintFindingsSummary: '共 {total} 处发现',

    // Ingestion status bar
    ingestionStatusBar: '提取中... 点击取消',
    lintStatusBar: '维护中... 点击取消',
    ingestStatusAnalyzing: '提取中… (点击取消)',
    lintStatusAnalyzing: '维护中… (点击取消)',
    // v1.25.11 PATCH #169 — fine-grained stage hints for the status bar.
    // These labels are ADD-only emission sandwiched between the page name
    // and the always-visible base label (e.g. "My Note · Generating summary ·
    // Ingesting… (click to cancel)"). They never replace the base label, so
    // the cancel affordance is preserved through every long-running stage.
    ingestStageAnalyze: '正在分析源',
    ingestStageSummary: '正在生成摘要',
    ingestStageEntity: '正在创建实体',
    ingestStageConcept: '正在创建概念',
    ingestStageRetry: '正在重试失败的页面',
    ingestStageSave: '正在保存页面',
    ingestStageIndex: '正在生成索引',
    pdfStageReading: '正在读取 PDF',
    pdfStageConverting: '正在转换 PDF',
    pdfStageSidecar: '正在写入附属文件',
    lintStagePrep: '正在读取页面',
    lintStageProgrammatic: '正在扫描链接',
    lintStageAnalyzing: '正在运行 LLM 分析',
    lintStageDedup: '正在检测重复',
    lintStageContradiction: '正在检测矛盾',
    ingestionCancelling: '正在取消 — 当前批次完成后将停止',
    ingestionCancelled: '提取已取消',
    // v1.26.3 PATCH follow-up (B2.5): status-bar progress text i18n
    ingestBatchInitial: '正在分析批次 1/{total}...',
    ingestBatchProgress: '正在分析批次 {current}/{total}（已提取 {entities} 个实体、{concepts} 个概念）...',
    ingestBatchProcessed: '已完成批次 {current}，正在处理...',
    ingestAnalyzing: '正在分析：{filename}',
    ingestCreatingSummary: '[{step}/{totalSteps}] 正在生成摘要...',
    ingestCreatingItem: '[{step}/{totalSteps}] {type}：{name}',
    ingestUpdating: '[{step}/{totalSteps}] 正在更新：{name}',
    ingestGeneratingIndex: '[{step}/{totalSteps}] 正在生成索引...',
    ingestItemTypeEntity: '实体',
    ingestItemTypeConcept: '概念',
    convAnalyzing: '正在分析对话...',
    convCheckingExisting: '正在检查已有知识...',
    convAlreadyExists: '此知识已存在于 Wiki',
    convCreatingSummary: '正在创建摘要页...',
    convGeneratingSummary: '正在生成摘要页...',
    convSavingEntity: '正在保存实体：{name}',
    convSavingConcept: '正在保存概念：{name}',
    convGeneratingIndex: '正在生成索引...',

    // 维护报告
    lintReportTitle: 'Wiki 维护报告',
    lintReportSummary: 'Wiki 状态概览：共 {total} 个页面，{aliasesMissing} 个缺失别名，重复 {duplicates} 个，断链 {deadLinks} 个（其中 {deadLinkFromDup} 个涉及重复页面），孤立 {orphans} 个（其中 {orphanFromDup} 个是重复页面），空洞 {emptyPages} 个，无来源引证 {ungroundedQuotes} 个，标签越界 {tagViolations} 个。本次 Lint 耗时 {elapsedSeconds} 秒',

    // Advanced LLM Settings (Issues #99 / #128)
    // v1.26.0 (#382 item 2): 名称由"高级参数设置"改为"LLM 高级参数"，
    // 明确这是 LLM 采样参数，与底部通用的"高级设置"面板区分。
    advancedLlmModeName: 'LLM 高级参数',
    advancedLlmModeDesc: '默认模式遵循模型提供商的推荐设置。仅当你有明确理由覆盖时才切到自定义（例如：某个模型需要固定温度，或者你想关闭模型的思考输出）。',
    advancedSettingsDefault: '默认（遵循提供商）',
    advancedSettingsCustom: '自定义（覆盖提供商）',
    // v1.26.0 (#382 item 2): 底部"高级设置"面板 — 所有非 LLM 采样参数的
    // 高级用户设置的通用归属（lint 阈值、欢迎页、未来扩展）。
    advancedSettingsSection: '高级设置',
    showAdvancedSettingsName: '显示高级设置',
    showAdvancedSettingsDesc: '开启后显示下方的高级设置；关闭后会隐藏这些设置并将其重置为默认值。',
    disableThinkingName: '禁用思考',
    disableThinkingDesc: '关闭模型响应中的思维链/推理过程输出。默认关闭 —— 由模型自己决定是否显示推理，这样通常能得到最好的回答。只有当你的提供商把原始推理文本塞进回复、而你希望得到一个干净的答案时，才打开它。',
    taskPoliciesPlaceholder: '示例：extract=text:off',
    taskPoliciesName: '按步骤设置输出模式与思考',
    taskPoliciesDesc: '每个流水线步骤一项，格式 `步骤=模式:思考`，逗号分隔，例如 `extract=text:off`。模式：`-`（不变）、`schema`、`json`、`text`；思考：`-`、`off`、`on`、`low`、`medium`、`high`。步骤名包括 extract、extract-retry、lemma-classify、merge-triage、source-stance、dedup、page-generate、related-page、lint-dedup（拼错的名称不会匹配任何步骤）。留空使用内置基线（抽取步骤为文本模式）。无法解析的条目不会保存。',
    // Issue #137: 兼容性提示（简短；不列举 provider，避免维护负担）
    extractionTemperatureName: '提取温度',
    extractionTemperatureDesc: '控制模型在写实体/概念页时是偏严谨还是偏创意。数值越低越确定、越忠于原文；数值越高变化越多。大多数用户留空即可。',
    chatTemperatureName: '查询温度',
    chatTemperatureDesc: '和"提取温度"思路相同，但只影响 Query Wiki 回答问题的方式。数值越低回答越字面化；数值越高越像在聊天。大多数用户留空即可。',
    repetitionPenaltyName: '重复惩罚',
    repetitionPenaltyDesc: '阻止模型反复说相同的字词。数值越高越能减少重复。只有部分本地模型提供商（Ollama、LM Studio、llama.cpp）接受这个参数；云端提供商会静默忽略。大多数用户留空即可。数值高于 1.0 可能导致提取时 LLM 输出错误（小模型在语法约束下易失败）——若运行失败，请减小或清空此值。',
    repetitionPenaltyErrorHint: '注意：已设置自定义重复惩罚值 {value}。高于 1.0 的值可能破坏小型本地模型的语法约束提取——请减小或清空此设置后重试。',
    temperaturePlaceholder: '留空 = 使用提供商默认',
    // v1.26.0 (#382 item 2): 重复检测阈值（仅自定义高级模式）。
    // 与上方温度输入共用占位文案，保持同一提示风格。
    lintDedupJaccardLinkThresholdName: '链接重复相似度',
    lintDedupJaccardLinkThresholdDesc: '范围 0–1（默认 0.4）。两个页面共同指向的 wiki 链接占各自链接集合的比例达到该值时，被标记为重复。调低 → 更多"只是都链接到同一中心页"的近似重复会被纳入；调高 → 只标记指向几乎相同页面的页面。若看到不相关页面恰好链接到同一中心页造成的误报，可调高此项。留空使用默认值。',
    lintDedupJaccardBodyGateName: '正文最低相似度',
    lintDedupJaccardBodyGateDesc: '范围 0–1（默认 0.2）。即使两个页面共享 wiki 链接，正文相似度（按比例）至少达到该值时才会被标记为重复。调低 → 更多候选进入 LLM 复核；调高 → 只标记正文几乎相同的页面。若 LLM 被频繁要求复核明显不是重复的页面，可调高此项。留空使用默认值。',
    lintDedupBigramThresholdName: '标题相似度',
    lintDedupBigramThresholdDesc: '范围 0–1（默认 0.4）。两个页面标题（或别名）的字符重合度达到该值时，被标记为重复。调低 → 拼写变体、笔误、同一概念的不同翻译都会纳入；调高 → 只标记标题几乎相同的页面。若 LLM 被要求复核标题差异很大、明显不是重复的页面，可调高此项。留空使用默认值。',
    lintDeadLinkSection: '断链（程序检测）[共 {count} 个]',
    lintEmptyPageSection: '空洞页面（程序检测）[共 {count} 个]',
    lintOrphanSection: '孤立页面（程序检测）[共 {count} 个]',
    lintContradictionSection: '矛盾（程序检测）',
    lintDeadLinkItem: '- [[{source}]] → **{target}**（页面不存在）{dupFlag}',
    lintDeadLinkMore: '- ... 共 {count} 处断链',
    lintEmptyPageItem: '- [[{page}]] — 内容不足 50 字符',
    lintOrphanItem: '- [[{page}]] — 无其他 Wiki 页面链接至此{dupFlag}',
    lintDeadLinkAffectedByDup: ' （⚠️ 涉及重复页面）',
    lintOrphanIsDuplicate: ' （⚠️ 重复页面）',
    lintHubLinkDensitySection: '枢纽页面链接密度问题（Issue #157 / #175）[{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} 个入链，{relatedCount} 个相关链接，区分度 {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ 建议剥离',
    lintHubLinkDensityReview: '🔍 建议复核',
    lintHubLinkDensityKeep: '✅ 保留',
    lintHubLinkDensitySummary: '摘要：{strip} 个页面建议剥离，{review} 个页面建议复核。',
    lintHubLinkDensityNoRelated: ' （未找到 ## Related 区块）',
    lintNoIssuesFound: '未检测到重复、断链、空洞、孤立页面或无来源引证。',
    lintSourceDriftSection: '导入后已变更的来源笔记 [共 {count} 个]',
    lintSourceDriftItem: '- [[{page}]] — 原始笔记 [[{note}]] 在导入后被编辑，页面内容可能已过时',
    lintContradictionMarkerSection: '带有矛盾标记的页面（合并分流）[共 {count} 个]',
    lintContradictionMarkerItem: '- [[{page}]] — 冲突来源：{sources}；审阅后请移除 contradictions: 标记',
    lintQuoteGroundingSection: '无来源引证（程序检测）[共 {count} 个]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}："{quote}"',
    lintContradictionOpen: '未解决的矛盾：{count} 个',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: '待处理',

    // 维护分析 Prompt

    // 维护修复进度
    lintFixProgress: '修复断链 {current}/{total}：[[{target}]]',
    lintFixDeadComplete: '断链修复完成。已修复 {fixed}/{total} 项。',
    lintFillProgress: '扩充空洞 {current}/{total}：{page}',
    lintFillComplete: '页面扩充完成。已填充 {filled}/{total} 页。',
    lintDeleteCompleted: '已删除 {count} 个空洞页面',
    lintDeleteFailed: '删除失败 {failed}/{total} 个空白 stub（详情见控制台）',
    lintFillFailed: '扩充失败：{page} — {error}',
    lintLinkProgress: '链接孤立 {current}/{total}：{page}',
    lintLinkComplete: '孤立页面链接完成。已链接 {linked} 页。',
    lintFixNoAction: '未执行操作（无 client）',
    lintFixIndexUpdated: 'Wiki 索引和日志已更新。',
    lintPollutedFixed: '已修复污染页面：{fixed}/{total}。索引已重建。',
    regenerateIndexCompleted: '索引已重建',
    operationFailed: '失败：',
    lintFixAllComplete: '所有修复已完成。详情见日志。',
    lintFixAllNoChanges: '未做任何修改 — 所有阶段报告 0 修复。详情见 wiki/log.md。',
    lintFixPhasesLabel: '个阶段已修改',

    // 维护报告弹窗
    lintModalActionsTitle: '修复建议（需消耗LLM Token）：',
    lintLogReference: '完整报告已保存至 log.md',
    lintModalFixDeadLinks: '修复断链（{count}）',
    lintModalExpandEmpty: '扩充空洞页面（{count}）',
    lintModalDeleteEmpty: '删除空洞页面（{count}）',
    lintModalLinkOrphans: '链接孤立页面（{count}）',
    lintModalAnalyzeSchema: '分析 Schema',
    lintModalMergeDuplicates: '合并重复页面（{count}）',
    lintModalFixAll: '一键修复所有问题（{count}）',
    lintDuplicateSection: '重复页面（程序检测）',
    lintPollutedSection: '污染页面（程序检测）[共 {count} 个]',
    lintPollutedItem: '- [[{page}]] → 应为 "{clean}"',
    lintSourcesNormalizedSection: 'Sources 已归一化（自动修复）[共 {files} 个文件 / {entries} 处]',
    lintSourcesNormalizedItem: '清理了 {files} 个文件中的 {entries} 处 sources 条目（已移除外部路径、.md 后缀、别名管道，并去重）。',
    lintDuplicateItem: '- [[{target}]] 与 [[{source}]] — {reason}',
    lintMergeProgress: '合并 {current}/{total}：{source} → {target}',
    lintMergeComplete: '重复页面合并完成。已合并 {merged}/{total} 对。',

    // 摄入报告弹窗
    ingestReportTitle: '摄入报告',
    ingestReportSourceFile: '源文件',
    ingestReportCreated: '已创建',
    ingestReportUpdated: '已更新',
    ingestReportContradictions: '发现矛盾',
    ingestReportFailedTitle: '未能摄入',
    ingestReportErrorDetail: '错误详情',
    ingestReportClose: '关闭',
    ingestReportCreatedPages: '创建页面：{count}',
    ingestReportUpdatedPages: '更新页面：{count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki 操作日志',
    logHeaderSubtitle: '每次摄入、Lint 运行和维护操作都会自动记录在这里。推荐使用**操作历史**面板获得更好的可视化呈现：',
    logHeaderShortcut: 'Cmd+P → "查看操作历史"',
    logHeaderSettingsShortcut: '或从 设置 → 自动维护 → 操作历史 进入',
    ingestionCreatedPages: '{count} 个页面已创建',
    ingestionUpdatedPages: '{count} 个页面已更新',
    ingestionNoticeHistoryHint: '查看操作历史了解详情',
    ingestReportEntitiesCount: '{count} 个实体',
    ingestReportConceptsCount: '{count} 个概念',
    ingestReportContradictionsFound: '发现矛盾：{count}',
    ingestReportEntityType: '实体',
    ingestReportConceptType: '概念',
    timeMinutes: '分',
    timeSeconds: '秒',

    // 速率限制警告
    rateLimitDetected: '⚠️ 检测到速率限制：{count} 个页面因 429 错误失败。建议：(1) 降低并发度至 {suggestedConcurrency} 或 1（串行），(2) 增大批次延迟至 {suggestedDelay}ms，(3) 切换到速率限制更高的提供商。',
    rateLimitDetectedShort: '⚠️ 触发速率限制 — 建议在设置 → 摄入加速中降低并发度或增大批次延迟。',

    // 长文本摄入提示
    sourceRejectedEmpty: '⏭️ "{filename}" 没有可提取的内容，已跳过。空笔记或仅含 frontmatter 的笔记不会生成 Wiki 页面。',
    sourceRejectedType: '⏭️ "{filename}" 不是受支持的文件类型，已跳过。仅可提取文本笔记（如 .md、.txt）。',
    sourceRejectedDuplicate: '⏭️ "{filename}" 已跳过——其内容已存在于 Wiki 中。',
    pdfReadingInProgress: '正在读取 PDF: {filename}',
    sourceRejectedPdfUnsupported: '⏭️ 「{filename}」已跳过——当前 provider 或模型不支持 PDF 输入。可在 Settings → LLM Configuration → Advanced 中切换 provider，或打开「强制启用 PDF 支持」再试一次，或切换 Markdown 转换后端为 MinerU（同时支持图片和 Office 文档）。',
    clearPdfCacheCommand: '清除 PDF 转换缓存',
    pdfCacheCleared: 'PDF 缓存已清除（{count} 个条目已移除）。',
    // v1.25.0 PR3: Advanced PDF settings
    forcePdfSupportName: '强制启用 PDF 支持',
    forcePdfSupportDesc: '默认关闭。如果你的 provider 不是原生支持 PDF 的，但又确实能处理 PDF，可以打开这个开关试一试。打开后会发送 PDF 给当前 provider，如果被拒绝，会用提示告诉你。原生支持 PDF 的 provider（Anthropic / OpenAI / Bedrock）不需要这个开关。',
    writePdfMarkdownToVaultName: '将转换后的 Markdown 写入 Vault',
    writePdfMarkdownToVaultDesc: '默认关闭。开启后，每次 PDF 转换的结果会写入源 PDF 旁边的 “<原名>.pdf.md” 文件。关闭时，转换结果仅保存在插件缓存，不在你的 Vault 中留下实现产物。',
    markdownConversionBackendName: 'Markdown 转换后端',
    markdownConversionBackendDesc: 'Native 使用 provider 自带的 PDF 支持（范围有限，并非所有 provider/model 都支持 PDF，消耗 LLM tokens）。MinerU 是在线服务——速度快、按日配额免费、支持 PDF/图片/Office——但需要 API Token（在下方字段填写）。',
    markdownConversionBackendNative: 'Provider PDF/图片 支持',
    markdownConversionBackendMineru: 'MinerU 在线 API',
    mineruApiBaseUrlName: 'MinerU 服务地址',
    mineruApiBaseUrlDesc: 'MinerU API 服务基础地址，默认为 https://mineru.net/api/v4。若使用代理、镜像或自建私有化服务可在此自定义。',
    mineruApiBaseUrlPlaceholder: 'https://mineru.net/api/v4',
    mineruApiTokenName: 'MinerU API Token',
    mineruApiTokenDesc: '在 https://mineru.net/apiManage/token 获取你的 Token。MinerU 接受最大 200 MB、最多 200 页的文件。',
    mineruApiTokenPlaceholder: '粘贴 MinerU API Token',
    mineruUploadingInProgress: '正在上传 PDF 到 MinerU：{filename}',
    mineruWaitingInProgress: '正在等待 MinerU 解析：{filename}',
    mineruDownloadingInProgress: '正在下载 MinerU 解析结果：{filename}',
    markdownConversionComplete: '转换完成：{filename}',
    markdownConversionCompleteSaved: '转换完成 — 已写入 {path}：{filename}',
    mineruPageLimitRejected: '{filename} 超过 MinerU 的 {limit} 页上限，请拆分文件后重试',
    mineruSizeLimitRejected: '{filename} 超过 MinerU 的 {limit} MB 大小上限',

    ingestRejectedSummary: '已跳过 {count} 个文件（空文件、重复或不支持的类型）。',
    reingestConfirmTitle: '重新提取该文件？',
    reingestConfirmBody: '"{filename}" 的内容已存在于 Wiki 中。仍要重新提取吗？',
    reingestConfirmYes: '重新提取',
    reingestConfirmNo: '跳过',
    lintDedupIncludeSourcesName: '在去重中包含来源',
    lintDedupIncludeSourcesDesc: '默认开启。开启后，正文相同的来源在 lint 阶段会被标记为重复。若你的来源语料产生过多误报，可关闭此选项。',
    // Issue #514: opt-in candidate gate (bottom Advanced settings panel).
    skipMentionOnlyCandidatesName: '跳过来源仅提及的候选',
    skipMentionOnlyCandidatesDesc: '默认关闭。开启后，提取出的实体或概念若其名称未出现在笔记正文中（完全未出现，或仅出现在括号、枚举或简短列表项中），将不生成页面、不再调用模型，并从其他候选的相关列表中移除。适用于具有词边界配置的 Wiki 语言（德语已测量；英语、法语、西班牙语、葡萄牙语、荷兰语为估计）；其他语言在摄入时会提示一次无法应用。若你的库是术语表风格或笔记以要点为主、希望每个被点名的术语都成为页面，请保持关闭。',
    createStubsForUnresolvableLinksName: '为无法解析的链接创建占位页',
    createStubsForUnresolvableLinksDesc: '默认开启。当“修复断链”无法把链接解析到任何现有页面时，会写入一个空的占位页并把链接改指向它——绝不由 LLM 填充。关闭后此类链接保持原样：它们在每次 lint 报告中保持可见，直到有真实来源定义它们。',
    lintDedupSectionHeading: '去重检测',
    // v1.26.0 (#382 item 1, Batch 2 follow-up): 通用 Toast 文案，
    // 复用于所有 LLM 业务路径（dedup / analysis / fix-runners /
    // conversation-ingest / merge / headless CLI）。{count} 是触发
    // 重试的批次数量。注意：不要在此承诺"任务已完成"——本次重试仅
    // 恢复本批次，同一扫描的其他批次可能仍在进行中。
    llmRetryRecoveredToast: 'LLM 任务：{count} 个批次因 provider 临时响应问题触发重试（已自动恢复）。详见控制台。若频繁出现，请考虑在 Provider 设置中降低 Page Generation Concurrency。',
    longSourceNotice: '📄 "{filename}" 包含 {lines} 行（{size}）。长文本需要多轮迭代提取，LLM 将完整读取文档进行多次分析，耗时可能较长，请耐心等待。',
    longSourceNoticeShort: '📄 检测到大文件（{lines} 行），摄入可能需要较长时间。',

    // 摄入历史面板 (#122) — UI 文案
    historyButton: '操作历史',
    historyButtonDesc: '查看 LLM-Wiki 最近的摄入、Lint 报告和其他变更记录',
    historyButtonOpen: '查看历史',
    historyModalTitle: '操作历史',
    historyModalSubtitle: 'LLM-Wiki 最近的变更记录',
    historyEmpty: '暂无操作记录。摄入笔记或运行 Lint 以填充此列表。',
    historyReadError: '无法读取操作日志：{error}',
    historyEntryKindIngest: '摄入',
    historyEntryKindMaintenance: '维护',
    historyEntryKindFix: '修复',
    historyEntryKindOther: '其他',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: '来源：{source}',
    historyEntrySourceUnknown: '未命名摄入',
    historyEntryCreatedLabel: '已创建',
    historyEntryUpdatedLabel: '已更新',
    historyEntryCreatedCount: '新建 {count} 个',
    historyEntryUpdatedCount: '更新 {count} 个',
    historyEntryNoChanges: '无页面变更',
    historyEntryContradictions: '⚠️ {count} 处矛盾',
    historyEntrySectionCreated: '创建的页面',
    historyEntrySectionUpdated: '更新的页面',
    historyEntrySectionContradictions: '矛盾',
    historyEntrySectionDetails: '详情',
    historyEntryOpenPage: '打开',
    historyEntryDetailsNoContradictions: '未发现矛盾',
    historySearchPlaceholder: '🔍 按来源标题或页面路径搜索…',
    historyFilterAll: '全部',
    historyFilterIngest: '仅摄入',
    historyFilterMaintenance: '仅维护报告',
    historyFilterFix: '仅修复',
    historyFilterContradictions: '⚠️ 含矛盾',
    historyRefreshButton: '⟳ 刷新',
    historyExpandDay: '点击展开',
    historyCollapseDay: '点击收起',
    historyShowMore: '显示更早的 {count} 条',
    historyNoMatch: '没有操作匹配您的搜索/筛选条件。',
    historyCloseButton: '关闭',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: '报告发现',
    historyKpiPages: '页面数',
    historyKpiDeadLinks: '断链',
    historyKpiOrphans: '孤立',
    historyKpiEmpty: '空洞',
    historyKpiDuplicates: '重复',
    historyKpiTagViolations: '标签问题',
    historyKpiUnsourced: '无来源',
    historyKpiDuration: 'Lint 耗时',
    historyKpiDurationSec: '{seconds} 秒',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: '断链 ({count})',
    historySectionTagViolations: '标签越界 ({count})',
    historySectionOrphans: '孤立页面 ({count})',
    historySectionEmptyPages: '空洞页面 ({count})',
    historySectionLlmAnalysis: 'LLM 分析 ({count})',
    historyDeadLinkSource: '来源',
    historyDeadLinkTarget: '缺失',
    historyOpenInLog: '在 log.md 中查看',
    historyShowMoreItems: '展开剩余 {count} 项',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ 持平',
    historyChipContradiction: '矛盾',
    historyChipOutdated: '过时',
    historyChipMissing: '缺失',
    historyChipStructure: '结构',
    historySeverityHigh: '高',
    historySeverityMedium: '中',
    historySeverityLow: '低',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: '您的 Wiki 当前有 {dead} 个断链、{orphans} 个孤立页面、{tags} 个标签问题。最近一次 Lint 耗时 {duration}。',
    historyGlobalInsightClean: '您的 Wiki 当前状态良好——没有断链、孤立页面或标签问题。',
    historyGlobalInsightNoData: '暂无维护报告——运行 Lint 以生成。',
    historyModalHeaderTitle: '操作历史',
    historyModalSubtitleWithCount: 'LLM-Wiki 最近的变更记录 · 共 {count} 条',
    historyTimeRangeAll: '全部时间',
    historyTimeRange1d: '近 1 天',
    historyTimeRange3d: '近 3 天',
    historyTimeRange1w: '近 1 周',
    historyTimeRange1m: '近 1 个月',
    historyIngestTotal: '页面总数',
    historyIngestByType: '按类型分布',
    historyIngestSource: '来源文件',
    historyIngestNoTimestamp: '无时间戳',
    historyIngestFirstTime: '首次摄入',
    historyIngestLatestTime: '最近摄入',
    historyTimeRangeCustom: '自定义范围',
    historyCustomRangeFrom: '起始',
    historyCustomRangeTo: '结束',
    historyCustomRangeApply: '应用',
    historyCustomRangeClear: '清除',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki：vault 为空。请创建你的第一个 source note 并运行 Ingest 以开始使用。',
    welcomeNoteTierBNotice: 'Karpathy Wiki：已创建 Welcome note。打开它以声明你的领域并选择 2-3 个 source note 来为链接图提供种子。',
    welcomeNoteRecreateCommand: '重建 Wiki Welcome note',
    welcomeNoteRecreateCommandTooltip: '使用当前的 domain seed 和 LLM 配置测试在 <wikiFolder>/Welcome.md 重新创建 Welcome note。已存在的文件将被覆盖。',
    welcomeNoteSettingsToggle: '首次运行时创建 Wiki Welcome note',
    welcomeNoteSettingsToggleDesc: '首次运行（wiki 文件夹为空时），自动在 <wikiFolder>/Welcome.md 创建一页入门笔记。它会说明 LLM-Wiki 是什么、引导你声明领域聚焦，并教你摄取前 2-3 条源笔记。笔记默认用英文写入，若 LLM 已配置则用你的 wiki 语言。如果已经熟悉插件用法不想多这一页，可以关掉。',
    welcomeNoteRunConfigTest: 'Welcome note 已用英文写入。打开 设置 → LLM Provider → Test Connection 以便下次重建时本地化。',
    welcomeNoteRecreated: '已重新创建 Wiki Welcome note 于 {path}',
    welcomeNoteNotRecreated: 'Welcome note 未重新创建。请检查 LLM 配置。',
    welcomeNoteGenerating: 'Wiki Welcome note 正在后台生成 — 完成后会显示通知。',
    welcomeNoteGenerationFailed: 'Wiki Welcome note 生成失败：{error}',
    startupCheckWelcomePending: 'Welcome note：正在后台生成（完成后会显示通知）。',
    welcomeNoteFileName: '欢迎使用 Karpathy LLM Wiki',
    startupCheckWelcomeCreated: 'Welcome note 已创建于 {path}',
    // v1.23.0 Phase 5.1.5: 多文件摄入 Modal 的"取消全部"按钮。一次取消
    // 队列中所有 pending + running 任务。Completed / failed 保留可见。
    cancelAllQueueJobs: '全部取消',
    // v1.23.0 Phase 5.1.5: Multi-File Suggest modal (cmdIngestMultipleFiles).
    // 标题、提示、搜索框占位、按钮、状态文字、队列空占位。
    multiFileModalTitle: '多文件摄入',
    multiFileModalHint: '选择源笔记加入队列。右侧面板实时显示队列与进度。',
    multiFileSearchPlaceholder: '按路径筛选文件…',
    multiFileAddToQueue: '加入队列',
    multiFileSelectAll: '全选',
    multiFileFileCount: '{count} 个文件',
    multiFileNoFilesAvailable: '暂无可摄入的文件。',
    multiFileNoFilesMatch: '未匹配到 "{q}"。',
    multiFileQueueEmpty: '队列为空。勾选左侧文件即可加入。',
    multiFileStatusPending: '等待中',
    multiFileStatusRunning: '摄入中',
    multiFileStatusCompleted: '已完成',
    multiFileStatusFailed: '已失败',
    multiFileCancelAria: '取消该文件',
    // #598: what the vault says about a row, resolved when the picker
    // opens. The queue only knows this session.
    multiFileRowIngested: '已摄入',
    multiFileRowDrifted: '摄入后笔记已修改',
    startupCheckNoticeLevelName: '显示快速修复结果',
    startupCheckNoticeLevelDesc: '快速修复在插件启动时始终运行（Welcome note、文件夹结构、源归一化、不完整页面、日志头）。选择启动后是否显示摘要通知。静默模式仅记录到开发者控制台和操作历史面板。',
    startupCheckNoticeVisible: '显示（弹出通知）',
    startupCheckNoticeSilent: '静默（无通知）',
} as const;
